export interface NaturalTerms {
  singular: string
  plural: string
  article: string
  feminin: boolean
  synonyms: string[]
  intentVerbs: string[]
  qualifiers: string[]
  commonQueries: string[]
}

const SHARED_VERBS = ['trouver', 'chercher', 'besoin de', 'contacter']

export const NATURAL_TERMS: Record<string, NaturalTerms> = {
  plombier: {
    singular: 'plombier',
    plural: 'plombiers',
    article: 'un plombier',
    feminin: false,
    synonyms: ['plombier chauffagiste', 'dépanneur plomberie'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['pas cher', 'urgent', 'de confiance', 'agréé', '24h/24'],
    commonQueries: [],
  },
  electricien: {
    singular: 'électricien',
    plural: 'électriciens',
    article: 'un électricien',
    feminin: false,
    synonyms: ['électricien bâtiment', 'artisan électricien'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['certifié', 'NF C 15-100', 'pas cher', 'urgent'],
    commonQueries: [],
  },
  serrurier: {
    singular: 'serrurier',
    plural: 'serruriers',
    article: 'un serrurier',
    feminin: false,
    synonyms: ['serrurier dépanneur', 'serrurier urgence'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['pas cher', 'urgent', 'de confiance', '24h/24'],
    commonQueries: [],
  },
  chauffagiste: {
    singular: 'chauffagiste',
    plural: 'chauffagistes',
    article: 'un chauffagiste',
    feminin: false,
    synonyms: ['installateur chauffage', 'dépanneur chaudière'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['agréé', 'RGE', 'pas cher', 'urgent'],
    commonQueries: [],
  },
  'peintre-en-batiment': {
    singular: 'peintre en bâtiment',
    plural: 'peintres en bâtiment',
    article: 'un peintre en bâtiment',
    feminin: false,
    synonyms: ['peintre intérieur', 'peintre décorateur', 'artisan peintre'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['pas cher', 'qualifié', 'devis gratuit'],
    commonQueries: [],
  },
  menuisier: {
    singular: 'menuisier',
    plural: 'menuisiers',
    article: 'un menuisier',
    feminin: false,
    synonyms: ['menuisier ébéniste', 'artisan menuisier'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'sur mesure', 'pas cher'],
    commonQueries: [],
  },
  carreleur: {
    singular: 'carreleur',
    plural: 'carreleurs',
    article: 'un carreleur',
    feminin: false,
    synonyms: ['carreleur mosaïste', 'poseur de carrelage'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  couvreur: {
    singular: 'couvreur',
    plural: 'couvreurs',
    article: 'un couvreur',
    feminin: false,
    synonyms: ['couvreur zingueur', 'artisan couvreur'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'urgent', 'pas cher'],
    commonQueries: [],
  },
  macon: {
    singular: 'maçon',
    plural: 'maçons',
    article: 'un maçon',
    feminin: false,
    synonyms: ['maçon bâtiment', 'artisan maçon'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  vitrier: {
    singular: 'vitrier',
    plural: 'vitriers',
    article: 'un vitrier',
    feminin: false,
    synonyms: ['dépanneur vitrier', 'remplacement vitre'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['urgent', 'pas cher', '24h/24'],
    commonQueries: [],
  },
  climaticien: {
    singular: 'climaticien',
    plural: 'climaticiens',
    article: 'un climaticien',
    feminin: false,
    synonyms: ['installateur climatisation', 'frigoriste'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['agréé', 'RGE', 'pas cher'],
    commonQueries: [],
  },
  cuisiniste: {
    singular: 'cuisiniste',
    plural: 'cuisinistes',
    article: 'un cuisiniste',
    feminin: false,
    synonyms: ['poseur de cuisine', 'installateur cuisine'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['sur mesure', 'pas cher', 'qualifié'],
    commonQueries: [],
  },
  charpentier: {
    singular: 'charpentier',
    plural: 'charpentiers',
    article: 'un charpentier',
    feminin: false,
    synonyms: ['charpentier bois', 'artisan charpentier'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'traditionnel', 'pas cher'],
    commonQueries: [],
  },
  zingueur: {
    singular: 'zingueur',
    plural: 'zingueurs',
    article: 'un zingueur',
    feminin: false,
    synonyms: ['couvreur zingueur', 'zingueur gouttières'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'pas cher', 'urgent'],
    commonQueries: [],
  },
  etancheiste: {
    singular: 'étanchéiste',
    plural: 'étanchéistes',
    article: 'un étanchéiste',
    feminin: false,
    synonyms: ['étancheur', 'spécialiste étanchéité'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'certifié', 'devis gratuit'],
    commonQueries: [],
  },
  facadier: {
    singular: 'façadier',
    plural: 'façadiers',
    article: 'un façadier',
    feminin: false,
    synonyms: ['ravaleur de façade', 'peintre façadier'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  platrier: {
    singular: 'plâtrier',
    plural: 'plâtriers',
    article: 'un plâtrier',
    feminin: false,
    synonyms: ['plâtrier plaquiste', 'plaquiste'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['qualifié', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  'salle-de-bain': {
    singular: 'salle de bain',
    plural: 'salles de bain',
    article: 'un spécialiste salle de bain',
    feminin: true,
    synonyms: ['rénovation salle de bain', 'installateur salle de bain'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['clé en main', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  'pompe-a-chaleur': {
    singular: 'pompe à chaleur',
    plural: 'pompes à chaleur',
    article: 'un installateur de pompe à chaleur',
    feminin: true,
    synonyms: ['installateur PAC', 'spécialiste pompe à chaleur'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['RGE', 'agréé', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  'panneaux-solaires': {
    singular: 'panneaux solaires',
    plural: 'panneaux solaires',
    article: 'un installateur de panneaux solaires',
    feminin: false,
    synonyms: ['installateur photovoltaïque', 'poseur panneaux solaires'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['RGE', 'certifié', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  'isolation-thermique': {
    singular: 'isolation thermique',
    plural: 'isolations thermiques',
    article: 'un spécialiste en isolation thermique',
    feminin: true,
    synonyms: ['isolateur thermique', 'entreprise isolation'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['RGE', 'certifié', 'pas cher', 'devis gratuit'],
    commonQueries: [],
  },
  'renovation-energetique': {
    singular: 'rénovation énergétique',
    plural: 'rénovations énergétiques',
    article: 'un spécialiste en rénovation énergétique',
    feminin: true,
    synonyms: ['rénovation thermique', 'audit énergétique'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['RGE', 'MaPrimeRénov', 'devis gratuit'],
    commonQueries: [],
  },
  'borne-recharge': {
    singular: 'borne de recharge',
    plural: 'bornes de recharge',
    article: 'un installateur de borne de recharge',
    feminin: true,
    synonyms: ['installateur IRVE', 'borne véhicule électrique'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['certifié IRVE', 'qualifié', 'devis gratuit'],
    commonQueries: [],
  },
  ramoneur: {
    singular: 'ramoneur',
    plural: 'ramoneurs',
    article: 'un ramoneur',
    feminin: false,
    synonyms: ['ramoneur fumiste', 'ramonage cheminée'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['certifié', 'pas cher', 'obligatoire'],
    commonQueries: [],
  },
  diagnostiqueur: {
    singular: 'diagnostiqueur',
    plural: 'diagnostiqueurs',
    article: 'un diagnostiqueur',
    feminin: false,
    synonyms: ['diagnostiqueur immobilier', 'expert diagnostic'],
    intentVerbs: SHARED_VERBS,
    qualifiers: ['certifié', 'pas cher', 'rapide'],
    commonQueries: [],
  },
}

/** Get natural terms for a service slug, with safe fallback */
export function getNaturalTerm(serviceSlug: string): NaturalTerms {
  return (
    NATURAL_TERMS[serviceSlug] ?? {
      singular: serviceSlug.replace(/-/g, ' '),
      plural: serviceSlug.replace(/-/g, ' ') + 's',
      article: `un ${serviceSlug.replace(/-/g, ' ')}`,
      feminin: false,
      synonyms: [],
      intentVerbs: SHARED_VERBS,
      qualifiers: ['pas cher', 'de confiance'],
      commonQueries: [],
    }
  )
}
