#!/bin/bash
BASE="https://servicesartisans.fr"
PASS=0
FAIL=0
SLOW=0

test_url() {
  local path="$1"
  local url="${BASE}${path}"
  local output
  output=$(curl -s -o /dev/null -w "%{http_code} %{time_starttransfer} %{time_total}" -H "Accept: text/html" --max-time 15 "$url" 2>/dev/null)
  local code ttfb total
  code=$(echo "$output" | awk '{print $1}')
  ttfb=$(echo "$output" | awk '{print $2}')
  total=$(echo "$output" | awk '{print $3}')
  local icon="OK"
  if [[ "$code" == "200" || "$code" == "301" || "$code" == "302" || "$code" == "308" ]]; then
    ((PASS++))
  elif [[ "$code" == "000" ]]; then
    icon="TIMEOUT"
    ((FAIL++))
  else
    icon="FAIL"
    ((FAIL++))
  fi
  local sf=""
  if command -v bc &>/dev/null; then
    local check=$(echo "$ttfb > 1.0" | bc -l 2>/dev/null)
    if [[ "$check" == "1" ]]; then
      sf=" [SLOW]"
      ((SLOW++))
    fi
  fi
  printf "%-4s %-60s %-7s TTFB:%-8s Total:%-8s%s\n" "$code" "$path" "$icon" "${ttfb}s" "${total}s" "$sf"
}

test_api() {
  local path="$1"
  local method="${2:-GET}"
  local url="${BASE}/api${path}"
  local output
  output=$(curl -s -o /dev/null -w "%{http_code} %{time_starttransfer} %{time_total}" -X "$method" --max-time 10 "$url" 2>/dev/null)
  local code ttfb total
  code=$(echo "$output" | awk '{print $1}')
  ttfb=$(echo "$output" | awk '{print $2}')
  total=$(echo "$output" | awk '{print $3}')
  local icon="OK"
  if [[ "$code" == "200" || "$code" == "401" || "$code" == "405" || "$code" == "400" || "$code" == "301" || "$code" == "302" || "$code" == "308" ]]; then
    ((PASS++))
  elif [[ "$code" == "000" ]]; then
    icon="TIMEOUT"
    ((FAIL++))
  else
    icon="FAIL"
    ((FAIL++))
  fi
  printf "%-4s %-60s %-7s TTFB:%-8s Total:%-8s\n" "$code" "/api${path}" "$icon" "${ttfb}s" "${total}s"
}

echo "================================================="
echo "  SERVICESARTISANS - TEST COMPLET DES ROUTES"
echo "================================================="
echo ""

echo "-- PAGES STATIQUES --"
test_url "/"
test_url "/a-propos"
test_url "/comment-ca-marche"
test_url "/contact"
test_url "/carrieres"
test_url "/faq"
test_url "/glossaire"
test_url "/plan-du-site"
test_url "/garantie"
test_url "/normes"
test_url "/cgv"
test_url "/confidentialite"
test_url "/mentions-legales"
test_url "/mediation"
test_url "/politique-avis"
test_url "/notre-processus-de-verification"
test_url "/accessibilite"
test_url "/partenaires"
test_url "/presse"
test_url "/recherche"
test_url "/mes-favoris"
test_url "/statisiques-artisans-france"
test_url "/offline"

echo ""
echo "-- SERVICES --"
test_url "/services"
test_url "/services/plombier"
test_url "/services/electricien"
test_url "/services/chauffagiste"
test_url "/services/couvreur"
test_url "/services/serrurier"
test_url "/services/peintre"
test_url "/services/menuisier"
test_url "/services/carreleur"
test_url "/services/maconnerie"
test_url "/services/climatisation"
test_url "/services/plombier/paris"
test_url "/services/electricien/lyon"
test_url "/services/chauffagiste/marseille"
test_url "/services/couvreur/toulouse"
test_url "/services/serrurier/bordeaux"
test_url "/services/plombier/lille"
test_url "/services/peintre/nantes"
test_url "/services/menuisier/strasbourg"

echo ""
echo "-- DEVIS --"
test_url "/devis"
test_url "/devis/plombier"
test_url "/devis/electricien"
test_url "/devis/chauffagiste"
test_url "/devis/plombier/paris"
test_url "/devis/electricien/lyon"
test_url "/devis/chauffagiste/marseille"

echo ""
echo "-- TARIFS --"
test_url "/tarifs"
test_url "/tarifs/plombier"
test_url "/tarifs/electricien"
test_url "/tarifs/chauffagiste"
test_url "/tarifs/couvreur"
test_url "/tarifs/plombier/paris"
test_url "/tarifs/electricien/lyon"
test_url "/tarifs/chauffagiste/marseille"
test_url "/tarifs/plombier/paris/debouchage-canalisation"
test_url "/tarifs/electricien/lyon/installation-tableau-electrique"

echo ""
echo "-- TARIFS ARTISANS --"
test_url "/tarifs-artisans"
test_url "/tarifs-artisans/plombier"
test_url "/tarifs-artisans/plombier/paris"

echo ""
echo "-- URGENCE --"
test_url "/urgence"
test_url "/urgence/plombier"
test_url "/urgence/electricien"
test_url "/urgence/serrurier"
test_url "/urgence/plombier/paris"
test_url "/urgence/plombier/marseille"
test_url "/urgence/serrurier/lyon"

echo ""
echo "-- AVIS --"
test_url "/avis"
test_url "/avis/plombier"
test_url "/avis/electricien"
test_url "/avis/plombier/paris"
test_url "/avis/electricien/lyon"

echo ""
echo "-- PROBLEMES --"
test_url "/problemes"
test_url "/problemes/fuite-eau"
test_url "/problemes/panne-electrique"
test_url "/problemes/fuite-eau/paris"

echo ""
echo "-- REGIONS --"
test_url "/regions"
test_url "/regions/ile-de-france"
test_url "/regions/auvergne-rhone-alpes"
test_url "/regions/provence-alpes-cote-d-azur"
test_url "/regions/ile-de-france/plombier"
test_url "/regions/auvergne-rhone-alpes/electricien"

echo ""
echo "-- DEPARTEMENTS --"
test_url "/departements"
test_url "/departements/paris"
test_url "/departements/rhone"
test_url "/departements/bouches-du-rhone"
test_url "/departements/paris/plombier"

echo ""
echo "-- VILLES --"
test_url "/villes"
test_url "/villes/paris"
test_url "/villes/lyon"
test_url "/villes/marseille"
test_url "/villes/toulouse"
test_url "/villes/bordeaux"
test_url "/villes/paris/montmartre"
test_url "/villes/lyon/bellecour"

echo ""
echo "-- BAROMETRE --"
test_url "/barometre"
test_url "/barometre/regions"
test_url "/barometre/regions/ile-de-france"
test_url "/barometre/tarifs"
test_url "/barometre/tarifs/plombier"
test_url "/barometre-prix"

echo ""
echo "-- BLOG --"
test_url "/blog"
test_url "/blog/categorie/renovation"
test_url "/blog/tag/plomberie"

echo ""
echo "-- GUIDES --"
test_url "/guides"
test_url "/guides/renovation-salle-de-bain"
test_url "/guides/maprimerenov-2026"
test_url "/guides/devis-travaux"
test_url "/guides/trouver-artisan"
test_url "/guides/isolation-thermique"
test_url "/guides/pompe-a-chaleur"
test_url "/guides/renovation-energetique-complete"
test_url "/guides/normes-electriques"
test_url "/guides/aides-renovation-2026"
test_url "/guides/eviter-arnaques-artisan"
test_url "/guides/garantie-decennale"
test_url "/guides/permis-construire"
test_url "/guides/renovation-toiture"
test_url "/guides/renovation-cuisine"
test_url "/guides/renovation-fenetres"
test_url "/guides/isolation-combles"
test_url "/guides/extension-maison"
test_url "/guides/diagnostics-immobiliers"
test_url "/guides/declaration-prealable-travaux"
test_url "/guides/assurance-dommage-ouvrage"
test_url "/guides/artisan-rge"
test_url "/guides/budget-renovation"
test_url "/guides/travaux-copropriete"

echo ""
echo "-- COMPARAISON & QUESTIONS --"
test_url "/comparaison"
test_url "/questions"

echo ""
echo "-- OUTILS --"
test_url "/outils/calculateur-prix"
test_url "/outils/diagnostic"
test_url "/calculateur"
test_url "/calendrier-travaux"
test_url "/checklist-travaux"
test_url "/widget-prix"
test_url "/widget"
test_url "/carte-artisans"
test_url "/avant-apres"
test_url "/badge-artisan"
test_url "/verifier-artisan"
test_url "/artisans"

echo ""
echo "-- AUTH --"
test_url "/connexion"
test_url "/inscription"
test_url "/inscription-artisan"
test_url "/mot-de-passe-oublie"
test_url "/definir-mot-de-passe"

echo ""
echo "-- ESPACE ARTISAN (auth required) --"
test_url "/espace-artisan"
test_url "/espace-artisan/dashboard"
test_url "/espace-artisan/leads"
test_url "/espace-artisan/profil"
test_url "/espace-artisan/messages"
test_url "/espace-artisan/portfolio"
test_url "/espace-artisan/avis"
test_url "/espace-artisan/calendrier"
test_url "/espace-artisan/parametres"
test_url "/espace-artisan/abonnement"
test_url "/espace-artisan/statistiques"
test_url "/espace-artisan/equipe"
test_url "/espace-artisan/demandes"
test_url "/espace-artisan/demandes-recues"
test_url "/espace-artisan/avis-recues"
test_url "/espace-artisan/leads/statistiques"

echo ""
echo "-- ESPACE CLIENT (auth required) --"
test_url "/espace-client"
test_url "/espace-client/mes-demandes"
test_url "/espace-client/avis"
test_url "/espace-client/messages"
test_url "/espace-client/factures"
test_url "/espace-client/parametres"
test_url "/espace-client/avis-donnes"

echo ""
echo "-- ADMIN --"
test_url "/admin"
test_url "/admin/connexion"

echo ""
echo "-- SEO / SITEMAPS / FEEDS --"
test_url "/sitemap.xml"
test_url "/robots.txt"
test_url "/feed.xml"
test_url "/api/sitemap-index"

echo ""
echo "-- API ROUTES --"
test_api "/auth/me"
test_api "/health" "POST"
test_api "/contact" "POST"
test_api "/widget"
test_api "/match"
test_api "/geo/menu-data"
test_api "/providers/listing"
test_api "/providers/by-city"
test_api "/reviews"
test_api "/reviews/featured"
test_api "/artisans"
test_api "/badge"
test_api "/badge/verified"
test_api "/badge/search"
test_api "/estimation" "POST"
test_api "/stats/public"
test_api "/prix-widget"
test_api "/v1/docs"
test_api "/v1/stats"
test_api "/v1/tarifs"
test_api "/newsletter" "POST"
test_api "/verify-siret" "POST"
test_api "/geocode" "POST"
test_api "/indexnow" "POST"
test_api "/availability"
test_api "/availability/slots"
test_api "/notifications"
test_api "/quotes"
test_api "/bookings"
test_api "/messages"
test_api "/conversations"
test_api "/devis"
test_api "/social-proof" "POST"
test_api "/revalidate" "POST"
test_api "/analytics" "POST"
test_api "/stripe/webhook" "POST"
test_api "/gdpr/consent" "POST"
test_api "/portfolio"
test_api "/inscription-artisan" "POST"

echo ""
echo "================================================="
echo "  RESUME"
echo "================================================="
echo "  OK:     $PASS"
echo "  FAIL:   $FAIL"
echo "  SLOW:   $SLOW (TTFB > 1s)"
echo "  Total:  $((PASS + FAIL))"
echo "================================================="
