/**
 * LLM spend monitor — rolling-window cost guard over `critic_runs`.
 *
 * Why critic_runs : it is the only LLM cost that is PERSISTED (migration 525,
 * `cost_usd` per run) AND generated by an AUTOMATED batch (the `cluster-critic`
 * cron runs Critic Opus on every generated page). That automation is the only
 * runaway-cost risk — a looping or oversized batch can silently rack up dollars.
 * Interactive LLM calls (answer-engine per request, admin prospection AI on
 * click) are bounded per-invocation and their cost is logged, not batched, so
 * they are out of scope here.
 *
 * The cron `src/app/api/cron/llm-spend-alert` calls `computeLlmSpendReport`
 * daily and escalates to Sentry/logger when the rolling-24h critic spend
 * crosses the env-configured thresholds.
 */

import type { SupabaseClient } from '@supabase/supabase-js'

export type SpendStatus = 'ok' | 'warning' | 'critical'

export type LlmSpendReport = {
  status: SpendStatus
  rolling24hUSD: number
  monthToDateUSD: number
  runCount24h: number
  warnThresholdUSD: number
  critThresholdUSD: number
  byModel: Array<{ model: string; costUSD: number; runs: number }>
}

// Defaults sized for a normal cluster-critic day (Opus 4.7 @ $15/$75 per M
// tokens → a few dollars). >20 USD/24h signals an unusually large or looping
// batch; >50 USD/24h is treated as runaway. Override per-env if the batch
// cadence changes.
export const DEFAULT_WARN_USD = 20
export const DEFAULT_CRIT_USD = 50

export function readThresholds(env: NodeJS.ProcessEnv = process.env): {
  warnThresholdUSD: number
  critThresholdUSD: number
} {
  const warn = Number(env.LLM_SPEND_DAILY_WARN_USD)
  const crit = Number(env.LLM_SPEND_DAILY_CRIT_USD)
  return {
    warnThresholdUSD: Number.isFinite(warn) && warn > 0 ? warn : DEFAULT_WARN_USD,
    critThresholdUSD: Number.isFinite(crit) && crit > 0 ? crit : DEFAULT_CRIT_USD,
  }
}

export function classifySpend(rolling24hUSD: number, warn: number, crit: number): SpendStatus {
  if (rolling24hUSD >= crit) return 'critical'
  if (rolling24hUSD >= warn) return 'warning'
  return 'ok'
}

type CriticCostRow = { model: string; cost_usd: number | null; created_at: string }

function round(n: number): number {
  return Number(n.toFixed(4))
}

export async function computeLlmSpendReport(
  supabase: SupabaseClient,
  now: Date,
  env: NodeJS.ProcessEnv = process.env
): Promise<LlmSpendReport> {
  const { warnThresholdUSD, critThresholdUSD } = readThresholds(env)
  const since24h = new Date(now.getTime() - 24 * 60 * 60 * 1000).toISOString()
  const since30d = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString()

  const { data, error } = await supabase
    .from('critic_runs')
    .select('model, cost_usd, created_at')
    .gte('created_at', since30d)
    .not('cost_usd', 'is', null)

  if (error) throw new Error(`critic_runs spend query failed: ${error.message}`)

  const rows = (data ?? []) as CriticCostRow[]
  let rolling24hUSD = 0
  let monthToDateUSD = 0
  let runCount24h = 0
  const modelMap = new Map<string, { costUSD: number; runs: number }>()

  for (const r of rows) {
    const cost = r.cost_usd ?? 0
    monthToDateUSD += cost
    if (r.created_at >= since24h) {
      rolling24hUSD += cost
      runCount24h += 1
      const m = modelMap.get(r.model) ?? { costUSD: 0, runs: 0 }
      m.costUSD += cost
      m.runs += 1
      modelMap.set(r.model, m)
    }
  }

  rolling24hUSD = round(rolling24hUSD)
  monthToDateUSD = round(monthToDateUSD)

  const byModel = Array.from(modelMap.entries())
    .map(([model, v]) => ({ model, costUSD: round(v.costUSD), runs: v.runs }))
    .sort((a, b) => b.costUSD - a.costUSD)

  return {
    status: classifySpend(rolling24hUSD, warnThresholdUSD, critThresholdUSD),
    rolling24hUSD,
    monthToDateUSD,
    runCount24h,
    warnThresholdUSD,
    critThresholdUSD,
    byModel,
  }
}
