/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 8 services, 446 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen8: Record<string, { src: string; alt: string }[]> = {
  diagnostiqueur: [
    {
      src: unsplash('1676630656246-3047520adfdf'),
      alt: 'a man working on a wall with a screwdriver',
    },
    { src: unsplash('1572120360610-d971b9d7767c'), alt: 'trees beside white house' },
    {
      src: unsplash('1645677040449-17dc9f184003'),
      alt: 'a person standing in front of a red door',
    },
    { src: unsplash('1516156008625-3a9d6067fab5'), alt: 'aerial photography of rural' },
    {
      src: unsplash('1516455590571-18256e5bb9ff'),
      alt: 'round clear glass-top table and five gray chairs dining se',
    },
    {
      src: unsplash('1769776400238-cd24612240ea'),
      alt: 'Magnifying glass over a wooden house model.',
    },
    {
      src: unsplash('1581578731567-c884e2816aaa'),
      alt: 'man in black t-shirt and blue denim jeans playing guitar',
    },
    {
      src: unsplash('1687982121908-eed863615c13'),
      alt: 'a man standing outside of a building drinking from a bottle',
    },
    { src: unsplash('1536940135352-b4b3875df888'), alt: 'man reading book in front of window' },
    { src: unsplash('1646776202025-648de1f2f0fe'), alt: 'a man standing in front of a blue door' },
    {
      src: unsplash('1581579746581-3954f2a31e7a'),
      alt: 'man in blue shirt and blue denim jeans sitting on brown wooden table',
    },
    {
      src: unsplash('1560520653-9e0e4c89eb11'),
      alt: 'white and red wooden house beside grey framed magnifying glass',
    },
    { src: unsplash('1657672733372-e6c8741d2e6c'), alt: 'a man brushing his teeth' },
    { src: unsplash('1504579524716-7eeaa8704f14'), alt: 'green bush by house at daytime' },
    {
      src: unsplash('1642775955839-830e41b93682'),
      alt: 'a gray house with a white porch and a brown door',
    },
    { src: unsplash('1585458667865-d3598174d8ff'), alt: 'man and woman sitting on floor' },
    {
      src: unsplash('1588712757679-06a3428ce119'),
      alt: 'brown brick building under blue sky during daytime',
    },
    {
      src: unsplash('1709787627975-9cb37bbeca60'),
      alt: 'a couple of people that are sitting in front of a house',
    },
    {
      src: unsplash('1714647212027-2a0ad30cb4f1'),
      alt: 'a man and a woman standing in a living room',
    },
    { src: unsplash('1632759145351-1d592919f522'), alt: 'a man standing on the roof of a house' },
    { src: unsplash('1611410885997-0636819b3cf0'), alt: 'white and brown concrete house' },
    { src: unsplash('1573941252622-4118390c7993'), alt: 'white and brown house' },
    {
      src: unsplash('1731341711808-7a103eff1d20'),
      alt: 'A man standing in a living room next to a fire place',
    },
    {
      src: unsplash('1585492240360-4766db177dd3'),
      alt: 'white and brown wooden house under blue sky during daytime',
    },
    {
      src: unsplash('1753232535908-9f92ba677225'),
      alt: 'A beautiful brick house sits on a green lawn.',
    },
    {
      src: unsplash('1634051808324-4baa77cb4ef8'),
      alt: 'a couple of men standing on top of a wooden porch',
    },
    { src: unsplash('1680808783328-37525aee02b2'), alt: 'a house with a clock on the front of it' },
    { src: unsplash('1617118602031-1edde7582212'), alt: 'green ruler on white surface' },
    {
      src: unsplash('1581579746640-99fc3d5d0e40'),
      alt: 'woman in pink long sleeve shirt standing beside black wood burner',
    },
    {
      src: unsplash('1595844730289-b248c919d6f9'),
      alt: 'person holding black and green power tool',
    },
    {
      src: unsplash('1694521787193-9293daeddbaa'),
      alt: 'a couple of men standing next to each other',
    },
    { src: unsplash('1604070974077-1482430f5122'), alt: 'gray concrete building during daytime' },
    { src: unsplash('1582176410262-005b25ee4aa7'), alt: 'red and white labeled pack' },
    {
      src: unsplash('1607764842505-82955490b8dc'),
      alt: 'black and white bird on white concrete building during daytime',
    },
    {
      src: unsplash('1723460041120-104bc4a62ee3'),
      alt: 'A building with scaffolding on top of it',
    },
    { src: unsplash('1527199768775-bdabf8b32f61'), alt: 'man doing welding on outdoors' },
    {
      src: unsplash('1659353586512-bcc4c7182d01'),
      alt: 'a person wearing a hard hat and looking at a tablet',
    },
    {
      src: unsplash('1653088078179-98ec14b69580'),
      alt: 'a blurry photo of a building with a clock tower',
    },
    {
      src: unsplash('1748027869634-fc2e545cfb0c'),
      alt: 'A construction worker is examining a door.',
    },
    { src: unsplash('1661168134865-2bc6286cc308'), alt: 'a building under construction' },
    { src: unsplash('1554035042-34f354352d97'), alt: '2 men in white hard hat holding a machine' },
    {
      src: unsplash('1747192904662-e03e8da1e0ab'),
      alt: 'A building is under construction with scaffolding.',
    },
    {
      src: unsplash('1748175471682-de85d9d5231d'),
      alt: 'An unfinished skyscraper structure rises under blue sky.',
    },
    { src: unsplash('1669234611002-173964d1c694'), alt: 'a building under construction' },
    { src: unsplash('1599707233265-10accf051fe0'), alt: 'orange crane on top of building' },
    { src: unsplash('1603838656896-b8091f534d66'), alt: 'brown concrete building during daytime' },
    {
      src: unsplash('1694521787799-ad4ad241cb39'),
      alt: 'a group of men standing next to each other in front of a building',
    },
    {
      src: unsplash('1701064265806-6dcfb317ade5'),
      alt: 'a building under construction with lots of wooden sticks sticking out of it',
    },
    { src: unsplash('1547002889-5cb2cb735346'), alt: 'grayscale high rise building' },
    { src: unsplash('1661520604588-b0f6c6ae46f0'), alt: 'a building with many windows' },
    {
      src: unsplash('1705579604303-3086e4162d34'),
      alt: 'a woman in a safety vest talking to a woman in a hard hat',
    },
    { src: unsplash('1564525804719-cfe95311cacd'), alt: 'silhouette of man inside building' },
    { src: unsplash('1537205125380-5e9b86a7b2b9'), alt: 'white high-rise building' },
    {
      src: unsplash('1772551419789-8075b4055f9e'),
      alt: 'Modern buildings under construction against a hazy sky',
    },
    {
      src: unsplash('1709052702774-6c534fc62fae'),
      alt: 'a very tall building with a bunch of wires on top of it',
    },
    { src: unsplash('1662154646905-8ad92263d5da'), alt: 'a building under construction' },
    {
      src: unsplash('1691341208697-e1ed6c1b233a'),
      alt: 'a tall building under construction with scaffolding around it',
    },
    {
      src: unsplash('1762407785760-3e4c22aede86'),
      alt: 'Unfinished building under construction with scaffolding.',
    },
    { src: unsplash('1618385455730-2571c38966b7'), alt: 'person using black laptop computer' },
    {
      src: unsplash('1639563722312-11bc9a31ee34'),
      alt: 'a construction worker with a yellow helmet on',
    },
  ],
  etancheiste: [
    {
      src: unsplash('1591645321243-3adc1e75cfdc'),
      alt: 'man in black jacket walking on sidewalk during daytime',
    },
    {
      src: unsplash('1681812490689-2bb9ab7ca660'),
      alt: 'a man in a raincoat is working on a boat',
    },
    { src: unsplash('1586774839818-40c7e1cd1243'), alt: 'brown and black wooden surface' },
    {
      src: unsplash('1621682988371-83cccd25c323'),
      alt: 'man in orange and black jacket and blue denim jeans jumping on gray concrete floor under',
    },
    {
      src: unsplash('1633527992904-53f86f81a23a'),
      alt: 'a close up of a cotton plant with a blurry background',
    },
    {
      src: unsplash('1663566673926-04241bfbe038'),
      alt: 'a pair of black and white ear buds on a white surface',
    },
    {
      src: unsplash('1636100686647-6c98cd346778'),
      alt: 'a man standing in the rain with his hands out',
    },
    { src: unsplash('1651823644613-4909ffd40614'), alt: 'a pair of brown shoes' },
    {
      src: unsplash('1599681906464-ec599150575b'),
      alt: 'black leather strap silver round analog watch',
    },
    {
      src: unsplash('1680699232561-de5452f56f8d'),
      alt: 'a couple of men standing next to a fire truck',
    },
    { src: unsplash('1624840048945-36bff42fe209'), alt: 'silver iphone 5s on white textile' },
    {
      src: unsplash('1636099652696-f5bec08a7503'),
      alt: 'a pair of blue headphones sitting on top of a phone',
    },
    {
      src: unsplash('1598034989845-48532781987e'),
      alt: 'black and gray speaker on brown wooden table',
    },
    { src: unsplash('1557901359-71e5668184b1'), alt: 'black framed sunglasses' },
    {
      src: unsplash('1681812507901-bbe29584bb31'),
      alt: 'a man in an orange safety suit painting a sign',
    },
    { src: unsplash('1636451096144-a4304c34c169'), alt: 'a pair of ear buds laying on a rock' },
    {
      src: unsplash('1681812491387-de0d8a1968b2'),
      alt: 'a man in yellow pants and a yellow hat walking down a road',
    },
    { src: unsplash('1681812490697-efdcb9be343b'), alt: 'a man in a wet suit holding a fish' },
    {
      src: unsplash('1775204440210-7d9c6d03574b'),
      alt: 'Water droplets on green and white striped fabric',
    },
    { src: unsplash('1607038602457-5bc473713cb5'), alt: 'water droplets on green surface' },
    {
      src: unsplash('1520991323542-c159d7282b9f'),
      alt: 'person in orange top wearing backpack walking on body of water in forest during daytime',
    },
    { src: unsplash('1600333791066-f3c7e752b44e'), alt: 'black and pink camera on tripod' },
    {
      src: unsplash('1648899936678-d66551cb292c'),
      alt: 'a red speaker sitting on top of a wooden table',
    },
    {
      src: unsplash('1546019739-f442c5e4696d'),
      alt: 'black and white drones on blue wooden bench',
    },
    { src: unsplash('1562028798-f6f372d1a6f8'), alt: 'close view of banana leaves' },
    { src: unsplash('1562753208-5de026733874'), alt: 'green banana leaves' },
    {
      src: unsplash('1610708946258-54af43706e64'),
      alt: 'child in black and yellow hoodie standing on white textile',
    },
    { src: unsplash('1617729220754-a84754c1be54'), alt: 'woman in yellow collared shirt smiling' },
    {
      src: unsplash('1593518779115-831235f45ec1'),
      alt: 'woman in blue and white polka dot tank top sitting on orange kayak on river during',
    },
    {
      src: unsplash('1775204440954-32f7923a5b51'),
      alt: 'Green and white striped fabric with water droplets.',
    },
    { src: unsplash('1678020704290-86c3bc1bc6d3'), alt: 'a close up of moss growing on a roof' },
    { src: unsplash('1678020706579-de8ce9e33ca8'), alt: 'moss growing on the roof of a building' },
    {
      src: unsplash('1705831890138-e0f1e38d5ac7'),
      alt: 'a bunch of trash sitting on the side of a building',
    },
    {
      src: unsplash('1738669465747-65e6454f2edc'),
      alt: 'A pigeon is perched on the roof of a house',
    },
    {
      src: unsplash('1763065137209-fae84984e38e'),
      alt: 'A seagull stands on a ledge with trees in background.',
    },
    {
      src: unsplash('1743517126833-4b111443311e'),
      alt: 'A pigeon is silhouetted against a blurry background.',
    },
    {
      src: unsplash('1764923436525-a67aff16187b'),
      alt: 'A tabby cat rests beside a uniqlo shopping bag.',
    },
    {
      src: unsplash('1775276406121-a1fdf9606b05'),
      alt: 'Close-up of weathered terracotta roof tiles in rows.',
    },
    {
      src: unsplash('1704216812766-c62ad0d9ff28'),
      alt: 'a pigeon standing next to a wooden fence',
    },
    {
      src: unsplash('1765468199472-eec8e065f410'),
      alt: 'Two drinks with autumn leaves decoration',
    },
    {
      src: unsplash('1718114759401-2decc5fff6e5'),
      alt: 'a view of a building from the top of a building',
    },
    { src: unsplash('1563174499-83c108efd397'), alt: 'brown shingle roof' },
    {
      src: unsplash('1638446160622-4965f6fe6efe'),
      alt: 'a couple of small trees standing in the middle of a snow covered field',
    },
    {
      src: unsplash('1642388514011-b4b4f43a2179'),
      alt: 'a close up of a roof with a broken gutter',
    },
    { src: unsplash('1681049400158-0ff6249ac315'), alt: 'two men working on the roof of a house' },
    { src: unsplash('1635424709845-3a85ad5e1f5e'), alt: 'a couple of people that are on a roof' },
    { src: unsplash('1544324577-af0a4a91f6ff'), alt: 'brown attic' },
    { src: unsplash('1570038797288-683aab8ff627'), alt: 'brown and white roof during daytime' },
    { src: unsplash('1668683997214-771199dcbaf2'), alt: 'a dock with trees in the background' },
    {
      src: unsplash('1674485169641-bcb2bf6f1df9'),
      alt: 'a man in a white coverall spray painting a roof',
    },
    { src: unsplash('1658536851794-4afd5c621aa8'), alt: 'a close up of a wood floor' },
    {
      src: unsplash('1635424825057-7fb6dcd651ef'),
      alt: 'a man working on a roof with a power drill',
    },
    {
      src: unsplash('1722235569646-3ccaca59bd59'),
      alt: 'A gutter gutter gutter gutter gutter gutter gutter gut',
    },
    { src: unsplash('1626977990516-c807a31c42d4'), alt: 'black and brown wooden frame' },
    {
      src: unsplash('1718284707769-f16eddc6b268'),
      alt: 'a bird sitting on top of a roof next to a building',
    },
    { src: unsplash('1657195721935-e73e545a2aae'), alt: 'a close-up of a roof' },
    { src: unsplash('1574693464259-4de81ffb9231'), alt: 'white painted wall' },
    {
      src: unsplash('1759073026614-cef5b89b1b6e'),
      alt: 'Close-up of weathered hexagonal roof tiles with moss.',
    },
    {
      src: unsplash('1606582218474-f49568e273fd'),
      alt: 'brown concrete brick wall during daytime',
    },
    {
      src: unsplash('1599570750519-a26b62691be7'),
      alt: 'brown roof tiles in close up photography',
    },
  ],
  nettoyage: [
    {
      src: unsplash('1581578731548-c64695cc6952'),
      alt: 'woman in white long sleeve shirt and blue denim jeans standing beside white wooden framed glass',
    },
    { src: unsplash('1437326300822-01d8f13c024f'), alt: 'man cleaning on floor beside white wall' },
    {
      src: unsplash('1601160458000-2b11f9fa1a0e'),
      alt: 'person in white robe holding black and yellow umbrella',
    },
    { src: unsplash('1669101602108-fa5ba89507ee'), alt: 'a person standing on a treadmill' },
    {
      src: unsplash('1504827274833-7db1774520e3'),
      alt: 'person using ski boards during daytime photography',
    },
    { src: unsplash('1571568495363-99048b36777b'), alt: 'red and black sports bike during day' },
    { src: unsplash('1580970098304-a4c30996b7db'), alt: 'person surfing on sea during daytime' },
    {
      src: unsplash('1747659354528-b534bcd71aea'),
      alt: 'Hand holding a white and black spray bottle.',
    },
    { src: unsplash('1569202743734-fc8657296e6a'), alt: 'white sports coupe on road' },
    {
      src: unsplash('1774271101773-8e7cacedf12b'),
      alt: 'A window cleaner works high on a building exterior.',
    },
    {
      src: unsplash('1774977867750-5b56e82051d0'),
      alt: 'Man in black shirt and hard hat using a tool.',
    },
    {
      src: unsplash('1775178120132-f0ff7fd5cb40'),
      alt: 'Worker in blue uniform cleans window with spray bottle',
    },
    { src: unsplash('1552234458-9a63237d6d93'), alt: 'a blue ball is surrounded by white balls' },
    {
      src: unsplash('1579528542333-4148f1769c35'),
      alt: 'person wearing blue and white nike athletic shoes',
    },
    {
      src: unsplash('1775654063422-54e0a71578ad'),
      alt: 'A man cleaning windows on a tall building',
    },
    {
      src: unsplash('1623006108099-487c445e950a'),
      alt: 'a white sports car parked on the side of the road',
    },
    { src: unsplash('1762087021974-b0729f37a8fe'), alt: 'Window cleaners work on a tall building' },
    {
      src: unsplash('1774979161326-6ba6ed3a1864'),
      alt: 'Two window cleaners work on a tall building.',
    },
    {
      src: unsplash('1747659365283-dd36e0fb5b80'),
      alt: 'Person holds a white spray bottle overhead.',
    },
    { src: unsplash('1747659362772-3caabc37c579'), alt: 'A close-up shot of a spray bottle.' },
    { src: unsplash('1747659365190-c4ceea97aff7'), alt: 'A hand holds a white pump sprayer.' },
    {
      src: unsplash('1742353980377-b8e42932c590'),
      alt: 'A robotic pool cleaner is working underwater.',
    },
    { src: unsplash('1747659364071-96c1d30b520e'), alt: 'A hand holds a spray bottle.' },
    { src: unsplash('1747659354838-7ac98504dbb4'), alt: 'A person is holding a water bottle.' },
    { src: unsplash('1486048084996-2cec8eabc2ad'), alt: 'group of people riding white ski lift' },
    {
      src: unsplash('1741021632650-162065ae2b0d'),
      alt: 'Window washers are cleaning a tall building.',
    },
    { src: unsplash('1771491237209-b89bc7290588'), alt: 'Man cleaning car dashboard with brush' },
    {
      src: unsplash('1759647516042-7ab902682d9c'),
      alt: 'Hands cleaning a camera lens with a cloth.',
    },
    {
      src: unsplash('1629150631968-f4b17111acf3'),
      alt: 'yellow ferrari 458 italia parked near white building',
    },
    {
      src: unsplash('1629150681462-11ecd445cbf8'),
      alt: 'yellow ferrari car on gray asphalt road during daytime',
    },
    {
      src: unsplash('1758273238415-01ec03d9ef27'),
      alt: 'A woman mops a bright, modern living room floor.',
    },
    {
      src: unsplash('1758273238594-9a9d6c20eaa2'),
      alt: 'Woman mopping floor while listening to music.',
    },
    {
      src: unsplash('1758273238795-c284e5ae09b6'),
      alt: 'Woman with headphones happily cleaning with yellow gloves',
    },
    {
      src: unsplash('1758273705433-d1485e8f00e0'),
      alt: 'Woman singing and dancing while vacuuming a room',
    },
    {
      src: unsplash('1758273238370-3bc08e399620'),
      alt: 'Woman happily mopping the floor in a bright room.',
    },
    {
      src: unsplash('1758272422155-d898efd14f81'),
      alt: 'Woman with headphones mopping a wooden floor',
    },
    {
      src: unsplash('1758273238847-bc2c2548e210'),
      alt: 'Person happily mopping the floor while listening to music.',
    },
    {
      src: unsplash('1758273705438-2bb9e0eb21b7'),
      alt: 'Woman with headphones cleaning and dancing',
    },
    {
      src: unsplash('1758272421751-963195322eaa'),
      alt: 'Woman wearing yellow gloves cleaning wooden surface',
    },
    { src: unsplash('1758273238903-b5ca5f9988d1'), alt: 'Woman with headphones cleaning a shelf' },
    { src: unsplash('1758272421664-ae691f6cdafc'), alt: 'Woman dancing while mopping the floor' },
    {
      src: unsplash('1758273238564-806f750a2cce'),
      alt: 'Woman cleaning floor with mop while wearing headphones',
    },
    {
      src: unsplash('1758273238698-c98a45a8df9a'),
      alt: 'Woman with headphones cleaning floor with mop',
    },
    {
      src: unsplash('1758273238738-9410f7e9d53c'),
      alt: 'Woman wearing headphones cleans near a window.',
    },
    {
      src: unsplash('1758273705629-02e3c4bee11d'),
      alt: 'Woman happily vacuuming living room while listening to music.',
    },
    {
      src: unsplash('1758523670739-0d26a3ee976d'),
      alt: 'A woman vacuuming a bright, modern living room',
    },
    {
      src: unsplash('1758273238715-2b6c250167c4'),
      alt: 'Woman with headphones cleaning and dancing happily',
    },
    {
      src: unsplash('1758273238741-f33ab240baa0'),
      alt: 'Young woman with headphones cleaning a shelf',
    },
    {
      src: unsplash('1758273705627-937374bfa978'),
      alt: 'Woman happily vacuuming a bright, modern living room.',
    },
    {
      src: unsplash('1758272421772-5b08f08dc2ea'),
      alt: 'Woman cleaning while listening to music on headphones',
    },
    { src: unsplash('1758272421995-e993f97fae22'), alt: 'Woman in yellow gloves cleaning a shelf' },
    {
      src: unsplash('1758272421701-569f31f05fd1'),
      alt: 'Woman with headphones mops floor in living room',
    },
    {
      src: unsplash('1758272422189-b10f36fd4ddd'),
      alt: 'Woman mopping floor while wearing headphones.',
    },
    {
      src: unsplash('1758687125687-512a331f6a0a'),
      alt: 'Young girl vacuuming a striped rug in a living room.',
    },
    {
      src: unsplash('1758273705601-50b1b61f7e6c'),
      alt: 'Woman vacuuming a bright, modern living room',
    },
    {
      src: unsplash('1758273705511-834c8c3204e7'),
      alt: 'Woman vacuuming and listening to music with headphones.',
    },
    {
      src: unsplash('1758523670798-db1acfb7f3b0'),
      alt: 'Man playing vacuum cleaner like a guitar',
    },
    {
      src: unsplash('1758273238947-7eb530b408e4'),
      alt: 'Woman happily vacuuming a bright, modern room',
    },
    {
      src: unsplash('1758691030988-c7c55ab2ba18'),
      alt: 'Elderly woman vacuuming a colorful living room floor.',
    },
    {
      src: unsplash('1758273238400-9b1367ae90ec'),
      alt: 'Woman happily mopping a bright, modern living room.',
    },
  ],
  'panneaux-solaires': [
    {
      src: unsplash('1635424825057-7fb6dcd651ef'),
      alt: 'a man working on a roof with a power drill',
    },
    { src: unsplash('1635424709961-f3a150459ad4'), alt: 'two men working on the roof of a house' },
    {
      src: unsplash('1635424710918-d5c138981922'),
      alt: 'a man in a yellow shirt with a chainsaw on a roof',
    },
    { src: unsplash('1635424709870-cdc6e64f0e20'), alt: 'a couple of men working on a roof' },
    { src: unsplash('1635424709845-3a85ad5e1f5e'), alt: 'a couple of people that are on a roof' },
    {
      src: unsplash('1635424824849-1b09bdcc55b1'),
      alt: 'a man working on a roof with a power drill',
    },
    {
      src: unsplash('1635424824800-692767998d07'),
      alt: 'a man in a yellow shirt is working on a roof',
    },
    { src: unsplash('1635424710928-0544e8512eae'), alt: 'a man on a roof working with a rope' },
    {
      src: unsplash('1754620906703-496ec2451744'),
      alt: 'Worker installs electrical components on a roof.',
    },
    { src: unsplash('1754620906571-9ba64bd3ffb4'), alt: 'Worker installs wires on a roof.' },
    {
      src: unsplash('1754620906555-ba341e4a8c25'),
      alt: 'Solar panel connectors and wiring on a roof.',
    },
    { src: unsplash('1771178300970-230f7de19e9c'), alt: 'Rows of solar panels under a cloudy sky' },
    { src: unsplash('1726795867801-63c0a37b80c6'), alt: 'A large array of blue and white tiles' },
    {
      src: unsplash('1726795867795-32bc9872a44a'),
      alt: 'Two rows of rows of blue and white tiles',
    },
    {
      src: unsplash('1726866492047-7f9516558c6e'),
      alt: 'An aerial view of a parking lot with lots of solar panels',
    },
    {
      src: unsplash('1753781466451-ec9d6029557c'),
      alt: 'A drone flies high against a cloudy sky.',
    },
    { src: unsplash('1762960490358-f749f5a08aa5'), alt: 'Solar panels mounted on a brick wall' },
    {
      src: unsplash('1762958266408-5a8278e26506'),
      alt: 'Solar panel being installed on a metal frame.',
    },
    {
      src: unsplash('1763114613273-ec505136d03a'),
      alt: 'Two solar panels on a rooftop with autumn foliage.',
    },
    { src: unsplash('1762958266615-949dc88dcb37'), alt: 'Solar panel on a balcony with plants' },
    {
      src: unsplash('1768839727824-28d6f0dcd1d1'),
      alt: 'Solar panels in a field under a cloudy sky',
    },
    {
      src: unsplash('1762958266774-95abba6e0685'),
      alt: 'Balcony with solar panels on brick building',
    },
    {
      src: unsplash('1773291934106-f6e551493b83'),
      alt: 'Modern building with abstract sculpture and clear sky',
    },
    {
      src: unsplash('1624397640148-949b1732bb0a'),
      alt: 'man in white dress shirt and blue denim jeans sitting on white and black solar panel',
    },
    {
      src: unsplash('1713544123580-12096cc9eb12'),
      alt: 'the roof of a building with a lot of solar panels on it',
    },
    { src: unsplash('1660330589782-83776f89dd1e'), alt: 'a man on a ladder' },
    { src: unsplash('1660330589243-4c640d878052'), alt: 'men on top of a roof' },
    { src: unsplash('1663321508309-4ceb96a3c791'), alt: 'a blue and black tiled surface' },
    { src: unsplash('1660330589257-813305a4a383'), alt: 'a man on a roof' },
    { src: unsplash('1668097613572-40b7c11c8727'), alt: 'a person working on a solar panel' },
    {
      src: unsplash('1769697714710-4fce4b88a215'),
      alt: 'Rooftop solar panels partially covered in snow.',
    },
    { src: unsplash('1723046106153-8d3810267931'), alt: 'A house with a solar panel on the roof' },
    { src: unsplash('1735306161036-a541d4835f26'), alt: 'An airplane is flying over a building' },
    { src: unsplash('1651379560002-7fe2278df5a7'), alt: 'a group of buildings with red roofs' },
    {
      src: unsplash('1761472823286-9f6093ed6663'),
      alt: 'Rainbow over a suburban neighborhood with solar panels.',
    },
    {
      src: unsplash('1775317628391-a0429fe3be1b'),
      alt: 'Industrial building with sawtooth roof and sky',
    },
    {
      src: unsplash('1728291014119-392c27e7fead'),
      alt: 'A house with a fence and a clock on the front of it',
    },
    {
      src: unsplash('1763680694720-750dff419121'),
      alt: 'Aerial view of a suburban neighborhood with a long road.',
    },
    {
      src: unsplash('1769699903260-ff85271faa4f'),
      alt: 'Rooftop solar panels on a modern building in winter.',
    },
    { src: unsplash('1720610784599-18c02b1cc9ee'), alt: 'A house with a solar panel on the roof' },
    {
      src: unsplash('1769697672933-0f599f913f4d'),
      alt: 'Modern building exterior with many windows and solar panels.',
    },
    { src: unsplash('1761234799877-75cdf927d5e5'), alt: 'Houses with mountains in the background' },
    {
      src: unsplash('1761158495585-eac721decf1b'),
      alt: 'Orange roof with solar panels and overhead wires',
    },
    { src: unsplash('1691421740425-48ff22b6d442'), alt: 'a house with a solar panel on the roof' },
    {
      src: unsplash('1769697265831-02425ab88a11'),
      alt: 'Modern apartment buildings with solar panels on roofs.',
    },
    {
      src: unsplash('1772326281137-b617cbf77c5f'),
      alt: 'Aerial view of a suburban neighborhood with houses and streets.',
    },
    {
      src: unsplash('1765884929034-8abfe2c6c8ae'),
      alt: 'Modern cityscape with tall buildings and trees.',
    },
  ],
}
