/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 2 services, 110 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen7: Record<string, { src: string; alt: string }[]> = {
  antenniste: [
    { src: unsplash('1748002094696-f6d2214824f2'), alt: 'A satellite dish is mounted on a wall.' },
    {
      src: unsplash('1731334511313-04bdde55f3ad'),
      alt: 'A satellite dish on the side of a building',
    },
    {
      src: unsplash('1640932721663-d658655d5c07'),
      alt: 'a trash can with a piece of paper sticking out of it',
    },
    {
      src: unsplash('1638290108867-1fa6bebcc89c'),
      alt: 'a satellite dish with a camera attached to it',
    },
    {
      src: unsplash('1722684766684-25078d22873f'),
      alt: 'A satellite dish with a blue sky in the background',
    },
    {
      src: unsplash('1709995487222-a7118b9d0aaa'),
      alt: 'a satellite dish mounted to the side of a building',
    },
    {
      src: unsplash('1710055526049-5b860f24e840'),
      alt: 'a white house with a satellite dish on the roof',
    },
    {
      src: unsplash('1729051205463-6f61a11deaa9'),
      alt: 'A satellite dish attached to a metal pole',
    },
    { src: unsplash('1722684767604-f35209087019'), alt: 'A satellite dish on top of a building' },
    {
      src: unsplash('1640826028459-85717fee837d'),
      alt: 'a satellite dish sitting on top of a building',
    },
    {
      src: unsplash('1746144369221-2565d8eb676e'),
      alt: 'A satellite dish watches the sunset over the city.',
    },
    { src: unsplash('1663316026819-ea3a6293e8e9'), alt: 'a satellite dish on a roof' },
    {
      src: unsplash('1598958260657-0031ba6d793f'),
      alt: 'blue and black bird on brown wooden stick during daytime',
    },
    { src: unsplash('1567591561392-3749515b0c49'), alt: 'five parabolic dishes on roof' },
    {
      src: unsplash('1653681963850-531767705d88'),
      alt: 'a large satellite dish sitting on top of a metal pole',
    },
    {
      src: unsplash('1776026020980-cd69ae72c4f6'),
      alt: 'Satellite dish on a tiled roof with chimneys.',
    },
    {
      src: unsplash('1632210503979-15f578eb0302'),
      alt: 'a couple of satellite dishes sitting on top of a building',
    },
    {
      src: unsplash('1559124253-b2d212e9f673'),
      alt: 'white parabolic antenna beside trees during daytime',
    },
    {
      src: unsplash('1714255288526-cc155b548aac'),
      alt: 'a large satellite dish sitting on top of a metal platform',
    },
    { src: unsplash('1651421745900-bc90a58ec0ed'), alt: 'a white structure with a blue sky' },
    {
      src: unsplash('1736181188872-db061ff70e0e'),
      alt: 'A satellite dish sitting on top of a roof',
    },
    {
      src: unsplash('1690050070284-d1a628f5b494'),
      alt: 'a large satellite dish sitting on top of a metal structure',
    },
    {
      src: unsplash('1678486207654-590491c6970a'),
      alt: 'a surfboard sitting on top of a pole next to a brick wall',
    },
    {
      src: unsplash('1671641237413-164fa379dd1e'),
      alt: 'a satellite dish on top of a building at sunset',
    },
    { src: unsplash('1541946245286-ca6fbe1ad39b'), alt: 'white parabolic antenna' },
    {
      src: unsplash('1774818803650-0e6d893f68e5'),
      alt: 'Satellite dish on a tiled roof with trees.',
    },
    {
      src: unsplash('1690050070619-9c2c33d8210a'),
      alt: 'a large satellite dish sitting on top of a building',
    },
    {
      src: unsplash('1638376391727-b0b9878c5e18'),
      alt: 'a satellite dish attached to a metal pole',
    },
    {
      src: unsplash('1743815941200-4b0a6cae0477'),
      alt: 'Satellite dish atop a brick building against a sky.',
    },
    { src: unsplash('1575309830879-53a9c8b51dd9'), alt: 'white parabolic antenna' },
    {
      src: unsplash('1636230837680-478e71305f22'),
      alt: 'a television antenna on a pole with a sky background',
    },
    { src: unsplash('1599905858319-ade1a3d6f228'), alt: 'two gray satellite dishes on white wall' },
    { src: unsplash('1609669483452-46ce81e443eb'), alt: 'green trees and plants during sunset' },
    {
      src: unsplash('1671699429772-7b2f65f38225'),
      alt: 'a building with lots of electrical wires on top of it',
    },
    {
      src: unsplash('1719596733209-4233eaec3d7c'),
      alt: 'A cat sitting on a window sill looking out the window',
    },
    { src: unsplash('1775508567498-6129a962791c'), alt: 'An old television antenna on a rooftop' },
    {
      src: unsplash('1691357197706-5216956df527'),
      alt: 'a couple of wind vane sitting on top of a building',
    },
    { src: unsplash('1566310105322-ed9d6a683ec9'), alt: 'silhouette of buildings' },
    {
      src: unsplash('1774008931096-2bad9c8b4211'),
      alt: 'Outdoor television antenna against a blue sky.',
    },
    {
      src: unsplash('1734126650058-623935bab140'),
      alt: 'A satellite dish sitting on top of a roof',
    },
    { src: unsplash('1583259034006-5ea8361109e7'), alt: 'black and blue coated wires' },
    { src: unsplash('1583602621722-cbd1130b210b'), alt: 'black metal tower under white sky' },
    { src: unsplash('1611434132218-d687f8a5f378'), alt: 'black crt tv on brown wooden table' },
    {
      src: unsplash('1606170034397-4f4f947335db'),
      alt: 'white concrete building with black metal cross',
    },
    {
      src: unsplash('1642764984388-80d8d77bc4b9'),
      alt: 'a man and a woman are standing on a balcony',
    },
    {
      src: unsplash('1647204240764-ae54f9f1c6b7'),
      alt: 'a large group of chimneys on top of a brick building',
    },
    { src: unsplash('1589807436173-031d49eab139'), alt: 'white and silver round tower' },
    {
      src: unsplash('1764151825324-4be510cd1e0f'),
      alt: 'Tall radio tower silhouetted against a hazy sky',
    },
    {
      src: unsplash('1764496018639-d5c7426b1331'),
      alt: 'Vintage television displaying a colorful scene',
    },
    {
      src: unsplash('1772990915003-db1f6095d7f7'),
      alt: 'A small building with antennas covered in frost',
    },
    {
      src: unsplash('1768139231971-639147b07b29'),
      alt: 'A tall communication tower stands near power lines.',
    },
  ],
  'architecte-interieur': [
    { src: unsplash('1618221195710-dd6b41faaea6'), alt: 'white and brown living room set' },
    { src: unsplash('1586023492125-27b2c045efd7'), alt: 'brown wooden framed yellow padded chair' },
    { src: unsplash('1606744824163-985d376605aa'), alt: 'black metal framed glass top table' },
    { src: unsplash('1606744888344-493238951221'), alt: 'green and brown sofa chair' },
    { src: unsplash('1664711942326-2c3351e215e6'), alt: 'a room with a couch and a table' },
    {
      src: unsplash('1503174971373-b1f69850bded'),
      alt: 'two black suede armchairs during daytime',
    },
    { src: unsplash('1507089947368-19c1da9775ae'), alt: 'white kitchen room set' },
    { src: unsplash('1618219740975-d40978bb7378'), alt: 'black and white wall mounted painting' },
    {
      src: unsplash('1537726235470-8504e3beef77'),
      alt: 'dining table set placed beside glass window',
    },
    { src: unsplash('1737474707380-5ef35770d8a7'), alt: 'A room with a chair and a desk in it' },
    { src: unsplash('1616137422495-1e9e46e2aa77'), alt: 'gray and white sofa set' },
    { src: unsplash('1632583824020-937ae9564495'), alt: 'a modern kitchen with a bar and stools' },
    { src: unsplash('1562438668-bcf0ca6578f0'), alt: 'gray bed in bedroom' },
    { src: unsplash('1615873968403-89e068629265'), alt: 'brown wooden framed white padded chairs' },
    {
      src: unsplash('1618221381711-42ca8ab6e908'),
      alt: 'orange and black sofa with throw pillows',
    },
    {
      src: unsplash('1600210491369-e753d80a41f3'),
      alt: 'white and black wooden table with chairs',
    },
    { src: unsplash('1653972233229-1b8c042d6d8e'), alt: 'a living room with a couch and a table' },
    {
      src: unsplash('1724582586529-62622e50c0b3'),
      alt: 'A modern living room with a large window',
    },
    {
      src: unsplash('1678762200388-51e11225d4de'),
      alt: 'a living room filled with furniture and a large window',
    },
    { src: unsplash('1618221469555-7f3ad97540d6'), alt: 'white wooden table with chairs' },
    {
      src: unsplash('1600494448850-6013c64ba722'),
      alt: 'living room with white sofa set and green potted plant',
    },
    {
      src: unsplash('1640357960494-9242650846d3'),
      alt: 'a black and white photo of a living room',
    },
    {
      src: unsplash('1637649228998-6c78a67dfa6c'),
      alt: 'a modern living room with a large window',
    },
    { src: unsplash('1593696140826-c58b021acf8b'), alt: 'black and white wooden table and chairs' },
    { src: unsplash('1617103996702-96ff29b1c467'), alt: 'white and brown living room set' },
    {
      src: unsplash('1605774337664-7a846e9cdf17'),
      alt: 'gray 2 seat sofa near brown wooden coffee table',
    },
    { src: unsplash('1738168246881-40f35f8aba0a'), alt: 'A living room with a large green couch' },
    { src: unsplash('1533779283484-8ad4940aa3a8'), alt: 'white wooden table' },
    {
      src: unsplash('1634547476021-c1155c01616c'),
      alt: 'a living room filled with furniture and a large window',
    },
    {
      src: unsplash('1631679706909-1844bbd07221'),
      alt: 'a living room filled with furniture and a mirror',
    },
    { src: unsplash('1567767292278-a4f21aa2d36e'), alt: 'brown fabric sofa set' },
    { src: unsplash('1560185007-cde436f6a4d0'), alt: 'brown-and-black wooden 5-piece dining set' },
    { src: unsplash('1613545325278-f24b0cae1224'), alt: 'white and brown living room set' },
    { src: unsplash('1560448204-e02f11c3d0e2'), alt: 'beige couch and armchair' },
    { src: unsplash('1560448204-603b3fc33ddc'), alt: 'empty living room' },
    { src: unsplash('1628745423035-0211f4d95596'), alt: 'white wooden table with chairs' },
    { src: unsplash('1560185009-dddeb820c7b7'), alt: 'brown and grey room interior' },
    { src: unsplash('1613545325268-9265e1609167'), alt: 'white couch near glass window' },
    {
      src: unsplash('1541123603104-512919d6a96c'),
      alt: 'white wooden sideboard beside gray padded sofa',
    },
    { src: unsplash('1560448205-4d9b3e6bb6db'), alt: 'two green and white pillows on empty bed' },
    { src: unsplash('1667450799167-09e7dd903e59'), alt: 'a living room with a fireplace' },
    { src: unsplash('1628744876497-eb30460be9f6'), alt: 'white couch and brown wooden table' },
    { src: unsplash('1541123437800-1bb1317badc2'), alt: 'dining set photography' },
    { src: unsplash('1560185013-ead8277ef8ea'), alt: 'brown and black metal-framed coffee table' },
    {
      src: unsplash('1560448204-61dc36dc98c8'),
      alt: 'round brown wooden table with six white leather padded chairs',
    },
    { src: unsplash('1734417511653-252ab0709e32'), alt: 'A person taking a picture of a kitchen' },
    {
      src: unsplash('1560448075-57d0285fc59b'),
      alt: 'bed with comforter set beside table lamps on nightstands',
    },
    { src: unsplash('1560185127-6ed189bf02f4'), alt: 'living room interior' },
    {
      src: unsplash('1609280069591-0c767e25e7a1'),
      alt: 'black candle holder on brown wooden table',
    },
    { src: unsplash('1612031736710-4c6a0ff216af'), alt: 'green plant on brown wooden table' },
    {
      src: unsplash('1772563156886-9fcfb121e500'),
      alt: 'Living room with sofa, coffee table, and movie posters.',
    },
    { src: unsplash('1612031736450-f5c532c9b6d4'), alt: 'opened book on brown wooden table' },
    {
      src: unsplash('1613545564267-b80e188a1541'),
      alt: 'white wooden kitchen cabinet near white wooden kitchen cabinet',
    },
    { src: unsplash('1613545564235-db7af30081bf'), alt: 'white and gray kitchen counter' },
    { src: unsplash('1613545564259-ede280773613'), alt: 'white wooden table with chairs' },
    { src: unsplash('1613545564241-296299063513'), alt: 'white ceramic bowl on white table' },
    { src: unsplash('1612031737124-28aeae3f2863'), alt: 'black fireplace in brown brick wall' },
    {
      src: unsplash('1613545564248-3dee90e4d4b6'),
      alt: 'white wooden kitchen cabinet near white wooden kitchen cabinet',
    },
    { src: unsplash('1613545564245-62b2c9ef8055'), alt: 'white wooden table with chairs' },
  ],
}
