/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 8 services, 446 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen8: Record<string, { src: string; alt: string }[]> = {
  diagnostiqueur: [
    {
      src: unsplash('1676630656246-3047520adfdf'),
      alt: 'a man working on a wall with a screwdriver',
    },
    { src: unsplash('1572120360610-d971b9d7767c'), alt: 'trees beside white house' },
    {
      src: unsplash('1645677040449-17dc9f184003'),
      alt: 'a person standing in front of a red door',
    },
    { src: unsplash('1516156008625-3a9d6067fab5'), alt: 'aerial photography of rural' },
    {
      src: unsplash('1516455590571-18256e5bb9ff'),
      alt: 'round clear glass-top table and five gray chairs dining se',
    },
    {
      src: unsplash('1769776400238-cd24612240ea'),
      alt: 'Magnifying glass over a wooden house model.',
    },
    {
      src: unsplash('1581578731567-c884e2816aaa'),
      alt: 'man in black t-shirt and blue denim jeans playing guitar',
    },
    {
      src: unsplash('1687982121908-eed863615c13'),
      alt: 'a man standing outside of a building drinking from a bottle',
    },
    { src: unsplash('1536940135352-b4b3875df888'), alt: 'man reading book in front of window' },
    { src: unsplash('1646776202025-648de1f2f0fe'), alt: 'a man standing in front of a blue door' },
    {
      src: unsplash('1581579746581-3954f2a31e7a'),
      alt: 'man in blue shirt and blue denim jeans sitting on brown wooden table',
    },
    {
      src: unsplash('1560520653-9e0e4c89eb11'),
      alt: 'white and red wooden house beside grey framed magnifying glass',
    },
    { src: unsplash('1657672733372-e6c8741d2e6c'), alt: 'a man brushing his teeth' },
    { src: unsplash('1504579524716-7eeaa8704f14'), alt: 'green bush by house at daytime' },
    {
      src: unsplash('1642775955839-830e41b93682'),
      alt: 'a gray house with a white porch and a brown door',
    },
    { src: unsplash('1585458667865-d3598174d8ff'), alt: 'man and woman sitting on floor' },
    {
      src: unsplash('1588712757679-06a3428ce119'),
      alt: 'brown brick building under blue sky during daytime',
    },
    {
      src: unsplash('1709787627975-9cb37bbeca60'),
      alt: 'a couple of people that are sitting in front of a house',
    },
    {
      src: unsplash('1714647212027-2a0ad30cb4f1'),
      alt: 'a man and a woman standing in a living room',
    },
    { src: unsplash('1632759145351-1d592919f522'), alt: 'a man standing on the roof of a house' },
    { src: unsplash('1611410885997-0636819b3cf0'), alt: 'white and brown concrete house' },
    { src: unsplash('1573941252622-4118390c7993'), alt: 'white and brown house' },
    {
      src: unsplash('1731341711808-7a103eff1d20'),
      alt: 'A man standing in a living room next to a fire place',
    },
    {
      src: unsplash('1585492240360-4766db177dd3'),
      alt: 'white and brown wooden house under blue sky during daytime',
    },
    {
      src: unsplash('1753232535908-9f92ba677225'),
      alt: 'A beautiful brick house sits on a green lawn.',
    },
    {
      src: unsplash('1634051808324-4baa77cb4ef8'),
      alt: 'a couple of men standing on top of a wooden porch',
    },
    { src: unsplash('1680808783328-37525aee02b2'), alt: 'a house with a clock on the front of it' },
    { src: unsplash('1617118602031-1edde7582212'), alt: 'green ruler on white surface' },
    {
      src: unsplash('1581579746640-99fc3d5d0e40'),
      alt: 'woman in pink long sleeve shirt standing beside black wood burner',
    },
    {
      src: unsplash('1595844730289-b248c919d6f9'),
      alt: 'person holding black and green power tool',
    },
    {
      src: unsplash('1694521787193-9293daeddbaa'),
      alt: 'a couple of men standing next to each other',
    },
    { src: unsplash('1604070974077-1482430f5122'), alt: 'gray concrete building during daytime' },
    { src: unsplash('1582176410262-005b25ee4aa7'), alt: 'red and white labeled pack' },
    {
      src: unsplash('1607764842505-82955490b8dc'),
      alt: 'black and white bird on white concrete building during daytime',
    },
    {
      src: unsplash('1723460041120-104bc4a62ee3'),
      alt: 'A building with scaffolding on top of it',
    },
    { src: unsplash('1527199768775-bdabf8b32f61'), alt: 'man doing welding on outdoors' },
    {
      src: unsplash('1659353586512-bcc4c7182d01'),
      alt: 'a person wearing a hard hat and looking at a tablet',
    },
    {
      src: unsplash('1653088078179-98ec14b69580'),
      alt: 'a blurry photo of a building with a clock tower',
    },
    {
      src: unsplash('1748027869634-fc2e545cfb0c'),
      alt: 'A construction worker is examining a door.',
    },
    { src: unsplash('1661168134865-2bc6286cc308'), alt: 'a building under construction' },
    { src: unsplash('1554035042-34f354352d97'), alt: '2 men in white hard hat holding a machine' },
    {
      src: unsplash('1747192904662-e03e8da1e0ab'),
      alt: 'A building is under construction with scaffolding.',
    },
    {
      src: unsplash('1748175471682-de85d9d5231d'),
      alt: 'An unfinished skyscraper structure rises under blue sky.',
    },
    { src: unsplash('1669234611002-173964d1c694'), alt: 'a building under construction' },
    { src: unsplash('1599707233265-10accf051fe0'), alt: 'orange crane on top of building' },
    { src: unsplash('1603838656896-b8091f534d66'), alt: 'brown concrete building during daytime' },
    {
      src: unsplash('1694521787799-ad4ad241cb39'),
      alt: 'a group of men standing next to each other in front of a building',
    },
    {
      src: unsplash('1701064265806-6dcfb317ade5'),
      alt: 'a building under construction with lots of wooden sticks sticking out of it',
    },
    { src: unsplash('1547002889-5cb2cb735346'), alt: 'grayscale high rise building' },
    { src: unsplash('1661520604588-b0f6c6ae46f0'), alt: 'a building with many windows' },
    {
      src: unsplash('1705579604303-3086e4162d34'),
      alt: 'a woman in a safety vest talking to a woman in a hard hat',
    },
    { src: unsplash('1564525804719-cfe95311cacd'), alt: 'silhouette of man inside building' },
    { src: unsplash('1537205125380-5e9b86a7b2b9'), alt: 'white high-rise building' },
    {
      src: unsplash('1772551419789-8075b4055f9e'),
      alt: 'Modern buildings under construction against a hazy sky',
    },
    {
      src: unsplash('1709052702774-6c534fc62fae'),
      alt: 'a very tall building with a bunch of wires on top of it',
    },
    { src: unsplash('1662154646905-8ad92263d5da'), alt: 'a building under construction' },
    {
      src: unsplash('1691341208697-e1ed6c1b233a'),
      alt: 'a tall building under construction with scaffolding around it',
    },
    {
      src: unsplash('1762407785760-3e4c22aede86'),
      alt: 'Unfinished building under construction with scaffolding.',
    },
    { src: unsplash('1618385455730-2571c38966b7'), alt: 'person using black laptop computer' },
    {
      src: unsplash('1639563722312-11bc9a31ee34'),
      alt: 'a construction worker with a yellow helmet on',
    },
  ],
  etancheiste: [
    {
      src: unsplash('1591645321243-3adc1e75cfdc'),
      alt: 'man in black jacket walking on sidewalk during daytime',
    },
    {
      src: unsplash('1681812490689-2bb9ab7ca660'),
      alt: 'a man in a raincoat is working on a boat',
    },
    { src: unsplash('1586774839818-40c7e1cd1243'), alt: 'brown and black wooden surface' },
    {
      src: unsplash('1621682988371-83cccd25c323'),
      alt: 'man in orange and black jacket and blue denim jeans jumping on gray concrete floor under',
    },
    {
      src: unsplash('1633527992904-53f86f81a23a'),
      alt: 'a close up of a cotton plant with a blurry background',
    },
    {
      src: unsplash('1663566673926-04241bfbe038'),
      alt: 'a pair of black and white ear buds on a white surface',
    },
    {
      src: unsplash('1636100686647-6c98cd346778'),
      alt: 'a man standing in the rain with his hands out',
    },
    { src: unsplash('1651823644613-4909ffd40614'), alt: 'a pair of brown shoes' },
    {
      src: unsplash('1599681906464-ec599150575b'),
      alt: 'black leather strap silver round analog watch',
    },
    {
      src: unsplash('1680699232561-de5452f56f8d'),
      alt: 'a couple of men standing next to a fire truck',
    },
    { src: unsplash('1624840048945-36bff42fe209'), alt: 'silver iphone 5s on white textile' },
    {
      src: unsplash('1636099652696-f5bec08a7503'),
      alt: 'a pair of blue headphones sitting on top of a phone',
    },
    {
      src: unsplash('1598034989845-48532781987e'),
      alt: 'black and gray speaker on brown wooden table',
    },
    { src: unsplash('1557901359-71e5668184b1'), alt: 'black framed sunglasses' },
    {
      src: unsplash('1681812507901-bbe29584bb31'),
      alt: 'a man in an orange safety suit painting a sign',
    },
    { src: unsplash('1636451096144-a4304c34c169'), alt: 'a pair of ear buds laying on a rock' },
    {
      src: unsplash('1681812491387-de0d8a1968b2'),
      alt: 'a man in yellow pants and a yellow hat walking down a road',
    },
    { src: unsplash('1681812490697-efdcb9be343b'), alt: 'a man in a wet suit holding a fish' },
    {
      src: unsplash('1775204440210-7d9c6d03574b'),
      alt: 'Water droplets on green and white striped fabric',
    },
    { src: unsplash('1607038602457-5bc473713cb5'), alt: 'water droplets on green surface' },
    {
      src: unsplash('1520991323542-c159d7282b9f'),
      alt: 'person in orange top wearing backpack walking on body of water in forest during daytime',
    },
    { src: unsplash('1600333791066-f3c7e752b44e'), alt: 'black and pink camera on tripod' },
    {
      src: unsplash('1648899936678-d66551cb292c'),
      alt: 'a red speaker sitting on top of a wooden table',
    },
    {
      src: unsplash('1546019739-f442c5e4696d'),
      alt: 'black and white drones on blue wooden bench',
    },
    { src: unsplash('1562028798-f6f372d1a6f8'), alt: 'close view of banana leaves' },
    { src: unsplash('1562753208-5de026733874'), alt: 'green banana leaves' },
    {
      src: unsplash('1610708946258-54af43706e64'),
      alt: 'child in black and yellow hoodie standing on white textile',
    },
    { src: unsplash('1617729220754-a84754c1be54'), alt: 'woman in yellow collared shirt smiling' },
    {
      src: unsplash('1593518779115-831235f45ec1'),
      alt: 'woman in blue and white polka dot tank top sitting on orange kayak on river during',
    },
    {
      src: unsplash('1775204440954-32f7923a5b51'),
      alt: 'Green and white striped fabric with water droplets.',
    },
    { src: unsplash('1678020704290-86c3bc1bc6d3'), alt: 'a close up of moss growing on a roof' },
    { src: unsplash('1678020706579-de8ce9e33ca8'), alt: 'moss growing on the roof of a building' },
    {
      src: unsplash('1705831890138-e0f1e38d5ac7'),
      alt: 'a bunch of trash sitting on the side of a building',
    },
    {
      src: unsplash('1738669465747-65e6454f2edc'),
      alt: 'A pigeon is perched on the roof of a house',
    },
    {
      src: unsplash('1763065137209-fae84984e38e'),
      alt: 'A seagull stands on a ledge with trees in background.',
    },
    {
      src: unsplash('1743517126833-4b111443311e'),
      alt: 'A pigeon is silhouetted against a blurry background.',
    },
    {
      src: unsplash('1764923436525-a67aff16187b'),
      alt: 'A tabby cat rests beside a uniqlo shopping bag.',
    },
    {
      src: unsplash('1775276406121-a1fdf9606b05'),
      alt: 'Close-up of weathered terracotta roof tiles in rows.',
    },
    {
      src: unsplash('1704216812766-c62ad0d9ff28'),
      alt: 'a pigeon standing next to a wooden fence',
    },
    {
      src: unsplash('1765468199472-eec8e065f410'),
      alt: 'Two drinks with autumn leaves decoration',
    },
    {
      src: unsplash('1718114759401-2decc5fff6e5'),
      alt: 'a view of a building from the top of a building',
    },
    { src: unsplash('1563174499-83c108efd397'), alt: 'brown shingle roof' },
    {
      src: unsplash('1638446160622-4965f6fe6efe'),
      alt: 'a couple of small trees standing in the middle of a snow covered field',
    },
    {
      src: unsplash('1642388514011-b4b4f43a2179'),
      alt: 'a close up of a roof with a broken gutter',
    },
    { src: unsplash('1681049400158-0ff6249ac315'), alt: 'two men working on the roof of a house' },
    { src: unsplash('1635424709845-3a85ad5e1f5e'), alt: 'a couple of people that are on a roof' },
    { src: unsplash('1544324577-af0a4a91f6ff'), alt: 'brown attic' },
    { src: unsplash('1570038797288-683aab8ff627'), alt: 'brown and white roof during daytime' },
    { src: unsplash('1668683997214-771199dcbaf2'), alt: 'a dock with trees in the background' },
    {
      src: unsplash('1674485169641-bcb2bf6f1df9'),
      alt: 'a man in a white coverall spray painting a roof',
    },
    { src: unsplash('1658536851794-4afd5c621aa8'), alt: 'a close up of a wood floor' },
    {
      src: unsplash('1635424825057-7fb6dcd651ef'),
      alt: 'a man working on a roof with a power drill',
    },
    {
      src: unsplash('1722235569646-3ccaca59bd59'),
      alt: 'A gutter gutter gutter gutter gutter gutter gutter gut',
    },
    { src: unsplash('1626977990516-c807a31c42d4'), alt: 'black and brown wooden frame' },
    {
      src: unsplash('1718284707769-f16eddc6b268'),
      alt: 'a bird sitting on top of a roof next to a building',
    },
    { src: unsplash('1657195721935-e73e545a2aae'), alt: 'a close-up of a roof' },
    { src: unsplash('1574693464259-4de81ffb9231'), alt: 'white painted wall' },
    {
      src: unsplash('1759073026614-cef5b89b1b6e'),
      alt: 'Close-up of weathered hexagonal roof tiles with moss.',
    },
    {
      src: unsplash('1606582218474-f49568e273fd'),
      alt: 'brown concrete brick wall during daytime',
    },
    {
      src: unsplash('1599570750519-a26b62691be7'),
      alt: 'brown roof tiles in close up photography',
    },
  ],
  ferronnier: [
    {
      src: unsplash('1700082820274-290879ba9286'),
      alt: 'a close up of a metal fence with a heart',
    },
    { src: unsplash('1589522790635-29723629fe1b'), alt: 'black metal fence with white snow' },
    { src: unsplash('1566234679754-8c8056cadef5'), alt: 'gray metal part' },
    { src: unsplash('1688673377324-b5d232c2b36f'), alt: 'a close up of a wrought iron gate' },
    { src: unsplash('1669338288125-c3aef5d3996a'), alt: 'diagram' },
    { src: unsplash('1674064033143-df751409e799'), alt: 'a close up of a window on a building' },
    { src: unsplash('1502861430055-601d8468f4f4'), alt: 'brown metal crate on blue surface' },
    {
      src: unsplash('1744467349958-c98442fd3efe'),
      alt: 'A rose blooms through decorative ironwork and brick.',
    },
    {
      src: unsplash('1697398797981-3cd8b4966d56'),
      alt: 'a wrought iron gate with a blue sky in the background',
    },
    { src: unsplash('1569156354402-a046629a31e7'), alt: 'black metal frame' },
    { src: unsplash('1671746719800-fc8b107df0ab'), alt: 'a black and white photo of a gate' },
    { src: unsplash('1548088034-2a22735c5e66'), alt: 'man holding welding rod' },
    {
      src: unsplash('1585934299487-2dee953ee83a'),
      alt: 'black metal fence in close up photography',
    },
    {
      src: unsplash('1567400389308-a5709e30eb79'),
      alt: 'closeup photo of person holding burning metal rod',
    },
    { src: unsplash('1681694826399-12f40b0f3e44'), alt: 'a rusted iron gate with a curved design' },
    {
      src: unsplash('1680202905084-a9e11d2715da'),
      alt: 'a close up of a metal fence with a view of the ocean',
    },
    {
      src: unsplash('1674064030307-17089301fa6f'),
      alt: 'a close up of a metal gate on a building',
    },
    {
      src: unsplash('1763940112467-688750e99df8'),
      alt: 'Ornate metalwork featuring fish and seaweed designs',
    },
    {
      src: unsplash('1748359281980-5196493557d6'),
      alt: 'An ornate door with decorative metalwork.',
    },
    {
      src: unsplash('1738501154823-fdbb4ec864f6'),
      alt: 'A close up of a metal gate with a tree in the background',
    },
    { src: unsplash('1607238341512-ef3f6b9c1eed'), alt: 'white metal bird cage during daytime' },
    { src: unsplash('1658762944591-01e617527ffa'), alt: 'a close-up of a flame' },
    { src: unsplash('1657043500068-ca0e4dedc8d1'), alt: 'a metal gate with a metal fence' },
    {
      src: unsplash('1641745688024-04f122bbf1bb'),
      alt: 'a close up of a blue metal gate with a flower',
    },
    { src: unsplash('1587541203147-5e3809296ccd'), alt: 'black metal fence on brown wooden wall' },
    { src: unsplash('1703368786653-f2f48bacbbe4'), alt: 'a close up of a wrought iron fence' },
    { src: unsplash('1749391468153-02eef584568d'), alt: 'Ornate wrought iron grille in a window.' },
    { src: unsplash('1549057242-0d34f22ffb7f'), alt: 'person smelting metal' },
    { src: unsplash('1624382497193-de32b368de64'), alt: 'person holding black and silver sword' },
    { src: unsplash('1624282348231-33e30d726bf2'), alt: 'silver and gold ball ornament' },
    {
      src: unsplash('1585580956413-5a952a885159'),
      alt: 'black and white city bike parked beside black metal fence',
    },
    { src: unsplash('1633357152047-ba20c3212670'), alt: 'a couple of gates that are in the grass' },
    {
      src: unsplash('1769869526447-efb0ec1f7910'),
      alt: 'Ornate purple metal gate with vine-like detailing',
    },
    {
      src: unsplash('1769527265705-b25cd698b5cc'),
      alt: 'White metal gate with brick pillar and overgrown plants',
    },
    {
      src: unsplash('1771807536690-b0e53c9fb3bb'),
      alt: 'An ornate black metal gate in a lush garden',
    },
    { src: unsplash('1622508116002-289ec1db7959'), alt: 'red and white stop sign' },
    {
      src: unsplash('1761815140370-7a3155de6a34'),
      alt: 'Green metal garden gate with floral design',
    },
    {
      src: unsplash('1774449582960-ae751419f790'),
      alt: 'Ornate wrought iron gate with weathered patina and overgrown foliage.',
    },
    {
      src: unsplash('1760078626283-ae761e2d9431'),
      alt: 'Ornate metal gate with leaf-like scrollwork',
    },
    {
      src: unsplash('1764061113203-daa3aa4a3f58'),
      alt: 'Ornate metal gate next to textured stone wall',
    },
    {
      src: unsplash('1762346006733-13b87070905e'),
      alt: 'Black metal fence in front of brick building',
    },
    {
      src: unsplash('1759082495648-d683ce2f1025'),
      alt: 'Green ornate gate with a gold star emblem.',
    },
    {
      src: unsplash('1761931332859-ec80195d4d33'),
      alt: 'Close-up of a decorative wrought iron grill and stone texture.',
    },
    { src: unsplash('1591123224422-62f665a12fb8'), alt: 'green plant beside brown brick wall' },
    {
      src: unsplash('1770398213837-3bf893afb4d8'),
      alt: 'Ornate wrought iron gates open to a tree-lined driveway.',
    },
    {
      src: unsplash('1769888318649-0eac313aa72c'),
      alt: 'Open gate leading to a misty forest path',
    },
    {
      src: unsplash('1761415452023-5e74d183efaf'),
      alt: 'Ornate metal gate in front of church interior',
    },
    { src: unsplash('1766076079172-0a33cb9bd3e3'), alt: 'Open gates lead to a snowy park path.' },
    { src: unsplash('1591202880306-fda749e5be8e'), alt: 'white and black concrete building' },
    { src: unsplash('1772723822856-702d10d1cb18'), alt: 'Brick building behind a gate and wall' },
    {
      src: unsplash('1774449581245-ee03eb522a7e'),
      alt: 'Ornate metal gate with autumn leaves against sky',
    },
    {
      src: unsplash('1666681719882-a92e33c7cae9'),
      alt: 'a white fence with flowers and a statue on top',
    },
    {
      src: unsplash('1765110850868-1a6cbf4a86ee'),
      alt: 'A bright moon shines through a dark sky.',
    },
    {
      src: unsplash('1770625297473-2f7159f1f244'),
      alt: 'Ornate archway with decorative metalwork and ceiling',
    },
    {
      src: unsplash('1619322704995-5215d5f47a75'),
      alt: 'black metal fence near green grass during daytime',
    },
    {
      src: unsplash('1587670270583-56aa78bdb6b1'),
      alt: 'grayscale photo of wooden fence with no smoking sign',
    },
    {
      src: unsplash('1773517459381-28bef4ea72ad'),
      alt: 'Ornate metal bars create a shadowy, abstract pattern.',
    },
    {
      src: unsplash('1774360852601-18f360fa2cf2'),
      alt: 'A snowy street with a house and metal fence',
    },
    { src: unsplash('1662348989066-d75e6c2ab54e'), alt: 'a table with chairs around it' },
    {
      src: unsplash('1767256125875-faca07a946b5'),
      alt: 'Two brick gatehouses with an ornate gate between them.',
    },
  ],
  geometre: [
    {
      src: unsplash('1628158088936-68ccaaa400dc'),
      alt: 'black and white tripod on green grass field during daytime',
    },
    {
      src: unsplash('1628158145409-9e222b56cc0b'),
      alt: 'city skyline under blue sky during daytime',
    },
    {
      src: unsplash('1682663810771-89d21838530f'),
      alt: 'a tripod with a camera attached to it in front of a construction site',
    },
    { src: unsplash('1628158088803-4200c2be52f1'), alt: 'gray tripod on brown rock' },
    { src: unsplash('1628155858736-bacadae33a88'), alt: 'blue and black corded device' },
    {
      src: unsplash('1628158088791-89567a8e84ec'),
      alt: 'man in black and yellow jacket wearing red helmet holding black and white stick',
    },
    {
      src: unsplash('1610081339336-46c23f599b3e'),
      alt: 'man in blue shirt and blue pants climbing on brown mountain during daytime',
    },
    {
      src: unsplash('1628155453612-27686cb94a25'),
      alt: 'man in black jacket holding black and gray stick',
    },
    { src: unsplash('1526593646509-03c680561a15'), alt: 'person holding digital device' },
    {
      src: unsplash('1628155849837-648cf206ec31'),
      alt: 'man in green and yellow vest standing beside orange and black heavy equipment',
    },
    {
      src: unsplash('1608926259241-5bfa7d2ea67f'),
      alt: 'man in black and white fitted cap holding black and green camera',
    },
    {
      src: unsplash('1720035136286-5d953e5bd1c0'),
      alt: 'A yellow and black device is on a pole in the middle of a dirt road',
    },
    {
      src: unsplash('1607134541550-2994abb8077b'),
      alt: 'man in gray and orange jacket holding green and black dslr camera during daytime',
    },
    {
      src: unsplash('1608923657667-fe22e4b44448'),
      alt: 'man in red jacket sitting on brown wooden ladder during daytime',
    },
    {
      src: unsplash('1654643353343-27b4e11b10d6'),
      alt: 'a man in an orange shirt is using a tripod',
    },
    {
      src: unsplash('1608926259193-f14ea1270898'),
      alt: 'boy in black knit cap holding green and black toy gun',
    },
    {
      src: unsplash('1582062322819-ff5d1ce9b6c3'),
      alt: 'man in black jacket holding gray and black camera',
    },
    {
      src: unsplash('1654643353201-8123d31163db'),
      alt: 'a man in an orange jacket is looking at a map on a tripod',
    },
    { src: unsplash('1545186070-de624ed19875'), alt: 'white and gray dumpy level' },
    {
      src: unsplash('1562601622-d344391156fb'),
      alt: 'man standing and using measuring level on road',
    },
    {
      src: unsplash('1607134541790-fbc00985b88e'),
      alt: 'man in orange white and black striped long sleeve shirt holding black dslr camera',
    },
    {
      src: unsplash('1582062322372-53bdc10af07c'),
      alt: 'man in black and orange jacket holding green and black camera during daytime',
    },
    {
      src: unsplash('1654643353084-10e62e05b9bf'),
      alt: 'a man standing next to a yellow and black tripod',
    },
    {
      src: unsplash('1720029865490-4004ba15f46c'),
      alt: 'A group of people standing on top of a grass covered field',
    },
    { src: unsplash('1526593740665-f57a5d42dd0a'), alt: 'man standing facing theodo light' },
    {
      src: unsplash('1607134541878-f3bbce97b2dd'),
      alt: 'man in orange and yellow jacket holding blue and gray camera',
    },
    { src: unsplash('1570130209119-df22b998a6fe'), alt: 'man standing beside orange leveler' },
    {
      src: unsplash('1682063631532-b865521538fa'),
      alt: 'a couple of men standing next to each other',
    },
    {
      src: unsplash('1654643353105-62d2482709d4'),
      alt: 'a red and white sign sitting on the side of a road',
    },
    {
      src: unsplash('1675600360017-f0d90a17ea54'),
      alt: 'a construction site with a camera on a tripod',
    },
    { src: unsplash('1628155938369-91aef06430b6'), alt: 'black and silver stand on brown sand' },
    {
      src: unsplash('1628155933410-8f2a84bb8076'),
      alt: 'gray and black camera on gray metal stand during daytime',
    },
    {
      src: unsplash('1764792522973-7b9cc4c9ae16'),
      alt: 'Surveying equipment set up at ancient ruins',
    },
    {
      src: unsplash('1701215339133-2753c235da34'),
      alt: 'a couple of large machines sitting on top of a dirt field',
    },
    { src: unsplash('1551336787-1f3038699084'), alt: 'gray and black controller' },
    {
      src: unsplash('1677475718598-0c0a0c15329d'),
      alt: 'a group of yellow construction vehicles parked next to each other',
    },
    {
      src: unsplash('1714261906973-feaafe69f7dc'),
      alt: 'a tractor is parked in the middle of a field',
    },
    {
      src: unsplash('1748073813267-af0cd7fddbaa'),
      alt: 'Tree workers operating heavy machinery on a job.',
    },
    {
      src: unsplash('1711489251756-6136fe7a70cd'),
      alt: 'a large machine that is sitting in the dirt',
    },
    {
      src: unsplash('1649807533255-bbc9c9fb7d77'),
      alt: 'a yellow excavator sitting on top of a dirt field',
    },
    {
      src: unsplash('1699989414700-a594eeb97c4d'),
      alt: 'a tractor is parked in a field with trees in the background',
    },
    {
      src: unsplash('1771974323395-42bc8993c64d'),
      alt: 'Two yellow john deere front-end loaders parked together.',
    },
    {
      src: unsplash('1769240628173-155c849658cc'),
      alt: 'Large excavator in a dry, dusty landscape',
    },
    {
      src: unsplash('1728330177586-40c1b10ee7dc'),
      alt: 'A large red machine sitting on top of a dirt field',
    },
    {
      src: unsplash('1610477865545-37711c53144d'),
      alt: 'yellow excavator on gray concrete road during daytime',
    },
    {
      src: unsplash('1702359562653-14a321274d47'),
      alt: 'a bulldozer and a bulldozer on a dirt road',
    },
    {
      src: unsplash('1649807438813-acc4489bcf0a'),
      alt: 'a yellow construction vehicle driving down a dirt road',
    },
    { src: unsplash('1602809254085-aa5c77291da1'), alt: 'yellow and black heavy equipment' },
    { src: unsplash('1576530107941-429553b97a91'), alt: 'yellow excavator near body of water' },
    {
      src: unsplash('1707510844722-ede3afa9858c'),
      alt: 'a large yellow bulldozer sitting on top of a gravel road',
    },
    { src: unsplash('1729799978438-dbfe9a1fee6d'), alt: 'A tractor and a bulldozer in a field' },
    {
      src: unsplash('1773525912431-ee1eff5e1ab9'),
      alt: 'Industrial screen printing machine in a workshop setting.',
    },
    {
      src: unsplash('1742163962826-6326bcba4181'),
      alt: 'A submarine control panel, full of buttons and dials.',
    },
    {
      src: unsplash('1693653409167-6cbb77374175'),
      alt: 'a yellow bulldozer is parked in the dirt',
    },
    {
      src: unsplash('1638245001983-62d08621621d'),
      alt: 'a tractor is parked in the middle of a field',
    },
    {
      src: unsplash('1719410545392-3b5bc1985902'),
      alt: 'A row of orange machines sitting next to each other',
    },
  ],
  metallier: [
    {
      src: unsplash('1711418235334-8895331a6cf9'),
      alt: 'a piece of metal being cut with a machine',
    },
    { src: unsplash('1681407979977-ea6060c802f6'), alt: 'a man working on a piece of metal' },
    {
      src: unsplash('1598302936625-6075fbd98dd7'),
      alt: 'person in black jacket holding brown wooden rolling pin',
    },
    {
      src: unsplash('1685713011172-3ba27ff25e22'),
      alt: 'a person using a grinder on a piece of metal',
    },
    {
      src: unsplash('1714504904786-b6732390b206'),
      alt: 'welder working on a piece of metal in a factory',
    },
    {
      src: unsplash('1745449064670-94bd0fc13df8'),
      alt: 'Workshop tools are scattered on a work table.',
    },
    { src: unsplash('1686236589375-15fd83d4584e'), alt: 'a man working on a piece of metal' },
    {
      src: unsplash('1648815546048-6da4f0083a6d'),
      alt: 'a man working on a metal object in a shop',
    },
    { src: unsplash('1648815546030-6a5792d4fa38'), alt: 'a welder working on a piece of metal' },
    { src: unsplash('1716031112197-db7e3e1e232e'), alt: 'a welder working on a pipe in the dark' },
    {
      src: unsplash('1764115424793-063c2a8b61f3'),
      alt: 'Man standing in a cluttered industrial workshop',
    },
    { src: unsplash('1745448797905-36e057c09088'), alt: 'Welding sparks brightly in the dark.' },
    {
      src: unsplash('1734888369502-3e01d4c0a46e'),
      alt: 'A man working with a grinder on a piece of metal',
    },
    {
      src: unsplash('1734888369524-bd915004d0c3'),
      alt: 'A man in a welding helmet working on a piece of metal',
    },
    {
      src: unsplash('1759847552281-60e45956124d'),
      alt: 'Welder working in a dark industrial setting',
    },
    { src: unsplash('1759159091728-e2c87b9d9315'), alt: 'Industrial metal clamps on machinery' },
    { src: unsplash('1727810655025-3b7bcdfc0d10'), alt: 'A toy airplane with a cat face on it' },
    { src: unsplash('1727413433181-ddbbdaacf7f5'), alt: 'A machine that is sitting on the ground' },
    {
      src: unsplash('1773401348019-629c2a92a871'),
      alt: 'Glowing hot coals with sparks flying upwards',
    },
    { src: unsplash('1775403908187-9bd4fc1ff053'), alt: "Man working at a blacksmith's forge" },
    {
      src: unsplash('1682332052872-0f7d7549e383'),
      alt: 'a person sitting on the ground in the dark',
    },
    { src: unsplash('1727413433452-b5c4b6367416'), alt: 'A man holding a gun in his right hand' },
    {
      src: unsplash('1773517460073-611de1ff5d1a'),
      alt: 'Vintage workbench with vises in a workshop',
    },
    {
      src: unsplash('1727413430950-ea623d4b2a42'),
      alt: 'A person using a grinder on a piece of metal',
    },
    {
      src: unsplash('1703113688767-4a32ef330643'),
      alt: 'a hammer and a block of wood on top of a bench',
    },
    {
      src: unsplash('1759763823587-c8bd07fca246'),
      alt: 'Workers in hard hats and safety vests in a workshop',
    },
    {
      src: unsplash('1763020884132-ff8075529d73'),
      alt: 'Person working at a forge with sparks flying',
    },
    {
      src: unsplash('1771591201020-5cd2ba14e731'),
      alt: 'A person grinding metal, creating sparks.',
    },
    {
      src: unsplash('1758873263528-6dbd0422cf84'),
      alt: 'Metal parts and components arranged on a wooden surface.',
    },
    { src: unsplash('1764037047390-b64587b70c76'), alt: 'Man working on a lathe in a workshop' },
    { src: unsplash('1648671921845-895549805092'), alt: 'a couple of men wearing protective gear' },
    {
      src: unsplash('1678611074737-4861a05715dd'),
      alt: 'a view of a factory from inside a building',
    },
    { src: unsplash('1610895953514-4c6f2f2f4393'), alt: 'brown metal wheel on brown brick wall' },
    {
      src: unsplash('1720282338064-6c47e32bc0b9'),
      alt: 'A large metal structure with a clock on top of it',
    },
    { src: unsplash('1610895953201-7740b6647dfa'), alt: 'brown and black metal pipe' },
    { src: unsplash('1610896813573-5c4bdd85b02f'), alt: 'brown wooden building during daytime' },
    { src: unsplash('1665167694074-6d7fedc04afe'), alt: 'a row of metal bars' },
    { src: unsplash('1610896813553-fdd1159eba3d'), alt: 'brown brick building during daytime' },
    { src: unsplash('1610895953389-01a345abfedc'), alt: 'brown and white abstract painting' },
    {
      src: unsplash('1610896813476-ac8945ca4348'),
      alt: 'gray concrete building under blue sky during daytime',
    },
    {
      src: unsplash('1610896813398-6e965b3cc1b3'),
      alt: 'the inside of a large building with lots of windows',
    },
    {
      src: unsplash('1666219462105-2909c2d72d01'),
      alt: 'a large factory building next to a body of water',
    },
    {
      src: unsplash('1711618734168-9935518143a4'),
      alt: 'a man standing in front of a construction site',
    },
    {
      src: unsplash('1610895953013-d545831dbe8e'),
      alt: 'brown concrete building under cloudy sky during daytime',
    },
    {
      src: unsplash('1764114441097-6a475eca993d'),
      alt: 'Industrial lathe machine with metal shavings',
    },
    {
      src: unsplash('1711618734367-0fc5e3d193aa'),
      alt: 'a bulldozer is parked in front of a construction site',
    },
    {
      src: unsplash('1764114235891-66ff86abaf87'),
      alt: 'Industrial laser cutter working on metal sheet',
    },
    {
      src: unsplash('1764114235896-034c8772de01'),
      alt: 'Industrial laser cutter working on metal sheet',
    },
    {
      src: unsplash('1765218933298-dc55fdfb517a'),
      alt: 'Industrial pipes and machinery in a factory',
    },
    {
      src: unsplash('1635895954202-378ac8928519'),
      alt: 'a rusted metal surface with rivets and rivet holes',
    },
    {
      src: unsplash('1764835994645-3faa2c40f708'),
      alt: 'Industrial machinery in a large factory setting',
    },
    {
      src: unsplash('1764114441005-df7e660bc2c8'),
      alt: 'Old industrial lathe machine with metal shavings',
    },
    {
      src: unsplash('1763950865631-4ca11bebe017'),
      alt: 'Various metal pipes and tubes stacked together.',
    },
    {
      src: unsplash('1673201159772-a3b7fa2ecc5d'),
      alt: 'a man wearing a hard hat working on a piece of metal',
    },
    {
      src: unsplash('1763926026024-2b294669e255'),
      alt: 'Metal rods stacked on shelves in a warehouse.',
    },
    {
      src: unsplash('1586333109867-812586269a58'),
      alt: 'man in green jacket and black pants holding fire',
    },
    {
      src: unsplash('1635895953897-054bbd0fffc8'),
      alt: 'a close up of a metal structure with holes in it',
    },
    {
      src: unsplash('1747999060057-89b7a533f347'),
      alt: 'Inside a large factory, equipment and workers are present.',
    },
    {
      src: unsplash('1673201159941-68fcdbbb4fa1'),
      alt: 'a machine room with lots of machines inside of it',
    },
  ],
  miroitier: [
    { src: unsplash('1625572648016-1a8e837e0502'), alt: 'red and yellow hallway with glass doors' },
    {
      src: unsplash('1571417876369-792231199054'),
      alt: 'a metal sculpture sitting in front of a building',
    },
    {
      src: unsplash('1575314027731-73250945c588'),
      alt: 'a group of disco balls sitting next to each other',
    },
    {
      src: unsplash('1730143459801-bf10c5bd52c9'),
      alt: 'A room that has a lot of glass on the floor',
    },
    { src: unsplash('1730143459225-34e62d0f0abf'), alt: 'A long hallway with a clock on the wall' },
    {
      src: unsplash('1730143459776-a53361397607'),
      alt: 'A broken mirror on the floor of a building',
    },
    {
      src: unsplash('1730143460206-3e1d04a430db'),
      alt: 'A group of people standing inside of a building',
    },
    { src: unsplash('1730143460099-fbcbbf6f24ee'), alt: 'A shattered glass table in a room' },
    {
      src: unsplash('1730143459319-1b102d86e555'),
      alt: 'A room with a light shining on the floor',
    },
    {
      src: unsplash('1730143459154-90d9fdf41e19'),
      alt: 'A large building with a lot of people inside of it',
    },
    {
      src: unsplash('1573484651903-701771f712be'),
      alt: 'grayscale photography of inside building view',
    },
    { src: unsplash('1650965173413-81827fa6ce5c'), alt: 'a woman with a mask on' },
    { src: unsplash('1730143459163-b076a9a559e1'), alt: 'A large room with a lot of windows' },
    {
      src: unsplash('1763396929790-6e7d1b378fa1'),
      alt: 'Geometric pattern with orange lines on black background',
    },
    {
      src: unsplash('1772550018820-7172a04e9c2e'),
      alt: 'A multitude of sparkling lights in the darkness',
    },
    {
      src: unsplash('1774560742713-cc20d835153c'),
      alt: 'Person taking a selfie in abstract mirrors on wall.',
    },
    {
      src: unsplash('1766997199917-dba5bfde06b2'),
      alt: 'Geometric tunnel with glowing teal lights',
    },
    { src: unsplash('1624007666785-8cccc435557e'), alt: 'white ceramic plates on glass shelf' },
    {
      src: unsplash('1642766590629-b9db3f838c6c'),
      alt: 'a white table topped with mirrors and a coat rack',
    },
    { src: unsplash('1666137127722-42835150f121'), alt: 'a close-up of a puzzle' },
    {
      src: unsplash('1539077161625-86a06d3ac12c'),
      alt: 'mirror displaying planes and concrete bridge',
    },
    { src: unsplash('1691844933287-b676037ab065'), alt: 'a mirror hanging on a wall above a sink' },
    { src: unsplash('1635413815784-fba90943b49b'), alt: 'a circular mirror on a white brick wall' },
    {
      src: unsplash('1600189530390-ccc3a5cc7bfb'),
      alt: 'clear glass ball with reflection of man standing on the floor',
    },
    { src: unsplash('1622010651510-78ce1782c2c1'), alt: 'white and black wall decor' },
    {
      src: unsplash('1736329101837-87bd1666bf63'),
      alt: 'A man taking a picture of himself in a mirror',
    },
    {
      src: unsplash('1740499270861-199e3f8537d9'),
      alt: 'A large room with a checkered floor and mirrors',
    },
    { src: unsplash('1616853107323-9d2d15f998c5'), alt: 'round silver ornament on white table' },
    {
      src: unsplash('1740499270987-537101d4a3a1'),
      alt: 'A large room with a checkered floor and mirrored walls',
    },
    {
      src: unsplash('1741346198350-5228f5f8a8d6'),
      alt: 'Ceiling tiles and wires are reflected on the floor.',
    },
    { src: unsplash('1702165641149-f7b957f8c91e'), alt: 'a man is working on a piece of wood' },
    { src: unsplash('1667234496425-78cb0c9a6225'), alt: 'a brick building with a brick wall' },
    {
      src: unsplash('1702165639480-f55d5391b9f6'),
      alt: 'a pair of scissors sitting on top of a wooden table',
    },
    {
      src: unsplash('1711006695550-ec63b64ca68b'),
      alt: 'a pair of black gloves are being used on a machine',
    },
    { src: unsplash('1586064957227-11d763b135a1'), alt: 'brown wooden handle on brown wooden box' },
    {
      src: unsplash('1723074832961-397744da2380'),
      alt: 'A wooden table topped with lots of legos',
    },
    {
      src: unsplash('1635184549996-8e482768acea'),
      alt: 'a man in a blue and white striped shirt working on a piece of metal',
    },
    {
      src: unsplash('1635184551030-5802a699c71b'),
      alt: 'a black and white photo of a man working in a factory',
    },
    { src: unsplash('1565062277727-7c545770e825'), alt: 'clear wine glass and clear glass bottle' },
    { src: unsplash('1672529275896-57e7a9f33616'), alt: 'a close up of a light on a table' },
    {
      src: unsplash('1705838942238-f5548a29bd3a'),
      alt: 'a glass filled with water on top of a table',
    },
    {
      src: unsplash('1775899538075-bcce0fa55359'),
      alt: 'Guitar and mechanical object on table near window',
    },
    {
      src: unsplash('1771965025951-040666ccaf2e'),
      alt: 'Man working in a dimly lit room through glass doors',
    },
    {
      src: unsplash('1768874020251-28706ecd7821'),
      alt: 'Bouquets of colorful flowers arranged on a table outdoors',
    },
  ],
  nettoyage: [
    {
      src: unsplash('1581578731548-c64695cc6952'),
      alt: 'woman in white long sleeve shirt and blue denim jeans standing beside white wooden framed glass',
    },
    { src: unsplash('1437326300822-01d8f13c024f'), alt: 'man cleaning on floor beside white wall' },
    {
      src: unsplash('1601160458000-2b11f9fa1a0e'),
      alt: 'person in white robe holding black and yellow umbrella',
    },
    { src: unsplash('1669101602108-fa5ba89507ee'), alt: 'a person standing on a treadmill' },
    {
      src: unsplash('1504827274833-7db1774520e3'),
      alt: 'person using ski boards during daytime photography',
    },
    { src: unsplash('1571568495363-99048b36777b'), alt: 'red and black sports bike during day' },
    { src: unsplash('1580970098304-a4c30996b7db'), alt: 'person surfing on sea during daytime' },
    {
      src: unsplash('1747659354528-b534bcd71aea'),
      alt: 'Hand holding a white and black spray bottle.',
    },
    { src: unsplash('1569202743734-fc8657296e6a'), alt: 'white sports coupe on road' },
    {
      src: unsplash('1774271101773-8e7cacedf12b'),
      alt: 'A window cleaner works high on a building exterior.',
    },
    {
      src: unsplash('1774977867750-5b56e82051d0'),
      alt: 'Man in black shirt and hard hat using a tool.',
    },
    {
      src: unsplash('1775178120132-f0ff7fd5cb40'),
      alt: 'Worker in blue uniform cleans window with spray bottle',
    },
    { src: unsplash('1552234458-9a63237d6d93'), alt: 'a blue ball is surrounded by white balls' },
    {
      src: unsplash('1579528542333-4148f1769c35'),
      alt: 'person wearing blue and white nike athletic shoes',
    },
    {
      src: unsplash('1775654063422-54e0a71578ad'),
      alt: 'A man cleaning windows on a tall building',
    },
    {
      src: unsplash('1623006108099-487c445e950a'),
      alt: 'a white sports car parked on the side of the road',
    },
    { src: unsplash('1762087021974-b0729f37a8fe'), alt: 'Window cleaners work on a tall building' },
    {
      src: unsplash('1774979161326-6ba6ed3a1864'),
      alt: 'Two window cleaners work on a tall building.',
    },
    {
      src: unsplash('1747659365283-dd36e0fb5b80'),
      alt: 'Person holds a white spray bottle overhead.',
    },
    { src: unsplash('1747659362772-3caabc37c579'), alt: 'A close-up shot of a spray bottle.' },
    { src: unsplash('1747659365190-c4ceea97aff7'), alt: 'A hand holds a white pump sprayer.' },
    {
      src: unsplash('1742353980377-b8e42932c590'),
      alt: 'A robotic pool cleaner is working underwater.',
    },
    { src: unsplash('1747659364071-96c1d30b520e'), alt: 'A hand holds a spray bottle.' },
    { src: unsplash('1747659354838-7ac98504dbb4'), alt: 'A person is holding a water bottle.' },
    { src: unsplash('1486048084996-2cec8eabc2ad'), alt: 'group of people riding white ski lift' },
    {
      src: unsplash('1741021632650-162065ae2b0d'),
      alt: 'Window washers are cleaning a tall building.',
    },
    { src: unsplash('1771491237209-b89bc7290588'), alt: 'Man cleaning car dashboard with brush' },
    {
      src: unsplash('1759647516042-7ab902682d9c'),
      alt: 'Hands cleaning a camera lens with a cloth.',
    },
    {
      src: unsplash('1629150631968-f4b17111acf3'),
      alt: 'yellow ferrari 458 italia parked near white building',
    },
    {
      src: unsplash('1629150681462-11ecd445cbf8'),
      alt: 'yellow ferrari car on gray asphalt road during daytime',
    },
    {
      src: unsplash('1758273238415-01ec03d9ef27'),
      alt: 'A woman mops a bright, modern living room floor.',
    },
    {
      src: unsplash('1758273238594-9a9d6c20eaa2'),
      alt: 'Woman mopping floor while listening to music.',
    },
    {
      src: unsplash('1758273238795-c284e5ae09b6'),
      alt: 'Woman with headphones happily cleaning with yellow gloves',
    },
    {
      src: unsplash('1758273705433-d1485e8f00e0'),
      alt: 'Woman singing and dancing while vacuuming a room',
    },
    {
      src: unsplash('1758273238370-3bc08e399620'),
      alt: 'Woman happily mopping the floor in a bright room.',
    },
    {
      src: unsplash('1758272422155-d898efd14f81'),
      alt: 'Woman with headphones mopping a wooden floor',
    },
    {
      src: unsplash('1758273238847-bc2c2548e210'),
      alt: 'Person happily mopping the floor while listening to music.',
    },
    {
      src: unsplash('1758273705438-2bb9e0eb21b7'),
      alt: 'Woman with headphones cleaning and dancing',
    },
    {
      src: unsplash('1758272421751-963195322eaa'),
      alt: 'Woman wearing yellow gloves cleaning wooden surface',
    },
    { src: unsplash('1758273238903-b5ca5f9988d1'), alt: 'Woman with headphones cleaning a shelf' },
    { src: unsplash('1758272421664-ae691f6cdafc'), alt: 'Woman dancing while mopping the floor' },
    {
      src: unsplash('1758273238564-806f750a2cce'),
      alt: 'Woman cleaning floor with mop while wearing headphones',
    },
    {
      src: unsplash('1758273238698-c98a45a8df9a'),
      alt: 'Woman with headphones cleaning floor with mop',
    },
    {
      src: unsplash('1758273238738-9410f7e9d53c'),
      alt: 'Woman wearing headphones cleans near a window.',
    },
    {
      src: unsplash('1758273705629-02e3c4bee11d'),
      alt: 'Woman happily vacuuming living room while listening to music.',
    },
    {
      src: unsplash('1758523670739-0d26a3ee976d'),
      alt: 'A woman vacuuming a bright, modern living room',
    },
    {
      src: unsplash('1758273238715-2b6c250167c4'),
      alt: 'Woman with headphones cleaning and dancing happily',
    },
    {
      src: unsplash('1758273238741-f33ab240baa0'),
      alt: 'Young woman with headphones cleaning a shelf',
    },
    {
      src: unsplash('1758273705627-937374bfa978'),
      alt: 'Woman happily vacuuming a bright, modern living room.',
    },
    {
      src: unsplash('1758272421772-5b08f08dc2ea'),
      alt: 'Woman cleaning while listening to music on headphones',
    },
    { src: unsplash('1758272421995-e993f97fae22'), alt: 'Woman in yellow gloves cleaning a shelf' },
    {
      src: unsplash('1758272421701-569f31f05fd1'),
      alt: 'Woman with headphones mops floor in living room',
    },
    {
      src: unsplash('1758272422189-b10f36fd4ddd'),
      alt: 'Woman mopping floor while wearing headphones.',
    },
    {
      src: unsplash('1758687125687-512a331f6a0a'),
      alt: 'Young girl vacuuming a striped rug in a living room.',
    },
    {
      src: unsplash('1758273705601-50b1b61f7e6c'),
      alt: 'Woman vacuuming a bright, modern living room',
    },
    {
      src: unsplash('1758273705511-834c8c3204e7'),
      alt: 'Woman vacuuming and listening to music with headphones.',
    },
    {
      src: unsplash('1758523670798-db1acfb7f3b0'),
      alt: 'Man playing vacuum cleaner like a guitar',
    },
    {
      src: unsplash('1758273238947-7eb530b408e4'),
      alt: 'Woman happily vacuuming a bright, modern room',
    },
    {
      src: unsplash('1758691030988-c7c55ab2ba18'),
      alt: 'Elderly woman vacuuming a colorful living room floor.',
    },
    {
      src: unsplash('1758273238400-9b1367ae90ec'),
      alt: 'Woman happily mopping a bright, modern living room.',
    },
  ],
  'panneaux-solaires': [
    {
      src: unsplash('1635424825057-7fb6dcd651ef'),
      alt: 'a man working on a roof with a power drill',
    },
    { src: unsplash('1635424709961-f3a150459ad4'), alt: 'two men working on the roof of a house' },
    {
      src: unsplash('1635424710918-d5c138981922'),
      alt: 'a man in a yellow shirt with a chainsaw on a roof',
    },
    { src: unsplash('1635424709870-cdc6e64f0e20'), alt: 'a couple of men working on a roof' },
    { src: unsplash('1635424709845-3a85ad5e1f5e'), alt: 'a couple of people that are on a roof' },
    {
      src: unsplash('1635424824849-1b09bdcc55b1'),
      alt: 'a man working on a roof with a power drill',
    },
    {
      src: unsplash('1635424824800-692767998d07'),
      alt: 'a man in a yellow shirt is working on a roof',
    },
    { src: unsplash('1635424710928-0544e8512eae'), alt: 'a man on a roof working with a rope' },
    {
      src: unsplash('1754620906703-496ec2451744'),
      alt: 'Worker installs electrical components on a roof.',
    },
    { src: unsplash('1754620906571-9ba64bd3ffb4'), alt: 'Worker installs wires on a roof.' },
    {
      src: unsplash('1754620906555-ba341e4a8c25'),
      alt: 'Solar panel connectors and wiring on a roof.',
    },
    { src: unsplash('1771178300970-230f7de19e9c'), alt: 'Rows of solar panels under a cloudy sky' },
    { src: unsplash('1726795867801-63c0a37b80c6'), alt: 'A large array of blue and white tiles' },
    {
      src: unsplash('1726795867795-32bc9872a44a'),
      alt: 'Two rows of rows of blue and white tiles',
    },
    {
      src: unsplash('1726866492047-7f9516558c6e'),
      alt: 'An aerial view of a parking lot with lots of solar panels',
    },
    {
      src: unsplash('1753781466451-ec9d6029557c'),
      alt: 'A drone flies high against a cloudy sky.',
    },
    { src: unsplash('1762960490358-f749f5a08aa5'), alt: 'Solar panels mounted on a brick wall' },
    {
      src: unsplash('1762958266408-5a8278e26506'),
      alt: 'Solar panel being installed on a metal frame.',
    },
    {
      src: unsplash('1763114613273-ec505136d03a'),
      alt: 'Two solar panels on a rooftop with autumn foliage.',
    },
    { src: unsplash('1762958266615-949dc88dcb37'), alt: 'Solar panel on a balcony with plants' },
    {
      src: unsplash('1768839727824-28d6f0dcd1d1'),
      alt: 'Solar panels in a field under a cloudy sky',
    },
    {
      src: unsplash('1762958266774-95abba6e0685'),
      alt: 'Balcony with solar panels on brick building',
    },
    {
      src: unsplash('1773291934106-f6e551493b83'),
      alt: 'Modern building with abstract sculpture and clear sky',
    },
    {
      src: unsplash('1624397640148-949b1732bb0a'),
      alt: 'man in white dress shirt and blue denim jeans sitting on white and black solar panel',
    },
    {
      src: unsplash('1713544123580-12096cc9eb12'),
      alt: 'the roof of a building with a lot of solar panels on it',
    },
    { src: unsplash('1660330589782-83776f89dd1e'), alt: 'a man on a ladder' },
    { src: unsplash('1660330589243-4c640d878052'), alt: 'men on top of a roof' },
    { src: unsplash('1663321508309-4ceb96a3c791'), alt: 'a blue and black tiled surface' },
    { src: unsplash('1660330589257-813305a4a383'), alt: 'a man on a roof' },
    { src: unsplash('1668097613572-40b7c11c8727'), alt: 'a person working on a solar panel' },
    {
      src: unsplash('1769697714710-4fce4b88a215'),
      alt: 'Rooftop solar panels partially covered in snow.',
    },
    { src: unsplash('1723046106153-8d3810267931'), alt: 'A house with a solar panel on the roof' },
    { src: unsplash('1735306161036-a541d4835f26'), alt: 'An airplane is flying over a building' },
    { src: unsplash('1651379560002-7fe2278df5a7'), alt: 'a group of buildings with red roofs' },
    {
      src: unsplash('1761472823286-9f6093ed6663'),
      alt: 'Rainbow over a suburban neighborhood with solar panels.',
    },
    {
      src: unsplash('1775317628391-a0429fe3be1b'),
      alt: 'Industrial building with sawtooth roof and sky',
    },
    {
      src: unsplash('1728291014119-392c27e7fead'),
      alt: 'A house with a fence and a clock on the front of it',
    },
    {
      src: unsplash('1763680694720-750dff419121'),
      alt: 'Aerial view of a suburban neighborhood with a long road.',
    },
    {
      src: unsplash('1769699903260-ff85271faa4f'),
      alt: 'Rooftop solar panels on a modern building in winter.',
    },
    { src: unsplash('1720610784599-18c02b1cc9ee'), alt: 'A house with a solar panel on the roof' },
    {
      src: unsplash('1769697672933-0f599f913f4d'),
      alt: 'Modern building exterior with many windows and solar panels.',
    },
    { src: unsplash('1761234799877-75cdf927d5e5'), alt: 'Houses with mountains in the background' },
    {
      src: unsplash('1761158495585-eac721decf1b'),
      alt: 'Orange roof with solar panels and overhead wires',
    },
    { src: unsplash('1691421740425-48ff22b6d442'), alt: 'a house with a solar panel on the roof' },
    {
      src: unsplash('1769697265831-02425ab88a11'),
      alt: 'Modern apartment buildings with solar panels on roofs.',
    },
    {
      src: unsplash('1772326281137-b617cbf77c5f'),
      alt: 'Aerial view of a suburban neighborhood with houses and streets.',
    },
    {
      src: unsplash('1765884929034-8abfe2c6c8ae'),
      alt: 'Modern cityscape with tall buildings and trees.',
    },
  ],
}
