/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 8 services, 464 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen5: Record<string, { src: string; alt: string }[]> = {
  macon: [
    { src: unsplash('1566474949309-1ecedbf7382e'), alt: 'stone wall' },
    { src: unsplash('1580863723632-061f02de8603'), alt: 'brown brick building during daytime' },
    { src: unsplash('1769104397835-2297e730f361'), alt: 'Stack of weathered red bricks' },
    {
      src: unsplash('1604205559635-4c6e883cf584'),
      alt: 'white and brown concrete building under white clouds during daytime',
    },
    { src: unsplash('1565433790755-34fe3b01eb30'), alt: 'white ornate embossed building' },
    {
      src: unsplash('1773601103174-306ffa23d441'),
      alt: 'Man repairing ancient brick structure outdoors',
    },
    {
      src: unsplash('1766499431068-7686d755cec7'),
      alt: 'Workers polishing large stone slabs outdoors',
    },
    {
      src: unsplash('1721244653657-ad6b91780492'),
      alt: 'A black and white photo of a plan of a building',
    },
    { src: unsplash('1763312774941-e1ae87003db2'), alt: 'Weathered stone wall with dark streaks.' },
    { src: unsplash('1565265652027-d0a5fdf66887'), alt: 'brown and green stone mansion' },
    {
      src: unsplash('1768154333269-dfc6c98e1ddc'),
      alt: 'Two construction workers repairing a dome structure.',
    },
    {
      src: unsplash('1769712905241-5d64503241ba'),
      alt: 'Close-up of an old weathered brick wall texture.',
    },
    {
      src: unsplash('1761932365108-013d069a71d0'),
      alt: 'A textured stone wall with rough, irregular blocks.',
    },
    {
      src: unsplash('1766355751664-ef8a25cf8463'),
      alt: 'Historic stone building with tall spires and trees.',
    },
    {
      src: unsplash('1763389168788-34255a794f20'),
      alt: 'Stone tower covered in ivy surrounded by trees',
    },
    {
      src: unsplash('1775982164149-75fe1242942e'),
      alt: 'Two thick ropes tied together in a knot.',
    },
    { src: unsplash('1774619167359-422fb85e7964'), alt: 'Circular stone pattern on a ceiling' },
    {
      src: unsplash('1774281175575-2c54e997a406'),
      alt: 'A wall made of irregular, multi-colored stones.',
    },
    {
      src: unsplash('1769193697750-a7e25a35a84e'),
      alt: 'Worker on lift repairing ancient roman archway',
    },
    {
      src: unsplash('1759681742529-178f7d8b4fb8'),
      alt: 'Ornate lantern hanging in arched walkway',
    },
    { src: unsplash('1774619188808-47786a040bb7'), alt: 'Stone ceiling with a circular pattern' },
    {
      src: unsplash('1766355751589-d8e1f3bad783'),
      alt: 'Stone church with autumn trees and gothic window',
    },
    {
      src: unsplash('1704005446360-5f30e4276182'),
      alt: 'a brick wall being built with a pair of hands',
    },
    {
      src: unsplash('1701850009190-2859ba2aeea6'),
      alt: 'a person is putting cement on a brick wall',
    },
    { src: unsplash('1704005446393-0262b4cb6877'), alt: 'a man is working on a brick wall' },
    {
      src: unsplash('1709880086179-b0bd18eee605'),
      alt: 'a couple of women sitting next to a pile of bricks',
    },
    {
      src: unsplash('1709200311586-82f9e485a2c8'),
      alt: 'a couple of people that are kneeling down in the dirt',
    },
    {
      src: unsplash('1673865641469-34498379d8af'),
      alt: 'a man in blue overalls working on cement',
    },
    {
      src: unsplash('1600762029324-04aad09c8680'),
      alt: 'man in white dress shirt and pants holding a stick',
    },
    { src: unsplash('1589176946347-cfd9aa09f2e0'), alt: 'brown and green camouflage utility cart' },
    {
      src: unsplash('1617720356637-6264c1c0b4bb'),
      alt: 'man in yellow t-shirt and blue denim jeans climbing on brown concrete wall during daytime',
    },
    { src: unsplash('1489514354504-1653aa90e34e'), alt: 'man walking on construction site' },
    { src: unsplash('1604177772199-15bd3a2b1217'), alt: 'brown and black brick wall' },
    {
      src: unsplash('1621871067013-1811c7c86293'),
      alt: 'gray concrete brick wall near green grass and trees during daytime',
    },
    { src: unsplash('1604177772727-521c04d3bdb5'), alt: 'brown and white brick wall' },
    { src: unsplash('1604177772691-1760e2586474'), alt: 'brown brick wall during daytime' },
    { src: unsplash('1604178449662-5a8811c420cd'), alt: 'white and black brick wall' },
    { src: unsplash('1604178101480-613d78ab0b92'), alt: 'brown and black brick wall' },
    { src: unsplash('1604178101301-cc4a8b6ce097'), alt: 'brown and black brick wall' },
    { src: unsplash('1604178449280-1b05d3429645'), alt: 'brown and gray brick wall' },
    { src: unsplash('1604177772549-5896d1ed1044'), alt: 'brown and white brick wall' },
    { src: unsplash('1604177772912-72e734fbf8a5'), alt: 'brown and black brick wall' },
    { src: unsplash('1663069102653-a8085910df24'), alt: 'a large stone building' },
    {
      src: unsplash('1695315145745-1bed621943d6'),
      alt: 'a man riding a skateboard on top of a wooden bench',
    },
    { src: unsplash('1740955725482-d038b0b9f13d'), alt: 'A close up of a red brick sidewalk' },
    {
      src: unsplash('1679108230151-77401eb692b6'),
      alt: 'a man sitting on a ledge working on something',
    },
    { src: unsplash('1724067526348-1c70579d7506'), alt: 'A close up of a red brick wall' },
    { src: unsplash('1682960972476-89d8a887e7aa'), alt: 'a teddy bear laying on a brick floor' },
    {
      src: unsplash('1718969604981-de826f44ce15'),
      alt: 'A tall red building sitting next to a tall building',
    },
    {
      src: unsplash('1681476318420-412c9aba1dfa'),
      alt: 'a pile of wood sitting next to a pile of rocks',
    },
    {
      src: unsplash('1636024523500-b1b7ab411ccb'),
      alt: 'a red fire hydrant in front of a brick wall',
    },
    { src: unsplash('1565118387387-add70a563efe'), alt: 'man working on building' },
    { src: unsplash('1651862318980-ecefc83c9f38'), alt: 'a brick wall with a brick wall' },
    { src: unsplash('1609546465772-c9c8b9d231d9'), alt: 'brown and gray brick wall' },
    { src: unsplash('1630180021706-47eed0b51e1b'), alt: 'brown and gray concrete brick' },
    { src: unsplash('1630180799448-f58750c61184'), alt: 'brown and white brick floor' },
    { src: unsplash('1517056338492-cb43f18f72a0'), alt: 'orange brick wall' },
    {
      src: unsplash('1671554553520-77d4916ea5bc'),
      alt: 'a close up of a hammer and a piece of wood',
    },
  ],
  jardinier: [
    {
      src: unsplash('1617576683096-00fc8eecb3af'),
      alt: 'person in blue long sleeve shirt holding brown and black bird',
    },
    { src: unsplash('1561563239-a6d2bd5dda20'), alt: 'red flower in a field during daytime' },
    { src: unsplash('1597868165956-03a6827955b1'), alt: 'person holding green plant stem' },
    {
      src: unsplash('1764173038986-9d1261cd01a1'),
      alt: 'Man trimming tall grass and reeds in park.',
    },
    {
      src: unsplash('1611735341450-74d61e660ad2'),
      alt: 'boy in black and white long sleeve shirt standing beside gray metal watering can during daytime',
    },
    {
      src: unsplash('1599778150914-88e98e0c3a3e'),
      alt: 'brown and green sock on gray wooden surface',
    },
    {
      src: unsplash('1726900712216-cafe6e5038c9'),
      alt: 'A small building with a blue chair in it',
    },
    {
      src: unsplash('1726900711780-66594b1536d0'),
      alt: 'A blue wheelbarrow hanging from the side of a building',
    },
    {
      src: unsplash('1764173040050-b7a87824bc22'),
      alt: 'Man trimming bushes with pruning shears outdoors.',
    },
    {
      src: unsplash('1764173040234-947b88cb6975'),
      alt: 'Man trimming bushes with shears in a grassy field.',
    },
    { src: unsplash('1721673026533-bbf642d94521'), alt: 'A woman pushing a wheelbarrow in a park' },
    {
      src: unsplash('1597868165446-b4d63d6103e5'),
      alt: 'person holding green vegetable on blue plastic container',
    },
    { src: unsplash('1598132393741-dc8c8eb5a54d'), alt: 'person holding green plastic cup' },
    {
      src: unsplash('1593296402439-e1a270dd253d'),
      alt: 'man in white long sleeve shirt and gray pants standing on green grass field',
    },
    {
      src: unsplash('1758524056457-df71fc7f6434'),
      alt: 'Couple tending to plants outside greenhouses',
    },
    { src: unsplash('1599907918964-36e6a527b42a'), alt: 'text' },
    { src: unsplash('1764173040025-0bf0a4bbb000'), alt: 'Man pruning dry plants in a field' },
    {
      src: unsplash('1678025546757-666c1f397c2d'),
      alt: 'a garden filled with lots of green plants',
    },
    { src: unsplash('1727513541940-399a95073612'), alt: 'Group of women holding gardening tools' },
    { src: unsplash('1597868067409-da83ce22ed76'), alt: 'yellow flower on persons hand' },
    {
      src: unsplash('1720637402638-91ec17edd738'),
      alt: 'A man in a white shirt and khaki pants standing in a greenhouse',
    },
    {
      src: unsplash('1733388972592-ec1da2ddc432'),
      alt: 'A group of people sitting on top of a bench',
    },
    { src: unsplash('1667627881443-1a427b90491e'), alt: 'a bee on a flower' },
    { src: unsplash('1599907919090-1a2a148978ea'), alt: 'green and white plant during daytime' },
    { src: unsplash('1769787703122-3576bbafb564'), alt: 'Young man tending to plants in a garden' },
    { src: unsplash('1667627881614-886b45a3101a'), alt: 'a bee on a flower' },
    {
      src: unsplash('1774647001686-314f877fb9c5'),
      alt: 'Gardening shears resting in soil within a pot',
    },
    {
      src: unsplash('1627740283098-1c544d3a479d'),
      alt: 'man in black and gray stripe long sleeve shirt and gray pants holding gray metal bar',
    },
    {
      src: unsplash('1749030420243-0169ddad203b'),
      alt: 'A person strolls through a lush greenhouse.',
    },
    {
      src: unsplash('1764173039235-fd1b8e9ad67f'),
      alt: 'Man in reflective vest examining plants with camera',
    },
    {
      src: unsplash('1734079692160-fcbe4be6ab96'),
      alt: 'A man pulling a wheelbarrow with a wheel',
    },
    {
      src: unsplash('1770234848941-8bd67b57d700'),
      alt: 'Manicured trees in a grassy garden setting.',
    },
    {
      src: unsplash('1750762286053-28632f48e717'),
      alt: 'Lush green pathway through a tropical garden.',
    },
    {
      src: unsplash('1761637823730-fab1f300084d'),
      alt: 'Stone wall with plants and a narrow window.',
    },
    {
      src: unsplash('1770820614472-3160d25f80f0'),
      alt: 'A manicured garden with red flowers and cypress trees.',
    },
    { src: unsplash('1759509474971-0f1f35a29efd'), alt: 'Topiary ducks in a garden setting' },
    {
      src: unsplash('1750762286044-d799678baf6d'),
      alt: 'A green garden path leads to the distance.',
    },
    {
      src: unsplash('1761637823293-f96835ec5038'),
      alt: 'Curved stone wall surrounding a circular paved area',
    },
    {
      src: unsplash('1639003332116-a2429ce6059b'),
      alt: 'a pond in a park with buildings in the background',
    },
    {
      src: unsplash('1626075218494-89e92b375502'),
      alt: 'woman in red jacket sitting on bench under green tree during daytime',
    },
    {
      src: unsplash('1775593047935-9f124b3f4e03'),
      alt: 'Green bushes and plants in front of a modern fence.',
    },
    { src: unsplash('1759577085762-7a7bfe8b5bf8'), alt: 'Red and white flowers in a garden bed' },
    {
      src: unsplash('1759577084515-63884a948fe6'),
      alt: 'Colorful flower bed with red and pink blossoms',
    },
    {
      src: unsplash('1759355787144-46638450cb0c'),
      alt: 'A large tan house with manicured gardens and palm trees.',
    },
    {
      src: unsplash('1759751048515-42d26d506098'),
      alt: 'A formal garden with manicured hedges and a gravel path.',
    },
    {
      src: unsplash('1759509474694-77d7c5d63beb'),
      alt: 'Lush green trees in a sunny park with blue sky.',
    },
    {
      src: unsplash('1761637823183-f5b3176a2fbc'),
      alt: 'Bamboo stalks and rocks in a garden setting',
    },
    {
      src: unsplash('1761489356802-afe917fe7ad2'),
      alt: 'A wooden bench sits in a manicured garden with hedges.',
    },
    {
      src: unsplash('1766256111797-a85b7ae50881'),
      alt: 'Terraced garden with stone walls and cypress trees',
    },
    {
      src: unsplash('1734079692079-aae7e24a7035'),
      alt: "A close up of a person's feet on the grass",
    },
    {
      src: unsplash('1622480190621-c277f2984fab'),
      alt: 'purple and pink flowers on green grass field',
    },
    {
      src: unsplash('1767334996666-e288d67821c2'),
      alt: 'A beautifully manicured garden with colorful flowers and trees.',
    },
    {
      src: unsplash('1758905458386-68ef08535428'),
      alt: 'Manicured garden with greenhouse and historic building.',
    },
    { src: unsplash('1566263687266-f59b56b50896'), alt: 'red bridge near tree' },
    {
      src: unsplash('1668120089662-42642838cfef'),
      alt: 'a large green lawn with bushes and trees',
    },
    {
      src: unsplash('1774272815977-f7b17dccfc73'),
      alt: 'A lush garden with blooming white flowers and green foliage.',
    },
    {
      src: unsplash('1759577085492-6377afa3f5ff'),
      alt: 'Colorful flower beds arranged in curved patterns',
    },
    {
      src: unsplash('1773424182268-c9b15a0ce10f'),
      alt: 'Purple dahlias bloom beside a path in a garden.',
    },
    {
      src: unsplash('1764523928406-724e4dc430db'),
      alt: 'Tall cypress tree with weeping branches against blue sky',
    },
    {
      src: unsplash('1775356127691-3aa87e5d8175'),
      alt: 'Lush garden with ornamental grasses and plants',
    },
  ],
  climaticien: [
    {
      src: unsplash('1761642119720-1ce47b16d09b'),
      alt: 'Multiple air conditioning units hanging indoors',
    },
    { src: unsplash('1716703432213-3c7a6f75e535'), alt: 'a ping pong table in a large room' },
    {
      src: unsplash('1757219525975-03b5984bc6e8'),
      alt: 'An air conditioning unit mounted on a wall.',
    },
    {
      src: unsplash('1722131646940-b821a6cc6252'),
      alt: 'A air conditioner mounted to the side of a building',
    },
    {
      src: unsplash('1673784716250-160cf5cb3a19'),
      alt: 'a black and white photo of an air conditioner on the side of a building',
    },
    {
      src: unsplash('1722010811002-a772b2066890'),
      alt: 'An air conditioner mounted to the side of a building',
    },
    {
      src: unsplash('1741252456359-448849473d01'),
      alt: 'Air conditioning units on a building roof.',
    },
    {
      src: unsplash('1705444509014-fed54b6191bf'),
      alt: 'a row of air conditioners sitting on top of a tiled floor',
    },
    {
      src: unsplash('1745745593296-28fd43a6ebba'),
      alt: 'Air conditioners are attached to a brick building.',
    },
    {
      src: unsplash('1737298336557-4c161fc6bc50'),
      alt: 'A tall building with lots of windows and a clock',
    },
    {
      src: unsplash('1758798157512-f0a864c696c9'),
      alt: 'Close-up of an air conditioning unit on a sunny day.',
    },
    {
      src: unsplash('1773952137490-2bea3f95ed39'),
      alt: 'Multiple air conditioning units mounted on a building.',
    },
    {
      src: unsplash('1738617456836-521b634c0141'),
      alt: 'A large air conditioner mounted on the side of a building',
    },
    {
      src: unsplash('1765850262030-1ae93e474473'),
      alt: 'Industrial ceiling with ventilation and lighting',
    },
    { src: unsplash('1617861648989-76a572012089'), alt: 'white and gray box fan' },
    { src: unsplash('1601993198415-19d86ae28424'), alt: 'black and gray box fan' },
    {
      src: unsplash('1635604866833-70844856de75'),
      alt: 'a building with a bunch of pipes on the side of it',
    },
    {
      src: unsplash('1723642045204-3ca8b1b6b43d'),
      alt: 'A group of speakers mounted to the side of a building',
    },
    {
      src: unsplash('1603516084021-1cfa399b64ca'),
      alt: 'white and gray box fan on brown wooden table',
    },
    { src: unsplash('1752336612713-cd5c2f0dac73'), alt: 'A green hose on a deck near a boat.' },
    { src: unsplash('1744478037987-538f5087fe94'), alt: 'Two air conditioners on a white wall.' },
    { src: unsplash('1668954095105-30b1f80deb9d'), alt: 'a building with windows and a tree' },
    {
      src: unsplash('1774851218623-900286a77155'),
      alt: 'Sunlight illuminates an old building with air conditioners.',
    },
    { src: unsplash('1774290331891-5d759056c68d'), alt: 'Row of white hvac units on a rooftop' },
    {
      src: unsplash('1654880821975-681bd2ff42ae'),
      alt: 'a room with a table and a window with curtains',
    },
    {
      src: unsplash('1722604534408-1b451a6e55e6'),
      alt: 'An empty room with a brick wall and two windows',
    },
    { src: unsplash('1565536076053-784a322e08eb'), alt: 'green leafed plant' },
    {
      src: unsplash('1728426340277-b2e45fa616a1'),
      alt: 'A wall mounted air conditioner on the side of a building',
    },
    { src: unsplash('1550998251-1e18917c975c'), alt: 'white air condenser unit' },
    {
      src: unsplash('1729913577179-19c9c89e405b'),
      alt: 'A tall building with lots of windows and air conditioners',
    },
    {
      src: unsplash('1708449287110-2f2418fb5a62'),
      alt: 'an airplane is flying over a city with tall buildings',
    },
    {
      src: unsplash('1695124348827-6b66b4771432'),
      alt: 'a black and white photo of an air conditioner in front of a building',
    },
    { src: unsplash('1667983453881-4992fe86ab1b'), alt: 'a wall with a few doors' },
    {
      src: unsplash('1647022528152-52ed9338611d'),
      alt: 'a white phone mounted to the side of a building',
    },
    {
      src: unsplash('1694675879520-ff32d348fb7f'),
      alt: 'a couple of air conditioners sitting on the side of a building',
    },
    {
      src: unsplash('1751486289950-5c4898a4c773'),
      alt: 'Pipes and equipment are installed on a wall.',
    },
    { src: unsplash('1665826254141-bfa10685e002'), alt: 'a white box with a vent' },
    {
      src: unsplash('1665826189237-19707ccb073b'),
      alt: 'a white rectangular object with a round metal object on it',
    },
    {
      src: unsplash('1719654139195-125b517a2acf'),
      alt: 'A building with a lot of windows and a sky background',
    },
    {
      src: unsplash('1737256359080-9354dbcc21ef'),
      alt: 'A large building with a roof and a sky background',
    },
    {
      src: unsplash('1637327534911-ee8057d51aec'),
      alt: 'a building with a clock on the side of it',
    },
    {
      src: unsplash('1634114581640-9a1734fae3e5'),
      alt: 'a black and white photo of a large metal object',
    },
    {
      src: unsplash('1677326140858-47e96c706b4e'),
      alt: 'an old electrical box on the side of a building',
    },
    { src: unsplash('1629933080351-da74fcddec5f'), alt: 'black and orange camera tripod' },
    {
      src: unsplash('1769531682600-205cb9eb391e'),
      alt: 'Outdoor air conditioning units and yellow pipes on wall.',
    },
    {
      src: unsplash('1637971821576-f42fa65cd79c'),
      alt: 'an air conditioner sitting on the side of a building',
    },
    {
      src: unsplash('1739573709776-5bbe22f1b708'),
      alt: 'A projector sitting on top of a window sill',
    },
    { src: unsplash('1647155879550-ff641f7c5576'), alt: 'a close up of a speaker in a car' },
    { src: unsplash('1573641232560-bb0873d987ef'), alt: 'gray window-type AC unit during daytime' },
    {
      src: unsplash('1757562593192-e15aa89e7876'),
      alt: 'Man wearing respirator and apron working in workshop.',
    },
    {
      src: unsplash('1718203862467-c33159fdc504'),
      alt: 'a white air conditioner sitting on top of a brick wall',
    },
    { src: unsplash('1590620284812-3216c0ea0a75'), alt: 'white ceiling fan turned on in room' },
    { src: unsplash('1668947038370-27639c916646'), alt: 'a building with a blue roof' },
    { src: unsplash('1668886581054-8f5b81c0e8c1'), alt: 'a close-up of a computer' },
    {
      src: unsplash('1768528385761-e88a54b261ea'),
      alt: 'Modern glass building with windows and air conditioners',
    },
  ],
  cuisiniste: [
    { src: unsplash('1618832515490-e181c4794a45'), alt: 'white wooden cabinet near window' },
    {
      src: unsplash('1601760561441-16420502c7e0'),
      alt: 'white wooden kitchen cabinet with white pendant lamp',
    },
    { src: unsplash('1507089947368-19c1da9775ae'), alt: 'white kitchen room set' },
    {
      src: unsplash('1613082374567-52aefdea4f3a'),
      alt: 'white wooden kitchen cabinet and white kitchen cabinet',
    },
    { src: unsplash('1565183928294-7063f23ce0f8'), alt: 'rectangular white wooden table' },
    {
      src: unsplash('1649083048428-3d8ed23a3ce0'),
      alt: 'a kitchen with a center island with stools',
    },
    {
      src: unsplash('1649083048198-f57bd8fb7a3b'),
      alt: 'a kitchen with a sink, stove, and a window',
    },
    {
      src: unsplash('1573168710465-7f7da9a23a15'),
      alt: 'turned on pendant lamps above kitchen island',
    },
    { src: unsplash('1611066415943-0a8cd437788c'), alt: 'white ceramic sink with faucet' },
    {
      src: unsplash('1649083048391-1c9e82472f65'),
      alt: 'a kitchen with three stools and a center island',
    },
    { src: unsplash('1552155235-a68a6c02d512'), alt: 'white wooden kitchen cabinet' },
    { src: unsplash('1611066415884-1eca899980ce'), alt: 'white ceramic bathtub near white wall' },
    {
      src: unsplash('1484154218962-a197022b5858'),
      alt: 'gray steel 3-door refrigerator near modular kitchen',
    },
    {
      src: unsplash('1682888813734-b1b0a4f79385'),
      alt: 'a kitchen with white cabinets and wood floors',
    },
    { src: unsplash('1587177139620-987629766ec7'), alt: 'silver and brown steel frame' },
    { src: unsplash('1546551613-09c2f83e1ede'), alt: 'three clear glass bar stools' },
    { src: unsplash('1541123437800-1bb1317badc2'), alt: 'dining set photography' },
    {
      src: unsplash('1571843439991-dd2b8e051966'),
      alt: 'a kitchen with a center island with stools',
    },
    {
      src: unsplash('1611066415694-3cac1296ad9c'),
      alt: 'white wooden kitchen cabinet near black flat screen tv',
    },
    {
      src: unsplash('1611493130828-1fd085ffadde'),
      alt: 'red and white flowers in clear glass vase on table',
    },
    {
      src: unsplash('1611066415991-4beffe4fd55b'),
      alt: 'yellow round fruits on white kitchen counter',
    },
    {
      src: unsplash('1611066415941-3262d8033fa9'),
      alt: 'orange fruits on stainless steel kitchen counter',
    },
    {
      src: unsplash('1772567732969-c1506edf80a0'),
      alt: 'Modern kitchen with island and pendant light.',
    },
    {
      src: unsplash('1755316388093-faff473ffdfb'),
      alt: 'Modern kitchen with marble island and dining area',
    },
    {
      src: unsplash('1765959990052-fab57c043979'),
      alt: 'Modern kitchen with light green cabinets and stainless steel appliances.',
    },
    {
      src: unsplash('1773867567732-556eb4351fd7'),
      alt: 'Modern stainless steel gas range in a bright kitchen.',
    },
    {
      src: unsplash('1773867567776-f727d0a6c1d4'),
      alt: 'Modern kitchen with island and bar stools',
    },
    {
      src: unsplash('1771862956702-4e8b247e28b5'),
      alt: 'Modern kitchen with sleek cabinets and pendant lights.',
    },
    {
      src: unsplash('1772567732923-5ba1956dcd07'),
      alt: 'Modern kitchen island with decorative vases and faucet.',
    },
    {
      src: unsplash('1769326541248-5e09a8ace25b'),
      alt: 'Modern kitchen with island and three stools',
    },
    {
      src: unsplash('1680210849773-f97a41c6b7ed'),
      alt: 'a kitchen area with a sink, cabinets and a window',
    },
    { src: unsplash('1665507279638-5b48073c637b'), alt: 'a kitchen with white cabinets' },
    { src: unsplash('1665507279636-0b268fb3f6ca'), alt: 'a kitchen with white cabinets' },
    { src: unsplash('1665507279750-ced2d97a9be9'), alt: 'a kitchen with white cabinets' },
    { src: unsplash('1665507279644-67d8ed143a84'), alt: 'a kitchen with white cabinets' },
    { src: unsplash('1665507279458-b21dea52c447'), alt: 'a kitchen with white cabinets' },
    { src: unsplash('1665507279656-0cdec047c4ea'), alt: 'a kitchen with white cabinets' },
    { src: unsplash('1658280911730-467b4764c09c'), alt: 'a kitchen with black cabinets' },
    {
      src: unsplash('1666704369274-83898c9309ef'),
      alt: 'a kitchen with a dining table and chairs',
    },
    {
      src: unsplash('1725257928373-dc6d2ac7b145'),
      alt: 'A kitchen and dining room with a table and chairs',
    },
    {
      src: unsplash('1639405069836-f82aa6dcb900'),
      alt: 'a modern kitchen with stainless steel appliances and marble counter tops',
    },
    { src: unsplash('1669046222569-a7672da06e12'), alt: 'a kitchen with white cabinets' },
    {
      src: unsplash('1682888813789-c39fe30921e2'),
      alt: 'a large kitchen with a center island in the middle of the room',
    },
    { src: unsplash('1609280069678-ab9ef26a0b05'), alt: 'brown and white pendant lamp' },
    {
      src: unsplash('1682888818602-b4492fadf2f8'),
      alt: 'a kitchen with white cabinets and a large window',
    },
    {
      src: unsplash('1682888818650-0a7cbb35287d'),
      alt: 'a kitchen with white cabinets and marble counter tops',
    },
    { src: unsplash('1668026694348-b73c5eb5e299'), alt: 'a kitchen with a bar and island' },
    {
      src: unsplash('1682888818620-94875adf5bb9'),
      alt: 'a kitchen with white cabinets and a stove top oven',
    },
    {
      src: unsplash('1682888813726-24adc990e6f7'),
      alt: 'a large kitchen with a center island and white cabinets',
    },
    {
      src: unsplash('1682888813795-192fca4a10d9'),
      alt: 'a large kitchen with a center island and marble counter tops',
    },
    {
      src: unsplash('1682888813788-373f947aacb3'),
      alt: 'a large white kitchen with a marble island',
    },
    {
      src: unsplash('1682888813913-e13f18692019'),
      alt: 'a large kitchen with a marble island and white cabinets',
    },
    {
      src: unsplash('1682888813788-bf57c360123e'),
      alt: 'a large kitchen with a center island and marble counter tops',
    },
    {
      src: unsplash('1682888818589-404faaa4dbc9'),
      alt: 'a kitchen with white cabinets and gold handles',
    },
    {
      src: unsplash('1758555226274-7b9f5c220b64'),
      alt: 'Modern kitchen with black countertops and stainless steel appliances.',
    },
    {
      src: unsplash('1682888818718-74b9ffa75907'),
      alt: 'a large kitchen with a table and chairs in it',
    },
    {
      src: unsplash('1771862956369-c840b0a1fc9d'),
      alt: 'Modern kitchen with island and bar stools',
    },
    {
      src: unsplash('1744094064448-3bfaac32eaa6'),
      alt: 'A modern kitchen with appliances and fruit.',
    },
    {
      src: unsplash('1774716925718-82ea2f2eb01b'),
      alt: 'Modern kitchen sink with white cabinets and countertop',
    },
    {
      src: unsplash('1759147960461-b74a7e9a75d4'),
      alt: 'Modern kitchen with island and bar stools.',
    },
  ],
  'salle-de-bain': [
    {
      src: unsplash('1584622650111-993a426fbf0a'),
      alt: 'white ceramic sink near white ceramic sink',
    },
    { src: unsplash('1629079447777-1e605162dc8d'), alt: 'white ceramic sink with mirror' },
    {
      src: unsplash('1620626011761-996317b8d101'),
      alt: 'white ceramic bathtub near green potted plant',
    },
    {
      src: unsplash('1631048499052-e6d9f305d2c0'),
      alt: 'white ceramic sink with stainless steel faucet',
    },
    {
      src: unsplash('1744869524920-f0efc925b82f'),
      alt: 'A modern bathroom with shower and bathtub.',
    },
    { src: unsplash('1517581177682-a085bb7ffb15'), alt: 'man climbing on ladder inside room' },
    { src: unsplash('1600488999585-e4364713b90a'), alt: 'white ceramic sink with faucet' },
    {
      src: unsplash('1564540579594-0930edb6de43'),
      alt: 'a bathroom with two sinks and a large mirror',
    },
    { src: unsplash('1507652313519-d4e9174996dd'), alt: 'white ceramic bathtub' },
    { src: unsplash('1609946860441-a51ffcf22208'), alt: 'blue wooden cabinet near white wall' },
    {
      src: unsplash('1618236444666-105ec54b5b69'),
      alt: 'white ceramic toilet bowl beside white ceramic toilet bowl',
    },
    {
      src: unsplash('1679736907648-601dcb45b5b9'),
      alt: 'a bathroom with two sinks, a toilet and a shower',
    },
    { src: unsplash('1572742482459-e04d6cfdd6f3'), alt: 'dresser near glass shower stall' },
    {
      src: unsplash('1682888818704-6dc91e9d7532'),
      alt: 'a bathroom with green cabinets and a marble shower',
    },
    {
      src: unsplash('1613688684111-5c197974be20'),
      alt: 'white wooden bathroom cabinet with mirror',
    },
    { src: unsplash('1564540583246-934409427776'), alt: 'white ceramic sink' },
    {
      src: unsplash('1679736581003-46477812b9a5'),
      alt: 'a bathroom sink with a plant in the corner',
    },
    {
      src: unsplash('1611066415697-7f58dc0a5d10'),
      alt: 'white ceramic sink beside white ceramic sink',
    },
    {
      src: unsplash('1774578342098-66adff9c1fe1'),
      alt: 'A modern bathroom vanity with two sinks and mirrors.',
    },
    {
      src: unsplash('1611066415956-91ab6f1f57cc'),
      alt: 'stainless steel shower head on white ceramic wall tiles',
    },
    {
      src: unsplash('1762418362644-a4daad168fb9'),
      alt: 'Modern bathroom with double vanity and mint green walls',
    },
    {
      src: unsplash('1611066415506-54b1bf5da1f7'),
      alt: 'white ceramic bathtub with stainless steel faucet',
    },
    {
      src: unsplash('1774578341998-d1e9a74e82f6'),
      alt: 'Modern bathroom vanity with double sinks and mirrors.',
    },
    {
      src: unsplash('1759223607861-f0ef3e617739'),
      alt: 'Luxurious marble bathroom with bathtub and vanity.',
    },
    { src: unsplash('1674649207745-f4667b978783'), alt: 'a bathroom with a sink and a window' },
    {
      src: unsplash('1774578341948-f3a15f81a34d'),
      alt: 'Modern freestanding bathtub with black faucet and side table.',
    },
    {
      src: unsplash('1772563175261-07ab8d463293'),
      alt: 'Modern bathroom with a sink and bathtub.',
    },
    {
      src: unsplash('1771681278446-6f8eb0c7323f'),
      alt: 'Two wooden vanities with oval mirrors and gold fixtures.',
    },
    {
      src: unsplash('1758548157466-7c454382035a'),
      alt: 'Modern bathroom with white marble and bathtub.',
    },
    {
      src: unsplash('1760126722520-0cc43cede2b5'),
      alt: 'Antique brass faucet with hot and cold handles',
    },
    {
      src: unsplash('1688786219616-598ed96aa19d'),
      alt: 'a bathtub in a bathroom with a plant in the corner',
    },
    {
      src: unsplash('1682888818696-906287d759f5'),
      alt: 'a bathroom with marble counter tops and green cabinets',
    },
    {
      src: unsplash('1769763917830-7b9c8317329d'),
      alt: 'Modern black oval sink with marble wall and countertop.',
    },
    { src: unsplash('1595515770120-6a44e3b2391c'), alt: 'black and silver box mod' },
    {
      src: unsplash('1613849925383-fab6d1d1353b'),
      alt: 'stainless steel faucet near white framed glass window',
    },
    { src: unsplash('1613849925594-415a32298f54'), alt: 'white bathtub near white bathtub' },
    { src: unsplash('1613849925352-96348d26bc51'), alt: 'white ceramic sink with mirror' },
    { src: unsplash('1595515107258-ce1e4ea1ba59'), alt: 'stainless steel sink with faucet' },
    { src: unsplash('1613849925502-7b0f95cbdda0'), alt: 'red towel on stainless steel towel rack' },
    { src: unsplash('1613849925580-8ef3bc1cf219'), alt: 'brown wooden cabinet with mirror' },
    {
      src: unsplash('1613849925362-38fb4c16ff36'),
      alt: 'black shower head on white ceramic wall tiles',
    },
    {
      src: unsplash('1613849925496-e6d683c091f1'),
      alt: 'stainless steel faucet on white ceramic sink',
    },
    {
      src: unsplash('1595428774795-8e16f034a3d6'),
      alt: 'white plastic bottle on brown wooden table',
    },
    {
      src: unsplash('1613849925387-6e7f31f0cf40'),
      alt: 'stainless steel faucet on white ceramic sink',
    },
    {
      src: unsplash('1595515422949-def28c1b4fb3'),
      alt: 'white wooden cabinet on white ceramic tiles',
    },
    { src: unsplash('1595514535141-0b20e6615700'), alt: 'white wooden vanity sink with mirror' },
    { src: unsplash('1595515106886-43b1443a2e8b'), alt: 'white paper on brown wooden cabinet' },
    { src: unsplash('1595515423727-13790b001cb9'), alt: 'brown wooden wall mounted shelf' },
    { src: unsplash('1595515422510-7ece0438c07d'), alt: 'white wooden 2 drawer chest' },
    { src: unsplash('1595515106969-1ce29566ff1c'), alt: 'brown wooden cabinet with mirror' },
    {
      src: unsplash('1595515422824-a17acde1b915'),
      alt: 'brown woven basket on white ceramic sink',
    },
    { src: unsplash('1595514535711-c31bb982d8b3'), alt: 'brown wooden 2 layer drawer' },
    {
      src: unsplash('1595514535310-e4e66107c31d'),
      alt: 'white ceramic sink with stainless steel faucet',
    },
    { src: unsplash('1595428774185-e1ec02f38bdd'), alt: 'white wooden cabinet with mirror' },
    {
      src: unsplash('1595515422730-cc7684b670dc'),
      alt: 'white wooden kitchen cabinet with black and white ceramic mugs on top',
    },
    {
      src: unsplash('1595515770358-b0047714ccb9'),
      alt: 'white ceramic sink with stainless steel faucet',
    },
    {
      src: unsplash('1595515769499-0f61fc8db2e9'),
      alt: 'white wooden cabinet beside white ceramic sink',
    },
  ],
  vitrier: [
    {
      src: unsplash('1719050817004-c76eb7c75c99'),
      alt: 'A man kneeling down next to a metal door',
    },
    { src: unsplash('1737687304261-f81cdf392ca9'), alt: 'A close up of a broken cell phone' },
    {
      src: unsplash('1719744755528-797de46cbbff'),
      alt: 'An apple watch with a cracked glass case',
    },
    {
      src: unsplash('1731391777974-18f9adb69490'),
      alt: 'A broken cell phone laying on top of a table',
    },
    {
      src: unsplash('1724116956471-aeb33202c14c'),
      alt: 'A very tall building sitting in the middle of a parking lot',
    },
    {
      src: unsplash('1731391747600-4d0f478b2184'),
      alt: 'A person holding a cell phone in their hand',
    },
    {
      src: unsplash('1731391747629-fbcba9014453'),
      alt: 'A person holding a cell phone in their hand',
    },
    { src: unsplash('1719744755507-a4c856c57cf7'), alt: 'An apple watch with a cracked screen' },
    {
      src: unsplash('1768945411414-a22f27b43cb4'),
      alt: 'Close-up of a textured metallic surface with repeating patterns',
    },
    {
      src: unsplash('1761109223068-6858c79df795'),
      alt: 'Collection of antique doll heads in a glass display case',
    },
    {
      src: unsplash('1769367542930-8e73dff5760e'),
      alt: 'A single vacuum tube sits on a workbench.',
    },
    {
      src: unsplash('1772987714654-2df39af2c658'),
      alt: 'Various skincare bottles and jars arranged on a shelf.',
    },
    { src: unsplash('1753813698731-fc9593d27b54'), alt: 'Shattered glass reveals a bullet hole.' },
    {
      src: unsplash('1576481798929-866e7eb13236'),
      alt: 'a broken window with a blue fire hydrant behind it',
    },
    {
      src: unsplash('1763862730106-5bd865b80f5e'),
      alt: 'Close-up of shattered glass with blurred lights in background',
    },
    { src: unsplash('1646942462469-30267eb9155a'), alt: 'a close up of a broken glass window' },
    {
      src: unsplash('1771507092806-a3fdb881fd53'),
      alt: 'Close-up of shattered blue glass with intricate cracks',
    },
    {
      src: unsplash('1643461394487-7e2856b215b8'),
      alt: 'a broken glass window with a field in the background',
    },
    {
      src: unsplash('1726378244224-32a7263c1842'),
      alt: 'A broken windshield of a car with a blue sky in the background',
    },
    {
      src: unsplash('1711006777187-2c991e1b90b2'),
      alt: 'a pair of gloves on a table with a laptop',
    },
    { src: unsplash('1515833305013-e64177301e04'), alt: 'a close up of a broken glass window' },
    { src: unsplash('1733590634512-66186b83ad07'), alt: 'A close up of a broken glass window' },
    {
      src: unsplash('1711006695550-ec63b64ca68b'),
      alt: 'a pair of black gloves are being used on a machine',
    },
    { src: unsplash('1616401970421-d7533dbc1300'), alt: 'white and black abstract painting' },
    { src: unsplash('1675705985481-ed9c092111d2'), alt: 'a close up of a broken glass window' },
    { src: unsplash('1636709833113-18c93a976cf9'), alt: 'a close up of a piece of metal' },
    { src: unsplash('1648583169802-ea86bd9bf847'), alt: 'a close-up of a watch' },
    { src: unsplash('1592457060850-46b358e206cd'), alt: 'grayscale photo of broken glass' },
    { src: unsplash('1558284377-30ae5c450b73'), alt: 'vehicle running in road during daytime' },
    {
      src: unsplash('1753840704905-b4ffede3451e'),
      alt: 'Broken glass obscures a chair in the background.',
    },
    { src: unsplash('1585557475416-9895e6d03463'), alt: 'red brick building during daytime' },
    { src: unsplash('1571944066826-daa1ba4ac56f'), alt: 'a reflection of a building in a window' },
    {
      src: unsplash('1708179422865-1a70c15e22ac'),
      alt: "a close up of a building's windows with blue sky in the background",
    },
    { src: unsplash('1586489624550-8767500ea3ab'), alt: 'brown wooden framed glass window' },
    { src: unsplash('1735299803246-d4550dfff1ca'), alt: 'A view of a field through a window' },
    { src: unsplash('1632208605477-c621e7d15199'), alt: 'a glass door' },
    {
      src: unsplash('1641035856054-55ee7bf8b02a'),
      alt: 'a window with a bird sitting on the window sill',
    },
    {
      src: unsplash('1635269537614-a79a611a7ac8'),
      alt: 'a close up of a window with a house in the background',
    },
    {
      src: unsplash('1646186067431-7e7bfc1933b1'),
      alt: 'the reflection of a building through a window',
    },
    { src: unsplash('1751779097941-c0033f2c9700'), alt: 'A building reflected through a window.' },
    {
      src: unsplash('1758375760228-414df6b58f74'),
      alt: 'Open window in glass block wall overlooking landscape',
    },
    {
      src: unsplash('1760004362135-54f24a445521'),
      alt: 'Diamond-shaped panes of stained glass with greenery outside blur',
    },
    {
      src: unsplash('1764104456774-47b45bd6247a'),
      alt: 'View of trees through a dirty window pane',
    },
    {
      src: unsplash('1760958643209-428bc036497b'),
      alt: 'Green window frames reflect blurred trees and sky',
    },
    {
      src: unsplash('1684147297610-6a452a965efc'),
      alt: 'a window with a view of the sky and trees',
    },
    { src: unsplash('1564327481459-8bcd5561cf86'), alt: 'grey metal framed glass window closed' },
    { src: unsplash('1660101355073-8754a9e34ea1'), alt: 'a spider on a window' },
    { src: unsplash('1715361436754-778d730b611a'), alt: 'a building that has some windows in it' },
    {
      src: unsplash('1752868365727-ec1027c135e8'),
      alt: 'Old, teal-framed window reflecting a blurry garden.',
    },
    { src: unsplash('1675209431223-a2c5edd04207'), alt: 'a window with a view of a tree outside' },
    { src: unsplash('1514994792087-578fe80d0ff9'), alt: 'closeup photo of window' },
    { src: unsplash('1571055931136-ea24804a8dbf'), alt: 'white metal framed window' },
    {
      src: unsplash('1680450061035-cad084ebc840'),
      alt: 'a large glass window with a building in the background',
    },
    { src: unsplash('1571944256971-f5f4ea0185ba'), alt: 'blue and black wooden sliding door' },
    {
      src: unsplash('1678316746404-9b66a7cfeb40'),
      alt: 'a close up of a window with a camera in it',
    },
    { src: unsplash('1651269424052-e11edb68c2b1'), alt: 'a close-up of a building' },
    {
      src: unsplash('1678988060799-60bdc3ca71a6'),
      alt: 'a room with a table, chairs, and a large window',
    },
    {
      src: unsplash('1771732006724-66039bbaba94'),
      alt: 'View through a decorative window pane of greenery.',
    },
    { src: unsplash('1645479118614-a84a1033714e'), alt: 'a view of a building through a window' },
    { src: unsplash('1509834828289-fd7dd7732f0a'), alt: 'assorted trees collage' },
  ],
  facadier: [
    {
      src: unsplash('1699625809637-31c6f327ac96'),
      alt: 'a man in an orange vest is standing in front of a building with scaf',
    },
    {
      src: unsplash('1769698375376-2129740fa696'),
      alt: 'Building facade with scaffolding against blue sky.',
    },
    {
      src: unsplash('1771761466436-fbc49700d6a1'),
      alt: 'Ornate buildings with arched windows and balconies',
    },
    {
      src: unsplash('1770551832323-5b84c49db94e'),
      alt: 'Building undergoing structural reinforcement with metal beams.',
    },
    {
      src: unsplash('1763358991455-72486e02973f'),
      alt: 'Building dome covered in scaffolding under blue sky',
    },
    { src: unsplash('1529391099842-4dff97809ebb'), alt: 'gray high-rise building' },
    {
      src: unsplash('1771582115253-b77d3c71d500'),
      alt: 'Rough brick wall with a small glass block window.',
    },
    {
      src: unsplash('1764150482147-c030dcf896bd'),
      alt: 'Colorful buildings line a town square with a fountain.',
    },
    { src: unsplash('1697992350283-e865ae4d5bac'), alt: 'a sign on the side of a tall building' },
    { src: unsplash('1576239414703-a4449131fda3'), alt: 'grey and brown concrete building' },
    {
      src: unsplash('1772895249313-2fa762d8823e'),
      alt: 'Modern white building with large windows and stairs.',
    },
    {
      src: unsplash('1763888786556-4f8524c1cab2'),
      alt: 'Building awnings covered in plastic sheeting',
    },
    {
      src: unsplash('1762424361258-c1ecb32097d9'),
      alt: 'Row of old buildings under a cloudy sky.',
    },
    {
      src: unsplash('1775402286356-9ae425bacf92'),
      alt: 'Old building facade covered with green netting',
    },
    {
      src: unsplash('1689765246201-a864def979f7'),
      alt: 'a construction site in the middle of a city',
    },
    {
      src: unsplash('1772713555020-332d1456fa97'),
      alt: 'Building under construction covered in orange netting.',
    },
    {
      src: unsplash('1768055974458-beec40ee1468'),
      alt: 'Building under construction with scaffolding and netting',
    },
    {
      src: unsplash('1761209911159-93532a1a97ce'),
      alt: 'Ornate old building facade with weathered details.',
    },
    {
      src: unsplash('1755502778032-d570687240ab'),
      alt: 'Dilapidated brick building with weathered facade and peeling facade.',
    },
    {
      src: unsplash('1762255141967-877c2b657a1b'),
      alt: 'Building exterior at night with scaffolding and lights',
    },
    {
      src: unsplash('1740328430912-1d2dee9be186'),
      alt: "A tall building with scaffolding around it's windows",
    },
    {
      src: unsplash('1774979159518-7706ca7bb2e6'),
      alt: 'Modern buildings against a clear blue sky.',
    },
    {
      src: unsplash('1760029971559-ca345ea9afa6'),
      alt: 'Construction site with temporary wooden barrier and traffic cones.',
    },
    {
      src: unsplash('1751005329578-456d1d164b9b'),
      alt: 'Buildings stand side by side on the city street.',
    },
    {
      src: unsplash('1774450967576-a8d49ba77266'),
      alt: 'Old window on a weathered brick building facade',
    },
    {
      src: unsplash('1758862502366-92fd33c49ab7'),
      alt: 'Modern building exterior with orange accents and glass windows',
    },
    {
      src: unsplash('1773141161305-cb9275c16fe0'),
      alt: 'Building facade with construction materials in foreground',
    },
    {
      src: unsplash('1775264350735-04aa36707c5c'),
      alt: 'Modern white building with pink accents under blue sky.',
    },
    {
      src: unsplash('1772713898807-3cd906787625'),
      alt: 'Two apartment buildings with fire escapes and balconies.',
    },
    {
      src: unsplash('1696454596753-12d58cc1578a'),
      alt: 'a boat is parked in front of a large building',
    },
    {
      src: unsplash('1759304428406-43c0259251b1'),
      alt: 'Weathered turquoise door set in a crumbling brick wall.',
    },
    {
      src: unsplash('1766961980272-921bba4240bc'),
      alt: 'Construction workers plastering a wall on scaffolding.',
    },
    {
      src: unsplash('1768306609349-eb017c164de8'),
      alt: 'Stone building wall with bullet holes and window.',
    },
    {
      src: unsplash('1760073643328-88547b90611a'),
      alt: 'Rough textured wall with exposed bricks below',
    },
    { src: unsplash('1593629965858-5d36849553d5'), alt: 'black bicycle parked beside window' },
    { src: unsplash('1760544137535-4d99f5fa4d59'), alt: 'Close-up of a rough grey textured wall' },
    {
      src: unsplash('1768835276445-31e095d70685'),
      alt: 'A weathered wall with a wooden door and window',
    },
    {
      src: unsplash('1635015288805-39dfa1abf6b3'),
      alt: 'a white wall with a black and white clock on it',
    },
    {
      src: unsplash('1727200446200-c9ee44dc6bb2'),
      alt: 'A close up of a cement surface with small cracks',
    },
    {
      src: unsplash('1774707595382-44ac3717b276'),
      alt: 'Ornate street lamp attached to a building exterior.',
    },
    {
      src: unsplash('1770885514360-f42594da979e'),
      alt: 'Ornate building facade with arched windows and balcony',
    },
    {
      src: unsplash('1764526492968-88390b468732'),
      alt: 'An old weathered outdoor staircase with white railings.',
    },
    {
      src: unsplash('1762711753037-a217d33035e0'),
      alt: 'Textured gray and white striped wall surface',
    },
    {
      src: unsplash('1764789057049-ea39ddd976de'),
      alt: 'Green vines grow on a textured concrete wall',
    },
    {
      src: unsplash('1759460367756-f8afa49a107c'),
      alt: 'Old weathered building facade with green shutters.',
    },
    {
      src: unsplash('1767307804683-613fdf9813c0'),
      alt: 'A close-up of a round vent on a textured wall.',
    },
    { src: unsplash('1760544140407-097baf49bc53'), alt: 'Old weathered wall with a barred window' },
    { src: unsplash('1769025143021-c552f0e83a40'), alt: 'A textured green surface with shadows' },
    {
      src: unsplash('1774888828007-6b5d2e0d7723'),
      alt: 'Dilapidated building with broken windows and balconies',
    },
    {
      src: unsplash('1762901508726-7a8acf2e0e8a'),
      alt: 'Old building with weathered facade and windows',
    },
    {
      src: unsplash('1764075884334-59bb888ce0d0'),
      alt: 'Row of colorful doors along a building facade.',
    },
    { src: unsplash('1753893558279-8beaad18dd96'), alt: 'A house under construction is shown.' },
    {
      src: unsplash('1753717202565-ee088d9871fc'),
      alt: 'A house extension in progress with new windows.',
    },
    {
      src: unsplash('1700502335822-d4856cca490a'),
      alt: 'a man standing next to a building with a hammer',
    },
    {
      src: unsplash('1682331335443-5894690cd06e'),
      alt: 'a building with a green door and trees in the background',
    },
    {
      src: unsplash('1704747885838-e4f86841c589'),
      alt: 'a cat sitting in a window sill of a building',
    },
    {
      src: unsplash('1682937546456-fea3237ba8aa'),
      alt: 'a close up of a blue building with a brown door',
    },
    {
      src: unsplash('1711296274829-4eb7e91d46eb'),
      alt: 'a white building with a window and a white door',
    },
    { src: unsplash('1533219169605-36c958821509'), alt: 'white sash window' },
  ],
}
