/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 8 services, 474 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen4: Record<string, { src: string; alt: string }[]> = {
  plombier: [
    {
      src: unsplash('1771122453274-d3270e73cf94'),
      alt: 'Close-up of a tool bag with various items inside.',
    },
    { src: unsplash('1676210134190-3f2c0d5cf58d'), alt: 'a man fixing a water heater in a room' },
    { src: unsplash('1676210134188-4c05dd172f89'), alt: 'a man working on a pipe in a wall' },
    {
      src: unsplash('1632918572888-7a975f4b67b6'),
      alt: 'a couple of men working on a wooden structure',
    },
    {
      src: unsplash('1581356465504-d140ac8c68a3'),
      alt: 'man in black jacket and yellow knit cap holding black smartphone',
    },
    {
      src: unsplash('1593346784778-2ec2dacc0313'),
      alt: 'man in white t-shirt holding black metal tray',
    },
    {
      src: unsplash('1613839397604-65fffe7fc3d4'),
      alt: 'man in black and white plaid dress shirt wearing black helmet',
    },
    {
      src: unsplash('1615749721143-3a38368d3d05'),
      alt: 'man in white and black striped long sleeve shirt washing the sink',
    },
    {
      src: unsplash('1590762947451-ca27667fbb9b'),
      alt: 'man in blue t-shirt and blue denim jeans standing near white top mount refrigerator',
    },
    { src: unsplash('1669642550102-4715072f1c84'), alt: 'a person pouring water into a bowl' },
    {
      src: unsplash('1599220967693-ec27426f552f'),
      alt: 'boy in yellow and black hoodie sitting on brown wooden bench',
    },
    { src: unsplash('1664902131524-dd8bb87ad281'), alt: 'a boy swinging a baseball bat' },
    {
      src: unsplash('1589140617346-4695986f678e'),
      alt: 'man in black crew neck t-shirt holding white ceramic plate',
    },
    {
      src: unsplash('1747999703278-ef065c39cb18'),
      alt: 'A worker is using a grinder in the workshop.',
    },
    { src: unsplash('1662296416406-4ff3afef67fe'), alt: 'a person holding a pipe' },
    {
      src: unsplash('1620653713380-7a34b773fef8'),
      alt: 'person holding yellow and gray hand tool',
    },
    { src: unsplash('1652990550645-c1fc90691ed2'), alt: 'a man working on a piece of wood' },
    {
      src: unsplash('1674302669567-dce7196ac2d9'),
      alt: 'a person washing their hands in a kitchen sink',
    },
    {
      src: unsplash('1673870861507-d72aa6855d89'),
      alt: 'a man holding a wrench in front of a wall of tools',
    },
    { src: unsplash('1505798577917-a65157d3320a'), alt: 'man standing infront of miter saw' },
    {
      src: unsplash('1561480337-03eb1b6795a2'),
      alt: 'man in white and black striped polo shirt in front of monitor',
    },
    {
      src: unsplash('1706622710966-331f0d5127e5'),
      alt: 'a man is washing his hands in a copper faucet',
    },
    { src: unsplash('1606189933558-71f9b4747578'), alt: 'man in gray t-shirt using macbook pro' },
    { src: unsplash('1659353591742-9fa64d94738e'), alt: 'a person wearing a hard hat' },
    {
      src: unsplash('1610259998914-d1b9afe0dc55'),
      alt: 'man in white dress shirt holding yellow and black power tool',
    },
    { src: unsplash('1663082075624-a9f764d37fcd'), alt: 'a man standing in front of a store' },
    {
      src: unsplash('1742646802822-8ef506c19dd6'),
      alt: 'A person cooks in a busy restaurant kitchen.',
    },
    { src: unsplash('1665281872447-959671912829'), alt: 'a person wearing a hard hat' },
    { src: unsplash('1659353591753-dac60f2f7896'), alt: 'a man in a blue shirt' },
    { src: unsplash('1640239259272-6f26a9affb98'), alt: 'a man sitting on the floor in a room' },
    {
      src: unsplash('1676842987856-0a23454e0b6e'),
      alt: 'a man sitting on a chair holding a piece of wood',
    },
    {
      src: unsplash('1702406647675-108ee05b20b9'),
      alt: 'a man standing in front of a building holding a pair of scissors',
    },
    {
      src: unsplash('1733342797839-83a59e328324'),
      alt: 'A man riding a skateboard on top of a wooden table',
    },
    {
      src: unsplash('1581578404991-245ebf59c917'),
      alt: 'man in red t-shirt and blue denim jeans sitting on black and white ride on on on on on',
    },
    { src: unsplash('1571234297817-abcd66e5661b'), alt: 'man wearing gray and black stripe shirt' },
    { src: unsplash('1613903580946-6300f1f96b85'), alt: 'person holding red and black metal tool' },
    { src: unsplash('1526757253012-c191bca7cb82'), alt: 'man spraying flat at white board' },
    {
      src: unsplash('1659353588886-563224402488'),
      alt: 'a man wearing a hard hat and holding a gun',
    },
    { src: unsplash('1582340027067-fc75da5f2593'), alt: 'person in black pants sitting on couch' },
    {
      src: unsplash('1753358994418-5b7da1f6aacb'),
      alt: "A man peeks into a building's dark interior.",
    },
    { src: unsplash('1650731656997-a5cf403efcdd'), alt: 'a person pouring water into a bucket' },
    {
      src: unsplash('1736187903844-bfcf110b99dc'),
      alt: 'A man kneeling down next to a pile of tools',
    },
    {
      src: unsplash('1607109345497-3a9e88cf13bc'),
      alt: 'man in black t-shirt holding black smartphone',
    },
    {
      src: unsplash('1626436312908-bad0007396c0'),
      alt: 'person in blue denim jeans and black shoes lying on white and blue floor tiles',
    },
    {
      src: unsplash('1595393245502-65eb5bc297f2'),
      alt: 'man in green t-shirt and blue denim jeans sitting on green bench',
    },
    {
      src: unsplash('1659353586026-05bb2cacdafd'),
      alt: 'a person wearing a hard hat and safety gear',
    },
    { src: unsplash('1538167007176-db721696a7d5'), alt: 'man standing near refrigerator' },
    { src: unsplash('1652778549583-ba1ff4f1e03d'), alt: 'a man sitting on a bucket in a room' },
    {
      src: unsplash('1593583810872-ddee4d6bd55a'),
      alt: 'man in blue denim jeans and brown jacket climbing on brown wooden ladder during daytime',
    },
    {
      src: unsplash('1696371704943-f2d67ba16b3f'),
      alt: 'a man in an orange shirt holding a baseball glove',
    },
    {
      src: unsplash('1569215736395-c72875f5679e'),
      alt: 'grayscale photography of water pouring from a pipe',
    },
    {
      src: unsplash('1582441814869-a262426017f9'),
      alt: 'man in gray dress shirt and blue denim jeans sitting on brown wooden floor',
    },
    { src: unsplash('1659353586823-ebf7a06b5b5c'), alt: 'a person holding a drill' },
    { src: unsplash('1685186112493-564c68f75d57'), alt: 'a man is putting something in a cooler' },
    { src: unsplash('1652250406996-cf8dc8197981'), alt: 'a man holding a large metal pipe' },
    {
      src: unsplash('1595856898575-9d187bd32fd6'),
      alt: 'man in red and black jacket wearing black pants and red helmet holding green and black',
    },
    {
      src: unsplash('1611866680964-9bd76dbebb29'),
      alt: 'person in black long sleeve shirt holding stainless steel faucet',
    },
    { src: unsplash('1733117440439-7c63b06f3ddf'), alt: 'A man digging a hole with a shovel' },
    {
      src: unsplash('1649835580664-e16c48a4ae3c'),
      alt: 'a man taking a picture of himself with his cell phone',
    },
    { src: unsplash('1611021061421-93741ec41ce1'), alt: 'person holding silver and orange pipe' },
  ],
  electricien: [
    {
      src: unsplash('1748171159071-d27f80d6774b'),
      alt: 'Power lines stretch across a hazy, sunset landscape.',
    },
    { src: unsplash('1754620906571-9ba64bd3ffb4'), alt: 'Worker installs wires on a roof.' },
    {
      src: unsplash('1747666095272-e53fc1593e2a'),
      alt: 'Modern speakers with glowing blue light.',
    },
    { src: unsplash('1667922578520-61558e79aa7e'), alt: 'a person wearing a black and white shoe' },
    {
      src: unsplash('1754620906703-496ec2451744'),
      alt: 'Worker installs electrical components on a roof.',
    },
    {
      src: unsplash('1759542877886-39d81e8f2eee'),
      alt: 'Linemen working on a utility pole with bucket truck.',
    },
    { src: unsplash('1646640381839-02748ae8ddf0'), alt: 'a man with a driller and a hat on' },
    { src: unsplash('1583954964358-1bd7215b6f7a'), alt: 'black cordless microphone on table' },
    {
      src: unsplash('1682345262055-8f95f3c513ea'),
      alt: 'a person holding a pair of wires in their hands',
    },
    {
      src: unsplash('1641996522656-a37938a1e665'),
      alt: 'a black and white photo of a person holding a cell phone',
    },
    {
      src: unsplash('1751486289947-4f5f5961b3aa'),
      alt: 'Electrical outlet disassembled, revealing the wiring.',
    },
    {
      src: unsplash('1617571607645-dd7dd3bf7f6b'),
      alt: 'black and yellow helmet on white concrete floor',
    },
    { src: unsplash('1660330590022-9f4ff56b63f6'), alt: 'a man using a machine' },
    {
      src: unsplash('1732660513320-a6b489f3fece'),
      alt: 'A man in a yellow jacket working on a computer',
    },
    { src: unsplash('1660330589827-da8ab7dd3c02'), alt: 'a man using a machine' },
    {
      src: unsplash('1732660780054-0cf9fadb9d30'),
      alt: 'A man in a yellow jacket pointing at something',
    },
    {
      src: unsplash('1621905251918-48416bd8575a'),
      alt: 'man in brown and white plaid dress shirt and yellow hard hat holding black and orange',
    },
    {
      src: unsplash('1660330589693-99889d60181e'),
      alt: 'a man wearing a hat and holding a green object',
    },
    { src: unsplash('1660330589487-39cc0177ba89'), alt: 'a person in a yellow jacket' },
    {
      src: unsplash('1758101755915-462eddc23f57'),
      alt: 'Electrician testing electrical panel with multimeter.',
    },
    {
      src: unsplash('1583586008354-bd5829259d7f'),
      alt: 'white and black round wall mounted decor',
    },
    {
      src: unsplash('1621905251189-08b45d6a269e'),
      alt: 'man in brown hat holding black and gray power tool',
    },
    {
      src: unsplash('1769788161278-8dc624a2d537'),
      alt: 'Man cleaning windows on a high-rise building',
    },
    {
      src: unsplash('1627207278573-58ecc196e08e'),
      alt: 'man in black jacket and black pants wearing black helmet on brown electric post during daytime',
    },
    { src: unsplash('1640238489583-dc6c0478f88e'), alt: 'a person is sitting on a power line' },
    {
      src: unsplash('1747110594869-789610507597'),
      alt: 'An electrician works on power lines from a lift.',
    },
    { src: unsplash('1608574839637-2f7d0290d01d'), alt: 'white wooden shelf with books' },
    { src: unsplash('1713937400833-f817938b51e4'), alt: 'a man working on an electrical pole' },
    { src: unsplash('1640238489600-9c8e01f76a94'), alt: 'a person is standing on a power line' },
    {
      src: unsplash('1595830807118-aef995773265'),
      alt: 'man in black and white long sleeve shirt wearing orange helmet',
    },
    { src: unsplash('1659353589241-f450b33f908a'), alt: 'a couple of men wearing hard hats' },
    {
      src: unsplash('1635335874521-7987db781153'),
      alt: 'a bunch of wires are plugged into a switch box',
    },
    { src: unsplash('1553873002-785d775854c9'), alt: 'black and yellow clamp meter' },
    {
      src: unsplash('1585531454154-c8ad0a6af12b'),
      alt: 'man in blue jacket and orange helmet climbing on brown wooden ladder during daytime',
    },
    { src: unsplash('1577542630455-5179ef3bcf8a'), alt: 'white wire on calendar on wall' },
    { src: unsplash('1543333101-840e043d2a7d'), alt: 'group of people fixing the wires on post' },
    {
      src: unsplash('1595831708961-1b13c0dd2422'),
      alt: 'man in blue orange and white jacket wearing red helmet',
    },
    {
      src: unsplash('1641194298727-fa6e5401bf1b'),
      alt: 'a group of men standing on top of a power line',
    },
    { src: unsplash('1562034037-ba96b6312a80'), alt: 'circuit breaker panel' },
    { src: unsplash('1659353588926-5a52f64e6389'), alt: 'a person wearing a hard hat' },
    { src: unsplash('1596480330945-12a5380b9c59'), alt: 'white and black electric wires' },
    { src: unsplash('1607631697491-61972eecf928'), alt: 'black and gray audio mixer' },
    { src: unsplash('1659353588580-8da374e328a1'), alt: 'a man holding a knife' },
    {
      src: unsplash('1659353586855-83f3bbb6bd90'),
      alt: 'a man wearing a hard hat and holding a pipe',
    },
    { src: unsplash('1588616437819-7d30e6f76e66'), alt: 'white and black audio mixer' },
    {
      src: unsplash('1610259998914-d1b9afe0dc55'),
      alt: 'man in white dress shirt holding yellow and black power tool',
    },
    {
      src: unsplash('1597502310092-31cdaa35b46d'),
      alt: 'man in red and black jacket wearing orange helmet',
    },
    { src: unsplash('1482731215275-a1f151646268'), alt: 'man on white ladder' },
    { src: unsplash('1640236888464-6791ed216dec'), alt: 'a man is working on a power line' },
    { src: unsplash('1576446468729-7674e99608f5'), alt: 'white circuit breakers' },
    {
      src: unsplash('1608109704808-62aadbc33a7d'),
      alt: 'man in red shirt and blue denim jeans standing on white wooden door',
    },
    {
      src: unsplash('1661745797378-7b204b476303'),
      alt: "Mechanic's hands repairing a carburetor with a screwdriver.",
    },
    {
      src: unsplash('1745169921021-3304a3eed8ed'),
      alt: 'Phones are charging on an electrical outlet.',
    },
    {
      src: unsplash('1509390373685-579356742d95'),
      alt: 'man standing on bucket beside gray current post at daytime',
    },
    { src: unsplash('1687819280272-95f9d2a3cdab'), alt: 'a man fixing a light switch on a wall' },
    { src: unsplash('1670388119209-040556de1319'), alt: 'a building with a green railing' },
    {
      src: unsplash('1767514536570-83d70c024247'),
      alt: 'Electrical wires connected with yellow terminal blocks.',
    },
    { src: unsplash('1576446470246-499c738d1c8e'), alt: 'white circuit breakers' },
    {
      src: unsplash('1574420219493-3763be83ab66'),
      alt: 'grayscale photo of person climbing electric post',
    },
    {
      src: unsplash('1555963966-b7ae5404b6ed'),
      alt: 'shallow focus photo of man fixing steel cable',
    },
  ],
  serrurier: [
    { src: unsplash('1564767609213-c75ee685263a'), alt: 'person holds door lever' },
    { src: unsplash('1564767609342-620cb19b2357'), alt: 'keys on hand' },
    { src: unsplash('1564767609424-270b9df918e1'), alt: 'clock at 4:05' },
    { src: unsplash('1707296916219-4f2d7529a4c5'), alt: 'a man opening the door of a black suv' },
    {
      src: unsplash('1707296916330-ae32416d9260'),
      alt: 'a person holding a remote control next to a van',
    },
    {
      src: unsplash('1707296916319-037ad32dc7f6'),
      alt: 'a person holding a car key in front of a white car',
    },
    { src: unsplash('1554863885-e3a33dd1bc82'), alt: 'padlock on grey metal hinge' },
    {
      src: unsplash('1707296916248-2fd3834fe3c4'),
      alt: 'a person holding two remotes in front of a truck',
    },
    {
      src: unsplash('1707296916498-7f93df6caff3'),
      alt: 'a person holding a car key in front of a van',
    },
    {
      src: unsplash('1707296916209-dd08c58d7117'),
      alt: 'a person holding a car keys in front of a red car',
    },
    { src: unsplash('1551292666-5b16a97101a8'), alt: 'man wearing brown high-top sneakers' },
    { src: unsplash('1550773231-59c9530140fd'), alt: 'man wearing red crew-neck shirt' },
    {
      src: unsplash('1770529934201-a6488ad7e395'),
      alt: 'A collection of keys hanging below a weathered "service" sign.',
    },
    {
      src: unsplash('1693468028442-33f240f13ce0'),
      alt: 'a close up of a metal object with a hole in it',
    },
    {
      src: unsplash('1758351507272-aa6929fe997e'),
      alt: 'A pile of old, rusty keys with intricate designs.',
    },
    {
      src: unsplash('1770386291952-e1347d13d947'),
      alt: 'Small shop selling various goods on a street',
    },
    { src: unsplash('1768201493344-766b6f04bb46'), alt: 'A psychic and key shop at night' },
    {
      src: unsplash('1516643622707-2052983d5f08'),
      alt: 'shallow focus photography of stainless steel padlock',
    },
    {
      src: unsplash('1629470937863-dfcbda177a46'),
      alt: 'a close up of an old fashioned typewriter',
    },
    {
      src: unsplash('1754414266760-f21ba503ce9f'),
      alt: 'A combination lock sits amongst organic debris.',
    },
    { src: unsplash('1579382311054-0701b08da226'), alt: 'person holding black steel door knob' },
    {
      src: unsplash('1646198852622-6e84475db438'),
      alt: 'a pile of metal objects sitting on top of each other',
    },
    { src: unsplash('1721273043814-883533ae708e'), alt: 'A couple of locks that are on a fence' },
    {
      src: unsplash('1709572374648-cd00913a3a6e'),
      alt: 'a bunch of padlocks that are attached to a wall',
    },
    {
      src: unsplash('1759452003649-552896c8ed63'),
      alt: 'A key is inserted into a lock mechanism.',
    },
    {
      src: unsplash('1688986550777-26427d87a1a3'),
      alt: 'a combination combination lock attached to a fence',
    },
    {
      src: unsplash('1765623821842-326f0aab531a'),
      alt: 'Close-up of a rusty old padlock attached to a chain.',
    },
    { src: unsplash('1577745983534-51f8ed677c10'), alt: 'gray metal grill gate' },
    {
      src: unsplash('1770219792093-85830ce757b7'),
      alt: 'Close-up of a metal screw with concentric circles',
    },
    { src: unsplash('1763370356214-e4dd692f8697'), alt: 'Old padlock securing a wooden door' },
    { src: unsplash('1592744254966-58c65cfd2e69'), alt: 'silver and black combination lock' },
    { src: unsplash('1714523863598-6d3523c3e112'), alt: 'a bunch of locks that are on a fence' },
    {
      src: unsplash('1766756744612-a3dbf11b5748'),
      alt: 'Close-up of many metal love locks attached together.',
    },
    { src: unsplash('1561756719-55231c95c511'), alt: 'brown padlock' },
    {
      src: unsplash('1700082820245-3bcca781106f'),
      alt: 'a close up of a bench with a padlock on it',
    },
    { src: unsplash('1577052587586-46ebc4e2782a'), alt: 'brown padlock' },
    {
      src: unsplash('1653264360521-d6406bd5a0f5'),
      alt: 'a padlock on a door with a tree in the background',
    },
    { src: unsplash('1602847192466-7b4b641cd986'), alt: 'grayscale photo of audio mixer' },
    { src: unsplash('1609160636043-584262aacc35'), alt: 'grayscale photo of padlock on wire' },
    { src: unsplash('1773425350177-af4d2249d641'), alt: 'Keys and a padlock near a blue toolbox' },
    {
      src: unsplash('1690142881852-192bbe7f27c0'),
      alt: 'a lock on a wooden door with a white wall in the background',
    },
    { src: unsplash('1629551742746-ca9135536077'), alt: 'brass padlock on green metal gate' },
    { src: unsplash('1568262299371-2b42a7ffb1f8'), alt: 'two brass-colored padlocks' },
    { src: unsplash('1655562693681-ee2a0a81db88'), alt: 'a group of metal objects' },
    { src: unsplash('1763370356082-124761e8c989'), alt: 'A padlock secures an old wooden door' },
    {
      src: unsplash('1765568183720-a8a5e50b6086'),
      alt: 'A silver padlock attached to a grey surface.',
    },
    { src: unsplash('1622525522886-fb4563a88019'), alt: 'brown and black padlock lot' },
    { src: unsplash('1484814915025-858e00100866'), alt: 'brown padlock' },
    { src: unsplash('1539438892292-ca450415b2a6'), alt: 'gate with padlock' },
    {
      src: unsplash('1721036265017-0f1494a20111'),
      alt: 'A padlock attached to a door with the word master written on it',
    },
    { src: unsplash('1645047573426-8d013c071193'), alt: 'an old padlock on a wooden door' },
    {
      src: unsplash('1691180067510-b2df0f36cabd'),
      alt: 'a black and white photo of a hair dryer laying on the ground',
    },
    { src: unsplash('1658901742270-2e4137fa15a6'), alt: 'a close-up of a toy' },
    { src: unsplash('1744329630282-ace56b873b79'), alt: "A padlock secures a door's bolt." },
    { src: unsplash('1698358530992-fa61968e0b15'), alt: 'a close up of a padlock on a door' },
    { src: unsplash('1662712474857-b2a4786af4fd'), alt: 'a key on a key chain' },
    {
      src: unsplash('1710849273281-c1f6618cf695'),
      alt: 'a rusted metal padlock with a horse on it',
    },
    { src: unsplash('1614064745560-e556fef374b0'), alt: 'two pink padlock on pink surface' },
    {
      src: unsplash('1736331998013-e6039e1e2378'),
      alt: 'A row of lockers with numbers and locks on them',
    },
    {
      src: unsplash('1749016750775-7b7be1c12b3a'),
      alt: 'Keys and calendars are displayed in a cluttered store.',
    },
  ],
  chauffagiste: [
    {
      src: unsplash('1772974776381-68f1f5fef1aa'),
      alt: 'Close-up of white stove knobs and settings.',
    },
    {
      src: unsplash('1770656506117-2372e446b6fa'),
      alt: 'Mechanic uses screwdriver to fix car engine part.',
    },
    {
      src: unsplash('1762329406444-57bb1f811012'),
      alt: 'Row of red illuminated buttons on a vintage device.',
    },
    {
      src: unsplash('1639866496281-573747d7051f'),
      alt: 'a group of people standing in front of a green and red flame',
    },
    { src: unsplash('1741022426163-d8b2c1c1d33a'), alt: 'A radiator and wires on a white wall' },
    {
      src: unsplash('1762329858510-46aec8fa54b5'),
      alt: 'Close-up of vintage audio equipment sliders',
    },
    {
      src: unsplash('1599028274511-e02a767949a3'),
      alt: 'white radiator heater beside brown wooden window',
    },
    { src: unsplash('1587725950196-6ef36e3b474e'), alt: 'silver round coin on white plastic case' },
    {
      src: unsplash('1751486289950-5c4898a4c773'),
      alt: 'Pipes and equipment are installed on a wall.',
    },
    {
      src: unsplash('1620653713380-7a34b773fef8'),
      alt: 'person holding yellow and gray hand tool',
    },
    {
      src: unsplash('1600951550501-5672f3f535a1'),
      alt: 'white radiator heater beside black leather chair',
    },
    {
      src: unsplash('1762329859074-6bb1d22f3ed6'),
      alt: 'Hand inserting old audio cassette into player',
    },
    { src: unsplash('1608179675969-6cef76642777'), alt: 'a radiator with a sign attached to it' },
    {
      src: unsplash('1762329858861-ea1b940fbb0e'),
      alt: 'Hand inserts red-lit component into device.',
    },
    {
      src: unsplash('1732660513320-a6b489f3fece'),
      alt: 'A man in a yellow jacket working on a computer',
    },
    { src: unsplash('1578151340477-8fe6208a9a92'), alt: 'five white pipes with hose clamps' },
    { src: unsplash('1507647185148-e27abccb6be5'), alt: 'close-up photo of metal tools' },
    { src: unsplash('1667264921635-0fdd6bab6174'), alt: 'a close-up of a machine' },
    { src: unsplash('1605359848061-682b4cae1e7a'), alt: 'purple and blue light digital wallpaper' },
    {
      src: unsplash('1594100618242-737edc8c517e'),
      alt: 'white radiator heater mounted on white wall',
    },
    {
      src: unsplash('1762329858728-b52427f818ab'),
      alt: 'Hand pressing red buttons on a vintage device.',
    },
    {
      src: unsplash('1770656505709-fd97236989b9'),
      alt: 'Mechanic working on car engine with tools',
    },
    {
      src: unsplash('1575088492380-ce4b12ef83ff'),
      alt: 'a mirror reflecting a room with wooden walls',
    },
    {
      src: unsplash('1748904005697-917f8307f3f2'),
      alt: 'Glowing oven heating elements are visible.',
    },
    { src: unsplash('1637296001293-9b5ed34740f9'), alt: 'a couple of gauges that are on a wall' },
    {
      src: unsplash('1650551182991-b07558247564'),
      alt: 'pipes and valves in a room with orange table',
    },
    {
      src: unsplash('1770656506122-99bc73ac9d66'),
      alt: 'Mechanic using a screwdriver on car engine parts.',
    },
    {
      src: unsplash('1711037694138-8df293d7ec28'),
      alt: 'a radiator in front of a window with a view of a parking lot',
    },
    {
      src: unsplash('1711571603482-12a23d3d1e43'),
      alt: 'a close up of many different types of wires',
    },
    { src: unsplash('1630993892916-c3a6542761a4'), alt: 'white and black concrete building' },
    { src: unsplash('1601914697928-0b536e76d048'), alt: 'white and black water heater' },
    {
      src: unsplash('1644143923004-9c8ac1f4c41a'),
      alt: 'a broken television sitting on top of snow covered ground',
    },
    {
      src: unsplash('1642229407351-7473e9482a94'),
      alt: 'a close up of a hard drive being removed from a computer',
    },
    {
      src: unsplash('1507337272725-eec743fbdc31'),
      alt: 'gray pipes mounted on concrete wall arrangement',
    },
    { src: unsplash('1669725341213-7379ff6c90d5'), alt: 'a white radiator in a room' },
    { src: unsplash('1542041424505-01527297cc72'), alt: 'red and grey knob' },
    { src: unsplash('1676840642827-4941f48ccddd'), alt: 'a black and white photo of a radiator' },
    { src: unsplash('1656652173501-9739078f0f4e'), alt: 'a white handheld game console' },
    {
      src: unsplash('1680012185807-4dd0afcacfbc'),
      alt: 'a close up of a rusty pipe with a hat on it',
    },
    {
      src: unsplash('1702241271926-4f752a29cb4f'),
      alt: 'a close up of a heater with a yellow light',
    },
    { src: unsplash('1599341540086-73f511694cba'), alt: 'gray and white electric heater' },
    {
      src: unsplash('1681301968402-5e3c8b8feba8'),
      alt: 'a close up of an old fashioned typewriter',
    },
    {
      src: unsplash('1767509274903-454b426b771e'),
      alt: 'Close-up of glowing hot filaments in a light bulb.',
    },
    { src: unsplash('1599028274529-31020a1fc1f7'), alt: 'white and black space heater' },
    { src: unsplash('1737292273837-854222bd200c'), alt: 'A close up of a machine with pipes' },
    { src: unsplash('1613500625241-aaf1a1cc6a52'), alt: 'brown and white cardboard box' },
    { src: unsplash('1618840626133-54463084a141'), alt: 'grayscale photo of metal pipe' },
    {
      src: unsplash('1774876549246-dfa8eae5d9f5'),
      alt: 'Finger pressing button on digital thermostat display.',
    },
    {
      src: unsplash('1764677367365-d56787922d83'),
      alt: 'A pot sits on a gas stove burner with flames.',
    },
    {
      src: unsplash('1737012197886-7d5a52ded45b'),
      alt: 'A person is working on a ceiling air conditioner',
    },
    { src: unsplash('1545259741-2ea3ebf61fa3'), alt: 'gray Nest thermostat displaying at 63' },
    { src: unsplash('1561513990-b76479fb0433'), alt: 'light bulb turned on' },
    {
      src: unsplash('1703041555997-f51216e6a532'),
      alt: 'a close up of a pressure gauge attached to a pipe',
    },
    { src: unsplash('1600876876700-ba4c72ae3517'), alt: 'orange and white analog gauge' },
    {
      src: unsplash('1580584162057-a1c7f739e2c1'),
      alt: 'brown wooden train rail during night time',
    },
    {
      src: unsplash('1707898310285-f475ef2c92be'),
      alt: 'a close up of a white radiator in a room',
    },
    { src: unsplash('1633596879450-e98a1a4d0c80'), alt: 'a close up of a heater in the dark' },
    {
      src: unsplash('1674471361523-195aa08e69b5'),
      alt: 'a close up of a pressure gauge on a machine',
    },
    {
      src: unsplash('1765850262030-1ae93e474473'),
      alt: 'Industrial ceiling with ventilation and lighting',
    },
    {
      src: unsplash('1676210132787-7ed33de174d6'),
      alt: 'a man in red gloves working on a machine',
    },
  ],
  'peintre-en-batiment': [
    { src: unsplash('1574359411659-15573a27fd0c'), alt: 'two men in ladder on wall' },
    {
      src: unsplash('1679939153545-95201a01fe5d'),
      alt: 'a bedroom with a bed, dresser and mirror',
    },
    {
      src: unsplash('1595814432314-90095f342694'),
      alt: 'woman in gray tank top and blue denim jeans sitting on bed',
    },
    { src: unsplash('1614194076674-0598e6dd5703'), alt: 'red and blue mermaid tail illustration' },
    {
      src: unsplash('1484154218962-a197022b5858'),
      alt: 'gray steel 3-door refrigerator near modular kitchen',
    },
    { src: unsplash('1505691938895-1758d7feb511'), alt: 'couch near painting' },
    { src: unsplash('1595814433015-e6f5ce69614e'), alt: '2 person wearing blue denim jeans' },
    {
      src: unsplash('1624352908259-ec0b31e421ee'),
      alt: 'man in black jacket standing beside brown wooden house during daytime',
    },
    {
      src: unsplash('1621870536986-151d03e2e99a'),
      alt: 'woman in black and white dress standing beside yellow wall with green plants',
    },
    {
      src: unsplash('1666179861891-db5155e290c3'),
      alt: 'a living room with a couch and a painting on the wall',
    },
    {
      src: unsplash('1672172230193-42893a5b2f68'),
      alt: 'a building with a sign on the side of it',
    },
    {
      src: unsplash('1605624817038-a0dd51aa82f9'),
      alt: 'brown wooden window on white concrete wall',
    },
    {
      src: unsplash('1605200344106-51b71afd3862'),
      alt: 'red and white marlboro cigarette pack on gray concrete pavement',
    },
    { src: unsplash('1669016950126-3f11b53e2b0d'), alt: 'a person painting on a table' },
    { src: unsplash('1453286465977-2de00962433b'), alt: 'brown concrete house under gray clouds' },
    { src: unsplash('1662796246357-36ffa59acbca'), alt: 'a group of brushes sit in a glass cup' },
    {
      src: unsplash('1742673506667-23361056407c'),
      alt: 'Farm buildings in a field under a colorful sky',
    },
    {
      src: unsplash('1743295691052-d13493dd454e'),
      alt: 'An interior room with bright sunlight through a window.',
    },
    { src: unsplash('1578927072306-be447c77ad29'), alt: 'brown cow on brown field' },
    {
      src: unsplash('1731329356198-187d98d12944'),
      alt: 'Abstract painting of a surreal, cluttered outdoor space',
    },
    { src: unsplash('1711319551974-aae40db224cd'), alt: 'a painting of a house on a lake' },
    {
      src: unsplash('1742649045622-a8aebd88e7eb'),
      alt: 'Adobe building with snow-capped mountains in background',
    },
    { src: unsplash('1562341517-2e59e50ada0e'), alt: 'white, beige, and pink building near trees' },
    { src: unsplash('1731329812779-f2de99278a3d'), alt: 'Farmyard scene with carts and buildings' },
    { src: unsplash('1676483752612-69cd502fd103'), alt: 'a window in a wall with a tree in it' },
    {
      src: unsplash('1762119594563-fc90dabb6161'),
      alt: 'A charming house covered in blooming pink flowers.',
    },
    {
      src: unsplash('1654467978514-22fd61143eb6'),
      alt: 'a chandelier hanging from the ceiling of a building',
    },
    {
      src: unsplash('1748721786735-157382144baa'),
      alt: 'White houses on a rocky hillside under blue sky',
    },
    {
      src: unsplash('1698941744413-a0b70c234400'),
      alt: 'a painting of a woman standing in front of a building',
    },
    { src: unsplash('1602581848778-3f76d6378e60'), alt: 'blue white and black abstract painting' },
    {
      src: unsplash('1579169233120-8acbdeef5de8'),
      alt: 'brown wooden house on green grass field under white clouds during daytime',
    },
    { src: unsplash('1650802605379-2d769596f492'), alt: 'a mural on a building' },
    { src: unsplash('1656168203484-e5e09e9f3510'), alt: 'logo' },
    { src: unsplash('1650530651450-af2b8010ddde'), alt: 'a mural on the side of a building' },
    { src: unsplash('1519068554083-0fb38e848f59'), alt: 'gray wooden window frame' },
    {
      src: unsplash('1709149469995-1fe94d53bac6'),
      alt: 'a painting of a town with a river running through it',
    },
    {
      src: unsplash('1642369259805-8b2d772512fe'),
      alt: 'a building with a painting on the side of it',
    },
    { src: unsplash('1759406066673-f76869a4e6db'), alt: 'Man painting the side of a brick house' },
    {
      src: unsplash('1740518904908-46cd6e7356b4'),
      alt: 'Pale yellow building with a wooden fence',
    },
    {
      src: unsplash('1745245423302-99701e3d6436'),
      alt: 'A grand estate with classical architecture and manicured gardens.',
    },
    { src: unsplash('1560878246-4ac020d03668'), alt: 'gold chandelier in painted wall room' },
    { src: unsplash('1612900870552-0312616bac06'), alt: 'white and orange box on gray surface' },
    {
      src: unsplash('1717702920072-d06a3518ed43'),
      alt: 'a painting of a house with a lake in the background',
    },
    {
      src: unsplash('1745761500085-e5e34684034f'),
      alt: 'A large yellow manor house surrounded by trees.',
    },
    { src: unsplash('1581539687231-fef259c4fa7a'), alt: 'green trees near body of water painting' },
    { src: unsplash('1574960170223-18161fee623b'), alt: 'white concrete house near body of water' },
    { src: unsplash('1577975142952-221c53e51a10'), alt: 'empty bed' },
    {
      src: unsplash('1757585756019-72284f0c8af4'),
      alt: 'Wooden pier with blue canopy over turquoise water',
    },
    { src: unsplash('1705604089620-e496cd1b0d87'), alt: 'a painting of a large group of people' },
    {
      src: unsplash('1624381025021-9831f75d625d'),
      alt: 'white and brown concrete building under white sky during daytime',
    },
    {
      src: unsplash('1731329354811-c8736cf4dba7'),
      alt: 'Abstract landscape with houses and trees in a moody atmosphere',
    },
    {
      src: unsplash('1752314495168-0c176ddab3aa'),
      alt: 'Watercolor sketch of an old european building with ornate details',
    },
    { src: unsplash('1704381880661-f24911e60c7a'), alt: 'a drawing of a house with a red roof' },
    {
      src: unsplash('1618259369179-27360c837a5d'),
      alt: 'blue and white commuter bike parked beside brown wooden house during daytime',
    },
    {
      src: unsplash('1605214104310-e8eeaf317e8c'),
      alt: 'blue bicycle parked beside blue and yellow floral wall',
    },
    {
      src: unsplash('1582289545106-efecf907f21e'),
      alt: 'white and black table with chairs near body of water painting',
    },
    { src: unsplash('1651901207423-738b618c9a90'), alt: 'a building with a mural on the side' },
    {
      src: unsplash('1723134970264-91f88a5a7d4a'),
      alt: 'A building with a mural on the side of it',
    },
    {
      src: unsplash('1704394516937-306c24209cfe'),
      alt: 'a drawing of a house with trees in the background',
    },
    {
      src: unsplash('1645730065116-888355870cf7'),
      alt: 'a goat standing in front of a yellow building',
    },
  ],
  menuisier: [
    { src: unsplash('1683115099191-51e617fc5ff1'), alt: 'a bunch of tools are hanging on a wall' },
    {
      src: unsplash('1683115097386-3a32cb5e3ce0'),
      alt: 'a man using a drill gun on a piece of wood',
    },
    {
      src: unsplash('1683115098652-db9813ecf284'),
      alt: 'a person using a power drill on a piece of wood',
    },
    { src: unsplash('1683115098516-9b8d5c643b5b'), alt: 'a bunch of tools are hanging on a wall' },
    { src: unsplash('1683115096447-5d01c11d3ead'), alt: 'a man working on a piece of wood' },
    { src: unsplash('1683115099414-c83156978045'), alt: 'a bunch of tools are hanging on a wall' },
    {
      src: unsplash('1683115099860-5379ac101bce'),
      alt: 'a man using a circular saw to cut a piece of wood',
    },
    { src: unsplash('1683115099413-5b7d85c2950c'), alt: 'a wooden wall with tools hanging on it' },
    {
      src: unsplash('1683115099260-5d5ae7e71a09'),
      alt: 'a person using a circular saw to cut a piece of wood',
    },
    {
      src: unsplash('1683115099089-363badefcc25'),
      alt: 'a man using a circular saw to cut a piece of wood',
    },
    {
      src: unsplash('1683115100395-645ae5775278'),
      alt: 'a man using a table saw to cut a piece of wood',
    },
    { src: unsplash('1683115100747-ee545c0fbdfd'), alt: 'a machine that is sitting on a table' },
    { src: unsplash('1683115099119-1af60e697f9a'), alt: 'a bunch of tools are hanging on a wall' },
    {
      src: unsplash('1683115094879-40096f84cc6a'),
      alt: 'a bottle of glue sitting on top of a wooden table',
    },
    { src: unsplash('1683115097279-415af7be0209'), alt: 'a bunch of tools hanging on a wall' },
    { src: unsplash('1683115099811-13b4c9e0f925'), alt: 'a bunch of tools hanging on a wall' },
    {
      src: unsplash('1683115099247-7e33663f91cc'),
      alt: 'a couple of drillers are hanging on a wall',
    },
    {
      src: unsplash('1728362369426-1647a7fd09d7'),
      alt: 'A close up of a bunch of knives on a table',
    },
    { src: unsplash('1552836514-bbf70221e437'), alt: 'grayscale photography of room with shelves' },
    { src: unsplash('1586064957227-11d763b135a1'), alt: 'brown wooden handle on brown wooden box' },
    {
      src: unsplash('1683115100702-af818681184d'),
      alt: 'a wooden frame with a bottle of glue on top of it',
    },
    { src: unsplash('1683115098695-229f4009390b'), alt: 'a man standing next to a wooden rail' },
    {
      src: unsplash('1683115099723-d07f9f56fd91'),
      alt: 'a man using a circular saw to cut a piece of wood',
    },
    {
      src: unsplash('1683115100623-5e872a9d533a'),
      alt: 'a man using a power drill on a piece of wood',
    },
    { src: unsplash('1683115097173-f24516d000c6'), alt: 'a bunch of tools are hanging on a wall' },
    {
      src: unsplash('1683115097492-3a3bd12cad3f'),
      alt: 'a blue bin filled with lots of screws and nuts',
    },
    {
      src: unsplash('1590880795696-20c7dfadacde'),
      alt: 'brown wooden table with white printer papers',
    },
    {
      src: unsplash('1579618215542-2ed5e10b65ed'),
      alt: 'grayscale photo of people sitting on chair inside building',
    },
    { src: unsplash('1613629954394-e12c49b4b965'), alt: 'blue and yellow abstract painting' },
    {
      src: unsplash('1687422810663-c316494f725a'),
      alt: 'a man smiles as he works on a piece of wood',
    },
    { src: unsplash('1631396326838-de37e5f8bcbc'), alt: 'a man working on a piece of wood' },
    {
      src: unsplash('1645651964715-d200ce0939cc'),
      alt: 'a couple of tools that are sitting on a table',
    },
    { src: unsplash('1547609434-b732edfee020'), alt: 'man sawing in room' },
    { src: unsplash('1497218770144-3fea6dbc33fe'), alt: 'hand tools on top of table' },
    {
      src: unsplash('1506599667882-385dd6673353'),
      alt: 'man wearing welding helmet in front of industrial machine',
    },
    { src: unsplash('1426927308491-6380b6a9936f'), alt: 'assorted handheld tools in tool rack' },
    {
      src: unsplash('1631396326870-da00e37a9fc6'),
      alt: 'a person holding a pair of scissors in their hand',
    },
    {
      src: unsplash('1685022515790-28eddf510f24'),
      alt: 'a person cutting a piece of wood with a pair of scissors',
    },
    { src: unsplash('1560846389-956694677531'), alt: 'gray tile saw' },
    {
      src: unsplash('1631396327481-661e938ae313'),
      alt: 'a close up of a wooden object on a table',
    },
    { src: unsplash('1685022515813-c42e8348639b'), alt: 'a man working on a piece of wood' },
    { src: unsplash('1453806839674-d1a9087ca1ed'), alt: 'carving tool set' },
    { src: unsplash('1679797850019-3d0d8659a695'), alt: 'a man working on a piece of wood' },
    {
      src: unsplash('1719639946880-9102dd53391b'),
      alt: 'A group of woodworking tools sitting on top of a wooden table',
    },
    {
      src: unsplash('1637176463673-8f63699a85b5'),
      alt: 'a pile of cut logs sitting on top of a pile of dirt',
    },
    { src: unsplash('1506968430777-bf7784a87f23'), alt: 'brown wooden surface' },
    { src: unsplash('1620254519036-454ef6a9f6c7'), alt: 'brown and black metal tool' },
    {
      src: unsplash('1685022515804-af2e8b3b75e0'),
      alt: 'a man using a table saw to cut a piece of wood',
    },
    { src: unsplash('1685022515887-c2a10c137162'), alt: 'a man is working on a piece of wood' },
    { src: unsplash('1631396328075-9c65a7406f09'), alt: 'a man working in a woodworking shop' },
    {
      src: unsplash('1414497729697-b8555ba6c1cc'),
      alt: 'close photography of black jack planer near chisel',
    },
    {
      src: unsplash('1631396328093-e5941f59cf7b'),
      alt: 'a knife and some wood shavings on a table',
    },
    {
      src: unsplash('1626081063434-79a2169791b1'),
      alt: 'person in white shirt holding brown wooden table',
    },
    { src: unsplash('1726219837190-58eddbe006e4'), alt: 'A desk with a laptop on it in a room' },
    {
      src: unsplash('1581166975727-9bdb6c1248af'),
      alt: 'black and white beaded necklace on brown wooden table',
    },
    { src: unsplash('1626081062126-d3b192c1fcb0'), alt: 'person holding brown wooden frame' },
    {
      src: unsplash('1670838895005-e73fad7f59af'),
      alt: 'a room with a bunch of tools hanging on the wall',
    },
  ],
  carreleur: [
    {
      src: unsplash('1703868669362-562283170216'),
      alt: 'a kitchen with a black counter top and white cabinets',
    },
    {
      src: unsplash('1701422052265-64f0ac28dcd6'),
      alt: 'a house with a lawn and steps leading to it',
    },
    { src: unsplash('1726589004565-bedfba94d3a2'), alt: 'A man on a roof working on a roof' },
    {
      src: unsplash('1773225044553-4874c42569c3'),
      alt: '28th street subway station sign with floral wallpaper',
    },
    {
      src: unsplash('1762532264908-c2984bfbce81'),
      alt: 'A lone figure stands near a large, dark object.',
    },
    {
      src: unsplash('1760046325942-cc3f739b38be'),
      alt: 'Modern building interior with large windows and concrete structure',
    },
    {
      src: unsplash('1763665814538-8ba04597286c'),
      alt: 'Workers installing roof tiles on a new building.',
    },
    {
      src: unsplash('1768933294578-02022bfb7532'),
      alt: 'Person stands before pixelated ghost art on wall',
    },
    {
      src: unsplash('1759421010297-d00fd31da0ae'),
      alt: 'Mural of three figures on a yellow building wall.',
    },
    {
      src: unsplash('1772391757988-f62fb64add49'),
      alt: 'Modern subway station with red art installation',
    },
    {
      src: unsplash('1762344681343-d24c0391279b'),
      alt: 'Red chili pepper sculpture in front of modern building',
    },
    {
      src: unsplash('1772391758153-978b30699d40'),
      alt: 'Modern subway station interior with white columns and red art.',
    },
    {
      src: unsplash('1762443151774-f6dc6ce755cb'),
      alt: 'Mosaic benches with flower design by the sea',
    },
    { src: unsplash('1587454308481-7ca9d21e0e04'), alt: 'grey and black basketball hoop' },
    {
      src: unsplash('1641811965803-c0392e12ec88'),
      alt: 'a close up of a tiled wall with trees in the background',
    },
    { src: unsplash('1656524698811-8827220e66e6'), alt: 'a brick wall with a light' },
    {
      src: unsplash('1636200534256-c08268363482'),
      alt: 'a hammer sitting on top of a pile of tile',
    },
    { src: unsplash('1560005627-c96e0aeb6eaa'), alt: 'brown and beige floral tiles' },
    { src: unsplash('1656524699038-4012bacb1c9a'), alt: 'a white brick wall' },
    { src: unsplash('1593424469977-77a35fed63c6'), alt: 'brass door knob on white ceramic tile' },
    {
      src: unsplash('1629195354259-fe4ff202c8e3'),
      alt: 'man in blue shirt and brown hat holding gray metal pipe',
    },
    {
      src: unsplash('1627991153184-ef1930130e0d'),
      alt: 'man in gray shirt and blue denim jeans standing near white wooden window',
    },
    {
      src: unsplash('1757904257660-75ee7df54420'),
      alt: 'Green and gray tiles in a modern bathroom',
    },
    {
      src: unsplash('1752581827127-75873775bc68'),
      alt: 'Corner of a wall and floor with flower patterns.',
    },
    {
      src: unsplash('1581519924547-7bead3a57608'),
      alt: 'gray concrete staircase with stainless steel railings',
    },
    { src: unsplash('1656524698253-e17ada339ddb'), alt: 'a window in a brick building' },
    {
      src: unsplash('1684783777567-1866b5221857'),
      alt: 'a close up of a wall made of small tiles',
    },
    { src: unsplash('1615136551313-38d6829ded25'), alt: 'green and white floral textile' },
    {
      src: unsplash('1563454656852-dbd502f61cf9'),
      alt: 'a close up of a tiled wall with blue and red tiles',
    },
    { src: unsplash('1656646523907-97b094c7e63a'), alt: 'a white tiled floor' },
    { src: unsplash('1548967199-79324abbe7dc'), alt: 'a close up of a pink marble tile wall' },
    {
      src: unsplash('1619439677623-6f881c7be58f'),
      alt: 'white ceramic bathtub with blue and white wall tiles',
    },
    {
      src: unsplash('1699543909013-4b9c73081b48'),
      alt: 'a close up of a white and red brick wall',
    },
    { src: unsplash('1609946860441-a51ffcf22208'), alt: 'blue wooden cabinet near white wall' },
    { src: unsplash('1564540583246-934409427776'), alt: 'white ceramic sink' },
    {
      src: unsplash('1642678751244-296d18c4cab3'),
      alt: 'a white toilet sitting next to a sink in a bathroom',
    },
    { src: unsplash('1603513188937-a5ec7a931eba'), alt: 'brown and white abstract painting' },
    { src: unsplash('1768924413730-ff5ad1ddb523'), alt: 'Corner of a building with tiled walls' },
    {
      src: unsplash('1567110755423-5dc198e6d41e'),
      alt: 'a bathroom with a brick wall and a shower head',
    },
    {
      src: unsplash('1650315534102-3ca1e51d41c5'),
      alt: 'a white toilet sitting next to a white sink',
    },
    {
      src: unsplash('1649446326998-a16524cfa667'),
      alt: 'a vase with flowers and towels in a bathroom',
    },
    {
      src: unsplash('1707291173710-10514ef55814'),
      alt: 'a towel hanging on a towel rack in a bathroom',
    },
    {
      src: unsplash('1621215058889-885f3d5a143c'),
      alt: 'A modern bathroom with bathtub and shower.',
    },
    {
      src: unsplash('1620626011761-996317b8d101'),
      alt: 'white ceramic bathtub near green potted plant',
    },
    {
      src: unsplash('1744828367881-97196efa6ec2'),
      alt: 'Two urinals hang against an orange tiled wall.',
    },
    {
      src: unsplash('1759223607861-f0ef3e617739'),
      alt: 'Luxurious marble bathroom with bathtub and vanity.',
    },
    { src: unsplash('1765556556784-7656ee0a1bd8'), alt: 'A grid of white textured tiles' },
    {
      src: unsplash('1758482355865-af58a68e0c68'),
      alt: 'Red and blue mosaic tiles with white grout',
    },
    { src: unsplash('1567110684145-43024ecf0fa7'), alt: 'soap on soap holder' },
    {
      src: unsplash('1758548157466-7c454382035a'),
      alt: 'Modern bathroom with white marble and bathtub.',
    },
    { src: unsplash('1608230417213-9e820702b170'), alt: 'a large tub next to a sink' },
    {
      src: unsplash('1630840450974-7c7ddad8bdfe'),
      alt: 'white ceramic sink beside blue wall tiles',
    },
    { src: unsplash('1608230417157-ca92e9067ca3'), alt: 'a counter with a sink and a mirror' },
    {
      src: unsplash('1762810963385-0d91f2539fa2'),
      alt: 'Modern bathroom with vanity, toilet, and hallway view',
    },
    { src: unsplash('1629079447777-1e605162dc8d'), alt: 'white ceramic sink with mirror' },
    {
      src: unsplash('1758548157276-00c54fd4a9fa'),
      alt: 'Modern bathroom vanity with marble tiles and round mirror',
    },
    {
      src: unsplash('1749137315764-4f6a62ea23ba'),
      alt: 'Cosmetics are neatly arranged in a tiled shelf.',
    },
    {
      src: unsplash('1759691337823-5b348f5fd98d'),
      alt: 'Modern bathroom with wooden vanity and glass shower.',
    },
    { src: unsplash('1608651061499-ff031fbf6645'), alt: 'pink towel on white metal rack' },
  ],
  couvreur: [
    { src: unsplash('1633759593085-1eaeb724fc88'), alt: 'a man with a hammer on top of a roof' },
    { src: unsplash('1635424709845-3a85ad5e1f5e'), alt: 'a couple of people that are on a roof' },
    {
      src: unsplash('1634750009079-6bf7bede038b'),
      alt: 'a couple of men standing on top of a roof',
    },
    {
      src: unsplash('1635424824849-1b09bdcc55b1'),
      alt: 'a man working on a roof with a power drill',
    },
    { src: unsplash('1632759145351-1d592919f522'), alt: 'a man standing on the roof of a house' },
    { src: unsplash('1726589004565-bedfba94d3a2'), alt: 'A man on a roof working on a roof' },
    {
      src: unsplash('1634750006909-3258af95e257'),
      alt: 'a couple of men standing on top of a roof',
    },
    { src: unsplash('1681049400158-0ff6249ac315'), alt: 'two men working on the roof of a house' },
    {
      src: unsplash('1635424825057-7fb6dcd651ef'),
      alt: 'a man working on a roof with a power drill',
    },
    { src: unsplash('1617459973560-33aea09d1c22'), alt: 'black rectangular device on brown roof' },
    { src: unsplash('1602193230480-7840a38eb0c3'), alt: 'black and white glass building' },
    {
      src: unsplash('1605450099279-533bd3ce379a'),
      alt: 'brown roof tiles in close up photography',
    },
    {
      src: unsplash('1727777266423-6a33048e4894'),
      alt: 'The roof of a building with a sky in the background',
    },
    {
      src: unsplash('1627591637320-fcfe8c34b62d'),
      alt: '2 men standing on white concrete building during daytime',
    },
    { src: unsplash('1570690732090-275b8807dd76'), alt: 'white brick house with green roof' },
    {
      src: unsplash('1760331840361-d751cfc1becf'),
      alt: 'Workers repairing a damaged roof with debris',
    },
    {
      src: unsplash('1713640113797-35abeadfe0fa'),
      alt: 'A close up of a roof with a tree in the background',
    },
    { src: unsplash('1770149682916-b3f31bcd8174'), alt: 'A monkey on a traditional asian roof' },
    {
      src: unsplash('1763665814485-a0a1b6f51ed7'),
      alt: 'Construction workers installing roofing materials on a house.',
    },
    {
      src: unsplash('1763665814605-a6489a3bf2a0'),
      alt: 'Workers installing shingles on a steep roof',
    },
    {
      src: unsplash('1770149682967-5733992e49ff'),
      alt: 'Workers repairing a tiled roof with scaffolding and corrugated metal.',
    },
    {
      src: unsplash('1763665814538-8ba04597286c'),
      alt: 'Workers installing roof tiles on a new building.',
    },
    {
      src: unsplash('1763665814965-b5c4b3547908'),
      alt: 'Construction workers installing roof tiles on a new building.',
    },
    {
      src: unsplash('1770121703450-1e59387f694b'),
      alt: 'Close-up of dark, wet roof tiles with some damage.',
    },
    {
      src: unsplash('1642749776312-aa42ce20c9f5'),
      alt: 'a couple of men standing on top of a roof',
    },
    {
      src: unsplash('1619296162786-13137c91a699'),
      alt: 'people sitting on bench near water fountain',
    },
    { src: unsplash('1761959166803-ed952543eeae'), alt: 'Dilapidated house with a damaged roof' },
    {
      src: unsplash('1761393665973-62fb8847bf9d'),
      alt: 'Workers in red suits on a white building roof',
    },
    {
      src: unsplash('1775276406121-a1fdf9606b05'),
      alt: 'Close-up of weathered terracotta roof tiles in rows.',
    },
    { src: unsplash('1759406066673-f76869a4e6db'), alt: 'Man painting the side of a brick house' },
    {
      src: unsplash('1643225523483-e2c434191bba'),
      alt: 'a man riding a skateboard on top of a roof',
    },
    {
      src: unsplash('1759407518955-678b648e3922'),
      alt: 'Workers constructing a house roof with scaffolding',
    },
    { src: unsplash('1652990550645-c1fc90691ed2'), alt: 'a man working on a piece of wood' },
    {
      src: unsplash('1720655256483-52df8ea8f147'),
      alt: 'A black and white photo of a man working on a truck',
    },
    { src: unsplash('1661545621129-0fc86efa2ea1'), alt: 'a person wearing a hard hat' },
    {
      src: unsplash('1726690330713-18c0c0efbdc0'),
      alt: 'A man sitting on the floor using a laptop computer',
    },
    {
      src: unsplash('1773245148692-bb4fa68e26fe'),
      alt: 'Man operating a laptop with wires and equipment.',
    },
    { src: unsplash('1738248427115-3489f1aaa337'), alt: 'A man working on a construction site' },
    {
      src: unsplash('1758876734777-dcc6981f3671'),
      alt: 'Construction worker in hard hat sits on bucket using phone.',
    },
    {
      src: unsplash('1507144159582-ee8a88b0ce07'),
      alt: 'man sitting on stool cleaning shoes at the alley',
    },
    { src: unsplash('1552721607-7e2845e2a677'), alt: 'man sitting on chair with headphones' },
    {
      src: unsplash('1621080367042-700e302c1895'),
      alt: 'man in black and orange long sleeve shirt holding brown wooden stick',
    },
    { src: unsplash('1567238563567-b99d8ac66e9b'), alt: 'man raking the sand' },
    { src: unsplash('1723166825970-f79f8dc4810e'), alt: 'A man standing on a boat near the ocean' },
    {
      src: unsplash('1591100585960-7e8fa7f938e8'),
      alt: 'man in black and white crew neck t-shirt standing beside man in white t-shirt',
    },
    {
      src: unsplash('1699108947915-bbe80636005f'),
      alt: 'a man standing next to a truck in front of a building',
    },
    {
      src: unsplash('1675179541138-4e33144e8967'),
      alt: 'a man riding a motorcycle down a street next to a red and white sign',
    },
    { src: unsplash('1665492302891-502760d2d888'), alt: 'a man wearing a mask' },
    { src: unsplash('1667207591141-96c7ef7a5a3b'), alt: 'a man wearing a mask' },
    { src: unsplash('1665281872447-959671912829'), alt: 'a person wearing a hard hat' },
    {
      src: unsplash('1705579612181-faf45962cfcb'),
      alt: 'a man wearing a hard hat and safety gear',
    },
    {
      src: unsplash('1721673028717-23c15f9a02bc'),
      alt: 'A construction worker pushing a wheelbarrow',
    },
    { src: unsplash('1579105582031-6f674f9db4e7'), alt: 'man using glass smoking device' },
    {
      src: unsplash('1654000749334-5a290b594dc5'),
      alt: 'a woman in an orange shirt carrying a tray on her head',
    },
    {
      src: unsplash('1659353587228-5dbbebb5d98f'),
      alt: 'a man in a yellow hard hat holding a tablet',
    },
    {
      src: unsplash('1667207591149-6989036d9ed9'),
      alt: 'a man wearing a safety vest working on a machine',
    },
    { src: unsplash('1553946550-4b8f3eea5451'), alt: 'man standing near rods' },
    { src: unsplash('1735480493109-a99ff7da7227'), alt: 'A man in blue shirt working on a pipe' },
  ],
}
