/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 8 services, 448 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen6: Record<string, { src: string; alt: string }[]> = {
  charpentier: [
    { src: unsplash('1520372561567-bac27b0e5fa1'), alt: 'black hammer on brown wood' },
    {
      src: unsplash('1687089454344-96a1acc71c2d'),
      alt: 'a tall building with lots of windows on the side of it',
    },
    {
      src: unsplash('1687089454022-2a4134852c4c'),
      alt: 'a group of buildings that are next to each other',
    },
    { src: unsplash('1607590556558-36a1955f0358'), alt: 'brown brick wall during daytime' },
    {
      src: unsplash('1649056325447-72874fa7db56'),
      alt: 'a long hallway with wooden beams and windows',
    },
    { src: unsplash('1518217990081-c99d5f404725'), alt: 'brown table outside house' },
    {
      src: unsplash('1569370029941-4a26ad1acaa0'),
      alt: 'brown and black concrete house during daytime',
    },
    {
      src: unsplash('1661246125136-63b22d1e0e62'),
      alt: 'a building with a person sitting in front of it',
    },
    { src: unsplash('1569370029765-33aaab1f4851'), alt: 'brown wooden house' },
    {
      src: unsplash('1700581316314-9e6a809bd656'),
      alt: 'a room that is being constructed with wood',
    },
    {
      src: unsplash('1693639767415-27ff64ce4da2'),
      alt: 'a house under construction with scaffolding around it',
    },
    {
      src: unsplash('1693639435051-d58ac86db299'),
      alt: 'a house under construction with a lot of scaffolding',
    },
    {
      src: unsplash('1693639385915-d7a7ddefe8e1'),
      alt: 'a building under construction with scaffolding and a clock',
    },
    {
      src: unsplash('1693639049292-0f9ec9c287d4'),
      alt: 'a building under construction with lots of scaffolding',
    },
    {
      src: unsplash('1693639056346-49cd9529378a'),
      alt: 'a building under construction with a crane in the background',
    },
    { src: unsplash('1738514770412-f00a7792cbe0'), alt: 'A black and white photo of a building' },
    {
      src: unsplash('1705685850059-407663c3bce1'),
      alt: 'a tall building with lots of windows next to a tall building',
    },
    { src: unsplash('1657453349716-ce4c10318414'), alt: 'a group of people walking down a street' },
    { src: unsplash('1746787533802-9e5b3c631b04'), alt: 'A new house is being built.' },
    {
      src: unsplash('1749882120717-7187fb3838d0'),
      alt: 'A building is under construction with exposed framing.',
    },
    {
      src: unsplash('1746787510909-92956787bb5f'),
      alt: 'A house under construction sits on a vacant lot.',
    },
    {
      src: unsplash('1774867633782-03465eea0760'),
      alt: 'New houses under construction with wooden framing.',
    },
    {
      src: unsplash('1774869174949-9fd84ba6cc0c'),
      alt: 'Several houses under construction with wooden frames.',
    },
    { src: unsplash('1749882120788-0237b2198b5f'), alt: 'A house is under construction.' },
    {
      src: unsplash('1700224619299-aa9736b543bc'),
      alt: 'a row of multi - colored buildings on a cobblestone street',
    },
    { src: unsplash('1576067620610-73cc985d0d20'), alt: 'white wooden glass window frame' },
    {
      src: unsplash('1543617251-b41223299e58'),
      alt: 'two white concrete buildings in closeup photography',
    },
    {
      src: unsplash('1687169512324-e447122cbd4f'),
      alt: 'a house under construction with a pile of dirt in front of it',
    },
    {
      src: unsplash('1687169503260-85f00f122398'),
      alt: 'a house under construction with scaffolding on the roof',
    },
    {
      src: unsplash('1722021427623-f5a13484ee73'),
      alt: 'A couple of buildings that are next to each other',
    },
    {
      src: unsplash('1693765411770-e8325f743d8f'),
      alt: 'a wooden bench sitting next to a wooden fence',
    },
    {
      src: unsplash('1775481929781-d1ea83579ed8'),
      alt: 'Wooden roof beams forming triangular patterns',
    },
    {
      src: unsplash('1761642119730-c871b492da01'),
      alt: 'Interior view of wooden structure with exposed beams above beams',
    },
    { src: unsplash('1587109525955-6a1b0dc9922d'), alt: 'grayscale photo of wooden ceiling' },
    {
      src: unsplash('1775547081703-1472317fe554'),
      alt: 'Modern cabin with large windows surrounded by trees',
    },
    {
      src: unsplash('1706871005986-f9edb5bc8295'),
      alt: 'a building that has a very large v on the side of it',
    },
    { src: unsplash('1666217356183-b0ba4dfe8810'), alt: 'a wooden building with a blue sky' },
    {
      src: unsplash('1764863713822-e6e01fd53326'),
      alt: 'Abstract geometric pattern of wooden beams and ceiling',
    },
    {
      src: unsplash('1771700497137-4b46dc982416'),
      alt: 'Wooden ceiling with a geometric star pattern',
    },
    {
      src: unsplash('1621703730950-994ffa5e9544'),
      alt: 'brown wooden ceiling with white ceiling lamp',
    },
    {
      src: unsplash('1570376185710-e6c770b74400'),
      alt: 'a close up of a wooden wall made of boards',
    },
    {
      src: unsplash('1761380693275-20e7cb7c95d5'),
      alt: 'Wooden arched ceiling with a central skylight',
    },
    {
      src: unsplash('1707256787750-e76d145c6dac'),
      alt: 'a chandelier hanging from the ceiling of a building',
    },
    { src: unsplash('1572533632166-d79f16bb3db6'), alt: 'brown concrete stairs' },
    {
      src: unsplash('1587937512179-735336f3ca24'),
      alt: 'brown wooden frame with blue and white striped textile',
    },
    { src: unsplash('1603937917500-231197cd060f'), alt: 'white and brown concrete building' },
    {
      src: unsplash('1772920908982-7c6e630f668b'),
      alt: 'Wooden roof beams against a clear blue sky',
    },
    {
      src: unsplash('1760856965762-3a6151df4342'),
      alt: 'Geometric wooden beams against a cloudy sky',
    },
    {
      src: unsplash('1767279141109-e63ff1e1e3e9'),
      alt: 'Intricate wooden ceiling with skylights showing blue sky',
    },
    {
      src: unsplash('1740176346532-2cdf49cecd70'),
      alt: 'A bathroom sign on a wooden wall with a sky background',
    },
    {
      src: unsplash('1740176346543-9db8cb02a240'),
      alt: 'A wooden building with a sign on the side of it',
    },
    {
      src: unsplash('1773414485958-10e1a4ca9a3d'),
      alt: 'Old weathered barn with a rusty, damaged roof.',
    },
    {
      src: unsplash('1613082364903-9ff4734f5dd1'),
      alt: 'brown wooden house on snow covered ground during daytime',
    },
    {
      src: unsplash('1763529321434-eaba722365e1'),
      alt: 'Traditional japanese temple roof with trees in foreground',
    },
    {
      src: unsplash('1673645652984-1a1a414db270'),
      alt: 'a close up of a roof with moss growing on it',
    },
    {
      src: unsplash('1759967583761-a2709f29be6f'),
      alt: 'Dilapidated wooden barn with overgrown vegetation',
    },
    {
      src: unsplash('1760712294257-7d078e3f3939'),
      alt: 'Old rusty farm structure with metal roof',
    },
    { src: unsplash('1766232590203-f474d0e3ddae'), alt: 'Wooden building with branches on roof' },
    {
      src: unsplash('1763067112540-dbc077cf9302'),
      alt: 'Old abandoned farm buildings with silo under clear sky',
    },
    { src: unsplash('1570376186239-7de65bf65905'), alt: 'brown wooden fence' },
  ],
  'isolation-thermique': [
    {
      src: unsplash('1751486289950-5c4898a4c773'),
      alt: 'Pipes and equipment are installed on a wall.',
    },
    {
      src: unsplash('1767514536631-b8a259fbb8bf'),
      alt: 'Exposed electrical wires in a textured wall opening',
    },
    {
      src: unsplash('1768321914149-5a6428ec2f82'),
      alt: 'Interior construction with metal framing and drywall panels',
    },
    {
      src: unsplash('1607400201889-565b1ee75f8e'),
      alt: 'person in blue pants sitting on brown wooden floor',
    },
    {
      src: unsplash('1753363562638-398f75158ea9'),
      alt: 'Inside of an attic with insulation and wood beams.',
    },
    {
      src: unsplash('1753363563295-bd0314e2a802'),
      alt: 'Insulated attic space with wooden beams and skylights.',
    },
    {
      src: unsplash('1753363562647-6a5f6296dedc'),
      alt: 'An attic with insulation and wooden beams.',
    },
    {
      src: unsplash('1625577816396-fbf677c54cee'),
      alt: 'blue and white bicycle near brown wooden wall',
    },
    {
      src: unsplash('1753460133429-40a7e4610720'),
      alt: 'An attic space is being used for storage.',
    },
    {
      src: unsplash('1591684080176-bb2b73f9ec68'),
      alt: 'man in green crew neck t-shirt holding smoking pipe',
    },
    {
      src: unsplash('1753460133435-3b294c9dda5e'),
      alt: 'Attic interior with insulation and a skylight.',
    },
    {
      src: unsplash('1753460133510-08edcb70d987'),
      alt: 'An attic with some stored items is pictured.',
    },
    {
      src: unsplash('1768321917437-1f1f6ae2ad28'),
      alt: 'Wooden wall section with spray foam insulation.',
    },
    {
      src: unsplash('1753717202579-9c6ac3592b62'),
      alt: 'An attic space with insulation and wooden beams.',
    },
    {
      src: unsplash('1753717202685-47704db818b9'),
      alt: 'An unfinished attic space with wooden support beams.',
    },
    { src: unsplash('1625577816955-4e2be76d1549'), alt: 'brown and white floral window curtain' },
    {
      src: unsplash('1752852381837-ce679ffdab31'),
      alt: 'Cluttered basement space with various items and boxes.',
    },
    { src: unsplash('1625577815636-d7a61b583799'), alt: 'red and white wooden door' },
    {
      src: unsplash('1753460133435-bf41927f77f7'),
      alt: 'Attic with insulation, beams, and storage.',
    },
    { src: unsplash('1657195721935-e73e545a2aae'), alt: 'a close-up of a roof' },
    {
      src: unsplash('1753460133418-e25fda007187'),
      alt: 'A dusty attic with insulation and wooden beams.',
    },
    { src: unsplash('1632214531568-02d981f57188'), alt: 'a room that has a skylight in it' },
    {
      src: unsplash('1751028582741-a534c41902e7'),
      alt: 'An attic filled with various stored items.',
    },
    {
      src: unsplash('1635171495000-72de0454f1cb'),
      alt: 'a close up of a building with metal pipes',
    },
    { src: unsplash('1683741991313-d0eb7e79adc9'), alt: 'a man on a ladder working on a jeep' },
    {
      src: unsplash('1711375201123-61eddb7804d7'),
      alt: 'a man working on a construction project in a cave',
    },
    {
      src: unsplash('1768321910174-6f55899299a2'),
      alt: 'Room under construction with exposed insulation and windows',
    },
    {
      src: unsplash('1750603244861-015017c77400'),
      alt: 'Ceiling construction is underway in the building.',
    },
    {
      src: unsplash('1753460133438-7fea0ff39b7c'),
      alt: 'An attic with insulation and skylights is shown.',
    },
    {
      src: unsplash('1695509098533-e4b1ba1479f9'),
      alt: 'a green building under construction with a blue sky in the background',
    },
    {
      src: unsplash('1701538517775-f94a4a6805ce'),
      alt: 'a close up of a rock formation with grass growing on top of it',
    },
    {
      src: unsplash('1589572394490-771aa22db633'),
      alt: 'white concrete wall under blue sky during daytime',
    },
    {
      src: unsplash('1759915554664-91baceca51e2'),
      alt: 'Yellow and pink painted brick wall texture',
    },
    {
      src: unsplash('1646066458890-45f713b9ab01'),
      alt: 'a tree with no leaves in front of a building',
    },
    {
      src: unsplash('1639804658358-daa1b83738f1'),
      alt: 'a room with a blue door and a white wall',
    },
    { src: unsplash('1658917608613-09b31cfda49f'), alt: 'a white column against a red wall' },
    { src: unsplash('1558361450-d39f20248588'), alt: 'a close up of a wall with a clock on it' },
    { src: unsplash('1584767159346-53684fcedfe8'), alt: 'brown concrete blocks with kanji text' },
    { src: unsplash('1567404469884-75c0620d0912'), alt: 'brown wall bricks' },
    {
      src: unsplash('1678459781158-f7e20db550d4'),
      alt: 'a close up of a brick wall with a window',
    },
    { src: unsplash('1660207237316-08a6ee93687a'), alt: 'a brick wall with a hole in it' },
    { src: unsplash('1608283832972-7402dc32545e'), alt: 'brown brick building during daytime' },
    {
      src: unsplash('1682937546456-fea3237ba8aa'),
      alt: 'a close up of a blue building with a brown door',
    },
    { src: unsplash('1669729414773-0dd7473fbdd3'), alt: 'a door in a room' },
    {
      src: unsplash('1758077222093-618ad9828d16'),
      alt: 'Wooden structure and tree on textured ground',
    },
    {
      src: unsplash('1761682751238-a9174874aeee'),
      alt: 'Rough concrete wall next to weathered red brick wall',
    },
    { src: unsplash('1720055702154-6345e3799386'), alt: 'A close up of a green and white line' },
    {
      src: unsplash('1761682751897-4c4fb96a6a85'),
      alt: 'Two walls, one brick, one concrete, with sky visible',
    },
    { src: unsplash('1613171233547-a9098bbef75b'), alt: 'white and brown concrete wall' },
    { src: unsplash('1685837491331-4270c81155fb'), alt: 'a cement wall with a hole in the middle' },
    {
      src: unsplash('1736624155621-a8fd88131510'),
      alt: 'A black and white photo of a brick building',
    },
    {
      src: unsplash('1580072140977-a66c2b23769b'),
      alt: 'white concrete wall under blue sky during daytime',
    },
    {
      src: unsplash('1746641017949-efc1ba790e73'),
      alt: 'Concrete blocks form an intricate geometric pattern.',
    },
    {
      src: unsplash('1768149524780-a6c7337cf619'),
      alt: 'A weathered white wall with faint lettering.',
    },
  ],
  paysagiste: [
    {
      src: unsplash('1595387426256-cc153122a6f1'),
      alt: 'gray concrete road between green and brown trees during daytime',
    },
    { src: unsplash('1599110906632-28d25094470f'), alt: 'white green and brown textile' },
    { src: unsplash('1696846912973-3233cc80bf86'), alt: 'a patio with a couch and a table in it' },
    { src: unsplash('1611895186551-4bfad81c5b11'), alt: 'green grass field with trees' },
    {
      src: unsplash('1634893448897-437a9593128e'),
      alt: 'a pathway lined with lush green bushes and palm trees',
    },
    { src: unsplash('1655731695281-b0f818014486'), alt: 'a garden with a stone path' },
    {
      src: unsplash('1595387426463-bef727e35bb3'),
      alt: 'green grass field with fountain in the middle of the forest',
    },
    {
      src: unsplash('1630752918954-d577d011d8df'),
      alt: 'green grass field near brown concrete building during daytime',
    },
    {
      src: unsplash('1617850687395-620757feb1f3'),
      alt: 'brown wooden framed blue padded armchair',
    },
    {
      src: unsplash('1569227997603-33b9f12af927'),
      alt: 'architectural photography of concrete stair',
    },
    { src: unsplash('1656646549794-17ce57191582'), alt: 'a house with a yard and trees' },
    {
      src: unsplash('1616281677557-a40d9d9ece5e'),
      alt: 'brown wooden bench near swimming pool during daytime',
    },
    { src: unsplash('1656646549569-e3ad3ff8f9f9'), alt: 'a house with a deck' },
    {
      src: unsplash('1696177124949-cf06353fecd7'),
      alt: 'a walkway between two buildings with flowers in the foreground',
    },
    { src: unsplash('1656646549671-000665d8d8bc'), alt: 'a building with a large roof' },
    { src: unsplash('1520302630591-fd1c66edc19d'), alt: 'succulent plant lot' },
    {
      src: unsplash('1696177183619-da501a48fc35'),
      alt: 'a brick walkway between two buildings with trees lining both sides',
    },
    { src: unsplash('1656646549697-8f6a21b8f7c2'), alt: 'a house with a yard and trees' },
    { src: unsplash('1656646549757-17739c7a7e3b'), alt: 'a house with a path and trees' },
    {
      src: unsplash('1713300596173-05d72fce4bad'),
      alt: 'a walkway in a grassy area between two buildings',
    },
    { src: unsplash('1607258524403-85db6a63085c'), alt: 'green plants on white ceramic tiles' },
    { src: unsplash('1660920320921-a05dbfa53483'), alt: 'a bench sits unoccupied' },
    {
      src: unsplash('1758792231451-4804f8f8659c'),
      alt: 'Aerial view of a star-shaped garden with manicured hedges.',
    },
    { src: unsplash('1703756293076-edb3627f2978'), alt: 'a couple of trees that are in the grass' },
    {
      src: unsplash('1767247795766-d07be9e609d6'),
      alt: 'Oval flower bed with colorful blossoms in a lush park',
    },
    {
      src: unsplash('1758848752618-39cdc0c24616'),
      alt: 'A bluebird lands on a birdhouse with yellow flowers.',
    },
    {
      src: unsplash('1773339874615-3f1dba3dd001'),
      alt: 'A whimsical castle adorned with lush greenery and a genie',
    },
    {
      src: unsplash('1758905458386-68ef08535428'),
      alt: 'Manicured garden with greenhouse and historic building.',
    },
    {
      src: unsplash('1772352214565-15aa17164299'),
      alt: 'A large, rounded evergreen tree against a blue sky.',
    },
    {
      src: unsplash('1770820614472-3160d25f80f0'),
      alt: 'A manicured garden with red flowers and cypress trees.',
    },
    {
      src: unsplash('1669045271480-063075441cab'),
      alt: 'a wooden structure with trees in the background',
    },
    {
      src: unsplash('1773979638724-c6ffed7fe0de'),
      alt: 'Wooden deck and steps leading to a grassy yard.',
    },
    {
      src: unsplash('1765004775728-e99163f1767d'),
      alt: 'Traditional chinese pavilion with intricate wooden details',
    },
    {
      src: unsplash('1547036233-8d7e8f19563e'),
      alt: 'calm body of water with concrete bridge at daytime',
    },
    {
      src: unsplash('1766177122141-f4d2b80aef2f'),
      alt: 'Greenhouse structure with manicured garden and trees',
    },
    {
      src: unsplash('1608394829674-66fbbcd5f4aa'),
      alt: 'green grass field with brown and gray house',
    },
    {
      src: unsplash('1771612464698-ffdd3f64fa8c'),
      alt: 'A white building nestled among trees under a blue sky.',
    },
    { src: unsplash('1614765437824-f5433016b7b6'), alt: 'green plants on brown wooden gazebo' },
    { src: unsplash('1578193660481-c69aa272b506'), alt: 'green tree' },
    {
      src: unsplash('1760119150457-07c2bb32511d'),
      alt: 'Ornate building with arched walkway and manicured garden',
    },
    {
      src: unsplash('1712411880136-cc82a565bf71'),
      alt: 'a group of people standing on top of a lush green field',
    },
    {
      src: unsplash('1746625518093-beaba1a98827'),
      alt: 'A round doorway reveals a lush garden path.',
    },
    { src: unsplash('1601676796593-f771034fa753'), alt: 'red and white concrete building' },
    { src: unsplash('1669024808541-71f502ac6e42'), alt: 'two yellow chairs in a garden' },
    {
      src: unsplash('1760217460921-e5625b121c3b'),
      alt: 'Stone turtle sculpture in a garden with fountains',
    },
    {
      src: unsplash('1765897727982-275b2c08a3e0'),
      alt: 'A formal garden path lined with conical trees',
    },
    {
      src: unsplash('1768577087453-8288bce62a06'),
      alt: 'Two decorative windows on a white wall with greenery.',
    },
    {
      src: unsplash('1773934797333-a09e2d984a65'),
      alt: 'A tranquil garden with a reflective pond and brick pillars.',
    },
    {
      src: unsplash('1650223879910-6afc56bc199c'),
      alt: 'a small brick building surrounded by trees and bushes',
    },
    {
      src: unsplash('1722950076290-d04b354afaf3'),
      alt: 'A black and white photo of a building in a park',
    },
    {
      src: unsplash('1758373344144-5124e40f3a8a'),
      alt: 'Stone structure covered in ivy with arched openings.',
    },
    {
      src: unsplash('1642105412568-86aed08338a0'),
      alt: 'a building with a glass roof surrounded by trees',
    },
    {
      src: unsplash('1760972543716-eb03ada2adb4'),
      alt: 'Aerial view of a u-shaped building with gardens',
    },
    {
      src: unsplash('1761637823293-f96835ec5038'),
      alt: 'Curved stone wall surrounding a circular paved area',
    },
    {
      src: unsplash('1759142635794-6d64acf4c19a'),
      alt: 'Stone pedestal with basin near building and bushes',
    },
    {
      src: unsplash('1772904507437-723852de6add'),
      alt: 'A formal garden with a fountain and benches.',
    },
    {
      src: unsplash('1769417476717-332a0a99a76b'),
      alt: 'Formal gardens with manicured hedges and rolling hills',
    },
    { src: unsplash('1697394730437-2643da0c87fb'), alt: 'a house with a waterfall in the yard' },
    { src: unsplash('1768656647906-b13ac4c4a798'), alt: 'Courtyard with green plants and windows' },
  ],
  'alarme-securite': [
    {
      src: unsplash('1558002038-1055907df827'),
      alt: 'gold Apple iPhone smartphone held at the door',
    },
    { src: unsplash('1621886943381-cb97cc18b17a'), alt: 'white and black security camera' },
    {
      src: unsplash('1770197247933-63e02c014cb7'),
      alt: 'Intercom device with red spray paint markings',
    },
    {
      src: unsplash('1774818803625-7a46ca67cc13'),
      alt: 'Security camera mounted on a post against a white background',
    },
    {
      src: unsplash('1767059439630-ca3844d07d77'),
      alt: 'Security camera mounted on a white ceiling.',
    },
    { src: unsplash('1728971568218-03a7f87c9e99'), alt: 'A couple of lights that are on a wall' },
    {
      src: unsplash('1728971975421-50f3dc9663a4'),
      alt: 'A small camera sitting on top of a white table',
    },
    { src: unsplash('1724343025504-3afb6d67566b'), alt: 'A camera that is sitting on a table' },
    {
      src: unsplash('1707296916498-7f93df6caff3'),
      alt: 'a person holding a car key in front of a van',
    },
    { src: unsplash('1558702729-673ee284a1ee'), alt: 'red light' },
    {
      src: unsplash('1587928116931-14de7cc690b1'),
      alt: 'a red fire alarm sign mounted to the side of a metal pole',
    },
    {
      src: unsplash('1564741749407-165a10a41a22'),
      alt: 'grey device in red wall close-up photography',
    },
    {
      src: unsplash('1660330589693-99889d60181e'),
      alt: 'a man wearing a hat and holding a green object',
    },
    { src: unsplash('1657116993933-7b60d354c405'), alt: 'a white door with red buttons' },
    { src: unsplash('1631053745666-5f3d88db46cb'), alt: 'clear glass jar with orange liquid' },
    { src: unsplash('1648558461974-deba21752a85'), alt: 'a red and white balloon' },
    {
      src: unsplash('1681746198342-8e977c6af906'),
      alt: 'a house number sign with a red light on it',
    },
    {
      src: unsplash('1565012384794-2160a7540a4a'),
      alt: 'a couple of blue boxes mounted to the side of a wall',
    },
    {
      src: unsplash('1614773742339-0a9b7dc62d32'),
      alt: 'person wearing black leather strap watch',
    },
    { src: unsplash('1666285571949-3ee1a4946059'), alt: 'text' },
    {
      src: unsplash('1653878729374-8d64c616023b'),
      alt: 'a red light sitting on the side of a building',
    },
    {
      src: unsplash('1594765351360-95bddec98686'),
      alt: 'red and white wooden door with love print',
    },
    { src: unsplash('1620451912554-296cb92f2475'), alt: 'black and brown telephone booth' },
    { src: unsplash('1572537842835-08c65286efef'), alt: 'gray stainless steel fire exit sign' },
    { src: unsplash('1660330589487-39cc0177ba89'), alt: 'a person in a yellow jacket' },
    { src: unsplash('1694532496411-3c38b97df3fc'), alt: 'a close up of a device with many wires' },
    {
      src: unsplash('1737200376804-8a623b06a25f'),
      alt: 'A red and white traffic light next to a brick building',
    },
    {
      src: unsplash('1632912332455-619973a35a83'),
      alt: 'a couple of black and white phones on a wall',
    },
    { src: unsplash('1658212662417-a2a76efe25df'), alt: 'a man holding a syringe' },
    {
      src: unsplash('1767741683084-08ac01518c8c'),
      alt: 'Red automatic alarm mounted on brick wall',
    },
    { src: unsplash('1655202904146-4f5b96c2284f'), alt: 'a building with windows and a ladder' },
    { src: unsplash('1666734057863-0087ebfa44a1'), alt: 'a red and black battery' },
    {
      src: unsplash('1572368561855-d7d05cb05e91'),
      alt: 'white megaphone on top of concrete building',
    },
    { src: unsplash('1667396473517-19461ee8eb4b'), alt: 'a white tower with a antenna' },
    { src: unsplash('1657653464580-2badf3d09040'), alt: 'a person using a phone' },
    { src: unsplash('1562840291-b8679949b725'), alt: 'outlet attached on white wall' },
    { src: unsplash('1575112096027-f601e335d37e'), alt: 'Fire button' },
    { src: unsplash('1637920952213-3467ee3df490'), alt: 'a red and white sign on a white wall' },
  ],
  platrier: [
    { src: unsplash('1660029763088-d8c1dff1a5e3'), alt: 'a window in a building' },
    {
      src: unsplash('1727200446200-c9ee44dc6bb2'),
      alt: 'A close up of a cement surface with small cracks',
    },
    { src: unsplash('1645865163049-bb8f076cbd38'), alt: 'a black and white photo of some water' },
    {
      src: unsplash('1766961980272-921bba4240bc'),
      alt: 'Construction workers plastering a wall on scaffolding.',
    },
    { src: unsplash('1577200080776-fe8b6c5559dc'), alt: 'a close up of a white stucco wall' },
    {
      src: unsplash('1645865163180-aba3a050feeb'),
      alt: 'a black and white photo of a textured surface',
    },
    {
      src: unsplash('1645865163176-cbc0459034c9'),
      alt: 'a close up of a red wall with a clock on it',
    },
    {
      src: unsplash('1628615613709-9642d17dbb54'),
      alt: 'brown wooden sticks on white ceramic plate',
    },
    {
      src: unsplash('1629195354259-fe4ff202c8e3'),
      alt: 'man in blue shirt and brown hat holding gray metal pipe',
    },
    { src: unsplash('1517421937867-725f85920dca'), alt: 'brown brick and blue wall paint' },
    {
      src: unsplash('1700502335822-d4856cca490a'),
      alt: 'a man standing next to a building with a hammer',
    },
    { src: unsplash('1738503145851-dff68385f9fe'), alt: 'A close up of a wall with peeling paint' },
    {
      src: unsplash('1675191863404-e1db618d6655'),
      alt: 'a man painting a wall with a paint roller',
    },
    { src: unsplash('1693591526237-14b58b9b4337'), alt: 'a wall that has some paint on it' },
    { src: unsplash('1710381608043-9cdc0197e409'), alt: 'a wall with peeling paint on it' },
    {
      src: unsplash('1738504049563-8a00347e63ef'),
      alt: 'A red fire hydrant sitting on the side of a cement wall',
    },
    {
      src: unsplash('1693591526021-d20fff15b500'),
      alt: 'a red fire hydrant sitting on the side of a cement wall',
    },
    { src: unsplash('1575147270841-b73b888b840c'), alt: 'brown brick wall' },
    {
      src: unsplash('1760073643328-88547b90611a'),
      alt: 'Rough textured wall with exposed bricks below',
    },
    { src: unsplash('1704052950803-959df3a5e99c'), alt: 'a brick wall with a light on it' },
    { src: unsplash('1758789646105-a9ca943d00ab'), alt: 'Peeling blue paint on a textured wall' },
    { src: unsplash('1605104466671-ac563bb438c2'), alt: 'white and gray concrete floor' },
    { src: unsplash('1544558074-d7356aeaf6f0'), alt: 'brown and white stone fragment' },
    { src: unsplash('1657309438199-45603b1d5ebe'), alt: 'a bird in a birdhouse' },
    { src: unsplash('1526399999529-e812236ab3ba'), alt: 'brown concrete wall' },
    { src: unsplash('1564741492473-a1d3f1e1a6ca'), alt: 'brown brick wall' },
    { src: unsplash('1657280952521-a21d42f59149'), alt: 'a close up of a grey surface' },
    {
      src: unsplash('1738503210080-189e3d9d13d3'),
      alt: 'A white wall with a blue and green painting on it',
    },
    { src: unsplash('1591712457013-36f84152bf58'), alt: 'brown and black round wall art' },
    { src: unsplash('1660207237316-08a6ee93687a'), alt: 'a brick wall with a hole in it' },
    {
      src: unsplash('1765147238231-443434e1800e'),
      alt: 'A dimly lit room with a figure on the floor.',
    },
    {
      src: unsplash('1768321917806-b4b6fbbef837'),
      alt: 'Interior room under construction with exposed framing and ceiling.',
    },
    {
      src: unsplash('1768321914149-5a6428ec2f82'),
      alt: 'Interior construction with metal framing and drywall panels',
    },
    { src: unsplash('1718816281207-3b253cff549a'), alt: 'A room that has some paint on the floor' },
    {
      src: unsplash('1768321902290-54497eeb9cf6'),
      alt: 'Interior room undergoing renovation with exposed walls and window.',
    },
    {
      src: unsplash('1768321910174-6f55899299a2'),
      alt: 'Room under construction with exposed insulation and windows',
    },
    {
      src: unsplash('1749571598487-5e7408886d66'),
      alt: 'An empty, spacious room with several areas.',
    },
    {
      src: unsplash('1695886517962-cafc014947de'),
      alt: 'a wall that has some wires attached to it',
    },
    {
      src: unsplash('1774977863604-59f4e6d37a90'),
      alt: 'Man on ladder working on ceiling access panel.',
    },
    {
      src: unsplash('1608109704808-62aadbc33a7d'),
      alt: 'man in red shirt and blue denim jeans standing on white wooden door',
    },
    {
      src: unsplash('1733431772808-82d878e59000'),
      alt: 'A large room with a lot of white paint on the walls',
    },
    { src: unsplash('1638890928047-10a4eb9d4744'), alt: 'a room with a brick wall and a window' },
    {
      src: unsplash('1733431774078-692252a6605e'),
      alt: 'A large room with a lot of paint on the walls',
    },
    {
      src: unsplash('1632143696577-809bae4b10f4'),
      alt: 'a room with a window and a white ceiling',
    },
    {
      src: unsplash('1768321913976-be576fce5763'),
      alt: 'Interior construction with exposed pipes and framing',
    },
    {
      src: unsplash('1638890929259-ba364d3a0d1f'),
      alt: 'a room with a bunch of stuff on the floor',
    },
    { src: unsplash('1749571598449-d45fee6f75a6'), alt: 'A kitchen and an open space in a house.' },
    {
      src: unsplash('1768321917129-80494daec0e9'),
      alt: 'Interior room under construction with metal studs.',
    },
    { src: unsplash('1634492485870-a9759c0e3792'), alt: 'a man standing in front of a building' },
    {
      src: unsplash('1726066851939-4053209db248'),
      alt: 'A room with a brick wall and white curtains',
    },
    {
      src: unsplash('1751486403833-f9586b50284c'),
      alt: 'A room with a window, paint cans, and white walls.',
    },
    {
      src: unsplash('1616179283726-e96f7aa16a56'),
      alt: 'man in white t-shirt and black pants standing on ladder',
    },
    { src: unsplash('1632143696848-ed6f1d57d66e'), alt: 'a room with a ladder and a brick wall' },
    {
      src: unsplash('1768321916027-d0f69289227f'),
      alt: 'Interior construction with exposed beams and framing.',
    },
    {
      src: unsplash('1768321902156-9358b5373d0a'),
      alt: 'Interior renovation with construction materials and supplies.',
    },
    {
      src: unsplash('1621754304921-09120a6b81c5'),
      alt: 'man in black t-shirt and black pants standing near blue door',
    },
    { src: unsplash('1707596830247-f4b161ffcff9'), alt: 'a room with a ladder and a chair in it' },
    { src: unsplash('1625600103239-35c023ec52b8'), alt: 'white and brown wooden ceiling' },
    { src: unsplash('1625577817040-a74f7ad0b520'), alt: 'white wooden framed glass window' },
  ],
}
