/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 8 services, 448 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen6: Record<string, { src: string; alt: string }[]> = {
  charpentier: [
    { src: unsplash('1520372561567-bac27b0e5fa1'), alt: 'black hammer on brown wood' },
    {
      src: unsplash('1687089454344-96a1acc71c2d'),
      alt: 'a tall building with lots of windows on the side of it',
    },
    {
      src: unsplash('1687089454022-2a4134852c4c'),
      alt: 'a group of buildings that are next to each other',
    },
    { src: unsplash('1607590556558-36a1955f0358'), alt: 'brown brick wall during daytime' },
    {
      src: unsplash('1649056325447-72874fa7db56'),
      alt: 'a long hallway with wooden beams and windows',
    },
    { src: unsplash('1518217990081-c99d5f404725'), alt: 'brown table outside house' },
    {
      src: unsplash('1569370029941-4a26ad1acaa0'),
      alt: 'brown and black concrete house during daytime',
    },
    {
      src: unsplash('1661246125136-63b22d1e0e62'),
      alt: 'a building with a person sitting in front of it',
    },
    { src: unsplash('1569370029765-33aaab1f4851'), alt: 'brown wooden house' },
    {
      src: unsplash('1700581316314-9e6a809bd656'),
      alt: 'a room that is being constructed with wood',
    },
    {
      src: unsplash('1693639767415-27ff64ce4da2'),
      alt: 'a house under construction with scaffolding around it',
    },
    {
      src: unsplash('1693639435051-d58ac86db299'),
      alt: 'a house under construction with a lot of scaffolding',
    },
    {
      src: unsplash('1693639385915-d7a7ddefe8e1'),
      alt: 'a building under construction with scaffolding and a clock',
    },
    {
      src: unsplash('1693639049292-0f9ec9c287d4'),
      alt: 'a building under construction with lots of scaffolding',
    },
    {
      src: unsplash('1693639056346-49cd9529378a'),
      alt: 'a building under construction with a crane in the background',
    },
    { src: unsplash('1738514770412-f00a7792cbe0'), alt: 'A black and white photo of a building' },
    {
      src: unsplash('1705685850059-407663c3bce1'),
      alt: 'a tall building with lots of windows next to a tall building',
    },
    { src: unsplash('1657453349716-ce4c10318414'), alt: 'a group of people walking down a street' },
    { src: unsplash('1746787533802-9e5b3c631b04'), alt: 'A new house is being built.' },
    {
      src: unsplash('1749882120717-7187fb3838d0'),
      alt: 'A building is under construction with exposed framing.',
    },
    {
      src: unsplash('1746787510909-92956787bb5f'),
      alt: 'A house under construction sits on a vacant lot.',
    },
    {
      src: unsplash('1774867633782-03465eea0760'),
      alt: 'New houses under construction with wooden framing.',
    },
    {
      src: unsplash('1774869174949-9fd84ba6cc0c'),
      alt: 'Several houses under construction with wooden frames.',
    },
    { src: unsplash('1749882120788-0237b2198b5f'), alt: 'A house is under construction.' },
    {
      src: unsplash('1700224619299-aa9736b543bc'),
      alt: 'a row of multi - colored buildings on a cobblestone street',
    },
    { src: unsplash('1576067620610-73cc985d0d20'), alt: 'white wooden glass window frame' },
    {
      src: unsplash('1543617251-b41223299e58'),
      alt: 'two white concrete buildings in closeup photography',
    },
    {
      src: unsplash('1687169512324-e447122cbd4f'),
      alt: 'a house under construction with a pile of dirt in front of it',
    },
    {
      src: unsplash('1687169503260-85f00f122398'),
      alt: 'a house under construction with scaffolding on the roof',
    },
    {
      src: unsplash('1722021427623-f5a13484ee73'),
      alt: 'A couple of buildings that are next to each other',
    },
    {
      src: unsplash('1693765411770-e8325f743d8f'),
      alt: 'a wooden bench sitting next to a wooden fence',
    },
    {
      src: unsplash('1775481929781-d1ea83579ed8'),
      alt: 'Wooden roof beams forming triangular patterns',
    },
    {
      src: unsplash('1761642119730-c871b492da01'),
      alt: 'Interior view of wooden structure with exposed beams above beams',
    },
    { src: unsplash('1587109525955-6a1b0dc9922d'), alt: 'grayscale photo of wooden ceiling' },
    {
      src: unsplash('1775547081703-1472317fe554'),
      alt: 'Modern cabin with large windows surrounded by trees',
    },
    {
      src: unsplash('1706871005986-f9edb5bc8295'),
      alt: 'a building that has a very large v on the side of it',
    },
    { src: unsplash('1666217356183-b0ba4dfe8810'), alt: 'a wooden building with a blue sky' },
    {
      src: unsplash('1764863713822-e6e01fd53326'),
      alt: 'Abstract geometric pattern of wooden beams and ceiling',
    },
    {
      src: unsplash('1771700497137-4b46dc982416'),
      alt: 'Wooden ceiling with a geometric star pattern',
    },
    {
      src: unsplash('1621703730950-994ffa5e9544'),
      alt: 'brown wooden ceiling with white ceiling lamp',
    },
    {
      src: unsplash('1570376185710-e6c770b74400'),
      alt: 'a close up of a wooden wall made of boards',
    },
    {
      src: unsplash('1761380693275-20e7cb7c95d5'),
      alt: 'Wooden arched ceiling with a central skylight',
    },
    {
      src: unsplash('1707256787750-e76d145c6dac'),
      alt: 'a chandelier hanging from the ceiling of a building',
    },
    { src: unsplash('1572533632166-d79f16bb3db6'), alt: 'brown concrete stairs' },
    {
      src: unsplash('1587937512179-735336f3ca24'),
      alt: 'brown wooden frame with blue and white striped textile',
    },
    { src: unsplash('1603937917500-231197cd060f'), alt: 'white and brown concrete building' },
    {
      src: unsplash('1772920908982-7c6e630f668b'),
      alt: 'Wooden roof beams against a clear blue sky',
    },
    {
      src: unsplash('1760856965762-3a6151df4342'),
      alt: 'Geometric wooden beams against a cloudy sky',
    },
    {
      src: unsplash('1767279141109-e63ff1e1e3e9'),
      alt: 'Intricate wooden ceiling with skylights showing blue sky',
    },
    {
      src: unsplash('1740176346532-2cdf49cecd70'),
      alt: 'A bathroom sign on a wooden wall with a sky background',
    },
    {
      src: unsplash('1740176346543-9db8cb02a240'),
      alt: 'A wooden building with a sign on the side of it',
    },
    {
      src: unsplash('1773414485958-10e1a4ca9a3d'),
      alt: 'Old weathered barn with a rusty, damaged roof.',
    },
    {
      src: unsplash('1613082364903-9ff4734f5dd1'),
      alt: 'brown wooden house on snow covered ground during daytime',
    },
    {
      src: unsplash('1763529321434-eaba722365e1'),
      alt: 'Traditional japanese temple roof with trees in foreground',
    },
    {
      src: unsplash('1673645652984-1a1a414db270'),
      alt: 'a close up of a roof with moss growing on it',
    },
    {
      src: unsplash('1759967583761-a2709f29be6f'),
      alt: 'Dilapidated wooden barn with overgrown vegetation',
    },
    {
      src: unsplash('1760712294257-7d078e3f3939'),
      alt: 'Old rusty farm structure with metal roof',
    },
    { src: unsplash('1766232590203-f474d0e3ddae'), alt: 'Wooden building with branches on roof' },
    {
      src: unsplash('1763067112540-dbc077cf9302'),
      alt: 'Old abandoned farm buildings with silo under clear sky',
    },
    { src: unsplash('1570376186239-7de65bf65905'), alt: 'brown wooden fence' },
  ],
  'isolation-thermique': [
    {
      src: unsplash('1751486289950-5c4898a4c773'),
      alt: 'Pipes and equipment are installed on a wall.',
    },
    {
      src: unsplash('1767514536631-b8a259fbb8bf'),
      alt: 'Exposed electrical wires in a textured wall opening',
    },
    {
      src: unsplash('1768321914149-5a6428ec2f82'),
      alt: 'Interior construction with metal framing and drywall panels',
    },
    {
      src: unsplash('1607400201889-565b1ee75f8e'),
      alt: 'person in blue pants sitting on brown wooden floor',
    },
    {
      src: unsplash('1753363562638-398f75158ea9'),
      alt: 'Inside of an attic with insulation and wood beams.',
    },
    {
      src: unsplash('1753363563295-bd0314e2a802'),
      alt: 'Insulated attic space with wooden beams and skylights.',
    },
    {
      src: unsplash('1753363562647-6a5f6296dedc'),
      alt: 'An attic with insulation and wooden beams.',
    },
    {
      src: unsplash('1625577816396-fbf677c54cee'),
      alt: 'blue and white bicycle near brown wooden wall',
    },
    {
      src: unsplash('1753460133429-40a7e4610720'),
      alt: 'An attic space is being used for storage.',
    },
    {
      src: unsplash('1591684080176-bb2b73f9ec68'),
      alt: 'man in green crew neck t-shirt holding smoking pipe',
    },
    {
      src: unsplash('1753460133435-3b294c9dda5e'),
      alt: 'Attic interior with insulation and a skylight.',
    },
    {
      src: unsplash('1753460133510-08edcb70d987'),
      alt: 'An attic with some stored items is pictured.',
    },
    {
      src: unsplash('1768321917437-1f1f6ae2ad28'),
      alt: 'Wooden wall section with spray foam insulation.',
    },
    {
      src: unsplash('1753717202579-9c6ac3592b62'),
      alt: 'An attic space with insulation and wooden beams.',
    },
    {
      src: unsplash('1753717202685-47704db818b9'),
      alt: 'An unfinished attic space with wooden support beams.',
    },
    { src: unsplash('1625577816955-4e2be76d1549'), alt: 'brown and white floral window curtain' },
    {
      src: unsplash('1752852381837-ce679ffdab31'),
      alt: 'Cluttered basement space with various items and boxes.',
    },
    { src: unsplash('1625577815636-d7a61b583799'), alt: 'red and white wooden door' },
    {
      src: unsplash('1753460133435-bf41927f77f7'),
      alt: 'Attic with insulation, beams, and storage.',
    },
    { src: unsplash('1657195721935-e73e545a2aae'), alt: 'a close-up of a roof' },
    {
      src: unsplash('1753460133418-e25fda007187'),
      alt: 'A dusty attic with insulation and wooden beams.',
    },
    { src: unsplash('1632214531568-02d981f57188'), alt: 'a room that has a skylight in it' },
    {
      src: unsplash('1751028582741-a534c41902e7'),
      alt: 'An attic filled with various stored items.',
    },
    {
      src: unsplash('1635171495000-72de0454f1cb'),
      alt: 'a close up of a building with metal pipes',
    },
    { src: unsplash('1683741991313-d0eb7e79adc9'), alt: 'a man on a ladder working on a jeep' },
    {
      src: unsplash('1711375201123-61eddb7804d7'),
      alt: 'a man working on a construction project in a cave',
    },
    {
      src: unsplash('1768321910174-6f55899299a2'),
      alt: 'Room under construction with exposed insulation and windows',
    },
    {
      src: unsplash('1750603244861-015017c77400'),
      alt: 'Ceiling construction is underway in the building.',
    },
    {
      src: unsplash('1753460133438-7fea0ff39b7c'),
      alt: 'An attic with insulation and skylights is shown.',
    },
    {
      src: unsplash('1695509098533-e4b1ba1479f9'),
      alt: 'a green building under construction with a blue sky in the background',
    },
    {
      src: unsplash('1701538517775-f94a4a6805ce'),
      alt: 'a close up of a rock formation with grass growing on top of it',
    },
    {
      src: unsplash('1589572394490-771aa22db633'),
      alt: 'white concrete wall under blue sky during daytime',
    },
    {
      src: unsplash('1759915554664-91baceca51e2'),
      alt: 'Yellow and pink painted brick wall texture',
    },
    {
      src: unsplash('1646066458890-45f713b9ab01'),
      alt: 'a tree with no leaves in front of a building',
    },
    {
      src: unsplash('1639804658358-daa1b83738f1'),
      alt: 'a room with a blue door and a white wall',
    },
    { src: unsplash('1658917608613-09b31cfda49f'), alt: 'a white column against a red wall' },
    { src: unsplash('1558361450-d39f20248588'), alt: 'a close up of a wall with a clock on it' },
    { src: unsplash('1584767159346-53684fcedfe8'), alt: 'brown concrete blocks with kanji text' },
    { src: unsplash('1567404469884-75c0620d0912'), alt: 'brown wall bricks' },
    {
      src: unsplash('1678459781158-f7e20db550d4'),
      alt: 'a close up of a brick wall with a window',
    },
    { src: unsplash('1660207237316-08a6ee93687a'), alt: 'a brick wall with a hole in it' },
    { src: unsplash('1608283832972-7402dc32545e'), alt: 'brown brick building during daytime' },
    {
      src: unsplash('1682937546456-fea3237ba8aa'),
      alt: 'a close up of a blue building with a brown door',
    },
    { src: unsplash('1669729414773-0dd7473fbdd3'), alt: 'a door in a room' },
    {
      src: unsplash('1758077222093-618ad9828d16'),
      alt: 'Wooden structure and tree on textured ground',
    },
    {
      src: unsplash('1761682751238-a9174874aeee'),
      alt: 'Rough concrete wall next to weathered red brick wall',
    },
    { src: unsplash('1720055702154-6345e3799386'), alt: 'A close up of a green and white line' },
    {
      src: unsplash('1761682751897-4c4fb96a6a85'),
      alt: 'Two walls, one brick, one concrete, with sky visible',
    },
    { src: unsplash('1613171233547-a9098bbef75b'), alt: 'white and brown concrete wall' },
    { src: unsplash('1685837491331-4270c81155fb'), alt: 'a cement wall with a hole in the middle' },
    {
      src: unsplash('1736624155621-a8fd88131510'),
      alt: 'A black and white photo of a brick building',
    },
    {
      src: unsplash('1580072140977-a66c2b23769b'),
      alt: 'white concrete wall under blue sky during daytime',
    },
    {
      src: unsplash('1746641017949-efc1ba790e73'),
      alt: 'Concrete blocks form an intricate geometric pattern.',
    },
    {
      src: unsplash('1768149524780-a6c7337cf619'),
      alt: 'A weathered white wall with faint lettering.',
    },
  ],
  platrier: [
    { src: unsplash('1660029763088-d8c1dff1a5e3'), alt: 'a window in a building' },
    {
      src: unsplash('1727200446200-c9ee44dc6bb2'),
      alt: 'A close up of a cement surface with small cracks',
    },
    { src: unsplash('1645865163049-bb8f076cbd38'), alt: 'a black and white photo of some water' },
    {
      src: unsplash('1766961980272-921bba4240bc'),
      alt: 'Construction workers plastering a wall on scaffolding.',
    },
    { src: unsplash('1577200080776-fe8b6c5559dc'), alt: 'a close up of a white stucco wall' },
    {
      src: unsplash('1645865163180-aba3a050feeb'),
      alt: 'a black and white photo of a textured surface',
    },
    {
      src: unsplash('1645865163176-cbc0459034c9'),
      alt: 'a close up of a red wall with a clock on it',
    },
    {
      src: unsplash('1628615613709-9642d17dbb54'),
      alt: 'brown wooden sticks on white ceramic plate',
    },
    {
      src: unsplash('1629195354259-fe4ff202c8e3'),
      alt: 'man in blue shirt and brown hat holding gray metal pipe',
    },
    { src: unsplash('1517421937867-725f85920dca'), alt: 'brown brick and blue wall paint' },
    {
      src: unsplash('1700502335822-d4856cca490a'),
      alt: 'a man standing next to a building with a hammer',
    },
    { src: unsplash('1738503145851-dff68385f9fe'), alt: 'A close up of a wall with peeling paint' },
    {
      src: unsplash('1675191863404-e1db618d6655'),
      alt: 'a man painting a wall with a paint roller',
    },
    { src: unsplash('1693591526237-14b58b9b4337'), alt: 'a wall that has some paint on it' },
    { src: unsplash('1710381608043-9cdc0197e409'), alt: 'a wall with peeling paint on it' },
    {
      src: unsplash('1738504049563-8a00347e63ef'),
      alt: 'A red fire hydrant sitting on the side of a cement wall',
    },
    {
      src: unsplash('1693591526021-d20fff15b500'),
      alt: 'a red fire hydrant sitting on the side of a cement wall',
    },
    { src: unsplash('1575147270841-b73b888b840c'), alt: 'brown brick wall' },
    {
      src: unsplash('1760073643328-88547b90611a'),
      alt: 'Rough textured wall with exposed bricks below',
    },
    { src: unsplash('1704052950803-959df3a5e99c'), alt: 'a brick wall with a light on it' },
    { src: unsplash('1758789646105-a9ca943d00ab'), alt: 'Peeling blue paint on a textured wall' },
    { src: unsplash('1605104466671-ac563bb438c2'), alt: 'white and gray concrete floor' },
    { src: unsplash('1544558074-d7356aeaf6f0'), alt: 'brown and white stone fragment' },
    { src: unsplash('1657309438199-45603b1d5ebe'), alt: 'a bird in a birdhouse' },
    { src: unsplash('1526399999529-e812236ab3ba'), alt: 'brown concrete wall' },
    { src: unsplash('1564741492473-a1d3f1e1a6ca'), alt: 'brown brick wall' },
    { src: unsplash('1657280952521-a21d42f59149'), alt: 'a close up of a grey surface' },
    {
      src: unsplash('1738503210080-189e3d9d13d3'),
      alt: 'A white wall with a blue and green painting on it',
    },
    { src: unsplash('1591712457013-36f84152bf58'), alt: 'brown and black round wall art' },
    { src: unsplash('1660207237316-08a6ee93687a'), alt: 'a brick wall with a hole in it' },
    {
      src: unsplash('1765147238231-443434e1800e'),
      alt: 'A dimly lit room with a figure on the floor.',
    },
    {
      src: unsplash('1768321917806-b4b6fbbef837'),
      alt: 'Interior room under construction with exposed framing and ceiling.',
    },
    {
      src: unsplash('1768321914149-5a6428ec2f82'),
      alt: 'Interior construction with metal framing and drywall panels',
    },
    { src: unsplash('1718816281207-3b253cff549a'), alt: 'A room that has some paint on the floor' },
    {
      src: unsplash('1768321902290-54497eeb9cf6'),
      alt: 'Interior room undergoing renovation with exposed walls and window.',
    },
    {
      src: unsplash('1768321910174-6f55899299a2'),
      alt: 'Room under construction with exposed insulation and windows',
    },
    {
      src: unsplash('1749571598487-5e7408886d66'),
      alt: 'An empty, spacious room with several areas.',
    },
    {
      src: unsplash('1695886517962-cafc014947de'),
      alt: 'a wall that has some wires attached to it',
    },
    {
      src: unsplash('1774977863604-59f4e6d37a90'),
      alt: 'Man on ladder working on ceiling access panel.',
    },
    {
      src: unsplash('1608109704808-62aadbc33a7d'),
      alt: 'man in red shirt and blue denim jeans standing on white wooden door',
    },
    {
      src: unsplash('1733431772808-82d878e59000'),
      alt: 'A large room with a lot of white paint on the walls',
    },
    { src: unsplash('1638890928047-10a4eb9d4744'), alt: 'a room with a brick wall and a window' },
    {
      src: unsplash('1733431774078-692252a6605e'),
      alt: 'A large room with a lot of paint on the walls',
    },
    {
      src: unsplash('1632143696577-809bae4b10f4'),
      alt: 'a room with a window and a white ceiling',
    },
    {
      src: unsplash('1768321913976-be576fce5763'),
      alt: 'Interior construction with exposed pipes and framing',
    },
    {
      src: unsplash('1638890929259-ba364d3a0d1f'),
      alt: 'a room with a bunch of stuff on the floor',
    },
    { src: unsplash('1749571598449-d45fee6f75a6'), alt: 'A kitchen and an open space in a house.' },
    {
      src: unsplash('1768321917129-80494daec0e9'),
      alt: 'Interior room under construction with metal studs.',
    },
    { src: unsplash('1634492485870-a9759c0e3792'), alt: 'a man standing in front of a building' },
    {
      src: unsplash('1726066851939-4053209db248'),
      alt: 'A room with a brick wall and white curtains',
    },
    {
      src: unsplash('1751486403833-f9586b50284c'),
      alt: 'A room with a window, paint cans, and white walls.',
    },
    {
      src: unsplash('1616179283726-e96f7aa16a56'),
      alt: 'man in white t-shirt and black pants standing on ladder',
    },
    { src: unsplash('1632143696848-ed6f1d57d66e'), alt: 'a room with a ladder and a brick wall' },
    {
      src: unsplash('1768321916027-d0f69289227f'),
      alt: 'Interior construction with exposed beams and framing.',
    },
    {
      src: unsplash('1768321902156-9358b5373d0a'),
      alt: 'Interior renovation with construction materials and supplies.',
    },
    {
      src: unsplash('1621754304921-09120a6b81c5'),
      alt: 'man in black t-shirt and black pants standing near blue door',
    },
    { src: unsplash('1707596830247-f4b161ffcff9'), alt: 'a room with a ladder and a chair in it' },
    { src: unsplash('1625600103239-35c023ec52b8'), alt: 'white and brown wooden ceiling' },
    { src: unsplash('1625577817040-a74f7ad0b520'), alt: 'white wooden framed glass window' },
  ],
}
