/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 8 services, 441 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen7: Record<string, { src: string; alt: string }[]> = {
  'borne-recharge': [
    {
      src: unsplash('1593941707874-ef25b8b4a92b'),
      alt: 'black and white usb cable plugged in black device',
    },
    {
      src: unsplash('1671785253964-bdb43087ed99'),
      alt: 'a white car plugged in to a charging station',
    },
    {
      src: unsplash('1600490819528-42405785433a'),
      alt: 'black car parked beside brown brick wall',
    },
    {
      src: unsplash('1703860271509-b50f5679f2a0'),
      alt: 'an electric car plugged in to a charging station',
    },
    { src: unsplash('1607197109166-3ab4ee4b468f'), alt: 'black and gray automatic motor scooter' },
    { src: unsplash('1616361715039-11dde2199a21'), alt: 'white and black corded device' },
    {
      src: unsplash('1707341597123-c53bbb7e7f93'),
      alt: 'an electric car plugged into a charging station',
    },
    { src: unsplash('1593941707882-a5bba14938c7'), alt: 'white and blue plastic tool' },
    { src: unsplash('1671785120538-c24cbe823ccc'), alt: 'a woman standing next to a blue car' },
    {
      src: unsplash('1635451048957-3beb7175f57f'),
      alt: 'a car plugged into a charging station on a city street',
    },
    {
      src: unsplash('1650452233063-8f308616b729'),
      alt: 'a group of gas pumps sitting next to each other',
    },
    { src: unsplash('1703860271482-16fd57dc35ca'), alt: 'a woman standing next to a white car' },
    {
      src: unsplash('1619913387719-a43ee8859d9c'),
      alt: 'black metal stand on gray concrete road during daytime',
    },
    {
      src: unsplash('1676539432110-78f836970ac4'),
      alt: 'a red scooter parked on the side of a road',
    },
    { src: unsplash('1605152276919-a5fd954f2be5'), alt: 'red and blue labeled box' },
    { src: unsplash('1692052463269-c7b2b31e016f'), alt: 'a man standing next to a blue car' },
    {
      src: unsplash('1768310465625-5824a01fff4c'),
      alt: 'Tesla electric car charging stations on a sunny day.',
    },
    { src: unsplash('1692052664566-477579a08e8c'), alt: 'a car plugged in to a wall charger' },
    { src: unsplash('1726471814092-4a8f4e71445d'), alt: 'A woman washing a car in a driveway' },
    {
      src: unsplash('1726471845977-9ebf30dc6822'),
      alt: 'A blue electric car plugged in to a garage',
    },
    { src: unsplash('1726471819205-faf7d51590bd'), alt: 'A woman is standing next to a car' },
    {
      src: unsplash('1726471766722-4004cab9bbc6'),
      alt: 'A car parked in front of a brick building',
    },
    {
      src: unsplash('1692052626528-cb97a934a63b'),
      alt: 'a man pumping gas into his car at a gas station',
    },
    { src: unsplash('1726471712667-3d310670e786'), alt: 'A car parked in front of a garage door' },
    {
      src: unsplash('1726471751243-adcc6e586479'),
      alt: 'A woman holding a cell phone in front of a car',
    },
    {
      src: unsplash('1699253801373-dac49c05066f'),
      alt: 'a yellow car is plugged into a charging station',
    },
    { src: unsplash('1669349412975-a9dd0d2292ee'), alt: 'a red and white gas pump' },
    { src: unsplash('1726471825079-c480955d8b16'), alt: 'A car is parked in front of a house' },
    { src: unsplash('1652904863459-54e8b5a65b25'), alt: "a close up of a car's fuel nozzle" },
    { src: unsplash('1663579747243-d639fc94e28d'), alt: 'a person using a gas pump' },
    {
      src: unsplash('1704475386627-dcfcd97ed51a'),
      alt: 'a woman is using a power washer on a brick wall',
    },
    {
      src: unsplash('1704475336842-0ab3798abf0e'),
      alt: 'a person pumping gas into a car at a gas station',
    },
    { src: unsplash('1631347826177-de288776ed3b'), alt: 'black car on parking lot during daytime' },
    { src: unsplash('1615901555268-839b7a1ede54'), alt: 'black car in tilt shift lens' },
    {
      src: unsplash('1692061157268-b128a8f37d6d'),
      alt: 'an electric car being charged at a charging station',
    },
    { src: unsplash('1646753020826-c518face72ad'), alt: 'a woman is pumping gas into her car' },
    { src: unsplash('1651688730796-151972ba8f87'), alt: 'a car with a charging cable' },
    {
      src: unsplash('1646753005675-bb29b53507f5'),
      alt: 'a person is charging an electric car with a charger',
    },
    {
      src: unsplash('1607171028974-319ba56cb013'),
      alt: 'red and black car on road during daytime',
    },
    {
      src: unsplash('1704475289650-6ab9fc4a0a5b'),
      alt: 'a white car parked in front of a wooden wall',
    },
    {
      src: unsplash('1751553512991-7ae218946be9'),
      alt: 'An electric car is charging at a station.',
    },
    { src: unsplash('1645709448380-6e4002beb900'), alt: 'a white car is at a gas pump' },
    { src: unsplash('1704474876770-742b0dfc2385'), alt: 'a man standing next to a white car' },
    {
      src: unsplash('1704474971843-23b282bb9321'),
      alt: 'a man standing next to a white toilet in front of a wooden wall',
    },
    {
      src: unsplash('1646752995273-85e432a354b3'),
      alt: 'a woman is opening the door of her house',
    },
    {
      src: unsplash('1645709495180-e340b2fc551f'),
      alt: 'a close up of a red and white tesla charging station',
    },
    {
      src: unsplash('1645709369972-93df2893c163'),
      alt: 'a close up of a white and red tesla gas station',
    },
    { src: unsplash('1645709470138-48a240c494bc'), alt: 'a close up of the hood of a car' },
    { src: unsplash('1704475067471-9d73f44bb3bb'), alt: 'a man standing next to a parked car' },
    {
      src: unsplash('1645709364557-0fefce7413e8'),
      alt: 'a white car parked next to a red and white pole',
    },
    {
      src: unsplash('1645709453620-2c9bfc5ac66f'),
      alt: 'an electric car plugged into a charging station',
    },
    { src: unsplash('1645709474344-57920e1b64b2'), alt: 'a close up of a white and red device' },
    {
      src: unsplash('1645709420918-32435f970052'),
      alt: 'a close up of a white car with a red stripe',
    },
    {
      src: unsplash('1646752985417-4ce779d7d9c2'),
      alt: 'a brick wall with a black light switch on it',
    },
    {
      src: unsplash('1740158404435-6ca48addcb6c'),
      alt: 'A man pumping gas into his car at a gas station',
    },
  ],
  demenageur: [
    {
      src: unsplash('1581573833610-487d80de9aab'),
      alt: 'man in blue t-shirt and blue denim shorts holding black dslr camera',
    },
    {
      src: unsplash('1614359835514-92f8ba196357'),
      alt: '2 boys in red shirt sitting on yellow metal bar',
    },
    {
      src: unsplash('1742858492775-8f58f645aa12'),
      alt: 'A delivery van with its back doors open.',
    },
    {
      src: unsplash('1594051723956-b14e836bdeb5'),
      alt: 'woman in blue dress holding brown cardboard box',
    },
    { src: unsplash('1551009175-32ecf04344bb'), alt: 'photo of city building during winter' },
    {
      src: unsplash('1601221016889-797d61aa4809'),
      alt: 'person in black pants and black boots standing beside blue and white wooden table during daytime',
    },
    { src: unsplash('1501700493788-fa1a4fc9fe62'), alt: 'truck on highway during daytime' },
    { src: unsplash('1646681545007-ead839a03a70'), alt: 'a yellow bus is going over a bridge' },
    {
      src: unsplash('1739813914275-a0952d33477b'),
      alt: 'A red van is parked on the side of the road',
    },
    { src: unsplash('1651331683937-1252a069e25d'), alt: 'buses parked at a bus stop' },
    {
      src: unsplash('1725477830938-c2df7532ef75'),
      alt: 'A woman sitting on the floor in a dark room',
    },
    {
      src: unsplash('1695393435939-8dbdea2c2c73'),
      alt: 'a group of people riding on the back of a vehicle',
    },
    { src: unsplash('1701467401174-0b4b79777b27'), alt: 'a train on a train track in a city' },
    { src: unsplash('1664435784961-405d28b4b2c2'), alt: 'a tractor pulling a trailer' },
    {
      src: unsplash('1766040923580-16ad32fae8b4'),
      alt: 'A large pile of brown cardboard boxes with blue tape.',
    },
    {
      src: unsplash('1766524790783-7915025f453a'),
      alt: 'A delivery truck with a panda logo and japanese text.',
    },
    { src: unsplash('1562883779-0a4c28a19324'), alt: 'people in multicolored building' },
    { src: unsplash('1662570070404-5d74c91ea4af'), alt: 'a large white monument' },
    {
      src: unsplash('1690995294352-7d9da8665942'),
      alt: 'a red crane is lifting a black object into the air',
    },
    {
      src: unsplash('1768467486058-5f2d31bcc8af'),
      alt: 'Yellow loader and trucks at a construction site',
    },
    { src: unsplash('1662568804805-ef2f2a5c2073'), alt: 'a group of wind turbines' },
    { src: unsplash('1662570070116-35da50220f01'), alt: 'a truck parked in front of windmills' },
    { src: unsplash('1662570069543-dfd1ccdbc610'), alt: 'a motorcycle parked on a gravel road' },
    { src: unsplash('1662570070648-62a4ec8a7b8a'), alt: 'a wind turbine under a blue sky' },
    {
      src: unsplash('1662568804760-e92aed4c7f6f'),
      alt: 'a group of wind turbines with Albany Wind Farm in the background',
    },
    {
      src: unsplash('1772430364901-4c9c15388c40'),
      alt: 'Green excavator working on a dry grassy hill.',
    },
    {
      src: unsplash('1614366324821-cfa7713a5163'),
      alt: 'orange and black heavy equipment on brown sand during daytime',
    },
    {
      src: unsplash('1764639567780-ac96b438171c'),
      alt: 'A bulldozer clearing brush in a wooded area',
    },
    {
      src: unsplash('1690995293820-de977158b460'),
      alt: 'a large stack of shipping containers sitting next to each other',
    },
    {
      src: unsplash('1775737403018-00ebbffc8df1'),
      alt: 'Two men in uniform push a cart down a sidewalk.',
    },
    {
      src: unsplash('1769972557854-7eae6f95585b'),
      alt: 'Man carrying a mattress down a sidewalk.',
    },
    { src: unsplash('1657049199023-87fb439d47c5'), alt: 'a group of people working on a horse' },
    {
      src: unsplash('1682973441491-6b41b7af1c6f'),
      alt: 'a black and white photo of a man moving a rug',
    },
    {
      src: unsplash('1714647211923-a3881cd1300f'),
      alt: 'a man and a woman standing in a room with moving boxes',
    },
    { src: unsplash('1694715669993-ea0022b470f7'), alt: 'a man is unloading boxes from a van' },
    { src: unsplash('1580451301279-9ffaa7d55b4b'), alt: 'man in blue t-shirt sitting on floor' },
    {
      src: unsplash('1714647211963-fa82bd5b3a7a'),
      alt: 'a man and a woman laying a rug on the floor',
    },
    {
      src: unsplash('1600518464441-9154a4dea21b'),
      alt: 'woman in blue shorts and black boots standing beside yellow and white truck during daytime',
    },
    { src: unsplash('1714647211902-bb711d643a17'), alt: 'a woman moving boxes in a living room' },
    {
      src: unsplash('1704167605116-0cd9f70dbaa0'),
      alt: 'a man in a blue shirt and white hat working on a shelf',
    },
    { src: unsplash('1750835101841-51f2ed4b0062'), alt: 'A man moves chairs on a cart.' },
    {
      src: unsplash('1689465571975-8d24a8b7a163'),
      alt: 'a man sitting on a bench next to a wooden box',
    },
    { src: unsplash('1714647211955-95c3104dc418'), alt: 'a man and a woman laying on a rug' },
    {
      src: unsplash('1581573741536-f0a67af91c7b'),
      alt: 'woman in pink long sleeve shirt and black pants sitting on brown wooden chair',
    },
    {
      src: unsplash('1586335925834-44121c1679c6'),
      alt: 'man in black jacket and pants standing beside white car during daytime',
    },
    {
      src: unsplash('1585541933300-3553dce8475c'),
      alt: 'man in blue denim jeans standing near white wooden table',
    },
    { src: unsplash('1555694746-edc80f35e53d'), alt: 'white padded brown armchair outside' },
    {
      src: unsplash('1530445271960-fdc4bcf1caef'),
      alt: 'empty round green stools beside brown table',
    },
    {
      src: unsplash('1583829249523-5c2bbc4666fa'),
      alt: 'man in red blue and white plaid dress shirt and blue denim jeans standing beside black',
    },
    {
      src: unsplash('1590451710341-6232b7303cbc'),
      alt: 'man in red blue and white plaid dress shirt and blue denim jeans standing beside black',
    },
    {
      src: unsplash('1733141001777-420f37c91e19'),
      alt: 'An old TV sitting on top of a wooden box',
    },
    {
      src: unsplash('1615647415164-cea788a29ba3'),
      alt: 'man in blue denim jacket carrying brown woven basket',
    },
    { src: unsplash('1657862035036-951df0c7b768'), alt: 'a person lifting another man up' },
    {
      src: unsplash('1580451300156-0d083445be56'),
      alt: 'man in blue polo shirt and black pants sitting on couch',
    },
    {
      src: unsplash('1593350074327-fe177b530a62'),
      alt: 'girl in white t-shirt writing on white paper',
    },
    { src: unsplash('1663751879720-33276273d7f7'), alt: 'a person standing next to a boat' },
    {
      src: unsplash('1580709652805-9d44c2b7ad20'),
      alt: 'man in white and black checkered button up shirt and blue denim jeans standing beside white',
    },
  ],
}
