/**
 * Auto-generated by scripts/generate-unsplash-images.mjs
 * 6 services, 341 images
 * NE PAS MODIFIER MANUELLEMENT
 */

function unsplash(id: string, w = 800, h = 500): string {
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`
}

export const serviceImagePool_gen9: Record<string, { src: string; alt: string }[]> = {
  'pompe-a-chaleur': [
    { src: unsplash('1659205212610-b941b3048b68'), alt: 'a bird feeder in a garden' },
    { src: unsplash('1614636935264-1f15247173a5'), alt: 'gray and brown wooden house' },
    {
      src: unsplash('1741062204894-3c5ac5a50c18'),
      alt: 'Cats are lounging on an outdoor air conditioning unit.',
    },
    { src: unsplash('1665309421336-b32607f19aeb'), alt: 'a white and black heater' },
    {
      src: unsplash('1718203862467-c33159fdc504'),
      alt: 'a white air conditioner sitting on top of a brick wall',
    },
    {
      src: unsplash('1710829558360-6f8f5e49fedd'),
      alt: 'a white air conditioner sitting in front of a building',
    },
    { src: unsplash('1665826254141-bfa10685e002'), alt: 'a white box with a vent' },
    {
      src: unsplash('1672918119393-a74a5706f95f'),
      alt: 'an air conditioner sitting on the side of a building',
    },
    {
      src: unsplash('1760243875486-0a362cab9021'),
      alt: 'Corrugated metal wall with overgrown plants and air conditioner.',
    },
    {
      src: unsplash('1700124113583-81aa99ea2aa2'),
      alt: 'a air conditioner sitting on the side of a building',
    },
    {
      src: unsplash('1757219525975-03b5984bc6e8'),
      alt: 'An air conditioning unit mounted on a wall.',
    },
    { src: unsplash('1752336612713-cd5c2f0dac73'), alt: 'A green hose on a deck near a boat.' },
    {
      src: unsplash('1763862729939-89e9b7649aa3'),
      alt: 'Autumn leaves and dry grass by a building',
    },
    {
      src: unsplash('1710829558487-53baf9e26003'),
      alt: 'a white and black air conditioner sitting outside of a building',
    },
    {
      src: unsplash('1773952137490-2bea3f95ed39'),
      alt: 'Multiple air conditioning units mounted on a building.',
    },
    {
      src: unsplash('1709432767122-d3cb5326911a'),
      alt: 'a couple of air conditioners sitting next to each other',
    },
    {
      src: unsplash('1566917064245-1c6bff30dbf1'),
      alt: 'grayscale photography of outdoor AC unit',
    },
    { src: unsplash('1617861648989-76a572012089'), alt: 'white and gray box fan' },
    {
      src: unsplash('1704137420041-09809a170f24'),
      alt: 'a small building with a gas pump next to it',
    },
    {
      src: unsplash('1775508131358-6cfae3729de4'),
      alt: 'White building with air conditioning units on rooftop',
    },
    { src: unsplash('1518795572197-5f93a03757bf'), alt: 'two mannequins inside building' },
    {
      src: unsplash('1724488751821-1415f5cf4960'),
      alt: 'A air conditioner sitting outside of a building',
    },
    {
      src: unsplash('1746077688741-049e1d910411'),
      alt: 'An air conditioner sits behind overgrown bushes.',
    },
    {
      src: unsplash('1722131646940-b821a6cc6252'),
      alt: 'A air conditioner mounted to the side of a building',
    },
    {
      src: unsplash('1766201926837-6b8cb0383de8'),
      alt: 'Air conditioner unit below large windows with green curtains',
    },
    {
      src: unsplash('1694675879520-ff32d348fb7f'),
      alt: 'a couple of air conditioners sitting on the side of a building',
    },
    {
      src: unsplash('1679303777007-c6c4522beb02'),
      alt: 'a wall mounted air conditioner mounted on the side of a building',
    },
    {
      src: unsplash('1635456395917-e3f8eb34fa78'),
      alt: 'an old brick building with a metal box in front of it',
    },
    {
      src: unsplash('1635604866833-70844856de75'),
      alt: 'a building with a bunch of pipes on the side of it',
    },
    { src: unsplash('1590416612506-ad6666c1065e'), alt: 'white and black basketball hoop' },
    { src: unsplash('1667983453881-4992fe86ab1b'), alt: 'a wall with a few doors' },
    {
      src: unsplash('1615625745497-0edd438803ef'),
      alt: 'white concrete building under blue sky during daytime',
    },
    { src: unsplash('1667876941443-f359eb8eae54'), alt: 'graphical user interface' },
    {
      src: unsplash('1671671584537-5da98a2a884f'),
      alt: 'four air conditioners sitting on top of a snow covered ground',
    },
    {
      src: unsplash('1762500824903-0f96b202e8f4'),
      alt: 'Woman and dog relax by large window with robot vacuum.',
    },
    { src: unsplash('1573573226985-72f731413b23'), alt: 'white AC condenser' },
    {
      src: unsplash('1712831328300-300d8602aa71'),
      alt: 'a black and white building with a sky background',
    },
    {
      src: unsplash('1630169839507-fedc46615129'),
      alt: 'white and gray window type air conditioner',
    },
    {
      src: unsplash('1699974783477-74e9ab7546a4'),
      alt: 'a row of air conditioners sitting in front of a building',
    },
    { src: unsplash('1744478037987-538f5087fe94'), alt: 'Two air conditioners on a white wall.' },
    { src: unsplash('1665670198221-f83f00860533'), alt: 'a group of white boxes in a bushy area' },
  ],
  ramoneur: [
    {
      src: unsplash('1594560225349-7d4541d32e87'),
      alt: 'man in black jacket sitting on roof during daytime',
    },
    { src: unsplash('1741120470594-7c1f8456f1e3'), alt: 'A brick chimney covered in fresh snow.' },
    { src: unsplash('1712583832063-1015cfccec2b'), alt: 'a bird is sitting on top of a post' },
    {
      src: unsplash('1649061740049-6061b6606710'),
      alt: 'smoke coming out of a chimney of a building',
    },
    {
      src: unsplash('1551906992-e2ce8f1e6b13'),
      alt: 'a chimney on top of a building with a sky background',
    },
    {
      src: unsplash('1742466997231-5056adc35ec0'),
      alt: 'Black chimneys on a roof against the sky.',
    },
    {
      src: unsplash('1610951062410-5436f36c51a0'),
      alt: 'brown concrete building under blue sky during daytime',
    },
    {
      src: unsplash('1767731415425-178001bad7d1'),
      alt: 'Smoke rising from a rustic chimney on a brick building.',
    },
    { src: unsplash('1707940521389-12d5c06ad8eb'), alt: 'a brick chimney on top of a building' },
    { src: unsplash('1667165564160-5a48f883ebdc'), alt: 'a stone roof with a chimney' },
    { src: unsplash('1655987639288-2ab1b26df093'), alt: 'a brick building with a chimney' },
    { src: unsplash('1718909704556-0fe9477637d9'), alt: 'A brick tower on top of a building' },
    { src: unsplash('1564865926101-d50c785ff163'), alt: 'brown and gray roof shingles' },
    {
      src: unsplash('1681463489647-ce324c6369b7'),
      alt: 'a brick building with a clock on the top of it',
    },
    {
      src: unsplash('1596775903078-9c99db812ce8'),
      alt: 'brown brick building under white clouds and blue sky during daytime',
    },
    {
      src: unsplash('1766777323124-4ae5c741c57f'),
      alt: 'Rooftops and chimneys under a cloudy sky.',
    },
    {
      src: unsplash('1684962654190-b1f1cc7095c9'),
      alt: 'a brick chimney with a blue sky in the background',
    },
    {
      src: unsplash('1650563990715-a1543dc1455f'),
      alt: 'a chimney on top of a roof with a blue sky in the background',
    },
    {
      src: unsplash('1759746897276-f91499015bb5'),
      alt: 'Three brick chimneys against a clear blue sky.',
    },
    {
      src: unsplash('1756376964483-0fc6438bbf68'),
      alt: 'Brick chimney on a rooftop under blue sky',
    },
    {
      src: unsplash('1584501310127-d8186c6be40f'),
      alt: 'brown concrete building near green trees under blue sky during daytime',
    },
    {
      src: unsplash('1767464952679-47c5949cb9f9'),
      alt: 'Silhouetted chimneys against a cloudy sky',
    },
    {
      src: unsplash('1723271938870-005c6a0014e5'),
      alt: 'A black and white photo of a building with smoke coming out of it',
    },
    {
      src: unsplash('1632925467885-a80363fbdf89'),
      alt: 'an old building with a weather vane on top of it',
    },
    {
      src: unsplash('1650308206340-bcd399e17922'),
      alt: 'a tall brick building with a bird on top of it',
    },
    { src: unsplash('1568444395817-b9dd2cd8372d'), alt: 'silhouette of bird perching on building' },
    {
      src: unsplash('1602921308447-17cf2b34cc65'),
      alt: 'brown brick building under blue sky during daytime',
    },
    {
      src: unsplash('1678043006492-371e8b80da45'),
      alt: 'a couple of towers that are on top of a building',
    },
    {
      src: unsplash('1674728108460-fe36b166d2f4'),
      alt: 'smoke coming out of a chimney on top of a building',
    },
    {
      src: unsplash('1603045866603-fc705869506f'),
      alt: 'white and brown concrete building under white clouds during daytime',
    },
    {
      src: unsplash('1771371428960-35a50c2d4e7c'),
      alt: 'Modern living room with fireplace and large television',
    },
    {
      src: unsplash('1642992608454-9f5070359ecd'),
      alt: 'a room with a fire place in the middle of it',
    },
    { src: unsplash('1652517210558-954882f97dca'), alt: 'a white door in a room' },
    {
      src: unsplash('1605127604869-a3256ca52056'),
      alt: 'brown and white lighted candles on black wooden table',
    },
    { src: unsplash('1652517209164-3a6771733570'), alt: 'a mirror with a cup on it' },
    {
      src: unsplash('1544811553-dbc217843074'),
      alt: 'a christmas tree with a merry christmas sign on it',
    },
    {
      src: unsplash('1762342911502-506a2915e38d'),
      alt: 'Modern living room with white sectional sofa and pink pillows.',
    },
    { src: unsplash('1554246248-8e077b50f22e'), alt: 'fireplace on fire' },
    { src: unsplash('1483217067170-e62094708cd8'), alt: 'firewood lot near fireplace' },
    { src: unsplash('1554332208-9dfebcc48334'), alt: 'fire wood on fireplace' },
    { src: unsplash('1550514704-ccce64a6d868'), alt: 'lighted fireplace' },
    { src: unsplash('1518267535284-967f6f2a6ac1'), alt: 'opened electric fireplace' },
    { src: unsplash('1646940930132-55abcc4ec001'), alt: 'a person opening a door to a fire place' },
    {
      src: unsplash('1609167782177-41d3c0f4becf'),
      alt: 'brown brick fireplace with brown brick wall',
    },
    { src: unsplash('1543393470-b2c833b98dce'), alt: 'fire burning on fireplace' },
    { src: unsplash('1626108436400-cf6010627eab'), alt: 'person holding black metal tool' },
    { src: unsplash('1520414920679-92381bf112f0'), alt: 'long exposure photography of fireplace' },
    { src: unsplash('1556760692-4a3fde615bb9'), alt: 'potted plant beside fireplace' },
    {
      src: unsplash('1610898917224-4586cbd7691d'),
      alt: 'person in blue denim jacket holding fire',
    },
    {
      src: unsplash('1718324864477-0a7811b309b6'),
      alt: 'a person opening a door to a wood burning stove',
    },
    { src: unsplash('1580821074409-1aeb733ee62f'), alt: 'fire on brown wooden table' },
    {
      src: unsplash('1706061717899-f0d2cd61e2bb'),
      alt: 'a fire burning in a fireplace with rocks and logs',
    },
    {
      src: unsplash('1717497043515-9e062f65ca3f'),
      alt: 'a living room with a fire in the fireplace',
    },
    {
      src: unsplash('1637765680614-535316c3419a'),
      alt: 'a close up of a window with a zebra pattern',
    },
    { src: unsplash('1712084247928-1c56f1c1235e'), alt: 'a close up of a grill with a fire in it' },
    {
      src: unsplash('1640455453903-2309f9096612'),
      alt: 'a fire burning in a fireplace with rocks and logs',
    },
    {
      src: unsplash('1462392587151-db92c7ca52c2'),
      alt: 'man in white and black checkered dress shirt sitting in front of bonfire',
    },
    { src: unsplash('1533495760816-6d2b820c1cf9'), alt: 'fireplace closeup photo' },
    {
      src: unsplash('1615505650086-960d1428f043'),
      alt: 'black metal candle holder on brown wooden table',
    },
    { src: unsplash('1526924104461-13fd33256359'), alt: 'turned on electric fireplace' },
  ],
  'renovation-energetique': [
    { src: unsplash('1566838803980-56bfa5300e8c'), alt: 'gray concrete house' },
    { src: unsplash('1727532028095-4f45e7083bf4'), alt: 'A small white house with a black roof' },
    {
      src: unsplash('1721134119763-e58e987c9774'),
      alt: 'A picture of a house with a lot of grass in front of it',
    },
    { src: unsplash('1708050394724-e1f149cff988'), alt: 'a house with a clock on the front of it' },
    {
      src: unsplash('1732149621629-6a496b9165ca'),
      alt: 'A couple of houses sitting on top of a hill',
    },
    { src: unsplash('1681264128028-b59ee25012a5'), alt: 'a house with a solar panel on the roof' },
    { src: unsplash('1568605114967-8130f3a36994'), alt: 'brown and black wooden house' },
    {
      src: unsplash('1618179223835-053605d766b2'),
      alt: 'white and brown concrete house near bare trees during daytime',
    },
    {
      src: unsplash('1654563098789-0c8342adfab1'),
      alt: 'a house with a deck and stairs leading up to it',
    },
    { src: unsplash('1583345237708-add35a664d77'), alt: 'brown and white concrete house' },
    {
      src: unsplash('1719559519300-e9d2c2bf6de1'),
      alt: 'A man holding a solar panel in front of a house',
    },
    { src: unsplash('1655300283246-1ef0317a565d'), alt: 'a house with solar panels' },
    { src: unsplash('1697300021651-67a5ea26d7db'), alt: 'an aerial view of a house in the woods' },
    {
      src: unsplash('1757270290882-2650ed106f94'),
      alt: 'A light-colored house with a dark roof and porch.',
    },
    {
      src: unsplash('1629316857924-3564908b05e7'),
      alt: 'white concrete house under blue sky during daytime',
    },
    {
      src: unsplash('1723066108565-c97ad671a18c'),
      alt: 'A blue house surrounded by trees and plants',
    },
    {
      src: unsplash('1642775955839-830e41b93682'),
      alt: 'a gray house with a white porch and a brown door',
    },
    {
      src: unsplash('1501183638710-841dd1904471'),
      alt: 'living room set with green dumb cane plant',
    },
    {
      src: unsplash('1645013062104-451abe603017'),
      alt: 'a large house with a driveway in front of it',
    },
    {
      src: unsplash('1584738766473-61c083514bf4'),
      alt: 'white and brown wooden house near green trees during daytime',
    },
    {
      src: unsplash('1652803723701-3e3952c35c53'),
      alt: 'a house with a lot of snow on the ground',
    },
    {
      src: unsplash('1607014692697-300608c357db'),
      alt: 'white concrete house near bare trees during daytime',
    },
    {
      src: unsplash('1701967685783-d2c416a49a95'),
      alt: 'a house on a hill with a solar panel on the roof',
    },
    { src: unsplash('1720175328600-06f71cee36c4'), alt: 'A small white house with a blue roof' },
    {
      src: unsplash('1675583102865-4d9314267cc4'),
      alt: 'a brown house with white trim and a red door',
    },
    { src: unsplash('1505798577917-a65157d3320a'), alt: 'man standing infront of miter saw' },
    {
      src: unsplash('1631830399050-40ff3d252c52'),
      alt: 'a black house with a white door and windows',
    },
    {
      src: unsplash('1750876331830-0d2480e07089'),
      alt: 'A white house stands in the evening sunlight.',
    },
    { src: unsplash('1687865014576-9ae3570f550a'), alt: 'a house with a solar panel on the roof' },
    { src: unsplash('1605653807811-a0dea2185f34'), alt: 'bare tree near white and brown house' },
    {
      src: unsplash('1565599573128-ae3ef5c9f478'),
      alt: 'low-angle photography of buildings with plants on it',
    },
    { src: unsplash('1451976426598-a7593bd6d0b2'), alt: 'gray concrete building covered trees' },
    { src: unsplash('1535689077097-a8726b5ff822'), alt: 'building scale model' },
    {
      src: unsplash('1693517596637-8190ac7afc0e'),
      alt: 'a very tall building with lots of plants growing on it',
    },
    { src: unsplash('1630404991412-9504d094e8ba'), alt: 'brown and white concrete building' },
    { src: unsplash('1593586710811-c92ee75ddf6d'), alt: 'green and gray high rise building' },
    {
      src: unsplash('1569227997603-33b9f12af927'),
      alt: 'architectural photography of concrete stair',
    },
    {
      src: unsplash('1654145167982-10c1ebde498a'),
      alt: 'a building with lots of plants growing inside of it',
    },
    {
      src: unsplash('1517544181962-9157536e648b'),
      alt: 'architectural photography of glass building',
    },
    { src: unsplash('1527690499469-ef2eff9c6735'), alt: 'top view of building with trees' },
    { src: unsplash('1504494645474-cc4e25299579'), alt: 'aerial photography of buildings' },
    { src: unsplash('1574496968378-3465b8576235'), alt: 'blue glass structure' },
    {
      src: unsplash('1613127935408-bb27a0e0b82d'),
      alt: 'green and black glass walled building under blue sky during daytime',
    },
    {
      src: unsplash('1704476441987-4580b1380c9d'),
      alt: 'a very tall building with lots of plants growing on it',
    },
    {
      src: unsplash('1496241028573-69327bf8f9d5'),
      alt: "bird's eyeview photo of person lying on green grass",
    },
    {
      src: unsplash('1683191457485-42a612eeea57'),
      alt: 'a very tall building with a bunch of plants growing on it',
    },
    {
      src: unsplash('1580041065738-e72023775cdc'),
      alt: 'green trees near swimming pool during daytime',
    },
    {
      src: unsplash('1505522678786-31df5cafeccb'),
      alt: "bird's eye view photography of a mid-rise building surrounded by trees near green body of water",
    },
    { src: unsplash('1531321538006-82b62d9fbb1f'), alt: 'concrete building under blue sky' },
    {
      src: unsplash('1600989930246-829897a96389'),
      alt: 'green and white wooden house under blue sky during daytime',
    },
    { src: unsplash('1531604627791-7202bc829fd6'), alt: 'a wall covered in lots of green plants' },
    { src: unsplash('1529313300790-70966a876b56'), alt: 'green leafed plants' },
    {
      src: unsplash('1504762453622-71611c124797'),
      alt: 'aerial photography of white architectural building',
    },
    {
      src: unsplash('1527891751199-7225231a68dd'),
      alt: 'black bicycle parked in front of building',
    },
    { src: unsplash('1662251772755-1c1a094f4259'), alt: 'a building with many windows' },
    {
      src: unsplash('1533698354996-1ba76dacab33'),
      alt: 'architectural photography of glass building',
    },
    { src: unsplash('1575663849788-ded5a98f9ee7'), alt: 'women leaning on glass wall' },
    { src: unsplash('1643482457452-4b0901f4634b'), alt: 'a double photo of a building' },
    {
      src: unsplash('1505060872009-ed2866c37da6'),
      alt: 'aerial photography of house surrounded by trees at daytime',
    },
    { src: unsplash('1531839203475-fd08d2bfd7ac'), alt: 'waterfalls near plants' },
  ],
  zingueur: [
    {
      src: unsplash('1770910452211-2e8fd91bc347'),
      alt: 'Modern building with metal roof and brick facade.',
    },
    {
      src: unsplash('1769033472729-a5e5ffcca512'),
      alt: 'Rooftops and domes against a pastel sunset sky.',
    },
    {
      src: unsplash('1568821692671-ea55f10b54ff'),
      alt: 'architectural photography of white monument',
    },
    {
      src: unsplash('1742812267701-22300e487867'),
      alt: 'A modern building with a view of the ocean.',
    },
    {
      src: unsplash('1563277383-0e5fdc0927f0'),
      alt: 'a close up of a building with a sky background',
    },
    {
      src: unsplash('1556309802-a237781b678f'),
      alt: 'architectural photography of gray and white concrete building',
    },
    { src: unsplash('1602064828974-fcac67d33f4e'), alt: 'white and black striped textile' },
    { src: unsplash('1602193230480-7840a38eb0c3'), alt: 'black and white glass building' },
    {
      src: unsplash('1764586173315-09d0afa108f4'),
      alt: 'Modern building with jagged roofline against sky',
    },
    {
      src: unsplash('1639129797888-13598d02775e'),
      alt: 'a metal roof with a blue sky in the background',
    },
    {
      src: unsplash('1602193069473-0c78775ec7e1'),
      alt: 'gray and white wooden house under white clouds',
    },
    {
      src: unsplash('1679382915249-489422f49eb3'),
      alt: 'a close up of a building with a blue sky in the background',
    },
    {
      src: unsplash('1639572655095-a110fdf22403'),
      alt: 'a black and white photo of a tall building',
    },
    {
      src: unsplash('1725183524108-c18b2b061bf6'),
      alt: 'A view of a building from across the street',
    },
    {
      src: unsplash('1739105329070-604d53e4f349'),
      alt: 'A bunch of metal bars stacked on top of each other',
    },
    {
      src: unsplash('1693015274282-d683501276c0'),
      alt: 'a close up of a metal roof with a tree in the background',
    },
    {
      src: unsplash('1680043647947-cd6a989505c3'),
      alt: 'a bird is perched on the roof of a building',
    },
    { src: unsplash('1665779736783-1b019f49c601'), alt: 'a close-up of a building' },
    {
      src: unsplash('1620443420983-26cf7e6cd2f6'),
      alt: 'white building under white clouds during daytime',
    },
    {
      src: unsplash('1642173082271-c88bd536ad06'),
      alt: 'a red fire hydrant sitting on the side of a building',
    },
    {
      src: unsplash('1695739313622-4c20018c13b3'),
      alt: 'a black building with a small window on the side of it',
    },
    {
      src: unsplash('1710330327050-5264f619188f'),
      alt: 'a tall building with a blue sky in the background',
    },
    { src: unsplash('1611944793527-62de6e2e537d'), alt: 'gray roof under blue sky during daytime' },
    { src: unsplash('1646641695635-690b0d0f5bf6'), alt: 'a rusted metal roof with two chimneys' },
    {
      src: unsplash('1575380585708-681561f22744'),
      alt: 'a close up of a building with many windows',
    },
    { src: unsplash('1629320790290-65a5573ad8e7'), alt: 'red and gray concrete building' },
    {
      src: unsplash('1690176287159-7e1526c04269'),
      alt: 'a green metal roof with a cloudy sky in the background',
    },
    {
      src: unsplash('1746187203564-54ae97d98096'),
      alt: 'Curved metal structure against a cloudy blue sky.',
    },
    { src: unsplash('1518736346281-76873166a64a'), alt: 'grey roof' },
    { src: unsplash('1661202321298-3c42c8fa9183'), alt: 'a low angle view of a building' },
    {
      src: unsplash('1732701167065-2d76f6baa3d5'),
      alt: "A hand holding a bunch of screws on it's wrist",
    },
    { src: unsplash('1524568292009-5c8f3fe5dcc7'), alt: 'white PVC tube under blue sky' },
    {
      src: unsplash('1654531015087-8cc3d04d1b2d'),
      alt: 'a gutter gutter attached to the side of a building',
    },
    {
      src: unsplash('1770580836737-88e86a973229'),
      alt: 'Modern building exterior with clear blue sky',
    },
    { src: unsplash('1762363145055-3d75459401e4'), alt: 'White building eaves against a blue sky' },
    {
      src: unsplash('1647079002654-f1f3f701b39f'),
      alt: 'a black and white photo of a building with a roof',
    },
    { src: unsplash('1588408052962-b0bc38175636'), alt: 'brown and white concrete building' },
    {
      src: unsplash('1707353644499-a8115a29e6e5'),
      alt: 'a close up of a metal pipe on a building',
    },
    {
      src: unsplash('1619784924192-050aabcb0653'),
      alt: 'brown concrete building under blue sky during daytime',
    },
    {
      src: unsplash('1681707954921-ea05497b1679'),
      alt: 'a bird is sitting on the roof of a house',
    },
    {
      src: unsplash('1680145114161-2468e057efaf'),
      alt: 'a close up of a building with a blue sky in the background',
    },
    {
      src: unsplash('1582586285604-a136d08ab100'),
      alt: 'brown and white wooden house under blue sky during daytime',
    },
    {
      src: unsplash('1711696467309-d80c4fd044ed'),
      alt: 'a close up of a clock on the side of a building',
    },
    { src: unsplash('1660913905008-a0959d03df60'), alt: 'a building with a blue sky' },
    {
      src: unsplash('1638029319565-189f0dcec97e'),
      alt: 'a black and white photo of a building with a sky background',
    },
    { src: unsplash('1668396290365-9d44d3c14bb4'), alt: 'a red building with a white pole' },
    {
      src: unsplash('1744044155829-610dded4cead'),
      alt: 'Dirty gutters and roof against a blue sky.',
    },
    { src: unsplash('1542479090-c5948d99475a'), alt: 'low angle photo of white building' },
    { src: unsplash('1659956658875-9c4d2d03ce6a'), alt: 'a person standing on a roof' },
    {
      src: unsplash('1601651545102-82b9d8a27ef0'),
      alt: 'brown wooden roof under white sky during daytime',
    },
    {
      src: unsplash('1675671509845-a5184ef9c4c6'),
      alt: 'a man is painting the side of a building',
    },
    {
      src: unsplash('1567507145544-da3fe1b4f8f9'),
      alt: 'man drilling on a wooden plank using a power drill',
    },
    { src: unsplash('1632675665453-429794881178'), alt: 'a red building with snow falling on it' },
    {
      src: unsplash('1722253358715-61e69ef7b5a1'),
      alt: 'A close up of a roof with a pipe sticking out of it',
    },
    {
      src: unsplash('1759001001060-a4b6e5fff734'),
      alt: 'White wall with tree shadows and blue sky',
    },
    {
      src: unsplash('1717505352369-f9b7df761923'),
      alt: 'a small bird perched on top of a wooden structure',
    },
    {
      src: unsplash('1771955927699-29ccd0af59f0'),
      alt: 'Modern building corner against a bright blue sky',
    },
    {
      src: unsplash('1647856144058-9fd3c1a24c3c'),
      alt: 'a close up of a row of benches in a park',
    },
    {
      src: unsplash('1693560821172-3a3cefbee30e'),
      alt: 'a house with a roof that has a green plant on top of it',
    },
    { src: unsplash('1574302637472-77aeb6de1711'), alt: 'low angle photo of wooden house' },
  ],
}
