#!/usr/bin/env python3
"""Generate existing-articles Part 4 (articles 21-27)."""
import json

articles = []

# ─── Article 21: garantie-decennale-tout-savoir ───
articles.append({
    "slug": "garantie-decennale-tout-savoir",
    "title": "Garantie décennale : tout ce qu'il faut savoir",
    "excerpt": "Durée, couverture, recours... La garantie décennale expliquée simplement pour protéger votre investissement immobilier pendant 10 ans.",
    "content": [
        "La garantie décennale est une protection essentielle pour tout propriétaire qui fait réaliser des travaux de construction ou de rénovation importante. Instituée par la loi Spinetta du 4 janvier 1978, elle constitue l'un des piliers du droit de la construction en France. Pourtant, selon les assureurs, près de 30 % des sinistres décennaux ne sont jamais déclarés par méconnaissance. Voici tout ce que vous devez savoir pour protéger votre investissement.",
        "## Qu'est-ce que la garantie décennale ?\n\n### Définition juridique\n\nC'est une assurance obligatoire prévue par l'article 1792 du Code civil. Elle couvre les malfaçons et dommages compromettant la solidité de l'ouvrage ou le rendant impropre à sa destination, pendant 10 ans après la [réception des travaux](/blog/reception-travaux-proces-verbal-reserves).\n\n### Les trois niveaux de garantie\n\nLe régime français prévoit trois garanties complémentaires :\n\n1. **Garantie de parfait achèvement** (1 an) : tous les défauts signalés pendant la première année\n2. **Garantie biennale** (2 ans) : les éléments d'équipement dissociables (robinetterie, volets, radiateurs)\n3. **Garantie décennale** (10 ans) : les dommages structurels graves\n\nPour un panorama complet des responsabilités, consultez notre article sur la [responsabilité artisan et maître d'ouvrage](/blog/responsabilite-artisan-maitre-ouvrage).\n\n:::info Bon à savoir\nLa garantie décennale repose sur une présomption de responsabilité : c'est à l'artisan de prouver qu'il n'est pas fautif, et non au propriétaire de prouver la faute. C'est une protection très favorable au maître d'ouvrage.\n:::",
        "## Quels travaux sont couverts ?\n\n### Les travaux de gros œuvre\n\n- Fondations, dalles, murs porteurs\n- Toiture et charpente\n- Escaliers structurels\n- Canalisations encastrées\n\n### Les éléments d'équipement indissociables\n\n- Chauffage central (canalisations, radiateurs encastrés)\n- Installation électrique encastrée\n- Carrelage scellé (par opposition au carrelage collé)\n- Plomberie encastrée\n\n### Les vices rendant le logement inhabitable\n\n- Infiltrations rendant des pièces inutilisables\n- Défauts d'isolation thermique ou phonique graves\n- Fissures structurelles évolutives\n\n:::warning Attention\nLa garantie décennale ne couvre pas les défauts esthétiques mineurs (micro-fissures non évolutives, léger défaut de teinte du carrelage) ni les équipements dissociables (robinetterie, volets, portes intérieures), qui relèvent de la garantie biennale.\n:::",
        "## Comment vérifier et activer la garantie\n\n### Avant les travaux\n\nDemandez à l'artisan son attestation de garantie décennale avant le début des travaux. L'attestation doit :\n\n- Être en cours de validité\n- Mentionner les activités couvertes (vérifiez que vos travaux y figurent)\n- Indiquer le nom de l'assureur et le numéro de police\n- Préciser la zone géographique de couverture\n\n### En cas de malfaçon\n\n1. **Envoyez une lettre recommandée avec AR** à l'artisan décrivant précisément les désordres constatés\n2. **Joignez des photos datées** et le procès-verbal de réception\n3. **Fixez un délai** de 30 jours pour la réparation\n4. Si l'artisan ne réagit pas, **contactez son assureur** directement (coordonnées sur l'attestation)\n5. En dernier recours, **saisissez le tribunal judiciaire** avec l'aide d'un expert\n\n### Le rôle de l'assurance dommages-ouvrage\n\nSi vous avez souscrit une [assurance dommages-ouvrage](/blog/assurance-dommages-ouvrage-guide-complet), elle vous indemnise rapidement (sous 90 jours) sans attendre la désignation du responsable. L'assureur DO se retourne ensuite contre l'artisan fautif.\n\n:::tip Conseil pro\nConservez précieusement l'attestation de garantie décennale de chaque artisan pendant 10 ans après la réception. En cas de revente dans ce délai, vous devrez la transmettre à l'acquéreur.\n:::\n\n:::takeaway\n- La garantie décennale couvre les malfaçons graves pendant 10 ans après réception\n- Elle repose sur une présomption de responsabilité favorable au propriétaire\n- Exigez l'attestation d'assurance AVANT le début des travaux\n- En cas de sinistre : LRAR à l'artisan, puis contact de l'assureur\n- L'assurance dommages-ouvrage accélère considérablement l'indemnisation\n- Conservez tous les documents pendant 10 ans minimum\n:::",
    ],
    "image": "/images/blog/garantie-decennale.jpg",
    "author": "Isabelle Renault",
    "authorBio": "Isabelle Renault, juriste spécialisée en droit de la construction et de l'immobilier, décrypte la réglementation pour les propriétaires.",
    "date": "2026-01-23",
    "updatedDate": "2026-02-08",
    "readTime": "12 min",
    "category": "Guides",
    "tags": ["Garantie", "Decennale", "Assurance"],
    "faq": [
        {"question": "La garantie décennale est-elle obligatoire pour tous les artisans ?", "answer": "Oui, tout constructeur ou artisan réalisant des travaux de construction ou de gros œuvre doit souscrire une assurance décennale (article L.241-1 du Code des assurances). Le défaut d'assurance est puni de 6 mois d'emprisonnement et 75 000 € d'amende."},
        {"question": "Que faire si l'artisan a cessé son activité ?", "answer": "La garantie décennale survit à la cessation d'activité. Contactez directement l'assureur mentionné sur l'attestation. Si vous ne retrouvez pas l'assureur, le Bureau Central de Tarification (BCT) peut vous aider."},
        {"question": "La garantie décennale couvre-t-elle les travaux de peinture ?", "answer": "Non, la peinture relève de la garantie de parfait achèvement (1 an). La garantie décennale couvre uniquement les dommages compromettant la solidité de l'ouvrage ou le rendant impropre à sa destination."},
    ],
})

# ─── Article 22: comment-choisir-cuisine-equipee-guide ───
articles.append({
    "slug": "comment-choisir-cuisine-equipee-guide",
    "title": "Comment choisir sa cuisine équipée : guide complet",
    "excerpt": "Matériaux, agencement, budget, erreurs à éviter... Tout pour réussir le choix de votre cuisine équipée et optimiser votre espace.",
    "content": [
        "La cuisine est la pièce la plus technique d'un logement et l'une des plus coûteuses à aménager. Son aménagement mérite une réflexion approfondie pour combiner fonctionnalité, esthétique et durabilité. Les Français y consacrent en moyenne 6 500 euros, mais les budgets s'échelonnent de 3 000 à plus de 25 000 euros selon les choix. Voici le guide complet pour faire les bons choix.",
        "## Définir l'agencement\n\n### Les configurations possibles\n\nCuisine en L, en U, en I ou avec îlot central ? Le choix dépend de la superficie et de la forme de la pièce :\n\n- **En I (linéaire)** : pour les petits espaces (moins de 6 m²), tout sur un seul mur\n- **En L** : la plus polyvalente, adaptée à partir de 8 m²\n- **En U** : beaucoup de rangements, nécessite au moins 10 m²\n- **Avec îlot** : l'idéal pour les cuisines ouvertes de plus de 15 m², convivial et fonctionnel\n\n### Le triangle d'activité\n\nRespectez le triangle d'activité entre les trois zones principales : évier (lavage), cuisson (four/plaques) et réfrigérateur (stockage froid). La somme des trois côtés du triangle doit idéalement mesurer entre 3,60 et 6,60 mètres pour un maximum de praticité.\n\n:::tip Conseil pro\nPour un îlot central, prévoyez un passage d'au moins 90 cm (120 cm si un four s'ouvre sur le passage). Un îlot trop serré dans l'espace rendra la cuisine impraticable.\n:::",
        "## Choisir les matériaux\n\n### Plan de travail\n\n| Matériau | Prix au mètre linéaire | Avantages | Inconvénients |\n| --- | --- | --- | --- |\n| Stratifié | 40 - 150 € | Économique, large choix | Sensible à la chaleur et aux coupures |\n| Quartz | 200 - 500 € | Très résistant, sans entretien | Prix élevé |\n| Granit | 250 - 600 € | Naturel, résistant | Poreux (à imperméabiliser), lourd |\n| Bois massif | 150 - 400 € | Chaleureux, réparable | Entretien régulier |\n| Inox | 200 - 500 € | Professionnel, hygiénique | Rayures visibles |\n\n### Façades de meubles\n\nMélaminé (économique), laqué (moderne, facile d'entretien), bois massif (chaleureux, haut de gamme), stratifié haute pression (résistant).\n\n:::info Bon à savoir\nLe quartz composite (Silestone, Caesarstone) est le matériau qui offre le meilleur rapport résistance/entretien pour un plan de travail. Contrairement au granit, il ne nécessite aucun traitement et résiste aux taches.\n:::",
        "## Le budget à prévoir\n\n### Les gammes de prix\n\n:::budget\n| Gamme | Prix (hors pose) | Caractéristiques |\n| Entrée de gamme | 3 000 - 5 000 € | Mélaminé, stratifié, quincaillerie basique |\n| Milieu de gamme | 5 000 - 12 000 € | Laqué/bois, quartz, quincaillerie qualité |\n| Haut de gamme | 12 000 - 25 000 €+ | Matériaux nobles, sur mesure, électroménager premium |\n:::\n\nAjoutez 2 000 à 5 000 € pour la pose par un cuisiniste professionnel, incluant les raccordements plomberie et électricité.\n\n## Les erreurs à éviter\n\n### Les pièges classiques\n\n- **Sous-estimer le rangement** : prévoyez 30 % de rangements de plus que ce que vous pensez nécessaire\n- **Oublier l'éclairage** : un éclairage LED sous les meubles hauts est indispensable pour le plan de travail\n- **Négliger la ventilation** : une hotte performante (débit minimum 400 m³/h) est essentielle\n- **Choisir des matériaux inadaptés** : la cuisine subit chaleur, humidité et projections quotidiennes\n- **Mal positionner les prises** : prévoyez au moins 6 prises au-dessus du plan de travail (norme NF C 15-100)\n\n:::warning Attention\nLes cuisines en kit des grandes surfaces nécessitent souvent des adaptations coûteuses (coupe sur mesure, fileurs, joues). Le prix final peut dépasser celui d'une cuisine sur mesure posée par un cuisiniste. Comparez les devis complets.\n:::\n\nPour l'aspect tendances et design, consultez nos articles sur les [tendances salle de bain 2026](/blog/tendances-salle-de-bain-2026).\n\n:::takeaway\n- Respectez le triangle d'activité pour une cuisine fonctionnelle\n- Le quartz est le meilleur compromis pour le plan de travail\n- Budget : 3 000-5 000 € (entrée de gamme) à 12 000-25 000 € (haut de gamme)\n- Ajoutez 2 000-5 000 € pour la pose professionnelle\n- Prévoyez 30 % de rangements supplémentaires\n- Ne négligez pas l'éclairage du plan de travail et la ventilation\n:::",
    ],
    "image": "/images/blog/cuisine-equipee.jpg",
    "author": "Thomas Bernard",
    "authorBio": "Thomas Bernard, architecte d'intérieur et consultant en rénovation, conseille les propriétaires sur l'optimisation de leur habitat.",
    "date": "2026-01-21",
    "updatedDate": "2026-02-07",
    "readTime": "13 min",
    "category": "Guides",
    "tags": ["Cuisine", "Amenagement", "Guides"],
    "faq": [
        {"question": "Vaut-il mieux une cuisine sur mesure ou en kit ?", "answer": "Pour les petits budgets et les cuisines aux dimensions standards, le kit peut suffire. Pour les espaces atypiques, les matériaux nobles ou une ergonomie optimale, le sur mesure est préférable. Comparez toujours les devis complets (pose incluse)."},
        {"question": "Quelle hauteur pour le plan de travail ?", "answer": "La hauteur standard est de 85-90 cm, mais l'idéal est de l'adapter à votre taille : le plan doit arriver à la hauteur de vos coudes fléchis à 90°. Pour une cuisine partagée, 87 cm est un bon compromis."},
        {"question": "Combien de temps pour installer une cuisine ?", "answer": "Comptez 2 à 4 jours pour la pose d'une cuisine standard par un professionnel, et 1 à 2 jours supplémentaires pour les raccordements plomberie et électricité."},
    ],
})

# ─── Article 23: isolation-thermique-meilleures-solutions-2026 ───
articles.append({
    "slug": "isolation-thermique-meilleures-solutions-2026",
    "title": "Isolation thermique : les meilleures solutions en 2026",
    "excerpt": "Combles, murs, sols... Comparatif détaillé des matériaux et techniques d'isolation thermique pour choisir la solution la plus adaptée à votre logement.",
    "content": [
        "L'isolation thermique est le premier investissement à réaliser pour réduire votre facture énergétique. En 2026, les solutions sont nombreuses et les [aides financières](/blog/renovation-energetique-aides-2026) généreuses. Mais face à la diversité des matériaux et des techniques, comment choisir la solution la plus adaptée à votre logement ? Voici le comparatif complet.",
        "## Isolation des combles perdus\n\n### La technique la plus rentable\n\nLe soufflage de laine de verre ou de ouate de cellulose est la technique la plus courante pour les combles non aménagés. L'isolant est projeté en vrac sur le plancher des combles, créant un matelas continu et homogène.\n\n- **Prix** : 20 à 50 €/m²\n- **Performance** : résistance thermique R = 7 minimum recommandé (soit environ 30 cm d'épaisseur)\n- **Durée des travaux** : une demi-journée pour une maison standard\n- **Durée de vie** : 25 à 30 ans\n\n:::budget\n| Isolant combles perdus | Prix moyen | R pour 30 cm | Avantage principal |\n| Laine de verre soufflée | 20 - 35 €/m² | 7,5 | Rapport qualité/prix |\n| Ouate de cellulose | 25 - 45 €/m² | 7,0 | Confort d'été |\n| Laine de roche soufflée | 25 - 40 €/m² | 7,5 | Résistance au feu |\n:::",
        "## Isolation des murs : ITE vs ITI\n\n### L'isolation par l'extérieur (ITE)\n\nL'ITE est la solution la plus performante car elle supprime tous les ponts thermiques et préserve l'inertie des murs. Idéale lors d'un [ravalement de façade](/blog/reglementation-ravalement-facade-obligations).\n\n- **Prix** : 100 à 200 €/m²\n- **Performance** : R ≥ 3,7 m².K/W\n- **Avantages** : pas de perte de surface habitable, suppression des ponts thermiques\n\n### L'isolation par l'intérieur (ITI)\n\nMoins coûteuse que l'ITE, l'ITI est adaptée quand l'ITE n'est pas possible (bâtiment classé, copropriété).\n\n- **Prix** : 40 à 90 €/m²\n- **Performance** : R ≥ 3,7 m².K/W\n- **Inconvénient** : perte de surface habitable (5-7 cm par mur)\n\n:::tip Conseil pro\nPour les maisons anciennes en pierre, privilégiez un isolant perspirant (fibre de bois, chanvre) qui laisse le mur « respirer ». Un isolant imperméable à la vapeur d'eau (polystyrène) peut piéger l'humidité et dégrader le mur.\n:::",
        "## Isolation du sol et les matériaux biosourcés\n\n### L'isolation du sol\n\nSouvent négligée, l'isolation du sol représente 7 à 10 % des déperditions thermiques. Deux techniques principales :\n\n- **Isolation en sous-face** (sous le plancher, depuis le vide sanitaire ou la cave) : 25 à 60 €/m²\n- **Isolation sur plancher** (couche isolante + nouveau revêtement) : 40 à 80 €/m²\n\n### Les matériaux biosourcés : l'avenir de l'isolation\n\nFavorisés par la [RE2020](/blog/reglementation-thermique-re2020-impact), les isolants biosourcés offrent un excellent confort d'été grâce à leur inertie thermique et un bilan carbone favorable :\n\n- **Fibre de bois** : lambda 0,038, excellent déphasage thermique (10-12h)\n- **Ouate de cellulose** : lambda 0,040, issue du recyclage de papier\n- **Chanvre** : lambda 0,040, bon régulateur d'humidité\n- **Laine de mouton** : lambda 0,035, excellente hygrorégulation\n\n:::info Bon à savoir\nLe déphasage thermique est le temps que met la chaleur à traverser l'isolant. Un déphasage de 10-12 heures (fibre de bois) signifie que la chaleur du midi atteint l'intérieur vers minuit, quand il fait frais dehors. Les isolants minéraux (laine de verre) ont un déphasage de seulement 4-6 heures.\n:::\n\nPour un guide complet sur l'isolation, consultez notre [guide de l'isolation thermique](/blog/isolation-thermique-guide).\n\n:::takeaway\n- Combles perdus par soufflage : solution la plus rentable (20-50 €/m²)\n- ITE : la plus performante mais la plus coûteuse (100-200 €/m²)\n- ITI : le compromis économique quand l'ITE n'est pas possible\n- Les isolants biosourcés offrent un meilleur confort d'été\n- Visez R ≥ 7 pour les combles et R ≥ 3,7 pour les murs\n- Les aides couvrent jusqu'à 75 % du coût selon vos revenus\n:::",
    ],
    "image": "/images/blog/isolation-solutions.jpg",
    "author": "Marc Lefebvre",
    "authorBio": "Marc Lefebvre, ingénieur thermicien et rédacteur technique, vulgarise les aspects complexes de la rénovation énergétique.",
    "date": "2026-01-19",
    "updatedDate": "2026-02-08",
    "readTime": "12 min",
    "category": "Energie",
    "tags": ["Isolation", "Thermique", "Energie"],
    "faq": [
        {"question": "Quel est le meilleur isolant en 2026 ?", "answer": "Il n'y a pas de meilleur isolant universel. Le choix dépend de la zone à isoler, du budget et des priorités (performance pure, confort d'été, bilan carbone). La fibre de bois offre le meilleur compromis global mais est plus chère que la laine de verre."},
        {"question": "L'isolation par l'extérieur nécessite-t-elle une autorisation ?", "answer": "Oui, l'ITE modifie l'aspect extérieur du bâtiment et nécessite une déclaration préalable de travaux. En zone ABF, l'accord de l'Architecte des Bâtiments de France est requis."},
        {"question": "Combien d'années pour rentabiliser l'isolation ?", "answer": "L'isolation des combles est rentabilisée en 3-5 ans, l'ITI en 5-8 ans, l'ITE en 8-12 ans. Avec les aides financières (MaPrimeRénov', CEE), ces délais peuvent être réduits de moitié."},
    ],
})

# ─── Article 24: prix-couvreur-2026-cout-refection-toiture ───
articles.append({
    "slug": "prix-couvreur-2026-cout-refection-toiture",
    "title": "Prix couvreur 2026 : coût réfection toiture",
    "excerpt": "Réfection complète, réparation de fuite, démoussage... Tous les tarifs couverture et toiture en 2026 pour anticiper votre budget.",
    "content": [
        "La toiture est un élément essentiel de votre habitation qui protège l'ensemble de la structure. Son entretien et sa rénovation représentent un budget important qu'il faut anticiper. Une toiture mal entretenue entraîne des infiltrations qui peuvent endommager la charpente, l'isolation et les finitions intérieures, avec des réparations pouvant atteindre 20 000 à 50 000 euros dans les cas graves.",
        "## Tarif horaire d'un couvreur\n\n### Les prix par zone\n\nLe tarif horaire d'un couvreur se situe entre 40 et 60 euros HT en province, et entre 55 et 80 euros HT en région parisienne. Le travail en hauteur justifie des tarifs légèrement supérieurs à d'autres corps de métier.\n\n:::budget\n| Zone | Tarif horaire HT |\n| Province | 40 - 60 € |\n| Grande métropole | 50 - 70 € |\n| Île-de-France | 55 - 80 € |\n:::",
        "## Prix d'une réfection complète\n\n### Selon le type de couverture\n\n| Matériau | Prix au m² (dépose + fourniture + pose) |\n| --- | --- |\n| Tuiles terre cuite | 80 - 150 €/m² |\n| Tuiles béton | 60 - 120 €/m² |\n| Ardoise naturelle | 100 - 200 €/m² |\n| Ardoise synthétique | 70 - 130 €/m² |\n| Zinc | 70 - 140 €/m² |\n| Bac acier | 40 - 80 €/m² |\n\nPour une maison de 100 m² au sol avec une toiture de 130 m², le budget d'une réfection complète en tuiles se situe entre 10 000 et 20 000 euros.\n\n:::info Bon à savoir\nSi votre toiture a plus de 30 ans, profitez de la réfection pour ajouter une isolation par l'extérieur (sarking). Cette technique ajoute 60-100 €/m² mais permet de bénéficier des aides à la rénovation énergétique et d'économiser sur le chauffage.\n:::",
        "## Réparations courantes et entretien\n\n### Prix des interventions\n\n:::budget\n| Intervention | Prix moyen |\n| Remplacement tuiles cassées | 50 - 100 €/tuile |\n| Réparation de fuite | 200 - 800 € |\n| Remplacement de gouttière | 40 - 80 €/ml |\n| Réparation de faîtage | 40 - 80 €/ml |\n| Remplacement de velux | 500 - 1 500 € |\n:::\n\n### Entretien préventif\n\n| Entretien | Prix moyen |\n| --- | --- |\n| Démoussage et traitement hydrofuge | 15 - 35 €/m² |\n| Nettoyage de gouttières | 10 - 15 €/ml |\n| Traitement de charpente | 20 - 40 €/m² |\n\n:::tip Conseil pro\nUn entretien régulier (démoussage tous les 5 ans, nettoyage de gouttières annuel) prolonge la durée de vie de votre toiture de 10 à 15 ans. C'est un investissement de 500 à 1 500 euros qui vous évite une réfection à 15 000 euros.\n:::\n\n:::takeaway\n- Tarif horaire couvreur : 40-60 € HT en province, 55-80 € HT en Île-de-France\n- Réfection complète en tuiles : 80-150 €/m², soit 10 000-20 000 € pour une maison standard\n- Réparation de fuite : 200-800 € selon la complexité\n- Le démoussage préventif (15-35 €/m²) prolonge la vie de votre toiture\n- Profitez d'une réfection pour isoler par l'extérieur (sarking)\n:::",
    ],
    "image": "/images/blog/prix-couvreur.jpg",
    "author": "Jean-Pierre Duval",
    "authorBio": "Jean-Pierre Duval, ancien artisan du bâtiment reconverti en journaliste, partage son expertise terrain pour aider les propriétaires à faire les bons choix.",
    "date": "2026-01-17",
    "updatedDate": "2026-02-07",
    "readTime": "10 min",
    "category": "Tarifs",
    "tags": ["Couverture", "Toiture", "Tarifs"],
    "faq": [
        {"question": "Quelle est la durée de vie d'une toiture ?", "answer": "Tuiles terre cuite : 50-100 ans. Ardoise naturelle : 75-100 ans. Zinc : 50-80 ans. Bac acier : 30-50 ans. Ces durées supposent un entretien régulier (démoussage, remplacement des éléments dégradés)."},
        {"question": "Faut-il une autorisation pour refaire sa toiture ?", "answer": "Une réfection à l'identique (même matériau, même couleur) ne nécessite généralement pas d'autorisation. Un changement de matériau ou de couleur nécessite une déclaration préalable. En zone ABF, l'accord de l'ABF est toujours requis."},
        {"question": "La réfection de toiture bénéficie-t-elle d'aides ?", "answer": "La réfection seule ne bénéficie pas d'aides. En revanche, si elle s'accompagne d'une isolation (sarking), vous pouvez obtenir MaPrimeRénov', les CEE et la TVA à 5,5 % sur la partie isolation."},
    ],
})

# ─── Article 25: renovation-salle-de-bain-budget-etapes ───
articles.append({
    "slug": "renovation-salle-de-bain-budget-etapes",
    "title": "Rénovation salle de bain : budget et étapes",
    "excerpt": "Coût moyen, planning des travaux, choix des matériaux... Le guide complet pour rénover votre salle de bain avec le bon budget et dans le bon ordre.",
    "content": [
        "La rénovation d'une salle de bain est un projet qui améliore à la fois votre confort quotidien et la valeur de votre bien immobilier (plus-value estimée de 5 à 10 %). C'est aussi l'un des projets les plus techniques, impliquant plomberie, électricité, étanchéité et finitions. Voici comment bien le préparer pour éviter les surcoûts et les mauvaises surprises.",
        "## Budget moyen en 2026\n\n### Les trois niveaux de rénovation\n\n:::budget\n| Niveau de rénovation | Budget moyen | Ce qui est inclus |\n| Légère (rafraîchissement) | 1 500 - 3 000 € | Peinture, accessoires, petit mobilier |\n| Standard (remplacement) | 5 000 - 10 000 € | Carrelage, sanitaires, robinetterie |\n| Complète (restructuration) | 8 000 - 20 000 € | Tout y compris plomberie et électricité |\n:::\n\nPour une salle de bain tendance intégrant les [dernières innovations](/blog/tendances-salle-de-bain-2026), prévoyez la fourchette haute.\n\n:::info Bon à savoir\nLe coût de la plomberie représente environ 30-40 % du budget d'une rénovation complète. Si votre installation actuelle est en bon état, vous pouvez économiser significativement en conservant les emplacements existants des sanitaires.\n:::",
        "## L'ordre des travaux\n\n### Le planning optimal\n\nRespecter l'ordre des travaux est essentiel pour éviter les reprises :\n\n1. **Démolition** de l'existant (carrelage, sanitaires, cloisons)\n2. **Plomberie** : modification des alimentations et évacuations\n3. **Électricité** : mise aux normes selon les volumes de sécurité [NF C 15-100](/blog/electricite-normes-securite)\n4. **Étanchéité** : pose du système d'étanchéité sous carrelage (SPEC)\n5. **Carrelage** : murs d'abord, puis sol\n6. **Installation des sanitaires** : douche/baignoire, vasque, WC\n7. **Peinture et finitions** : plafond, parties non carrelées, joints silicone\n\n:::warning Attention\nNe négligez jamais l'étanchéité sous carrelage, surtout pour une douche à l'italienne. Un défaut d'étanchéité est la première cause de dégâts des eaux en salle de bain, avec un coût de réparation pouvant atteindre 5 000 à 15 000 € (reprise du carrelage, traitement de l'humidité, réparation chez le voisin du dessous).\n:::",
        "## Les choix de matériaux et erreurs à éviter\n\n### Carrelage et revêtements\n\n- **Grès cérame** : le plus durable, large choix de formats et de finitions (30-80 €/m²)\n- **Faïence** : pour les murs, légère et facile à poser (15-50 €/m²)\n- **Mosaïque** : pour les touches décoratives et les receveurs de douche (40-120 €/m²)\n- **Béton ciré** : tendance mais nécessite un applicateur qualifié (80-150 €/m²)\n\n### Les erreurs classiques\n\n- **Négliger l'étanchéité** : source de dégâts des eaux coûteux\n- **Sous-dimensionner la ventilation** : une VMC insuffisante provoque moisissures et dégradations\n- **Oublier les rangements** : prévoyez des niches encastrées, un meuble vasque avec rangements\n- **Choisir des matériaux non adaptés** : le bois non traité et certains métaux ne supportent pas l'humidité constante\n\nPour une rénovation accessible, consultez notre guide sur les [normes PMR en salle de bain](/blog/accessibilite-pmr-logement-normes).\n\n:::tip Conseil pro\nPrévoyez un siphon de sol (obligatoire en copropriété pour les douches à l'italienne) et une pente de 1-2 % vers l'évacuation. Faites appel à un étancheur certifié pour la pose du SPEC (Système de Protection à l'Eau sous Carrelage).\n:::\n\n:::takeaway\n- Budget : 1 500-3 000 € (légère), 5 000-10 000 € (standard), 8 000-20 000 € (complète)\n- Respectez l'ordre : démolition → plomberie → électricité → étanchéité → carrelage → sanitaires\n- L'étanchéité sous carrelage est non négociable, surtout pour les douches à l'italienne\n- Le grès cérame offre le meilleur rapport durabilité/prix pour le sol\n- Conserver les emplacements existants réduit considérablement le budget plomberie\n:::",
    ],
    "image": "/images/blog/renovation-sdb.jpg",
    "author": "Thomas Bernard",
    "authorBio": "Thomas Bernard, architecte d'intérieur et consultant en rénovation, conseille les propriétaires sur l'optimisation de leur habitat.",
    "date": "2026-01-14",
    "updatedDate": "2026-02-06",
    "readTime": "12 min",
    "category": "Guides",
    "tags": ["Salle de bain", "Renovation", "Budget"],
    "faq": [
        {"question": "Combien de temps dure la rénovation d'une salle de bain ?", "answer": "Comptez 1 à 2 semaines pour une rénovation standard et 2 à 4 semaines pour une rénovation complète avec modification de la plomberie. Prévoyez un point d'eau alternatif pendant les travaux."},
        {"question": "Peut-on rénover sa salle de bain soi-même ?", "answer": "La peinture et le petit mobilier sont accessibles en auto-rénovation. En revanche, la plomberie, l'électricité (normes de sécurité strictes) et l'étanchéité doivent être réalisées par des professionnels qualifiés."},
        {"question": "La rénovation de salle de bain bénéficie-t-elle d'aides ?", "answer": "Les travaux courants bénéficient de la TVA à 10 %. Si la rénovation inclut l'adaptation PMR (remplacement baignoire par douche pour personnes âgées), MaPrimeAdapt' peut financer jusqu'à 70 % des travaux."},
    ],
})

# ─── Article 26: chauffage-pompe-chaleur-vs-chaudiere-gaz-2026 ───
articles.append({
    "slug": "chauffage-pompe-chaleur-vs-chaudiere-gaz-2026",
    "title": "Chauffage : pompe à chaleur vs chaudière gaz en 2026",
    "excerpt": "Coût d'installation, consommation, aides disponibles... Comparatif complet et objectif pour choisir entre pompe à chaleur et chaudière gaz.",
    "content": [
        "Le choix du système de chauffage est crucial pour votre confort et votre budget sur le long terme. En 2026, la pompe à chaleur et la chaudière gaz à condensation restent les deux options les plus courantes en rénovation. Mais le contexte réglementaire et économique évolue rapidement. Voici un comparatif objectif pour faire le choix le plus adapté à votre situation.",
        "## Pompe à chaleur air-eau\n\n### Performances et coûts\n\n- **Coût d'installation** : 8 000 à 16 000 € (équipement + pose)\n- **Coût annuel de fonctionnement** : 500 à 900 € pour 100 m²\n- **Durée de vie** : 15 à 20 ans\n- **COP moyen** : 3 à 4 (produit 3-4 kWh de chaleur pour 1 kWh consommé)\n- **Éligible à MaPrimeRénov'** : jusqu'à 5 000 € d'aide + CEE (2 500-4 000 €)\n\n### Avantages\n\n- Économies d'énergie de 50-70 % par rapport au gaz\n- Fonction réversible (climatisation en été)\n- Éligible à toutes les aides\n- Énergie renouvelable, faibles émissions CO2\n\n### Inconvénients\n\n- Investissement initial élevé\n- Performances réduites par grand froid (< -7 °C)\n- Nuisance sonore de l'unité extérieure\n- Entretien spécialisé tous les 2 ans\n\n:::tip Conseil pro\nOptez pour une PAC haute température si vos radiateurs sont anciens (dimensionnés pour 65-70 °C). Une PAC basse température (35-45 °C) est idéale avec un plancher chauffant ou des radiateurs basse consommation.\n:::",
        "## Chaudière gaz à condensation\n\n### Performances et coûts\n\n- **Coût d'installation** : 3 000 à 7 000 € (équipement + pose)\n- **Coût annuel de fonctionnement** : 1 000 à 1 500 € pour 100 m²\n- **Durée de vie** : 15 à 25 ans\n- **Rendement** : > 100 % sur PCI (récupération de la chaleur des fumées)\n\n:::warning Attention\nDepuis la [RE2020](/blog/reglementation-thermique-re2020-impact), l'installation de chaudières gaz est interdite dans les logements neufs. En rénovation, elle reste autorisée mais les aides MaPrimeRénov' ont été supprimées pour cet équipement depuis 2024. Le gaz est voué à disparaître progressivement.\n:::\n\n## Le verdict comparatif\n\n### Tableau récapitulatif\n\n| Critère | PAC air-eau | Chaudière gaz condensation |\n| --- | --- | --- |\n| Coût d'installation | 8 000 - 16 000 € | 3 000 - 7 000 € |\n| Coût annuel (100 m²) | 500 - 900 € | 1 000 - 1 500 € |\n| Coût sur 15 ans | 15 500 - 29 500 € | 18 000 - 29 500 € |\n| Aides disponibles | Jusqu'à 9 000 € | CEE uniquement |\n| Impact écologique | Faible | Moyen |\n| Avenir réglementaire | Favorable | Défavorable |\n\nLa pompe à chaleur est plus économique à l'usage et plus respectueuse de l'environnement. La chaudière gaz reste pertinente en remplacement dans les logements déjà équipés au gaz, mais elle est amenée à disparaître.\n\n### Les alternatives\n\n- **Poêle à granulés** (2 000-5 000 €) : excellent appoint ou chauffage principal pour les maisons bien isolées\n- **Chaudière biomasse** (10 000-20 000 €) : remplacement idéal d'une chaudière fioul\n- **Système hybride** PAC + gaz : transition progressive, performance optimale\n\nPour un panorama plus large, consultez notre guide [Quel chauffage choisir](/blog/chauffage-solution-economique).\n\n:::takeaway\n- La PAC air-eau est le choix optimal en 2026 : économique, écologique, éligible aux aides\n- La chaudière gaz reste viable en remplacement mais perd ses aides\n- Sur 15 ans, la PAC revient souvent moins cher grâce aux aides et aux économies d'énergie\n- Isolez d'abord pour dimensionner correctement le chauffage\n- Faites réaliser une étude thermique avant de choisir\n:::",
    ],
    "image": "/images/blog/pac-vs-gaz.jpg",
    "author": "Marc Lefebvre",
    "authorBio": "Marc Lefebvre, ingénieur thermicien et rédacteur technique, vulgarise les aspects complexes de la rénovation énergétique.",
    "date": "2026-01-12",
    "updatedDate": "2026-02-09",
    "readTime": "13 min",
    "category": "Energie",
    "tags": ["Chauffage", "PAC", "Gaz"],
    "faq": [
        {"question": "La PAC fonctionne-t-elle par grand froid ?", "answer": "Les PAC modernes fonctionnent jusqu'à -15 à -25 °C selon les modèles. Cependant, leur rendement diminue en dessous de -7 °C. Dans les régions très froides, un appoint électrique intégré prend le relais."},
        {"question": "Peut-on garder les radiateurs existants avec une PAC ?", "answer": "Oui, si vous choisissez une PAC haute température (65-70 °C). Les PAC basse température (35-45 °C) nécessitent des radiateurs surdimensionnés ou un plancher chauffant."},
        {"question": "L'installation d'une PAC est-elle bruyante pour les voisins ?", "answer": "L'unité extérieure émet environ 45-55 dB. La réglementation impose un respect des seuils de bruit au voisinage. Placez l'unité à distance des chambres des voisins et sur des plots anti-vibrations."},
    ],
})

# ─── Article 27: droits-obligations-travaux-chez-soi ───
articles.append({
    "slug": "droits-obligations-travaux-chez-soi",
    "title": "Droits et obligations lors de travaux chez soi",
    "excerpt": "Autorisations, horaires, nuisances, responsabilités... Tout savoir sur le cadre légal des travaux à domicile pour éviter les conflits et les sanctions.",
    "content": [
        "Réaliser des travaux chez soi implique de respecter certaines règles légales qui protègent à la fois le propriétaire, les artisans et le voisinage. Méconnaître ces obligations peut entraîner des amendes, des arrêts de chantier ou des conflits de voisinage coûteux. Voici un guide complet pour connaître vos droits et obligations.",
        "## Les autorisations nécessaires\n\n### Selon la nature des travaux\n\n| Type de travaux | Autorisation requise |\n| --- | --- |\n| Travaux intérieurs sans modification de structure | Aucune |\n| Modification de l'aspect extérieur (fenêtres, volets, ravalement) | Déclaration préalable |\n| Extension de 5 à 20 m² (ou 40 m² en zone PLU) | Déclaration préalable |\n| Extension de plus de 20 m² (ou 40 m² en zone PLU) | Permis de construire |\n| Surface totale après travaux > 150 m² | Permis de construire + architecte |\n\nPour un guide détaillé, consultez notre article [Permis de construire ou déclaration préalable](/blog/permis-construire-declaration-prealable-guide).\n\n:::warning Attention\nRéaliser des travaux soumis à autorisation sans la demander expose à une amende de 1 200 à 6 000 €/m² de surface construite (article L.480-4 du Code de l'urbanisme) et à une obligation de remise en état, voire de démolition.\n:::",
        "## Les horaires à respecter\n\n### La réglementation sur le bruit\n\nEn règle générale, les travaux bruyants sont autorisés :\n\n- **Lundi à vendredi** : 8h à 20h\n- **Samedi** : 9h à 20h (ou 8h dans certaines communes)\n- **Dimanche et jours fériés** : travaux bruyants interdits sauf dérogation\n\n### Les règlements locaux\n\nCertaines communes ont des réglements plus restrictifs. Consultez l'arrêté municipal sur le bruit en mairie. En copropriété, le règlement peut imposer des restrictions supplémentaires (par exemple : pas de travaux le samedi après-midi).\n\n:::info Bon à savoir\nLe bruit de chantier est mesuré en émergence : le bruit des travaux ne doit pas dépasser le bruit ambiant de plus de 5 dB le jour et 3 dB la nuit (décret n° 2006-1099). En cas de plainte, un constat d'huissier peut être requis.\n:::",
        "## En copropriété et responsabilités\n\n### Les obligations en copropriété\n\n- **Prévenez le syndic** et les voisins au moins 15 jours avant le début des travaux\n- **Respectez le règlement de copropriété** (souvent plus strict que la loi)\n- Les travaux touchant les parties communes nécessitent un **vote en assemblée générale**\n- Protégez les parties communes (bâches dans l'ascenseur, protection de la cage d'escalier)\n\n### La responsabilité de l'artisan\n\nL'artisan est responsable des dommages causés pendant les travaux (responsabilité contractuelle). Il doit être assuré en RC professionnelle. Après les travaux :\n\n- **Garantie de parfait achèvement** : 1 an — tous les défauts signalés doivent être réparés\n- **Garantie biennale** : 2 ans — éléments d'équipement dissociables\n- **[Garantie décennale](/blog/garantie-decennale-tout-savoir)** : 10 ans — dommages structurels graves\n\nEn cas de [litige avec un artisan](/blog/litige-artisan-recours-mediation-justice), plusieurs voies de recours existent, de la médiation amiable à l'action en justice.\n\n:::tip Conseil pro\nAvant des travaux importants en copropriété, faites réaliser un constat d'huissier de l'état des parties communes (hall, escalier, ascenseur). Cela vous protège en cas de dégradation contestée par le syndic ou un voisin.\n:::\n\n:::takeaway\n- Pas d'autorisation pour les travaux intérieurs sans modification de structure\n- Déclaration préalable pour les modifications extérieures et extensions < 40 m²\n- Travaux bruyants : lundi-vendredi 8h-20h, samedi 9h-20h, interdit dimanche\n- En copropriété : prévenez syndic et voisins, respectez le règlement\n- L'artisan est responsable pendant 10 ans (garantie décennale)\n- Conservez tous les documents (devis, factures, PV de réception)\n:::",
    ],
    "image": "/images/blog/droits-travaux.jpg",
    "author": "Isabelle Renault",
    "authorBio": "Isabelle Renault, juriste spécialisée en droit de la construction et de l'immobilier, décrypte la réglementation pour les propriétaires.",
    "date": "2026-01-09",
    "updatedDate": "2026-02-06",
    "readTime": "12 min",
    "category": "Guides",
    "tags": ["Legislation", "Travaux", "Droits"],
    "faq": [
        {"question": "Peut-on faire des travaux le dimanche ?", "answer": "Les travaux bruyants sont interdits le dimanche et les jours fériés dans la plupart des communes. Les travaux silencieux (peinture, papier peint) sont tolérés. Vérifiez l'arrêté municipal de votre commune."},
        {"question": "Faut-il prévenir les voisins avant des travaux ?", "answer": "Ce n'est pas une obligation légale en maison individuelle, mais c'est fortement recommandé pour maintenir de bonnes relations de voisinage. En copropriété, c'est une obligation du règlement de copropriété."},
        {"question": "Qui est responsable si un artisan endommage la propriété d'un voisin ?", "answer": "L'artisan est responsable via son assurance RC professionnelle. Cependant, le maître d'ouvrage (vous) peut être mis en cause si vous avez choisi un artisan non assuré. Vérifiez toujours les assurances avant les travaux."},
    ],
})

with open('/tmp/articles_part4.json', 'w', encoding='utf-8') as f:
    json.dump(articles, f, ensure_ascii=False, indent=2)

print(f"Part 4: {len(articles)} articles written to /tmp/articles_part4.json")
