#!/usr/bin/env python3
"""Generate the transformed existing-articles.ts file."""
import json

articles = []

# ─── Article 1: comment-choisir-son-plombier ───
articles.append({
    "slug": "comment-choisir-son-plombier",
    "title": "Comment choisir son plombier : le guide complet",
    "excerpt": "Tous nos conseils pour trouver un plombier de confiance et éviter les arnaques. Vérifications, devis, assurances : tout ce qu'il faut savoir avant de faire appel à un professionnel.",
    "content": [
        "Choisir un plombier peut sembler simple, mais c'est une décision qui mérite une réflexion approfondie. Selon la Fédération française du bâtiment, plus de 15 % des litiges dans le secteur du BTP concernent la plomberie. Un mauvais choix peut entraîner des réparations coûteuses, des fuites persistantes ou même des dégâts des eaux dont la facture moyenne s'élève à 2 400 euros selon les assureurs. Voici notre guide complet pour vous aider à faire le bon choix et trouver un [plombier fiable](/services/plomberie) dès la première fois.",

        "## 1. Vérifiez les qualifications et certifications\n\n### Le minimum indispensable\n\nUn plombier professionnel doit posséder certaines certifications et qualifications attestant de son savoir-faire. Au minimum, il doit être titulaire d'un CAP Installateur sanitaire ou d'un CAP Installateur thermique, voire d'un BP (Brevet Professionnel) ou d'un BTS Fluides, Énergies, Domotique.\n\n### Les labels de qualité\n\nRecherchez les labels suivants :\n\n- **RGE** (Reconnu Garant de l'Environnement) : indispensable si vous envisagez des travaux liés à l'énergie, comme l'installation d'un [chauffe-eau thermodynamique](/blog/chauffage-solution-economique) ou d'une pompe à chaleur\n- **Qualibat** : certification attestant des compétences techniques de l'entreprise\n- **NF** : label de conformité aux normes françaises\n\n:::tip Conseil pro\nVérifiez la validité des certifications directement sur les sites officiels : qualibat.com pour Qualibat et france-renov.gouv.fr pour le label RGE. Un certificat expiré n'a aucune valeur.\n:::",

        "## 2. Demandez plusieurs devis détaillés\n\n### La règle des trois devis\n\nNe vous contentez jamais d'un seul devis. Comparez au moins trois propositions pour avoir une idée réaliste des prix du marché. Selon une étude de l'UFC-Que Choisir, les écarts de prix entre artisans peuvent atteindre 50 % pour une même prestation.\n\n### Ce que doit contenir un bon devis\n\nChaque devis doit obligatoirement mentionner :\n\n1. Les coordonnées complètes de l'entreprise et son numéro SIRET\n2. La description détaillée de chaque prestation\n3. Les quantités et prix unitaires des matériaux\n4. Le coût de la main-d'œuvre\n5. Le montant total HT et TTC avec le taux de TVA applicable\n6. La durée de validité du devis\n7. Les conditions et l'échéancier de paiement\n\n:::warning Attention\nMéfiez-vous des devis anormalement bas qui peuvent cacher des matériaux de mauvaise qualité, une absence d'assurance ou des coûts supplémentaires non annoncés. Un devis 30 % en dessous du marché est un signal d'alerte.\n:::\n\nPour approfondir l'analyse de vos devis, consultez notre guide sur [comment lire et comprendre un devis de travaux](/blog/devis-travaux-comprendre).",

        "## 3. Consultez les avis et références clients\n\n### Les avis en ligne\n\nLes avis en ligne sont précieux mais doivent être analysés avec discernement. Sur ServicesArtisans, tous nos artisans sont évalués par leurs clients après chaque intervention. Privilégiez les professionnels avec :\n\n- Une note supérieure à 4/5\n- Au moins 10 avis vérifiés\n- Des commentaires détaillés mentionnant la ponctualité, la propreté et la qualité du travail\n\n### Les références de chantier\n\nN'hésitez pas à demander des références de chantiers similaires au vôtre. Un plombier sérieux sera fier de vous montrer des photos de ses réalisations précédentes et de vous mettre en contact avec d'anciens clients satisfaits.\n\n:::info Bon à savoir\nLes avis Google, bien que populaires, sont moins fiables que ceux des plateformes spécialisées car ils ne sont pas systématiquement vérifiés. Privilégiez les plateformes qui exigent une preuve d'intervention avant de publier un avis.\n:::",

        "## 4. Vérifiez les assurances obligatoires\n\n### La responsabilité civile professionnelle\n\nUn plombier professionnel doit obligatoirement disposer d'une assurance responsabilité civile professionnelle (RC Pro). Cette assurance couvre les dommages causés à des tiers pendant l'intervention : dégât des eaux chez un voisin, détérioration d'un revêtement, blessure accidentelle.\n\n### La garantie décennale\n\nPour les travaux importants touchant au gros œuvre ou aux éléments indissociables du bâtiment (canalisations encastrées, système de chauffage central), la [garantie décennale](/blog/garantie-decennale-tout-savoir) est obligatoire. Elle couvre pendant 10 ans les dommages compromettant la solidité de l'ouvrage ou le rendant impropre à sa destination.\n\n:::warning Attention\nDemandez systématiquement une copie de l'attestation d'assurance en cours de validité avant le début des travaux. Un artisan qui refuse de la fournir ne doit pas être retenu, quel que soit son prix.\n:::",

        "## 5. Évaluez la réactivité et le professionnalisme\n\n### La communication, un critère clé\n\nLa communication est essentielle dans la relation avec votre plombier. Un bon professionnel :\n\n- Répond rapidement à vos demandes (sous 24 à 48 heures)\n- Se présente à l'heure aux rendez-vous\n- Explique clairement les travaux à réaliser et les différentes options\n- Vous tient informé de l'avancement du chantier\n- Fournit un devis écrit avant toute intervention\n\n### Les signaux d'alerte\n\nMéfiez-vous d'un artisan qui :\n\n- Refuse de fournir un devis écrit\n- Demande un acompte supérieur à 30 % du montant total\n- Exige un paiement en espèces\n- Ne dispose pas d'un numéro SIRET vérifiable\n- Fait du [démarchage à domicile](/blog/artisan-pas-cher-attention-arnaques) non sollicité",

        "## 6. Comprenez les tarifs et modes de facturation\n\n### Les différents modes de tarification\n\nLes plombiers facturent généralement selon trois modes :\n\n- **Au forfait** : prix global pour une prestation définie (le plus sécurisant pour vous)\n- **À l'heure** : tarif horaire + fournitures (attention aux dépassements)\n- **Au mètre linéaire** : pour les travaux de canalisation\n\n:::budget\n| Prestation | Prix moyen en 2026 |\n| Tarif horaire (province) | 40 - 70 € HT |\n| Tarif horaire (Île-de-France) | 60 - 90 € HT |\n| Débouchage canalisation | 80 - 250 € |\n| Remplacement robinet | 80 - 150 € |\n| Réparation de fuite | 100 - 300 € |\n| Installation chauffe-eau | 300 - 800 € (hors fournitures) |\n:::\n\nPour un panorama complet des tarifs, consultez notre article dédié sur le [prix d'un plombier en 2026](/blog/prix-plombier-2026-tarifs-horaires).",

        "## 7. Privilégiez le bouche-à-oreille et les plateformes vérifiées\n\n### Le réseau personnel\n\nLe bouche-à-oreille reste le moyen le plus fiable de trouver un bon plombier. Interrogez votre entourage : famille, amis, voisins, collègues. Une recommandation personnelle vaut souvent mieux que des dizaines d'avis en ligne.\n\n### Les plateformes spécialisées\n\nSur ServicesArtisans, chaque professionnel est [vérifié via le numéro SIREN](/blog/trouver-artisan-verifie-siren) auprès de l'INSEE. Nous contrôlons l'existence légale de l'entreprise, son statut d'activité et la validité de ses assurances.\n\n:::takeaway\n- Comparez au minimum 3 devis détaillés avant de vous engager\n- Vérifiez systématiquement le SIRET, les assurances et les qualifications\n- Privilégiez les artisans avec des avis vérifiés et un historique de chantiers\n- N'acceptez jamais un acompte supérieur à 30 % du montant total\n- Exigez un devis écrit et détaillé, même pour une petite intervention\n- La garantie décennale est obligatoire pour tous les travaux touchant au bâti\n:::",
    ],
    "image": "/images/blog/plombier.jpg",
    "author": "Sophie Martin",
    "authorBio": "Sophie Martin, rédactrice spécialisée en rénovation et habitat, accompagne les particuliers dans leurs projets depuis plus de 8 ans.",
    "date": "2026-01-15",
    "updatedDate": "2026-02-10",
    "readTime": "12 min",
    "category": "Conseils",
    "tags": ["Plomberie", "Conseils", "Artisans"],
    "faq": [
        {"question": "Comment vérifier qu'un plombier est bien assuré ?", "answer": "Demandez une copie de son attestation d'assurance RC professionnelle et de sa garantie décennale. Vérifiez que les dates de validité couvrent la période des travaux. Vous pouvez également contacter directement l'assureur mentionné sur l'attestation pour confirmer sa validité."},
        {"question": "Quel est le tarif moyen d'un plombier en 2026 ?", "answer": "Le tarif horaire moyen se situe entre 40 et 70 € HT en province, et entre 60 et 90 € HT en Île-de-France. Ces tarifs peuvent doubler en cas d'intervention d'urgence (nuit, week-end, jours fériés). Les fournitures sont généralement facturées en supplément."},
        {"question": "Un plombier peut-il refuser de fournir un devis ?", "answer": "Non. Depuis le décret du 28 août 2015, tout professionnel doit remettre un devis gratuit pour les travaux dont le montant estimé dépasse 150 €. Pour les dépannages urgents, un ordre de réparation peut remplacer le devis, mais le montant doit être annoncé au préalable."},
        {"question": "Que faire si le plombier ne respecte pas le devis signé ?", "answer": "Le devis signé a valeur de contrat. En cas de surfacturation, adressez une réclamation par lettre recommandée. Si le litige persiste, vous pouvez saisir le médiateur de la consommation, puis le tribunal judiciaire. Conservez tous les documents (devis, factures, échanges écrits)."},
    ],
})

# ─── Article 2: renovation-energetique-aides-2026 ───
articles.append({
    "slug": "renovation-energetique-aides-2026",
    "title": "Rénovation énergétique : toutes les aides en 2026",
    "excerpt": "MaPrimeRénov', CEE, éco-PTZ... Tour d'horizon complet des aides financières pour financer vos travaux de rénovation énergétique en 2026, avec les montants actualisés et les conditions d'éligibilité.",
    "content": [
        "La rénovation énergétique est plus que jamais au cœur des préoccupations des Français. Avec la hausse continue des prix de l'énergie — le tarif réglementé de l'électricité a augmenté de plus de 40 % entre 2022 et 2025 — et le renforcement des obligations liées au [DPE (Diagnostic de Performance Énergétique)](/blog/audit-energetique-dpe-obligations-2026), rénover son logement est devenu une nécessité économique et environnementale. Bonne nouvelle : en 2026, un arsenal d'aides financières permet de couvrir jusqu'à 90 % du coût des travaux pour les ménages les plus modestes. Voici un tour d'horizon complet pour ne manquer aucune opportunité.",

        "## MaPrimeRénov' : l'aide phare de l'État\n\n### Principe et fonctionnement\n\nMaPrimeRénov' est la principale aide de l'État pour la rénovation énergétique. Gérée par l'Agence Nationale de l'Habitat (ANAH), elle est accessible à tous les propriétaires, qu'ils soient occupants ou bailleurs, sans condition de revenus. Le montant de l'aide dépend de votre catégorie de revenus et du type de travaux réalisés.\n\n### Les quatre catégories de revenus\n\nLes ménages sont classés en quatre catégories, déterminées par le revenu fiscal de référence :\n\n- **Bleu** (très modestes) : aides maximales, jusqu'à 90 % du coût des travaux\n- **Jaune** (modestes) : aides importantes, jusqu'à 75 %\n- **Violet** (intermédiaires) : aides significatives, jusqu'à 60 %\n- **Rose** (aisés) : aides réduites mais toujours disponibles, jusqu'à 40 %\n\n### Les deux parcours MaPrimeRénov'\n\nDepuis 2024, MaPrimeRénov' se décline en deux parcours :\n\n1. **Parcours par geste** : pour un ou deux travaux ciblés (isolation, changement de chauffage)\n2. **Parcours accompagné** : pour une rénovation globale visant un gain d'au moins 2 classes DPE\n\n:::tip Conseil pro\nLe Parcours accompagné est plus avantageux financièrement. Pour une maison classée F passant en C, l'aide peut atteindre 63 000 € pour les ménages très modestes. Un Accompagnateur Rénov' agréé est obligatoire pour ce parcours.\n:::\n\n:::budget\n| Travaux | Aide MaPrimeRénov' (ménage modeste) |\n| Isolation des combles | 25 €/m² |\n| Isolation des murs (ITE) | 75 €/m² |\n| Pompe à chaleur air-eau | 5 000 € |\n| Chaudière biomasse | 7 000 € |\n| Fenêtres double vitrage | 100 €/fenêtre |\n| VMC double flux | 2 500 € |\n:::",

        "## Les CEE (Certificats d'Économies d'Énergie)\n\n### Un financement complémentaire essentiel\n\nLes fournisseurs d'énergie (EDF, Engie, TotalEnergies) sont obligés par la loi de promouvoir l'efficacité énergétique auprès de leurs clients. Pour remplir cette obligation, ils proposent des primes, appelées CEE, pour financer une partie de vos travaux. Ces aides sont **cumulables avec MaPrimeRénov'**.\n\n### Les montants en 2026\n\nLes primes CEE varient selon la zone climatique et la nature des travaux :\n\n- Isolation des combles perdus : 10 à 12 €/m²\n- Pompe à chaleur air-eau : 2 500 à 4 000 €\n- Chaudière biomasse : 3 000 à 5 000 €\n- Fenêtres double vitrage : 80 à 120 € par fenêtre\n\n:::warning Attention\nVous devez impérativement vous inscrire au dispositif CEE **avant** de signer votre devis. Si vous signez d'abord et demandez la prime ensuite, votre dossier sera refusé. C'est l'erreur la plus fréquente des particuliers.\n:::\n\nPour un guide détaillé sur les CEE, consultez notre article sur les [Certificats d'Économies d'Énergie](/blog/certificats-economies-energie-cee-guide).",

        "## L'éco-prêt à taux zéro (éco-PTZ)\n\n### Un emprunt sans intérêts\n\nL'éco-PTZ vous permet d'emprunter jusqu'à 50 000 euros sans intérêts pour financer vos travaux de rénovation énergétique. Prolongé jusqu'au 31 décembre 2027, il est accessible sans condition de revenus et permet de financer le reste à charge après déduction des aides.\n\n### Les plafonds selon les travaux\n\n| Type de travaux | Plafond éco-PTZ |\n| --- | --- |\n| Action unique | 15 000 € |\n| Bouquet de 2 travaux | 25 000 € |\n| Bouquet de 3 travaux ou plus | 30 000 € |\n| Rénovation globale (gain ≥ 35 %) | 50 000 € |\n\nLa durée de remboursement va jusqu'à 15 ans pour une action unique et 20 ans pour une rénovation globale.\n\n:::info Bon à savoir\nDepuis 2023, un éco-PTZ simplifié permet de financer directement le reste à charge de MaPrimeRénov'. Le formulaire est pré-rempli avec les informations de votre dossier, ce qui accélère considérablement la procédure.\n:::\n\nRetrouvez tous les détails dans notre [guide complet de l'éco-PTZ 2026](/blog/eco-pret-taux-zero-guide-complet-2026).",

        "## TVA réduite à 5,5 %\n\n### Une économie automatique\n\nLes travaux d'amélioration énergétique bénéficient d'une TVA réduite à 5,5 % au lieu de 20 %, soit une économie de 14,5 points. Pour des travaux de 20 000 € HT, la différence est de 2 900 € ! Cette réduction s'applique automatiquement sur la facture de l'artisan.\n\n### Conditions d'éligibilité\n\n- Le logement doit être achevé depuis plus de 2 ans\n- Les travaux doivent concerner l'amélioration de la performance énergétique\n- Vous devez remettre à l'artisan une attestation simplifiée (cerfa n° 1300-SD)\n\nPour comprendre les différents taux, consultez notre guide sur la [TVA réduite pour travaux](/blog/tva-reduite-travaux-renovation-guide).",

        "## Les aides locales et le cumul stratégique\n\n### Des aides complémentaires précieuses\n\nDe nombreuses collectivités — régions, départements, métropoles, communes — proposent des aides complémentaires souvent méconnues. Ces aides peuvent représenter plusieurs milliers d'euros supplémentaires. Renseignez-vous auprès de votre mairie, de l'ADIL de votre département ou de l'Espace Conseil France Rénov' le plus proche.\n\n### Comment optimiser le cumul des aides ?\n\nToutes ces aides sont cumulables entre elles. Voici la stratégie optimale :\n\n1. **Faites réaliser un audit énergétique** pour identifier les travaux prioritaires\n2. **Inscrivez-vous aux CEE** avant toute signature de devis\n3. **Déposez votre dossier MaPrimeRénov'** avec les devis d'artisans RGE\n4. **Demandez l'éco-PTZ** pour financer le reste à charge\n5. **Vérifiez les aides locales** pour compléter le financement\n\n:::info Bon à savoir\nLe total des aides publiques ne peut pas dépasser 100 % du coût TTC des travaux. En pratique, pour les ménages très modestes, le reste à charge peut descendre à moins de 10 % du montant total.\n:::\n\nPour une stratégie complète de cumul, consultez notre [guide stratégique du cumul des aides en 2026](/blog/aides-renovation-2026-cumul-guide).\n\n:::takeaway\n- MaPrimeRénov' Parcours accompagné offre les aides les plus généreuses (jusqu'à 63 000 €)\n- Les CEE sont cumulables et doivent être demandés avant la signature du devis\n- L'éco-PTZ permet d'emprunter jusqu'à 50 000 € sans intérêts\n- La TVA à 5,5 % s'applique automatiquement aux travaux d'amélioration énergétique\n- Les aides locales sont un bonus souvent méconnu\n- Tous les travaux doivent être réalisés par un artisan RGE pour être éligibles\n:::",
    ],
    "image": "/images/blog/renovation.jpg",
    "author": "Claire Dubois",
    "authorBio": "Claire Dubois, experte en économie de la construction, analyse les prix du marché et les aides financières pour informer les consommateurs.",
    "date": "2026-01-10",
    "updatedDate": "2026-02-08",
    "readTime": "14 min",
    "category": "Aides & Subventions",
    "tags": ["Renovation", "Aides", "Energie"],
    "faq": [
        {"question": "Peut-on cumuler MaPrimeRénov' et les CEE ?", "answer": "Oui, MaPrimeRénov' et les CEE sont parfaitement cumulables. Vous pouvez également y ajouter l'éco-PTZ, la TVA réduite à 5,5 % et les aides locales. Le total des aides ne peut toutefois pas dépasser 100 % du coût TTC des travaux."},
        {"question": "Faut-il obligatoirement un artisan RGE pour bénéficier des aides ?", "answer": "Oui, pour toutes les aides à la rénovation énergétique (MaPrimeRénov', CEE, éco-PTZ, TVA 5,5 %), les travaux doivent être réalisés par un artisan certifié RGE (Reconnu Garant de l'Environnement). Vérifiez la validité du certificat sur france-renov.gouv.fr."},
        {"question": "Quels sont les travaux les plus rentables en rénovation énergétique ?", "answer": "L'isolation des combles offre le meilleur rapport coût/économies : pour un investissement de 20 à 50 €/m², vous pouvez réduire vos déperditions thermiques de 25 à 30 %. Le remplacement d'une vieille chaudière par une pompe à chaleur divise par 3 la facture de chauffage."},
        {"question": "Combien de temps faut-il pour obtenir MaPrimeRénov' ?", "answer": "Le délai d'instruction est de 2 à 4 semaines pour le Parcours par geste et de 4 à 8 semaines pour le Parcours accompagné. Ne commencez jamais les travaux avant d'avoir reçu la notification d'accord."},
    ],
})

# ─── Article 3: tendances-salle-de-bain-2026 ───
articles.append({
    "slug": "tendances-salle-de-bain-2026",
    "title": "Les tendances salle de bain en 2026",
    "excerpt": "Couleurs, matériaux, équipements innovants... Découvrez les tendances qui transforment la salle de bain en un véritable espace de bien-être cette année.",
    "content": [
        "La salle de bain est devenue un véritable espace de bien-être, dépassant largement sa fonction utilitaire d'antan. Les Français y consacrent en moyenne 6 000 à 12 000 euros lors d'une [rénovation complète](/blog/renovation-salle-de-bain-budget-etapes), et les tendances 2026 reflètent cette exigence croissante de confort et d'esthétique. Entre matériaux naturels, technologies connectées et design biophilique, voici les grandes orientations qui marqueront cette année.",

        "## Les matériaux naturels : authenticité et durabilité\n\n### Le retour du brut et de l'organique\n\nPierre naturelle, bois traité, terrazzo, béton ciré... Les matériaux bruts et authentiques dominent les salles de bain modernes. Ils apportent une touche chaleureuse et contemporaine, loin des ambiances cliniques des décennies précédentes.\n\n### Le travertin : la star de 2026\n\nLe travertin, pierre calcaire aux tonalités chaudes, s'impose comme le matériau phare de l'année. Utilisé en revêtement mural, en plan de vasque ou en receveur de douche, il apporte une élégance intemporelle. Comptez 60 à 120 €/m² pour un travertin de qualité, pose comprise.\n\n### Le bois traité et le teck\n\nLe bois fait une entrée remarquée dans la salle de bain, à condition d'être correctement traité. Le teck massif pour les meubles de vasque, le chêne huilé pour les étagères, le bambou pour les accessoires — ces essences résistent naturellement à l'humidité.\n\n:::info Bon à savoir\nLe bois brut nécessite un traitement hydrofuge spécifique pour résister à l'humidité de la salle de bain. Optez pour des essences naturellement résistantes (teck, bambou, iroko) ou un bois certifié PEFC/FSC avec traitement en usine.\n:::",

        "## Les couleurs : chaleur et sérénité\n\n### Terracotta et tons chauds\n\nLes teintes chaudes comme le terracotta, le caramel et l'ocre doré remplacent les blancs cliniques. Ces couleurs créent une ambiance apaisante et cocooning, rappelant les tons de la terre et de la Méditerranée.\n\n### Le vert sauge et les tons naturels\n\nLes verts doux — sauge, olive, céladon — s'imposent comme la palette complémentaire idéale. Associés à des éléments en bois et en pierre, ils renforcent l'atmosphère naturelle et zen de la salle de bain.\n\n:::tip Conseil pro\nPour une salle de bain intemporelle, adoptez la règle 60-30-10 : 60 % de couleur principale (murs, sol), 30 % de couleur secondaire (meubles, carrelage accent), 10 % de couleur d'accentuation (accessoires, robinetterie).\n:::",

        "## La douche à l'italienne : toujours incontournable\n\n### Un design qui traverse les années\n\nLa douche à l'italienne reste incontournable en 2026. Son design épuré, sans marche ni rebord, offre un maximum d'espace et une esthétique minimaliste. Elle répond également aux [normes d'accessibilité PMR](/blog/accessibilite-pmr-logement-normes), ce qui en fait un choix pérenne.\n\n### Les évolutions 2026\n\n- **La douche ouverte (walk-in)** : sans porte ni paroi, avec un simple receveur extra-plat\n- **La niche encastrée** : pour ranger shampooings et savons sans étagère visible\n- **Le caniveau linéaire** : évacuation discrète intégrée au sol\n- **La pomme de tête XXL** : format 40 x 40 cm pour un effet pluie enveloppant\n\n:::budget\n| Type d'installation | Prix moyen (pose comprise) |\n| Douche à l'italienne standard | 2 500 - 5 000 € |\n| Douche walk-in haut de gamme | 4 000 - 8 000 € |\n| Remplacement baignoire par douche | 3 000 - 7 000 € |\n:::",

        "## Les robinetteries et le design biophilique\n\n### Le noir mat : le classique moderne\n\nLe noir mat s'impose comme la finition tendance pour les robinets, pommeaux de douche et accessoires. Un choix élégant qui contraste avec les tons clairs des murs et du carrelage.\n\n### Le laiton brossé et le doré\n\nLe laiton brossé apporte une touche de chaleur et de sophistication. Moins brillant que le doré traditionnel, il vieillit avec élégance et s'accorde parfaitement avec les matériaux naturels.\n\n### Le design biophilique\n\nLe design biophilique consiste à intégrer des éléments naturels dans l'espace intérieur pour favoriser le bien-être. Dans la salle de bain, cela se traduit par des plantes tropicales adaptées à l'humidité, un éclairage naturel et des matériaux organiques. La grande nouveauté 2026 : les murs végétaux en mousse stabilisée, qui ne nécessitent ni arrosage ni entretien. Comptez 150 à 400 €/m².\n\n:::takeaway\n- Les matériaux naturels (travertin, teck, terrazzo) dominent les tendances 2026\n- Les couleurs chaudes (terracotta, sauge) remplacent le blanc clinique\n- La douche à l'italienne évolue vers le format walk-in ouvert\n- Le noir mat et le laiton brossé sont les finitions robinetterie phares\n- Le design biophilique et les technologies connectées enrichissent l'expérience\n- Un budget de 8 000 à 15 000 € permet une rénovation tendance et complète\n:::",
    ],
    "image": "/images/blog/salle-de-bain.jpg",
    "author": "Thomas Bernard",
    "authorBio": "Thomas Bernard, architecte d'intérieur et consultant en rénovation, conseille les propriétaires sur l'optimisation de leur habitat.",
    "date": "2026-01-08",
    "updatedDate": "2026-02-05",
    "readTime": "13 min",
    "category": "Inspiration",
    "tags": ["Salle de bain", "Tendances", "Decoration"],
    "faq": [
        {"question": "Quel budget prévoir pour une salle de bain tendance en 2026 ?", "answer": "Pour une rénovation complète intégrant les tendances actuelles, prévoyez entre 8 000 et 15 000 € pour une salle de bain de 5 à 8 m². Ce budget comprend la dépose, la plomberie, le carrelage, les sanitaires et les finitions."},
        {"question": "Le travertin est-il adapté à la salle de bain ?", "answer": "Oui, à condition de le traiter avec un hydrofuge adapté. Le travertin est une pierre calcaire naturellement poreuse qui nécessite un traitement d'imprégnation initial puis un entretien régulier."},
        {"question": "La douche à l'italienne nécessite-t-elle un sol spécifique ?", "answer": "Oui, elle nécessite une chape avec une pente de 1 à 2 % vers l'évacuation et une étanchéité renforcée (système SPEC ou membrane). Vérifiez que la dalle permet l'encastrement du receveur."},
    ],
})

# ─── Article 4: devis-travaux-comprendre ───
articles.append({
    "slug": "devis-travaux-comprendre",
    "title": "Comment lire et comprendre un devis de travaux",
    "excerpt": "Les éléments essentiels à vérifier avant de signer un devis pour éviter les mauvaises surprises. Mentions obligatoires, pièges à éviter et conseils de négociation.",
    "content": [
        "Un devis de travaux est un document essentiel qui engage juridiquement les deux parties une fois signé. Pourtant, selon une enquête de l'UFC-Que Choisir, plus de 40 % des particuliers signent un devis sans en vérifier toutes les mentions. Résultat : surfacturations, travaux incomplets ou litiges coûteux. Savoir lire et comprendre un devis est crucial pour protéger vos intérêts et maîtriser votre budget.",

        "## Les mentions obligatoires d'un devis\n\n### Ce que dit la loi\n\nSelon l'arrêté du 24 janvier 2017, un devis de travaux doit comporter des mentions obligatoires. L'absence de l'une d'entre elles est un signal d'alerte.\n\n### La liste complète\n\n1. **La date d'établissement** du devis\n2. **Les coordonnées complètes** de l'artisan : nom, adresse, téléphone, email\n3. **Le numéro SIRET** de l'entreprise (14 chiffres)\n4. **L'assurance professionnelle** : nom de l'assureur, numéro de police\n5. **Le détail précis des prestations** : nature, quantité, prix unitaire\n6. **Le prix des matériaux** : désignation, marque, référence, quantité\n7. **Le coût de la main-d'œuvre** : tarif horaire ou forfait\n8. **Le montant total HT et TTC** avec indication du taux de TVA\n9. **La durée de validité** du devis\n10. **Les conditions de paiement** : échéancier, acompte, solde\n11. **La durée estimée des travaux**\n\n:::warning Attention\nUn devis sans numéro SIRET est un signal d'alerte majeur. Cela peut signifier que l'artisan travaille au noir. Vérifiez toujours le SIRET sur [ServicesArtisans](/blog/trouver-artisan-verifie-siren) ou sur sirene.fr.\n:::",

        "## Le détail des prestations\n\n### Exigez la précision\n\nChaque ligne du devis doit décrire précisément la prestation : nature des travaux, quantités exactes, matériaux utilisés avec marque et référence, prix unitaire et prix total par ligne.\n\n### Les formulations à refuser\n\nMéfiez-vous des descriptions vagues telles que :\n\n- « Travaux divers » ou « travaux de rénovation »\n- « Fournitures courantes » ou « matériaux standards »\n- « Selon les besoins du chantier »\n\n:::tip Conseil pro\nDemandez systématiquement les références exactes des matériaux proposés. Cela vous permet de vérifier les prix en magasin et d'avoir la certitude de la qualité posée.\n:::",

        "## La TVA applicable\n\n### Les trois taux en vigueur\n\nLe taux de TVA varie selon le type de travaux et l'ancienneté du logement :\n\n- **20 %** : constructions neuves et logements de moins de 2 ans\n- **10 %** : travaux de rénovation dans les logements de plus de 2 ans\n- **5,5 %** : travaux d'amélioration de la performance énergétique\n\n:::info Bon à savoir\nUn même devis peut comporter plusieurs taux de TVA si les travaux sont de nature différente. Vérifiez que l'artisan ventile correctement sa facture. Consultez notre [guide TVA travaux](/blog/tva-reduite-travaux-renovation-guide) pour tous les cas de figure.\n:::",

        "## Les conditions de paiement\n\n### L'échéancier type\n\nLe devis doit préciser clairement l'échéancier de paiement :\n\n1. **Acompte à la signature** : 20 à 30 % du montant total\n2. **Versement intermédiaire** : 30 à 40 % en cours de travaux\n3. **Solde à la réception** : 30 à 50 %, après vérification des travaux\n\n### La retenue de garantie de 5 %\n\nPour les marchés importants, la loi du 16 juillet 1971 autorise le maître d'ouvrage à retenir 5 % du montant total jusqu'à la [levée des réserves](/blog/reception-travaux-proces-verbal-reserves).\n\n:::warning Attention\nNe versez jamais plus de 30 % d'acompte à la signature. Un artisan qui exige 50 % ou plus d'avance présente un risque financier majeur. Refusez systématiquement les demandes de paiement en espèces au-delà de 1 000 €.\n:::",

        "## Les pièges courants et la négociation\n\n### Les pièges à déjouer\n\n- **Le devis trop vague** : un total global sans décomposition empêche toute vérification\n- **Le devis « compétitif » incomplet** : un prix bas cache souvent des prestations manquantes\n- **Les travaux supplémentaires non encadrés** : exigez un accord écrit pour tout ajout\n- **L'absence de date de fin** : sans délai, aucun levier en cas de retard\n\n### Leviers de négociation\n\n- **Le prix des fournitures** : proposez de les acheter vous-même\n- **Le regroupement de travaux** : un chantier global est plus rentable\n- **Le calendrier** : un artisan avec un creux peut consentir 5 à 10 % de remise\n\nPour aller plus loin, consultez notre guide [Devis travaux : comment comparer et choisir](/blog/devis-travaux-comment-comparer-choisir).\n\n:::takeaway\n- Vérifiez les mentions obligatoires avant de signer tout devis\n- Exigez un détail ligne par ligne avec références des matériaux\n- Contrôlez le taux de TVA applicable à chaque poste\n- Ne versez jamais plus de 30 % d'acompte\n- Comparez au moins 3 devis pour le même périmètre de travaux\n:::",
    ],
    "image": "/images/blog/devis.jpg",
    "author": "Jean-Pierre Duval",
    "authorBio": "Jean-Pierre Duval, ancien artisan du bâtiment reconverti en journaliste, partage son expertise terrain pour aider les propriétaires à faire les bons choix.",
    "date": "2026-01-05",
    "updatedDate": "2026-02-06",
    "readTime": "13 min",
    "category": "Conseils",
    "tags": ["Devis", "Travaux", "Conseils"],
    "faq": [
        {"question": "Un devis signé peut-il être modifié en cours de chantier ?", "answer": "Un devis signé a valeur de contrat. Toute modification doit faire l'objet d'un avenant écrit signé par les deux parties. L'artisan doit vous présenter un devis complémentaire que vous êtes libre d'accepter ou de refuser."},
        {"question": "Combien de temps un devis est-il valable ?", "answer": "La durée de validité doit être mentionnée sur le devis, en général 1 à 3 mois. Passé ce délai, l'artisan peut modifier ses tarifs."},
        {"question": "Peut-on annuler un devis après l'avoir signé ?", "answer": "Si le devis a été signé à votre domicile (démarchage), vous disposez d'un délai de rétractation de 14 jours. Sinon, l'annulation constitue une rupture de contrat."},
        {"question": "Un devis gratuit engage-t-il à quelque chose ?", "answer": "Non, un devis gratuit n'engage à rien tant qu'il n'est pas signé. Depuis 2017, les devis pour travaux de plus de 150 € doivent être gratuits."},
    ],
})

# ─── Article 5: isolation-thermique-guide ───
articles.append({
    "slug": "isolation-thermique-guide",
    "title": "Guide complet de l'isolation thermique",
    "excerpt": "Tout savoir sur l'isolation de votre maison : techniques, matériaux, performances et économies à la clé. Le guide pour réduire votre facture énergétique.",
    "content": [
        "L'isolation thermique est le premier levier pour réduire votre facture énergétique. Un logement bien isolé peut diminuer votre consommation de chauffage de 25 à 30 %, soit une économie de 400 à 700 euros par an pour une maison de 100 m². Avec la hausse des prix de l'énergie et les nouvelles obligations du [DPE](/blog/audit-energetique-dpe-obligations-2026), isoler son logement est devenu un investissement incontournable. Voici le guide complet pour comprendre les différentes techniques et faire les bons choix.",

        "## L'isolation des combles : la priorité absolue\n\n### Pourquoi commencer par les combles ?\n\nLes combles représentent jusqu'à 30 % des déperditions thermiques d'un logement. C'est la zone où la chaleur s'échappe le plus rapidement, car l'air chaud monte naturellement. Isoler les combles offre donc le meilleur retour sur investissement.\n\n### Combles perdus : le soufflage\n\nL'isolation des combles perdus par soufflage est l'une des solutions les plus efficaces et les moins coûteuses. La laine de verre, la laine de roche ou la ouate de cellulose est projetée en vrac sur le plancher des combles, créant un matelas isolant continu sans pont thermique.\n\n- **Performance** : résistance thermique R ≥ 7 m².K/W (recommandation)\n- **Prix** : 20 à 50 €/m²\n- **Durée des travaux** : une demi-journée pour une maison standard\n\n### Combles aménagés : l'isolation par l'intérieur\n\nPour les combles aménageables, l'isolation se fait sous rampants avec des panneaux rigides ou semi-rigides. Une lame d'air ventilée entre l'isolant et la couverture est indispensable pour éviter la condensation.\n\n:::tip Conseil pro\nPrivilégiez une isolation en double couche croisée pour éliminer les ponts thermiques au niveau des chevrons. La première couche se place entre les chevrons, la seconde perpendiculairement en dessous.\n:::",

        "## L'isolation des murs : intérieur ou extérieur ?\n\n### L'isolation par l'extérieur (ITE)\n\nL'ITE est la solution la plus performante car elle supprime tous les ponts thermiques et préserve l'inertie thermique des murs. Elle transforme également l'aspect extérieur du bâtiment, ce qui en fait une solution idéale lors d'un [ravalement de façade](/blog/reglementation-ravalement-facade-obligations).\n\n- **Performance** : R ≥ 3,7 m².K/W (minimum pour les aides)\n- **Prix** : 100 à 200 €/m²\n- **Avantages** : pas de perte de surface habitable, suppression des ponts thermiques\n- **Inconvénients** : coût élevé, modification de l'aspect extérieur\n\n### L'isolation par l'intérieur (ITI)\n\nMoins coûteuse que l'ITE, l'ITI réduit légèrement la surface habitable (5 à 7 cm par mur). Elle est idéale quand l'ITE n'est pas possible : bâtiment classé, copropriété refusant les travaux extérieurs, façade en pierre apparente à conserver.\n\n- **Performance** : R ≥ 3,7 m².K/W\n- **Prix** : 40 à 90 €/m²\n- **Avantages** : coût modéré, pas d'autorisation d'urbanisme\n- **Inconvénients** : perte de surface, ponts thermiques résiduels\n\n:::warning Attention\nL'isolation par l'intérieur nécessite impérativement la pose d'un pare-vapeur côté chaud (intérieur) pour éviter la condensation dans l'isolant. Un pare-vapeur mal posé peut provoquer des moisissures invisibles et dégrader la qualité de l'air.\n:::",

        "## Les matériaux isolants : comparatif\n\n### Les isolants minéraux\n\n- **Laine de verre** : le plus répandu, bon rapport performance/prix (R = 2,5 à 3 pour 10 cm), sensible à l'humidité\n- **Laine de roche** : meilleure résistance au feu et à l'humidité, légèrement plus cher\n\n### Les isolants synthétiques\n\n- **Polystyrène expansé (PSE)** : très bon marché, résistant à l'humidité, mais faible inertie thermique\n- **Polystyrène extrudé (XPS)** : haute résistance mécanique, idéal pour les sols et fondations\n- **Polyuréthane** : la meilleure performance thermique par épaisseur (lambda 0,022), mais coût élevé\n\n### Les isolants biosourcés\n\n- **Ouate de cellulose** : excellent rapport qualité/prix, bonne inertie thermique, issu du recyclage\n- **Fibre de bois** : très bonne inertie thermique (confort d'été), bilan carbone favorable\n- **Chanvre** : bon régulateur d'humidité, produit en France\n- **Laine de mouton** : excellente régulation hygrométrique, production locale possible\n\n:::info Bon à savoir\nLes isolants biosourcés sont favorisés par la [RE2020](/blog/reglementation-thermique-re2020-impact) en raison de leur faible empreinte carbone. Ils offrent également un meilleur confort d'été grâce à leur inertie thermique supérieure.\n:::",

        "## Les aides financières pour l'isolation\n\n### Un financement généreux\n\nL'isolation thermique est éligible à toutes les aides à la rénovation énergétique :\n\n- **MaPrimeRénov'** : de 15 à 75 €/m² selon les revenus et le type d'isolation\n- **CEE** : 10 à 12 €/m² pour les combles, 15 à 25 €/m² pour les murs\n- **TVA réduite** : 5,5 % au lieu de 20 %\n- **Éco-PTZ** : jusqu'à 15 000 € pour une action unique\n\nCes aides peuvent couvrir jusqu'à 75 % du coût des travaux selon vos revenus. Consultez notre guide complet des [aides à la rénovation énergétique en 2026](/blog/renovation-energetique-aides-2026).\n\n:::budget\n| Type d'isolation | Prix moyen | Aide MaPrimeRénov' (modeste) |\n| Combles perdus (soufflage) | 20 - 50 €/m² | 25 €/m² |\n| Murs par l'extérieur (ITE) | 100 - 200 €/m² | 75 €/m² |\n| Murs par l'intérieur (ITI) | 40 - 90 €/m² | 25 €/m² |\n| Sol / plancher bas | 30 - 70 €/m² | 15 €/m² |\n:::\n\n:::takeaway\n- Les combles sont la priorité n°1 : jusqu'à 30 % de déperditions\n- L'ITE est la solution la plus performante mais la plus coûteuse\n- Les isolants biosourcés offrent un meilleur confort d'été\n- Les aides peuvent couvrir jusqu'à 75 % du coût des travaux\n- Faites toujours réaliser les travaux par un artisan RGE\n- Exigez une résistance thermique R ≥ 7 pour les combles et R ≥ 3,7 pour les murs\n:::",
    ],
    "image": "/images/blog/isolation.jpg",
    "author": "Marc Lefebvre",
    "authorBio": "Marc Lefebvre, ingénieur thermicien et rédacteur technique, vulgarise les aspects complexes de la rénovation énergétique.",
    "date": "2026-01-02",
    "updatedDate": "2026-02-04",
    "readTime": "14 min",
    "category": "Guides",
    "tags": ["Isolation", "Energie", "Renovation"],
    "faq": [
        {"question": "Quelle est la meilleure isolation pour une maison ancienne ?", "answer": "Pour une maison ancienne, l'ITE est la solution idéale car elle traite tous les ponts thermiques. Si l'ITE n'est pas possible (façade en pierre, copropriété), l'ITI avec un isolant perspirant (fibre de bois, chanvre) permet de préserver la capacité du mur à réguler l'humidité."},
        {"question": "L'isolation des combles est-elle rentable ?", "answer": "C'est l'investissement le plus rentable en rénovation énergétique. Pour un coût de 1 500 à 3 000 € (maison de 80 m²), vous économisez 300 à 500 €/an sur le chauffage. Le retour sur investissement est atteint en 3 à 5 ans, hors aides financières."},
        {"question": "Faut-il un artisan RGE pour l'isolation ?", "answer": "Oui, obligatoirement si vous souhaitez bénéficier des aides (MaPrimeRénov', CEE, TVA 5,5 %). Même sans aides, un artisan RGE garantit une mise en œuvre conforme aux règles de l'art et aux DTU en vigueur."},
        {"question": "Quelle épaisseur d'isolant pour les combles ?", "answer": "Pour atteindre la résistance thermique R = 7 recommandée, comptez environ 30 cm de laine de verre, 28 cm de ouate de cellulose ou 32 cm de fibre de bois. L'épaisseur dépend du lambda (conductivité thermique) de l'isolant choisi."},
    ],
})

# ─── Article 6: electricite-normes-securite ───
articles.append({
    "slug": "electricite-normes-securite",
    "title": "Électricité : les normes de sécurité à connaître",
    "excerpt": "NF C 15-100, mise aux normes, diagnostic... Tout ce qu'il faut savoir sur l'électricité de votre logement pour garantir la sécurité de votre famille.",
    "content": [
        "L'électricité est un domaine où la sécurité est primordiale. Selon l'Observatoire National de la Sécurité Électrique (ONSE), les installations électriques défaillantes sont responsables de plus de 50 000 incendies domestiques chaque année en France, causant environ 3 000 blessés et 80 décès. Un tiers des logements français présente au moins une anomalie électrique. Comprendre les normes en vigueur est essentiel pour protéger votre famille et votre patrimoine.",

        "## La norme NF C 15-100 : la référence\n\n### Qu'est-ce que la NF C 15-100 ?\n\nC'est la norme de référence pour les installations électriques dans les logements en France. Elle définit les règles de conception, de réalisation et d'entretien des installations électriques basse tension. Régulièrement mise à jour (dernière révision en 2015, amendement A5 en 2020), elle s'applique à toutes les installations neuves et aux rénovations complètes.\n\n### Les principales exigences\n\nLa NF C 15-100 impose notamment :\n\n- Un tableau électrique avec disjoncteur différentiel 30 mA sur tous les circuits\n- Un nombre minimum de prises par pièce (5 dans un séjour de 20 m², 3 dans une chambre)\n- Des circuits dédiés pour les appareils de forte puissance (four, lave-linge, plaques)\n- Une protection parafoudre en zone à risque (AQ2)\n- Un espace technique électrique du logement (ETEL) aux dimensions normalisées\n\n:::info Bon à savoir\nLa NF C 15-100 n'impose pas la mise aux normes des installations existantes. Cependant, en cas de rénovation importante ou de vente, un diagnostic électrique peut révéler des anomalies qu'il est fortement recommandé de corriger.\n:::",

        "## Le diagnostic électrique obligatoire\n\n### Quand est-il obligatoire ?\n\nLe diagnostic électrique est obligatoire :\n\n- Pour la **vente** d'un logement dont l'installation a plus de 15 ans (validité : 3 ans)\n- Pour la **location** d'un logement dont l'installation a plus de 15 ans (validité : 6 ans)\n\n### Que vérifie-t-il ?\n\nLe diagnostiqueur certifié contrôle 87 points selon la norme XP C 16-600, répartis en 6 grands domaines :\n\n1. L'appareil général de commande et de protection\n2. La protection différentielle à l'origine de l'installation\n3. La prise de terre et les liaisons équipotentielles\n4. Les dispositifs de protection contre les surintensités\n5. L'absence de matériel vétuste ou inadapté\n6. Les conditions de sécurité dans les salles d'eau\n\n:::warning Attention\nUn diagnostic révélant des anomalies graves n'oblige pas légalement le vendeur à effectuer les travaux. Cependant, il engage sa responsabilité en cas d'accident. Négociez le coût de la mise aux normes lors de l'achat.\n:::",

        "## Les signes d'une installation vétuste\n\n### Les signaux d'alerte à ne pas ignorer\n\nPlusieurs symptômes indiquent qu'une mise aux normes est nécessaire :\n\n- Disjoncteurs qui sautent fréquemment\n- Prises qui chauffent ou noircissent\n- Éclairage qui vacille ou grésille\n- Odeur de brûlé près d'un interrupteur\n- Prises sans terre (ancien modèle à deux broches)\n- Fils électriques apparents ou gainés tissu\n- Tableau électrique avec fusibles à broches\n\n:::warning Attention\nSi vous constatez l'un de ces signes, faites intervenir un [électricien qualifié](/services/electricite) dans les plus brefs délais. Une installation défaillante peut provoquer un incendie ou une électrocution à tout moment.\n:::",

        "## Le coût d'une mise aux normes\n\n### Les tarifs en 2026\n\nLe prix d'une mise aux normes électrique varie considérablement selon l'étendue des travaux et la superficie du logement :\n\n:::budget\n| Intervention | Prix moyen |\n| Remplacement du tableau électrique | 800 - 2 000 € |\n| Mise aux normes complète (appartement 60 m²) | 5 000 - 8 000 € |\n| Mise aux normes complète (maison 100 m²) | 8 000 - 15 000 € |\n| Ajout d'un circuit dédié | 150 - 300 € |\n| Installation disjoncteur différentiel 30 mA | 200 - 400 € |\n| Remplacement des prises (par unité) | 60 - 120 € |\n:::\n\nPour des tarifs détaillés, consultez notre guide des [prix d'un électricien en 2026](/blog/prix-electricien-2026-tarifs-travaux).\n\n:::tip Conseil pro\nDemandez plusieurs devis et vérifiez que l'électricien est certifié Qualifelec. À la fin des travaux, exigez une attestation de conformité Consuel (obligatoire pour les installations neuves ou entièrement rénovées).\n:::\n\n:::takeaway\n- La norme NF C 15-100 est la référence pour toutes les installations électriques\n- Le diagnostic est obligatoire pour la vente ou la location de logements de plus de 15 ans\n- Disjoncteurs qui sautent, prises qui chauffent : ces signes exigent une intervention urgente\n- Comptez 50 à 100 €/m² pour une mise aux normes complète\n- Faites appel à un électricien certifié Qualifelec pour garantir la conformité\n- Les travaux de mise aux normes bénéficient de la TVA réduite à 10 %\n:::",
    ],
    "image": "/images/blog/electricite.jpg",
    "author": "Marc Lefebvre",
    "authorBio": "Marc Lefebvre, ingénieur thermicien et rédacteur technique, vulgarise les aspects complexes de la rénovation énergétique.",
    "date": "2026-01-28",
    "updatedDate": "2026-02-10",
    "readTime": "13 min",
    "category": "Securite",
    "tags": ["Electricite", "Normes", "Securite"],
    "faq": [
        {"question": "Est-il obligatoire de mettre aux normes une installation ancienne ?", "answer": "Non, la mise aux normes n'est pas obligatoire pour les installations existantes, sauf en cas de rénovation lourde. Cependant, en cas d'accident, le propriétaire peut être tenu responsable si l'installation n'est pas conforme."},
        {"question": "Combien de temps dure une mise aux normes électrique ?", "answer": "Comptez 2 à 3 jours pour un appartement et 4 à 7 jours pour une maison. La durée dépend de l'étendue des travaux et de l'accessibilité des gaines. Prévoyez de ne pas occuper le logement pendant les travaux."},
        {"question": "La mise aux normes électrique bénéficie-t-elle d'aides ?", "answer": "La mise aux normes bénéficie de la TVA à 10 % dans les logements de plus de 2 ans. Si les travaux intègrent une dimension énergétique (éclairage LED, domotique), certains postes peuvent bénéficier de la TVA à 5,5 %."},
    ],
})

# Write Part 1 marker
with open('/tmp/articles_part1.json', 'w', encoding='utf-8') as f:
    json.dump(articles, f, ensure_ascii=False, indent=2)

print(f"Part 1: {len(articles)} articles written to /tmp/articles_part1.json")
