#!/usr/bin/env python3
"""Generate existing-articles Part 2 (articles 7-14)."""
import json

articles = []

# ─── Article 7: peinture-interieure-conseils ───
articles.append({
    "slug": "peinture-interieure-conseils",
    "title": "Réussir sa peinture intérieure : nos conseils",
    "excerpt": "Préparation, choix des couleurs, techniques d'application... Tous les secrets d'une peinture réussie pour transformer vos pièces comme un professionnel.",
    "content": [
        "La peinture est l'un des travaux de rénovation les plus courants et les plus transformateurs. Bien réalisée, elle peut métamorphoser une pièce en quelques jours pour un budget maîtrisé. Selon les professionnels du bâtiment, 80 % de la réussite d'une peinture dépend de la préparation des surfaces. Voici nos conseils complets pour un résultat professionnel, que vous fassiez appel à un [peintre qualifié](/services/peinture) ou que vous vous lanciez en auto-rénovation.",

        "## La préparation des surfaces : la clé du succès\n\n### Pourquoi la préparation est essentielle\n\nLa clé d'une belle peinture, c'est la préparation. Un mur mal préparé laissera apparaître toutes les imperfections une fois la peinture sèche. Comptez 60 à 70 % du temps total de chantier pour cette étape cruciale.\n\n### Les étapes de préparation\n\n1. **Lessivez** les murs à la lessive Saint-Marc ou à la lessive spéciale peinture pour éliminer les traces de gras et la poussière\n2. **Rebouchez** les trous et fissures avec un enduit de rebouchage (petits trous) ou un enduit de lissage (grandes surfaces)\n3. **Poncez** légèrement au papier abrasif grain 120 pour obtenir une surface lisse et favoriser l'adhérence\n4. **Dépoussiérez** avec un chiffon humide ou une éponge\n5. **Appliquez une sous-couche** adaptée au support (plâtre, bois, métal, ancien revêtement)\n\n:::tip Conseil pro\nPour les murs très abîmés, appliquez une toile de verre (voile de verre lisse ou toile à peindre) qui masque les imperfections et renforce le support. Comptez 5 à 15 €/m² fourniture et pose.\n:::",

        "## Le choix de la peinture\n\n### Les types de peinture\n\n- **Peinture acrylique (à l'eau)** : la plus courante, séchage rapide, peu d'odeur, nettoyage à l'eau. Idéale pour les pièces sèches (chambres, séjour)\n- **Peinture glycéro (à l'huile)** : meilleure résistance à l'humidité et aux taches, mais odeur forte et nettoyage au white-spirit. Pour cuisines et salles de bain\n- **Peinture alkyde** : compromis entre acrylique et glycéro, résistante et peu odorante\n- **Peinture bio/écologique** : faible teneur en COV, idéale pour les chambres d'enfants\n\n### Les finitions\n\n- **Mat** : masque les défauts du support, ambiance feutrée, mais fragile aux taches\n- **Satiné** : le meilleur compromis, lessivable, adapté aux pièces à vivre\n- **Brillant** : très résistant et lessivable, mais révèle tous les défauts du mur\n- **Velours** : légèrement satiné, aspect doux et chaleureux\n\n:::info Bon à savoir\nUne peinture de qualité professionnelle coûte entre 25 et 60 € le litre mais offre un meilleur pouvoir couvrant (souvent une seule couche suffit) et une meilleure durabilité. Sur le long terme, elle revient moins cher qu'une peinture premier prix nécessitant trois couches.\n:::",

        "## Les techniques d'application\n\n### La méthode professionnelle\n\n1. **Protégez** la pièce : bâches au sol, adhésif de masquage sur les plinthes, interrupteurs et encadrements\n2. **Commencez par les angles** au pinceau à réchampir (pinceau biseauté) pour dégager les bords\n3. **Appliquez au rouleau** en croisant les passes : d'abord horizontalement, puis verticalement pour lisser\n4. **Travaillez par pans de mur complets** pour éviter les traces de reprise\n5. **Respectez les temps de séchage** entre chaque couche (2 à 4 heures pour l'acrylique, 12 à 24 heures pour la glycéro)\n\n### Les erreurs à éviter\n\n- Charger trop le rouleau (provoque des coulures)\n- Repasser sur une zone en cours de séchage (crée des surépaisseurs)\n- Peindre par temps trop chaud (> 25 °C) ou trop humide (> 70 % HR)\n- Négliger la sous-couche (mauvaise adhérence, consommation excessive)\n\n:::warning Attention\nNe peignez jamais un mur humide. L'humidité emprisonnée sous la peinture provoquera des cloques et des décollements. Si vous constatez des traces d'humidité, identifiez et traitez la cause avant de peindre.\n:::",

        "## Le budget à prévoir\n\n### Tarifs professionnels\n\n:::budget\n| Prestation | Prix moyen en 2026 |\n| Peinture murs (par un professionnel) | 20 - 45 €/m² |\n| Peinture plafond | 25 - 50 €/m² |\n| Peinture boiseries (portes, plinthes) | 30 - 60 €/ml |\n| Chambre complète (12 m²) | 400 - 800 € |\n| Salon complet (25 m²) | 700 - 1 500 € |\n:::\n\n### En auto-rénovation\n\nEn réalisant vous-même la peinture, le coût est divisé par trois environ. Prévoyez le matériel : peinture (25-60 €/L), rouleaux et pinceaux (30-50 €), bâches et adhésifs (20-30 €), sous-couche (15-30 €/L).\n\nPour des tarifs complets, consultez notre [guide des prix peintre en bâtiment 2026](/blog/prix-peintre-batiment-2026-guide-complet).\n\n:::takeaway\n- 80 % de la réussite dépend de la préparation des surfaces\n- Choisissez la peinture adaptée à chaque pièce (acrylique, glycéro, alkyde)\n- Le mat masque les défauts, le satiné est le plus polyvalent\n- Travaillez toujours par pans de mur complets pour éviter les traces\n- Comptez 20 à 45 €/m² pour une peinture professionnelle\n- Investissez dans une peinture de qualité : un seul passage suffit souvent\n:::",
    ],
    "image": "/images/blog/peinture.jpg",
    "author": "Thomas Bernard",
    "authorBio": "Thomas Bernard, architecte d'intérieur et consultant en rénovation, conseille les propriétaires sur l'optimisation de leur habitat.",
    "date": "2026-01-20",
    "updatedDate": "2026-02-08",
    "readTime": "12 min",
    "category": "DIY",
    "tags": ["Peinture", "Decoration", "DIY"],
    "faq": [
        {"question": "Combien de couches de peinture faut-il appliquer ?", "answer": "En règle générale, deux couches suffisent avec une peinture de qualité professionnelle. Sur un support brut ou lors d'un changement de couleur radical (du foncé au clair), comptez une sous-couche + deux couches de finition."},
        {"question": "Quelle peinture choisir pour une chambre d'enfant ?", "answer": "Optez pour une peinture acrylique à faible teneur en COV (composés organiques volatils), certifiée A+ pour les émissions dans l'air intérieur. Les peintures biosourcées ou à base de résines végétales sont idéales."},
        {"question": "Combien de temps faut-il pour peindre une pièce ?", "answer": "Pour un professionnel, comptez 1 jour pour une chambre de 12 m² (préparation + 2 couches) et 2 jours pour un séjour de 25 m². En auto-rénovation, doublez ces durées."},
    ],
})

# ─── Article 8: chauffage-solution-economique ───
articles.append({
    "slug": "chauffage-solution-economique",
    "title": "Quel chauffage choisir pour faire des économies ?",
    "excerpt": "Pompe à chaleur, poêle à granulés, chaudière... Comparatif complet des solutions de chauffage les plus économiques en 2026, avec coûts d'installation et de fonctionnement.",
    "content": [
        "Le chauffage représente en moyenne 66 % de la consommation énergétique d'un logement français, soit environ 1 700 euros par an pour une maison de 100 m² mal isolée. Bien choisir son système de chauffage est donc essentiel pour maîtriser son budget et réduire son empreinte carbone. En 2026, plusieurs solutions performantes s'offrent à vous, chacune avec ses avantages et ses contraintes.",

        "## La pompe à chaleur air-eau : la championne de l'efficacité\n\n### Principe et performance\n\nAvec un COP (Coefficient de Performance) moyen de 3 à 4, la pompe à chaleur air-eau produit 3 à 4 kWh de chaleur pour chaque kWh d'électricité consommé. C'est l'une des solutions les plus économiques à l'usage, malgré un investissement initial élevé.\n\n### Avantages et inconvénients\n\n- **Coût d'installation** : 8 000 à 16 000 €\n- **Coût annuel de fonctionnement** : 500 à 900 € pour 100 m²\n- **Durée de vie** : 15 à 20 ans\n- **Éligible à MaPrimeRénov'** : jusqu'à 5 000 € d'aide\n- **Inconvénient** : performances réduites par grand froid (en dessous de -7 °C), nuisance sonore de l'unité extérieure\n\nPour un comparatif détaillé, consultez notre article [Pompe à chaleur vs chaudière gaz](/blog/chauffage-pompe-chaleur-vs-chaudiere-gaz-2026).\n\n:::tip Conseil pro\nDimensionnez correctement votre PAC : une pompe à chaleur surdimensionnée effectuera des cycles courts qui usent le compresseur et augmentent la consommation. Faites réaliser une étude thermique préalable par un bureau d'études.\n:::",

        "## Le poêle à granulés : le confort au meilleur prix\n\n### Un combustible économique\n\nLe granulé de bois (ou pellet) est le combustible le moins cher du marché, avec un coût d'environ 6 à 8 centimes par kWh en 2026. Un poêle à granulés peut chauffer une maison de 100 m² pour environ 500 à 800 euros par an.\n\n### Les atouts du poêle à granulés\n\n- **Coût d'installation** : 2 500 à 6 000 € (pose et conduit compris)\n- **Coût annuel de fonctionnement** : 500 à 800 € pour 100 m²\n- **Rendement** : 85 à 95 %\n- **Autonomie** : 12 à 72 heures selon la capacité du réservoir\n- **Éligible aux aides** : MaPrimeRénov', CEE, TVA 5,5 %\n\n:::info Bon à savoir\nLe poêle à granulés est idéal en chauffage principal pour les maisons bien isolées (moins de 100 m²) ou en chauffage d'appoint pour les maisons plus grandes. Pour une maison de plus de 120 m², envisagez une chaudière à granulés avec distribution par radiateurs.\n:::",

        "## La chaudière gaz à condensation : le remplacement malin\n\n### Toujours pertinente en rénovation\n\nPlus performante qu'une chaudière classique, la chaudière à condensation récupère la chaleur des fumées pour préchauffer l'eau de retour. Elle offre un rendement supérieur à 100 % (sur PCI) et s'installe facilement en remplacement d'une ancienne chaudière.\n\n- **Coût d'installation** : 3 000 à 7 000 €\n- **Coût annuel de fonctionnement** : 1 000 à 1 500 € pour 100 m²\n- **Durée de vie** : 15 à 25 ans\n\n:::warning Attention\nDepuis la [RE2020](/blog/reglementation-thermique-re2020-impact), l'installation de chaudières gaz est interdite dans les logements neufs. En rénovation, la chaudière gaz à condensation reste autorisée mais les aides MaPrimeRénov' pour ce type d'équipement ont été supprimées depuis 2024. La chaudière gaz est amenée à disparaître progressivement.\n:::",

        "## Les aides au changement de chauffage\n\n### Un financement généreux\n\nLe remplacement d'un ancien système de chauffage est éligible à de nombreuses aides qui peuvent couvrir jusqu'à 50 % du coût des travaux :\n\n- **MaPrimeRénov'** : 3 000 à 11 000 € selon l'équipement et les revenus\n- **CEE** : 2 500 à 5 000 € selon l'équipement\n- **TVA réduite** : 5,5 % au lieu de 20 %\n- **Éco-PTZ** : jusqu'à 15 000 € sans intérêts\n\n:::budget\n| Solution | Installation | Fonctionnement/an | Aides possibles |\n| PAC air-eau | 8 000 - 16 000 € | 500 - 900 € | 5 000 - 11 000 € |\n| Poêle à granulés | 2 500 - 6 000 € | 500 - 800 € | 1 500 - 3 000 € |\n| Chaudière gaz condensation | 3 000 - 7 000 € | 1 000 - 1 500 € | CEE uniquement |\n| Chaudière biomasse | 10 000 - 20 000 € | 400 - 700 € | 5 000 - 11 000 € |\n:::\n\nConsultez notre guide complet des [aides à la rénovation énergétique](/blog/renovation-energetique-aides-2026) pour optimiser votre financement.\n\n:::takeaway\n- La pompe à chaleur air-eau offre le meilleur rapport performance/économies\n- Le poêle à granulés est la solution la plus abordable à l'installation\n- La chaudière gaz reste pertinente en remplacement mais les aides diminuent\n- Isolez d'abord, chauffez ensuite : une bonne isolation réduit le dimensionnement\n- Les aides cumulées peuvent couvrir 50 % ou plus du coût d'installation\n- Faites toujours réaliser une étude thermique avant de choisir\n:::",
    ],
    "image": "/images/blog/chauffage.jpg",
    "author": "Marc Lefebvre",
    "authorBio": "Marc Lefebvre, ingénieur thermicien et rédacteur technique, vulgarise les aspects complexes de la rénovation énergétique.",
    "date": "2026-01-18",
    "updatedDate": "2026-02-09",
    "readTime": "13 min",
    "category": "Energie",
    "tags": ["Chauffage", "Energie", "Economies"],
    "faq": [
        {"question": "Quel est le chauffage le plus économique en 2026 ?", "answer": "En coût de fonctionnement, le poêle à granulés et la pompe à chaleur air-eau sont les plus économiques (500-900 €/an pour 100 m²). En coût global (installation + fonctionnement sur 15 ans), la PAC air-eau est généralement la plus avantageuse grâce aux aides."},
        {"question": "Peut-on remplacer une chaudière gaz par une pompe à chaleur ?", "answer": "Oui, c'est même le remplacement le plus courant. La PAC air-eau se raccorde au circuit de radiateurs existant. Si vos radiateurs sont dimensionnés pour de la haute température (vieille chaudière), optez pour une PAC haute température ou envisagez de changer les radiateurs."},
        {"question": "Le poêle à granulés peut-il chauffer toute une maison ?", "answer": "Un poêle à granulés de 8 à 12 kW peut chauffer une maison bien isolée de 80 à 120 m² en pièce principale. Pour les pièces éloignées, il faudra un système de distribution d'air chaud (gainable) ou un chauffage d'appoint."},
    ],
})

# ─── Article 9: combien-coute-un-plombier-tarifs-devis ───
articles.append({
    "slug": "combien-coute-un-plombier-tarifs-devis",
    "title": "Combien coûte un plombier en 2026 ? Tarifs et devis",
    "excerpt": "Prix horaire, tarif d'intervention, coût des réparations courantes... Tous les tarifs plomberie à connaître avant de demander un devis en 2026.",
    "content": [
        "Le coût d'un plombier varie considérablement selon le type d'intervention, l'urgence, la région et la complexité des travaux. Avant de faire appel à un professionnel, il est essentiel de connaître les tarifs du marché pour [comparer efficacement les devis](/blog/devis-travaux-comment-comparer-choisir) et éviter les mauvaises surprises. Voici le guide complet des tarifs plomberie en 2026, régulièrement mis à jour.",

        "## Le tarif horaire moyen\n\n### En province\n\nLe tarif horaire d'un plombier se situe entre 40 et 70 euros HT en province. Ce tarif couvre uniquement la main-d'œuvre ; les fournitures et les frais de déplacement sont facturés en supplément.\n\n### En Île-de-France\n\nEn région parisienne, les tarifs sont sensiblement plus élevés : entre 60 et 90 euros HT de l'heure. L'écart s'explique par le coût de la vie, les charges d'entreprise plus élevées et la forte demande.\n\n### Les majorations\n\nCe tarif peut doubler en cas d'intervention en urgence ou le week-end :\n\n- **Majoration week-end** : +50 à 75 %\n- **Majoration nuit (20h-8h)** : +75 à 100 %\n- **Majoration jours fériés** : +100 %\n\n:::warning Attention\nLes majorations doivent être annoncées avant l'intervention et figurer sur le devis ou l'ordre de service. Un plombier qui applique une majoration surprise sur la facture commet une pratique commerciale abusive.\n:::",

        "## Les interventions courantes et leurs prix\n\n### Dépannages\n\n:::budget\n| Intervention | Prix moyen (main-d'œuvre + fournitures) |\n| Débouchage canalisation simple | 80 - 200 € |\n| Débouchage avec furet ou haute pression | 150 - 400 € |\n| Remplacement d'un robinet | 80 - 150 € |\n| Remplacement mitigeur | 100 - 250 € |\n| Réparation de fuite apparente | 100 - 300 € |\n| Réparation de fuite encastrée | 200 - 600 € |\n| Remplacement chasse d'eau | 100 - 200 € |\n| Remplacement joint de robinet | 50 - 100 € |\n:::\n\n### Installations\n\n| Installation | Prix moyen (fournitures comprises) |\n| --- | --- |\n| Chauffe-eau électrique (pose) | 300 - 800 € |\n| Chauffe-eau thermodynamique (pose) | 800 - 1 500 € |\n| Cumulus (remplacement complet) | 600 - 1 500 € |\n| WC complet | 300 - 600 € |\n| Lave-vaisselle (raccordement) | 80 - 150 € |",

        "## Le devis gratuit et les frais de déplacement\n\n### Le devis planifié\n\nLa plupart des plombiers proposent un devis gratuit pour les travaux planifiés. Le professionnel se déplace, évalue la situation et vous remet un devis détaillé sous 24 à 72 heures.\n\n### Le déplacement en urgence\n\nEn revanche, un déplacement en urgence peut être facturé 30 à 80 euros même si les travaux ne sont pas réalisés. Ce forfait couvre le temps de trajet et le diagnostic sur place.\n\n:::info Bon à savoir\nLe plombier doit vous informer du coût du déplacement avant de se déplacer. S'il constate sur place que l'intervention dépasse 150 €, il doit vous remettre un devis écrit avant d'intervenir (article L.111-3 du Code de la consommation).\n:::",

        "## Comment économiser sur la plomberie\n\n### Nos conseils pratiques\n\n1. **Comparez au moins 3 devis** : les écarts peuvent atteindre 50 % pour une même prestation\n2. **Privilégiez les interventions en semaine** et aux heures ouvrables (8h-18h) pour éviter les majorations\n3. **Regroupez les petits travaux** pour réduire les frais de déplacement : faites une liste de toutes les réparations nécessaires\n4. **Entretenez régulièrement** : un détartrage annuel du chauffe-eau et un nettoyage des canalisations évitent les pannes coûteuses\n5. **Apprenez les gestes simples** : changer un joint de robinet ou déboucher un siphon ne nécessite pas de plombier\n\n:::tip Conseil pro\nSur ServicesArtisans, vous pouvez [vérifier les artisans](/blog/comment-verifier-artisan-avant-engager) et obtenir plusieurs devis gratuits en quelques clics. Comparer les offres est le meilleur moyen de maîtriser votre budget plomberie.\n:::\n\n:::takeaway\n- Le tarif horaire moyen est de 40-70 € HT en province, 60-90 € HT en Île-de-France\n- Les majorations nuit/week-end peuvent doubler le tarif de base\n- Débouchage simple : 80-200 €, réparation de fuite : 100-300 €\n- Un déplacement d'urgence coûte 30-80 € même sans intervention\n- Comparez 3 devis et regroupez les travaux pour économiser\n- Privilégiez les interventions en semaine aux heures ouvrables\n:::",
    ],
    "image": "/images/blog/tarifs-plombier.jpg",
    "author": "Claire Dubois",
    "authorBio": "Claire Dubois, experte en économie de la construction, analyse les prix du marché et les aides financières pour informer les consommateurs.",
    "date": "2026-02-05",
    "updatedDate": "2026-02-11",
    "readTime": "11 min",
    "category": "Guides",
    "tags": ["Plomberie", "Tarifs", "Devis"],
    "faq": [
        {"question": "Un plombier peut-il facturer le déplacement si les travaux ne sont pas réalisés ?", "answer": "Oui, si le tarif du déplacement a été annoncé au préalable. Le plombier doit vous informer du coût avant de se déplacer. En revanche, un devis planifié (non urgent) est généralement gratuit."},
        {"question": "Comment éviter les arnaques sur les tarifs de plomberie ?", "answer": "Vérifiez le SIRET de l'artisan, demandez un devis écrit avant toute intervention, comparez plusieurs offres et méfiez-vous des tarifs anormalement bas ou élevés. Ne faites jamais appel à un plombier trouvé par démarchage téléphonique."},
        {"question": "Les tarifs plomberie incluent-ils les fournitures ?", "answer": "Cela dépend du devis. Certains plombiers facturent la main-d'œuvre et les fournitures séparément, d'autres proposent un forfait tout compris. Vérifiez systématiquement ce point dans le devis."},
    ],
})

# ─── Article 10: trouver-artisan-verifie-siren ───
articles.append({
    "slug": "trouver-artisan-verifie-siren",
    "title": "Trouver un artisan vérifié : pourquoi le SIREN compte",
    "excerpt": "Numéro SIREN, assurance décennale, qualifications... Les vérifications indispensables avant de faire appel à un artisan pour protéger votre projet de travaux.",
    "content": [
        "Faire appel à un artisan non vérifié peut avoir des conséquences graves : travaux mal réalisés, absence de garantie, recours impossible en cas de litige. Selon la DGCCRF, plus de 10 000 signalements de pratiques frauduleuses dans le secteur du bâtiment sont enregistrés chaque année en France. Le numéro SIREN est votre première protection pour vérifier le sérieux d'un professionnel.",

        "## Qu'est-ce que le numéro SIREN ?\n\n### Un identifiant unique\n\nLe SIREN (Système d'Identification du Répertoire des Entreprises) est un identifiant unique de 9 chiffres attribué par l'INSEE à chaque entreprise lors de sa création. Le SIRET (14 chiffres) ajoute un identifiant d'établissement au SIREN. Ces numéros permettent de vérifier :\n\n- L'existence légale de l'entreprise\n- Son statut d'activité (en activité, radiée, en liquidation)\n- Sa date de création\n- Son code APE (activité principale exercée)\n- Son adresse officielle\n\n### Pourquoi c'est essentiel\n\nUn artisan sans SIREN est un artisan qui travaille au noir. Cela signifie :\n\n- **Aucune assurance** : pas de RC Pro, pas de garantie décennale\n- **Aucun recours** : en cas de malfaçon, impossible de faire jouer les garanties\n- **Risques légaux** : le client qui fait appel sciemment à un travailleur non déclaré s'expose à des sanctions fiscales\n\n:::warning Attention\nFaire appel à un artisan non déclaré vous expose à une amende de 45 000 € et 3 ans d'emprisonnement pour travail dissimulé (article L.8224-1 du Code du travail). En cas d'accident sur le chantier, votre responsabilité peut être engagée.\n:::",

        "## Comment vérifier un artisan ?\n\n### Sur ServicesArtisans\n\nSur notre plateforme, chaque artisan est vérifié automatiquement via l'API SIREN de l'INSEE. Nous contrôlons :\n\n1. L'existence et l'activité de l'entreprise\n2. La cohérence du code APE avec le métier déclaré\n3. La validité des assurances professionnelles\n4. Les éventuelles procédures collectives\n\n### Par vous-même\n\nVous pouvez aussi vérifier vous-même sur :\n\n- **sirene.fr** (base officielle INSEE) : recherche gratuite par numéro ou nom\n- **Infogreffe.fr** : informations financières et légales\n- **societe.com** : synthèse des informations publiques\n- **Annuaire des entreprises** (entreprise.data.gouv.fr) : base de données officielle\n\n:::tip Conseil pro\nRecherchez le SIRET plutôt que le SIREN : le SIRET identifie l'établissement exact, ce qui vous permet de vérifier que l'adresse correspond bien à celle de l'artisan qui vous a contacté.\n:::",

        "## Les autres vérifications essentielles\n\n### Au-delà du SIREN\n\nLe SIREN confirme l'existence de l'entreprise, mais ne garantit pas la qualité du travail. Vérifiez également :\n\n- **L'assurance RC professionnelle** : demandez l'attestation en cours de validité\n- **La garantie décennale** : obligatoire pour les travaux de gros œuvre. Voir notre guide sur la [garantie décennale](/blog/garantie-decennale-tout-savoir)\n- **Les qualifications professionnelles** : RGE pour les travaux énergétiques, Qualibat, Qualifelec. Consultez notre article sur les [certifications du bâtiment](/blog/qualibat-qualifelec-certifications-batiment)\n- **L'inscription au Registre des Métiers** : obligatoire pour les artisans\n\n:::info Bon à savoir\nDepuis 2023, l'inscription au Registre National des Entreprises (RNE) a remplacé le Répertoire des Métiers et le Registre du Commerce. Vérifiez l'inscription de l'artisan sur formalites.entreprises.gouv.fr.\n:::",

        "## Que faire en cas de problème ?\n\n### Si vous avez fait appel à un artisan non déclaré\n\nVos recours sont extrêmement limités. Sans contrat légal, sans facture officielle, sans assurance, vous ne pouvez pas :\n\n- Faire jouer la garantie décennale\n- Saisir le tribunal pour obtenir réparation\n- Bénéficier de la médiation de la consommation\n\n### Les bons réflexes\n\nPrivilégiez toujours des professionnels vérifiés pour bénéficier des garanties légales :\n\n1. Vérifiez le SIRET avant tout engagement\n2. Demandez les attestations d'assurance\n3. Exigez un devis écrit et détaillé\n4. Conservez tous les documents (devis, factures, échanges)\n5. Formalisez la [réception des travaux](/blog/reception-travaux-proces-verbal-reserves) par un PV écrit\n\n:::takeaway\n- Le SIREN/SIRET est la carte d'identité de l'entreprise : vérifiez-le systématiquement\n- Un artisan sans SIREN = pas d'assurance, pas de garantie, pas de recours\n- Vérifiez sur sirene.fr, Infogreffe ou ServicesArtisans\n- Au-delà du SIREN, contrôlez les assurances et les qualifications\n- Faire appel au travail dissimulé vous expose à des sanctions pénales\n- Conservez tous les documents pour protéger vos droits\n:::",
    ],
    "image": "/images/blog/verification-siren.jpg",
    "author": "Isabelle Renault",
    "authorBio": "Isabelle Renault, juriste spécialisée en droit de la construction et de l'immobilier, décrypte la réglementation pour les propriétaires.",
    "date": "2026-02-03",
    "updatedDate": "2026-02-10",
    "readTime": "11 min",
    "category": "Conseils",
    "tags": ["Verification", "SIREN", "Artisans"],
    "faq": [
        {"question": "Comment trouver le numéro SIREN d'un artisan ?", "answer": "Le SIREN ou SIRET doit figurer sur tous les documents officiels de l'artisan : devis, factures, carte de visite, site internet. Vous pouvez aussi le rechercher sur sirene.fr par le nom de l'entreprise ou sur ServicesArtisans."},
        {"question": "Que faire si le SIREN de l'artisan est invalide ?", "answer": "Si la recherche du SIREN ne donne aucun résultat ou indique une entreprise radiée, ne faites pas appel à cet artisan. Signalez-le éventuellement à la DGCCRF et cherchez un professionnel vérifié."},
        {"question": "Le SIREN garantit-il la qualité des travaux ?", "answer": "Non, le SIREN confirme uniquement l'existence légale de l'entreprise. Pour évaluer la qualité, vérifiez également les certifications (Qualibat, RGE), les avis clients et les références de chantiers similaires."},
    ],
})

# ─── Article 11: renovation-maison-par-ou-commencer ───
articles.append({
    "slug": "renovation-maison-par-ou-commencer",
    "title": "Rénovation maison : par où commencer ?",
    "excerpt": "Ordre des travaux, budget prévisionnel, choix des artisans... Le guide étape par étape pour réussir la rénovation de votre maison sans stress ni surcoûts.",
    "content": [
        "Rénover une maison est un projet excitant mais complexe qui nécessite une planification rigoureuse. Selon la FFB (Fédération Française du Bâtiment), 30 % des chantiers de rénovation connaissent des dépassements de budget, souvent liés à un mauvais ordonnancement des travaux. Suivre le bon ordre est essentiel pour éviter les reprises coûteuses et les retards. Voici le guide étape par étape pour mener votre rénovation avec sérénité.",

        "## 1. Le diagnostic initial : ne brûlez pas cette étape\n\n### Faire un état des lieux complet\n\nAvant de commencer, faites réaliser un diagnostic complet de votre maison par un professionnel. Ce bilan permet de prioriser les travaux et d'éviter les mauvaises surprises :\n\n- **Toiture et charpente** : état des tuiles, présence de fuites, solidité de la charpente, présence de parasites (termites, capricornes)\n- **Structure** : murs porteurs, fondations, fissures éventuelles\n- **Installation électrique** : conformité à la norme NF C 15-100, [sécurité](/blog/electricite-normes-securite)\n- **Plomberie** : état des canalisations, pression, évacuations\n- **Isolation** : [DPE](/blog/audit-energetique-dpe-obligations-2026) pour évaluer la performance énergétique\n- **Amiante et plomb** : obligatoire pour les bâtiments construits avant 1997 (amiante) et 1949 (plomb)\n\n:::tip Conseil pro\nFaites réaliser un audit énergétique complet (800-1 500 €) plutôt qu'un simple DPE. L'audit propose des scénarios de travaux chiffrés et hiérarchisés, ce qui facilite la planification et l'accès aux aides.\n:::",

        "## 2. Le gros œuvre en premier\n\n### Les fondations de votre projet\n\nCommencez toujours par le gros œuvre : c'est le squelette de votre maison. Ces travaux sont les plus importants et conditionnent tout le reste de la rénovation :\n\n1. **Toiture** : réfection si nécessaire, traitement de charpente\n2. **Charpente** : renforcement ou remplacement des éléments dégradés\n3. **Murs porteurs** : ouvertures, renforcements, traitement des fissures\n4. **Fondations** : reprise en sous-œuvre si nécessaire\n5. **Maçonnerie** : ravalement, traitement des remontées capillaires\n\n:::warning Attention\nToute modification d'un mur porteur nécessite l'intervention d'un bureau d'études structure. Une ouverture mal calculée peut entraîner l'effondrement partiel du bâtiment. Le coût d'une étude structure (500-1 500 €) est dérisoire comparé aux conséquences d'une erreur.\n:::",

        "## 3. L'isolation et l'étanchéité\n\n### Créer une enveloppe performante\n\nUne fois le gros œuvre terminé, passez à l'[isolation thermique](/blog/isolation-thermique-guide) et à l'étanchéité. Ces travaux permettent de réduire considérablement votre facture énergétique et conditionnent le dimensionnement du système de chauffage.\n\nOrdre recommandé :\n\n1. Isolation de la toiture ou des combles (30 % des déperditions)\n2. Isolation des murs (20-25 % des déperditions)\n3. Remplacement des fenêtres et portes extérieures (10-15 %)\n4. Isolation du plancher bas (7-10 %)\n\n## 4. Les réseaux (électricité, plomberie, chauffage)\n\n### Moderniser les artères de la maison\n\nMettez ensuite aux normes les réseaux électriques et de plomberie. Ces travaux doivent impérativement être réalisés avant les finitions :\n\n- **Électricité** : mise en conformité NF C 15-100, tableau électrique, câblage\n- **Plomberie** : remplacement des canalisations vétustes, alimentation et évacuations\n- **Chauffage** : installation du nouveau système ([PAC, poêle, chaudière](/blog/chauffage-solution-economique))\n- **Ventilation** : VMC double flux pour une bonne qualité d'air\n\n## 5. Les finitions\n\n### Donner vie à votre projet\n\nEnfin, réalisez les finitions qui donnent vie à votre projet :\n\n- Plâtrerie et cloisonnement\n- [Peinture](/blog/peinture-interieure-conseils) et revêtements muraux\n- Revêtements de sol (carrelage, parquet, vinyle)\n- Menuiseries intérieures (portes, placards)\n- Équipements sanitaires et [cuisine](/blog/comment-choisir-cuisine-equipee-guide)\n\n:::takeaway\n- Diagnostic complet avant tout : c'est la base d'une rénovation réussie\n- Gros œuvre d'abord, finitions en dernier : ne jamais inverser l'ordre\n- Isolez avant de choisir le chauffage pour un dimensionnement optimal\n- Les réseaux (électricité, plomberie) passent avant les finitions\n- Prévoyez une marge de 10-15 % du budget pour les imprévus\n- Faites appel à un maître d'œuvre pour les rénovations importantes\n:::",
    ],
    "image": "/images/blog/renovation-maison.jpg",
    "author": "Jean-Pierre Duval",
    "authorBio": "Jean-Pierre Duval, ancien artisan du bâtiment reconverti en journaliste, partage son expertise terrain pour aider les propriétaires à faire les bons choix.",
    "date": "2026-02-01",
    "updatedDate": "2026-02-09",
    "readTime": "14 min",
    "category": "Guides",
    "tags": ["Renovation", "Maison", "Travaux"],
    "faq": [
        {"question": "Quel budget prévoir pour rénover une maison ?", "answer": "Le budget dépend de l'ampleur des travaux : 500-800 €/m² pour une rénovation légère (peinture, sols, électricité), 800-1 500 €/m² pour une rénovation complète, 1 500-2 500 €/m² pour une rénovation lourde avec gros œuvre. Prévoyez toujours 10-15 % de marge pour les imprévus."},
        {"question": "Faut-il un architecte pour rénover une maison ?", "answer": "Un architecte est obligatoire si la surface totale après travaux dépasse 150 m². En dessous, il n'est pas obligatoire mais fortement recommandé pour les rénovations complexes. Un maître d'œuvre peut être une alternative plus économique."},
        {"question": "Combien de temps dure une rénovation complète ?", "answer": "Comptez 4 à 6 mois pour une rénovation standard d'une maison de 100 m² et 8 à 12 mois pour une rénovation lourde. Les délais dépendent de la disponibilité des artisans et de la complexité des travaux."},
    ],
})

# ─── Article 12: artisan-pas-cher-attention-arnaques ───
articles.append({
    "slug": "artisan-pas-cher-attention-arnaques",
    "title": "Artisan pas cher : attention aux arnaques",
    "excerpt": "Devis anormalement bas, travaux bâclés, faux artisans... Comment repérer les arnaques et protéger votre projet de travaux. Les signaux d'alerte et les réflexes à adopter.",
    "content": [
        "Un devis anormalement bas doit toujours éveiller votre méfiance. Selon la DGCCRF, le secteur du bâtiment concentre chaque année plus de 10 000 plaintes de consommateurs pour pratiques commerciales trompeuses. Les arnaques vont du simple devis gonflé au faux artisan qui disparaît avec l'acompte. Voici les principaux signaux d'alerte et les réflexes à adopter pour protéger votre projet et votre portefeuille.",

        "## Les signaux d'alerte à connaître\n\n### Les indices qui doivent vous alerter\n\n- **Devis sans mention de SIRET** : un professionnel légitime a toujours un numéro SIRET. Vérifiez-le sur [ServicesArtisans](/blog/trouver-artisan-verifie-siren) ou sirene.fr\n- **Prix très en dessous du marché** : un prix 30 % inférieur à la concurrence cache souvent une arnaque ou du travail bâclé\n- **Demande d'acompte élevé en espèces** : un acompte supérieur à 30 % et/ou un paiement en espèces sont des signaux d'alerte majeurs\n- **Absence de contrat écrit** : tout engagement doit faire l'objet d'un [devis signé](/blog/devis-travaux-comprendre)\n- **Urgence artificielle** : « cette offre est valable uniquement aujourd'hui » est une technique de manipulation classique\n- **Pas d'adresse physique** : uniquement un numéro de portable, pas de local professionnel\n\n:::warning Attention\nLes arnaques à l'isolation à 1 euro, aux panneaux solaires gratuits ou à l'audit énergétique offert persistent malgré les alertes. Ces dispositifs ont été supprimés ou profondément modifiés. Tout démarchage en leur nom est frauduleux.\n:::",

        "## Le démarchage à domicile : danger\n\n### Un terrain propice aux abus\n\nMéfiez-vous des artisans qui frappent à votre porte pour proposer des travaux. Le démarchage à domicile dans le bâtiment est souvent associé à des pratiques douteuses : prix gonflés, matériaux de mauvaise qualité, travaux inutiles.\n\n### Vos droits en cas de démarchage\n\n- **Délai de rétractation de 14 jours** : pour tout contrat signé à domicile (article L.221-18 du Code de la consommation)\n- **Interdiction de percevoir un paiement** pendant les 7 premiers jours suivant la signature (article L.221-10)\n- **Obligation d'information** : le démarcheur doit vous remettre un formulaire de rétractation\n\n:::info Bon à savoir\nDepuis la loi du 24 juillet 2020, le démarchage téléphonique dans le secteur de la rénovation énergétique est interdit. Tout appel non sollicité proposant des travaux d'isolation ou de chauffage est illégal. Raccrochez et signalez le numéro sur bloctel.gouv.fr.\n:::",

        "## Comment se protéger efficacement\n\n### La méthode en 5 étapes\n\n1. **Vérifiez systématiquement le SIRET** sur ServicesArtisans ou sur societe.com avant tout engagement\n2. **Demandez des références** de chantiers similaires et contactez les anciens clients\n3. **Comparez au moins 3 devis** détaillés pour le même périmètre de travaux\n4. **Ne payez jamais plus de 30 % d'acompte** à la signature du devis\n5. **Refusez tout paiement en espèces** : exigez un virement ou un chèque avec facture officielle\n\n### Les vérifications complémentaires\n\n- Recherchez l'artisan sur les réseaux sociaux et les avis en ligne\n- Vérifiez les assurances ([RC Pro et garantie décennale](/blog/garantie-decennale-tout-savoir))\n- Consultez le Registre des Métiers pour confirmer l'inscription\n- Appelez l'assureur mentionné sur l'attestation pour vérifier sa validité\n\n:::tip Conseil pro\nAvant de signer un devis important, faites une recherche rapide sur le nom de l'entreprise suivi de « arnaque » ou « avis négatif » sur un moteur de recherche. Cela peut révéler des témoignages d'autres victimes.\n:::",

        "## En cas d'arnaque : les recours\n\n### Les démarches immédiates\n\n1. **Portez plainte** auprès de la police ou de la gendarmerie\n2. **Signalez l'artisan à la DGCCRF** via signal.conso.gouv.fr\n3. **Contactez votre assurance habitation** : certaines garanties couvrent les malfaçons\n4. **Consultez une association de consommateurs** (UFC-Que Choisir, CLCV) pour obtenir un accompagnement juridique\n\n### La médiation et la justice\n\nPour les litiges inférieurs à 5 000 €, la médiation est obligatoire avant toute action en justice. Au-delà, vous pouvez saisir directement le tribunal judiciaire. Consultez notre guide sur les [recours en cas de litige avec un artisan](/blog/litige-artisan-recours-mediation-justice).\n\n:::takeaway\n- Un devis 30 % en dessous du marché est un signal d'arnaque\n- Vérifiez toujours le SIRET, les assurances et les références\n- Le démarchage téléphonique pour la rénovation énergétique est interdit\n- Ne payez jamais plus de 30 % d'acompte et refusez les espèces\n- En cas de démarchage à domicile, vous avez 14 jours pour vous rétracter\n- Portez plainte et signalez à la DGCCRF en cas d'arnaque avérée\n:::",
    ],
    "image": "/images/blog/arnaques.jpg",
    "author": "Isabelle Renault",
    "authorBio": "Isabelle Renault, juriste spécialisée en droit de la construction et de l'immobilier, décrypte la réglementation pour les propriétaires.",
    "date": "2026-01-30",
    "updatedDate": "2026-02-10",
    "readTime": "12 min",
    "category": "Securite",
    "tags": ["Arnaques", "Securite", "Conseils"],
    "faq": [
        {"question": "Comment savoir si un devis est anormalement bas ?", "answer": "Comparez avec au moins 2 autres devis pour la même prestation. Un écart de plus de 30 % par rapport à la moyenne est suspect. Consultez également nos guides de prix pour chaque corps de métier."},
        {"question": "Que faire si j'ai déjà versé un acompte à un artisan suspect ?", "answer": "Envoyez immédiatement une lettre recommandée de mise en demeure exigeant le remboursement ou l'exécution des travaux. Si le contrat a été signé à domicile, exercez votre droit de rétractation sous 14 jours. Portez plainte en parallèle."},
        {"question": "Le démarchage à domicile est-il interdit pour les artisans ?", "answer": "Le démarchage n'est pas interdit en soi, mais il est encadré. Le démarchage téléphonique pour la rénovation énergétique est interdit depuis 2020. Pour le démarchage physique, un délai de rétractation de 14 jours s'applique et aucun paiement ne peut être perçu pendant les 7 premiers jours."},
    ],
})

with open('/tmp/articles_part2.json', 'w', encoding='utf-8') as f:
    json.dump(articles, f, ensure_ascii=False, indent=2)

print(f"Part 2: {len(articles)} articles written to /tmp/articles_part2.json")
