-- Migration: Analytics Dashboard System
-- Phase 6: World-Class Analytics Dashboard

-- Enhanced analytics events with more tracking data
ALTER TABLE analytics_events
ADD COLUMN IF NOT EXISTS session_id TEXT,
ADD COLUMN IF NOT EXISTS device_type TEXT CHECK (device_type IN ('desktop', 'mobile', 'tablet')),
ADD COLUMN IF NOT EXISTS source TEXT, -- 'organic', 'direct', 'referral', 'social', 'paid'
ADD COLUMN IF NOT EXISTS referrer TEXT,
ADD COLUMN IF NOT EXISTS funnel_step INTEGER,
ADD COLUMN IF NOT EXISTS funnel_name TEXT,
ADD COLUMN IF NOT EXISTS duration_seconds INTEGER,
ADD COLUMN IF NOT EXISTS page_path TEXT,
ADD COLUMN IF NOT EXISTS utm_source TEXT,
ADD COLUMN IF NOT EXISTS utm_medium TEXT,
ADD COLUMN IF NOT EXISTS utm_campaign TEXT;

-- Aggregate stats cache for fast dashboard loading
CREATE TABLE IF NOT EXISTS analytics_aggregates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    period_type TEXT NOT NULL CHECK (period_type IN ('day', 'week', 'month', 'quarter', 'year')),
    metrics JSONB NOT NULL, -- {views: 100, clicks: 50, bookings: 10, revenue: 500}
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(provider_id, period_start, period_type)
);

-- Benchmarking data for competitive analysis
CREATE TABLE IF NOT EXISTS provider_benchmarks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    service_category TEXT NOT NULL,
    city TEXT NOT NULL,
    region TEXT,
    metrics JSONB NOT NULL, -- {avg_rating: 4.5, avg_bookings: 20, avg_revenue: 2000}
    percentiles JSONB NOT NULL, -- {rating: 75, bookings: 60, revenue: 80}
    rank_in_city INTEGER,
    rank_in_region INTEGER,
    rank_national INTEGER,
    total_competitors INTEGER,
    calculated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Scheduled reports configuration
CREATE TABLE IF NOT EXISTS scheduled_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    config JSONB NOT NULL, -- {metrics: ['views', 'bookings'], period: 'weekly', format: 'pdf'}
    frequency TEXT NOT NULL CHECK (frequency IN ('daily', 'weekly', 'biweekly', 'monthly')),
    day_of_week INTEGER CHECK (day_of_week >= 0 AND day_of_week <= 6), -- 0=Sunday
    day_of_month INTEGER CHECK (day_of_month >= 1 AND day_of_month <= 28),
    time_of_day TIME DEFAULT '08:00',
    timezone TEXT DEFAULT 'Europe/Paris',
    next_run TIMESTAMPTZ NOT NULL,
    last_run TIMESTAMPTZ,
    recipients TEXT[] NOT NULL, -- Email addresses
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Report generation history
CREATE TABLE IF NOT EXISTS report_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scheduled_report_id UUID REFERENCES scheduled_reports(id) ON DELETE SET NULL,
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    report_type TEXT NOT NULL,
    period_start DATE,
    period_end DATE,
    file_url TEXT,
    file_size INTEGER,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'generating', 'completed', 'failed')),
    error_message TEXT,
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    delivered_at TIMESTAMPTZ
);

-- Funnel definitions
CREATE TABLE IF NOT EXISTS analytics_funnels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    steps JSONB NOT NULL, -- [{name: 'View Profile', event_type: 'profile_view'}, ...]
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert default funnel
INSERT INTO analytics_funnels (name, description, steps) VALUES
('Booking Funnel', 'Main conversion funnel from search to booking', '[
    {"step": 1, "name": "Recherche", "event_type": "search"},
    {"step": 2, "name": "Vue profil", "event_type": "profile_view"},
    {"step": 3, "name": "Demande devis", "event_type": "quote_request"},
    {"step": 4, "name": "Devis reçu", "event_type": "quote_received"},
    {"step": 5, "name": "Contact", "event_type": "contact"},
    {"step": 6, "name": "Réservation", "event_type": "booking_started"},
    {"step": 7, "name": "Paiement", "event_type": "payment_completed"},
    {"step": 8, "name": "Terminé", "event_type": "booking_completed"}
]'::jsonb)
ON CONFLICT DO NOTHING;

-- Insights generated by the system
CREATE TABLE IF NOT EXISTS analytics_insights (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    insight_type TEXT NOT NULL CHECK (insight_type IN (
        'performance_trend', 'anomaly', 'opportunity',
        'benchmark_comparison', 'recommendation', 'warning'
    )),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    data JSONB, -- {trend: 'up', percentage: 15, metric: 'bookings'}
    priority TEXT DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
    action_url TEXT,
    action_label TEXT,
    is_read BOOLEAN DEFAULT false,
    is_dismissed BOOLEAN DEFAULT false,
    valid_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Goals / targets for providers
CREATE TABLE IF NOT EXISTS provider_goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    metric TEXT NOT NULL, -- 'bookings', 'revenue', 'rating', 'response_rate'
    target_value DECIMAL NOT NULL,
    current_value DECIMAL DEFAULT 0,
    period_type TEXT NOT NULL CHECK (period_type IN ('day', 'week', 'month', 'quarter', 'year')),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    is_achieved BOOLEAN DEFAULT false,
    achieved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(provider_id, metric, period_start, period_type)
);

-- Real-time activity log
CREATE TABLE IF NOT EXISTS realtime_activity (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    provider_id UUID NOT NULL,
    activity_type TEXT NOT NULL, -- 'profile_view', 'message', 'booking', 'review'
    title TEXT NOT NULL,
    description TEXT,
    metadata JSONB,
    is_important BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create function to update aggregates
CREATE OR REPLACE FUNCTION update_analytics_aggregates()
RETURNS TRIGGER AS $$
DECLARE
    v_period_start DATE;
    v_provider_id UUID;
BEGIN
    v_provider_id := NEW.provider_id;
    v_period_start := DATE_TRUNC('day', NEW.created_at)::DATE;

    -- Update daily aggregate
    INSERT INTO analytics_aggregates (provider_id, period_start, period_end, period_type, metrics)
    VALUES (
        v_provider_id,
        v_period_start,
        v_period_start,
        'day',
        jsonb_build_object(NEW.event_type, 1)
    )
    ON CONFLICT (provider_id, period_start, period_type)
    DO UPDATE SET
        metrics = analytics_aggregates.metrics ||
            jsonb_build_object(
                NEW.event_type,
                COALESCE((analytics_aggregates.metrics->>NEW.event_type)::INTEGER, 0) + 1
            ),
        updated_at = NOW();

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for auto-aggregation
DROP TRIGGER IF EXISTS trigger_update_analytics_aggregates ON analytics_events;
CREATE TRIGGER trigger_update_analytics_aggregates
AFTER INSERT ON analytics_events
FOR EACH ROW
WHEN (NEW.provider_id IS NOT NULL)
EXECUTE FUNCTION update_analytics_aggregates();

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_analytics_events_provider ON analytics_events(provider_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_events_funnel ON analytics_events(provider_id, funnel_name, funnel_step);
CREATE INDEX IF NOT EXISTS idx_analytics_events_session ON analytics_events(session_id);
CREATE INDEX IF NOT EXISTS idx_analytics_aggregates_provider ON analytics_aggregates(provider_id, period_type, period_start DESC);
CREATE INDEX IF NOT EXISTS idx_provider_benchmarks_provider ON provider_benchmarks(provider_id);
CREATE INDEX IF NOT EXISTS idx_provider_benchmarks_location ON provider_benchmarks(city, service_category);
CREATE INDEX IF NOT EXISTS idx_scheduled_reports_next_run ON scheduled_reports(next_run) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_report_history_provider ON report_history(provider_id, generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_insights_provider ON analytics_insights(provider_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_insights_unread ON analytics_insights(provider_id, is_read) WHERE is_read = false;
CREATE INDEX IF NOT EXISTS idx_provider_goals_provider ON provider_goals(provider_id, period_start);
CREATE INDEX IF NOT EXISTS idx_realtime_activity_provider ON realtime_activity(provider_id, created_at DESC);

-- Enable realtime for activity feed
ALTER PUBLICATION supabase_realtime ADD TABLE realtime_activity;
ALTER PUBLICATION supabase_realtime ADD TABLE analytics_insights;

-- RLS Policies
ALTER TABLE analytics_aggregates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers can view their own aggregates" ON analytics_aggregates
FOR SELECT USING (provider_id = auth.uid());

ALTER TABLE provider_benchmarks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers can view their own benchmarks" ON provider_benchmarks
FOR SELECT USING (provider_id = auth.uid());

ALTER TABLE scheduled_reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers can view their own scheduled reports" ON scheduled_reports
FOR SELECT USING (provider_id = auth.uid());

CREATE POLICY "Providers can manage their own scheduled reports" ON scheduled_reports
FOR ALL USING (provider_id = auth.uid());

ALTER TABLE report_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers can view their own report history" ON report_history
FOR SELECT USING (provider_id = auth.uid());

ALTER TABLE analytics_funnels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view active funnels" ON analytics_funnels
FOR SELECT USING (is_active = true);

ALTER TABLE analytics_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers can view their own insights" ON analytics_insights
FOR SELECT USING (provider_id = auth.uid());

CREATE POLICY "Providers can update their own insights" ON analytics_insights
FOR UPDATE USING (provider_id = auth.uid());

ALTER TABLE provider_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers can view their own goals" ON provider_goals
FOR SELECT USING (provider_id = auth.uid());

CREATE POLICY "Providers can manage their own goals" ON provider_goals
FOR ALL USING (provider_id = auth.uid());

ALTER TABLE realtime_activity ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Providers can view their own activity" ON realtime_activity
FOR SELECT USING (provider_id = auth.uid());
